"""IR5A universe items, part 7: controlling decisions and pending law."""
S = "sources/"
def sent(k):
    return r"[^.;]*" + k + r"[^.;]*[.;]"
ITEMS = [
 ("LeRoy v Sayers, 217 AD2d 63 (1st Dept 1995)", "state", "case", "S4 trust (commingling)", "1st Dept: GOL 7-103 imposes a fiduciary (trust) duty to segregate the deposit, actionable as breach of fiduciary duty.",
  S+"REVIEW4A_NY_CASE_LeRoy_v_Sayers_1995_1stDept.txt", sent(r"a breach of fiduciary duty under General Obligations Law § 7-103, which requires a landlord to deposit security funds")),
 ("Paterno v Carroll, 75 AD3d 625 (2d Dept 2010)", "state", "case", "S4 trust (commingling)", "2d Dept: commingling forfeits any use of the deposit; tenant has an immediate right to its return even if it breached the lease (damage claims remain separate).",
  S+"NY_CASE_Paterno_v_Carroll_2010_75AD3d625.txt", sent(r"Paterno forfeited his right to avail himself of the deposit for any purpose")),
 ("Gihon, LLC v 501 Second St., LLC, 103 AD3d 840 (2d Dept 2013)", "state", "case", "S4 interest (6-unit count)", "7-103(2-a) six-unit threshold is counted per building.",
  S+"NY_CASE_Gihon_v_501SecondSt_2013_103AD3d840.txt", sent(r"six or more")),
 ("Cohen v Abruzzo, 228 AD3d 724 (2d Dept 2024)", "state", "case", "S6 statement timing", "Statement 'provided' when sent within 14 days (2d Dept).",
  S+"NY_CASE_Cohen_v_Abruzzo_2024_228AD3d724.txt", sent(r"fourteen days|14 days")),
 ("Urban v Zipper, 241 AD3d 1186 (1st Dept 2025)", "state", "case", "S6 statement timing", "1st Dept: 7-108(1-a)(e) timing measured from vacatur to sending.",
  S+"NY_CASE_Urban_v_Zipper_2025_241AD3d1186.txt", sent(r"General Obligations Law")),
 ("Karole v 340 W. End (Civ Ct 2022) / Prando v Kelly", "state", "case", "S8 willful", "Willful = knowing, intentional or deliberate failure; negligence or inadvertence is not willful.",
  S+"NY_CASE_Karole_v_340WEnd_2022.txt", r"requires more than inadvertence\[,\] and we have noted in other contexts that it requires actions performed .knowingly, intentionally or deliberately."),
 ("Lasky v Lissik (1931)", "state", "case", "S7 payee (co-tenants)", "Joint obligees without words of severance hold a joint right; payment to one discharges the obligor.",
  S+"NY_CASE_Lasky_v_Lissik_1931.txt", sent(r"assumed a several liability or acquired a several right")),
 ("Kunik v Club at Pearl River (App Term 2d 2023)", "state", "case", "S5 charges (early move-out)", "After early move-out, deposit may cover only rent already due, and mitigation under 227-e governs future rent.",
  S+"REVIEW2_NY_CASE_Kunik_v_ClubAtPearlRiver_2023_AppTerm2d.txt", sent(r"227-e")),
 ("JMD Holding Corp. v Congress Fin. Corp., 4 NY3d 373 (2005)", "state", "case", "S5 charges (liquidated damages)", "Liquidated damages enforceable only if actual damages hard to determine and sum not conspicuously disproportionate.",
  S+"REVIEW2_NY_CASE_JMD_Holding_v_Congress_2005_CoA.txt", sent(r"conspicuously disproportionate|readily ascertainable")),
 ("Truck Rent-A-Center v Puritan Farms 2nd, 41 NY2d 420 (1977)", "state", "case", "S5 charges (liquidated damages)", "Penalty clauses unenforceable; test of reasonable proportion to probable loss.",
  S+"REVIEW4A_NY_CASE_TruckRent_v_PuritanFarms_1977_CoA.txt", sent(r"A contractual provision fixing damages in the event of breach will be sustained if the amount liquidated bears a reasonable proportion to the probable loss")),
 ("172 Van Duzer Realty Corp. v Globe Alumni Student Assistance Assn., 24 NY3d 528 (2014)", "state", "case", "S5 charges (acceleration)", "Rent acceleration clause may be a penalty requiring a hearing on disproportion.",
  S+"REVIEW4A_NY_CASE_172VanDuzer_v_GlobeAlumni_2014_CoA.txt", sent(r"acceleration")),
 ("Riverside Research Inst. v KMGA, 68 NY2d 689 (1986)", "state", "case", "S2 surrender", "Surrender by operation of law requires conduct so inconsistent with the landlord-tenant relationship that both parties intend termination.",
  S+"REVIEW4A_NY_CASE_Riverside_v_KMGA_1986_CoA.txt", r"A surrender by operation of law occurs when the parties to a lease both do some act so inconsistent with the landlord-\*692tenant relationship that it indicates their intent to deem the lease terminated"),
 ("8902 Corp. v Helmsley-Spear, 12 AD3d 193 (1st Dept 2005)", "state", "case", "S5 belongings", "No bailment of tenant's left property without agreement.",
  S+"NY_CASE_8902Corp_v_HelmsleySpear_2005_1stDept.txt", sent(r"bailment")),
 ("Stauber v Antelo, 163 AD2d 246 (1st Dept 1990)", "state", "case", "S2 tenancy end", "RPL 232: NYC agreement without duration runs to October 1.",
  S+"SWEEP_NY_CASE_Stauber_v_Antelo_1990_1stDept.txt", sent(r"October")),
 ("Chazon, LLC v Maugenest, 19 NY3d 410 (2012)", "state", "case", "S10 preconditions (CO)", "MDL 302 bars rent for illegal occupancy of multiple dwelling (compliance cure prospective).",
  S+"REVIEW2_NY_CASE_Chazon_v_Maugenest_2012_CoA.txt", sent(r"Multiple Dwelling Law")),
 ("Fields v Pinkney (2d Dept 2025)", "state", "case", "S13 licensing", "Collecting rent for another for a fee requires a broker's licence.",
  S+"SWEEP_NY_CASE_Fields_v_Pinkney_2025_2dDept.txt", sent(r"licens")),
 ("Romea v Heiberger & Assocs., 163 F3d 111 (2d Cir 1998)", "federal", "case", "S13 collection (scope)", "Back rent is a 'debt' under the FDCPA; a rent demand by a collector is covered.",
  S+"US_CASE_Romea_v_Heiberger_1998.txt", sent(r"back rent")),
 ("Henson v Santander, 582 US 79 (2017)", "federal", "case", "S13 collection (scope)", "An entity collecting debts it owns for itself is not collecting debts 'owed another'.",
  S+"US_CASE_Henson_v_Santander_2017.txt", sent(r"owed or due another")),
 ("Heintz v Jenkins, 514 US 291 (1995)", "federal", "case", "S13 collection (lawyers)", "Lawyers who regularly collect consumer debts through litigation are debt collectors.",
  S+"REVIEW4A_US_CASE_Heintz_v_Jenkins_1995.txt", sent(r"litigation")),
 ("Avila v Riexinger & Assocs., 817 F3d 72 (2d Cir 2016)", "federal", "case", "S12 interest / S13", "A collector stating a balance that accrues interest or fees must disclose that it may increase.",
  S+"REVIEW4A_US_CASE_Avila_v_Riexinger_2016_2dCir.txt", r"We hold that Section 1692e of the FDCPA requires debt 8 collectors, when they notify consumers of their account balance, to disclose that 9 the balance may increase due to inter"),
 ("Alibrandi v Financial Outsourcing Servs., 333 F3d 82 (2d Cir 2003)", "federal", "case", "S13 collection (default)", "'Default' for FDCPA exclusion set by the contract or creditor's treatment, not the due date.",
  S+"US_CASE_Alibrandi_v_Financial_Outsourcing_2003.txt", sent(r"default")),
 ("Lefferts (2026)", "state", "case", "S11 limitations", "A residential lease balance is not a consumer credit transaction for CPLR 214-i.",
  S+"NY_CASE_Lefferts_v_Keennlyside_2026.txt", sent(r"consumer credit")),
 ("In re Sweet N Sour 7th Ave. Corp. (Bankr SDNY 2010)", "federal", "case", "S15 bankruptcy (setoff)", "Applying a deposit after the filing is a setoff stayed by 362(a)(7).",
  S+"US_CASE_In_re_Sweet_N_Sour_2010.txt", r"the automatic stay applies to any setoff effort, but not to a creditor’s recoupment"),
 ("Citizens Bank of Md. v Strumpf, 516 US 16 (1995)", "federal", "case", "S15 bankruptcy (hold)", "A temporary administrative hold pending relief is not a setoff.",
  S+"US_CASE_Citizens_Bank_v_Strumpf_1995.txt", sent(r"temporary")),
 ("S9760/A10182-A Consumer Debt Uniformity Act (passed both houses 2026-06-02/03; not delivered)", "state", "pending", "S11 limitations (future)", "If signed: three-year limit for actions on consumer debt including lease balances against natural persons, from its effective date.",
  S+"REVIEW4B_NY_A10182_status_2026-09-29.txt", r"06/03/2026 passed assembly 06/03/2026 returned to senate"),
 ("S00947/A03121 (ACH / online rent payment fee ban; passed Senate 2026-03-18, Assembly 2026-05-13; not delivered)", "state", "pending", "S5 charges (future)", "If signed: residential landlords may not charge fees for rent paid by ACH or online systems.",
  S+"REVIEW4A_NY_A03121_S00947_Assembly_2025-26.txt", r"2\. A landlord shall not assess any fee or other charge for the use of 9 an automated clearing house payment"),
 ("S09650/A00659 (421-a lease decontrol information; passed both houses 2026; not delivered)", "state", "pending", "S0 routing (future)", "If signed: $1,000 violation for incorrect rent-decontrol information in Affordable New York (421-a) leases; applies to leases from its 60th day.",
  S+"REVIEW5A_NY_A00659_Assembly_2025-26.txt", sent(r"incorrect information")),
]
