"""IR5A universe items, part 2: RPL art. 7, 6-A, 12-A; RPAPL."""
S = "sources/"
ITEMS = [
 ("RPL 220", "state", "statute", "S2 rent stops / use and occupancy", "Landlord may recover reasonable compensation for use and occupation where there is no rent agreement (holdover period).",
  S+"NY_RPL_220.txt", r"The landlord may recover a reasonable compensation for the use and occupation of real property, by any person, under an agreement, not made by deed"),
 ("RPL 223", "state", "statute", "S3 who may collect", "Grantee of the reversion or of the rent has the landlord's remedies for rent and breach.",
  S+"NY_RPL_223.txt", r"The grantee of leased real property, or of a reversion thereof, or of any rent[^.]*\."),
 ("RPL 223-b(5)", "state", "statute", "S2 non-renewal", "Non-renewal or eviction within a year after a tenant's good-faith complaint raises a rebuttable presumption of retaliation (owner-occupied <4-unit exception).",
  S+"REVIEW5A_NY_RPL_223-b.txt", r"5\. In an action or proceeding instituted against a tenant[^.]*\."),
 ("RPL 226-b", "state", "statute", "S3 who owes (assignment/sublet)", "Unreasonable refusal of assignment consent: tenant released on 30 days' notice; building with 4+ units: right to sublet with consent not unreasonably withheld; sublessor stays liable.",
  S+"NY_RPL_226-B.txt", ("consent may be unconditionally withheld without cause provided that the owner shall release the tenant", "the tenant shall not be released from the lease.")),
 ("RPL 226-c", "state", "statute", "S2 tenancy end", "Non-renewal or >=5% increase needs 30/60/90 days' written notice by occupancy length; if late, tenancy continues on existing terms until the notice period expires.",
  S+"NY_RPL_226-C.txt", r"If the landlord fails to provide timely notice, the occupant's lawful tenancy shall continue under the existing terms of the tenancy[^.]*\."),
 ("RPL 227", "state", "statute", "S2 rent stops", "Building destroyed/untenantable without tenant's fault and no contrary written agreement: tenant may surrender and owes no rent after surrender; prepaid rent refundable.",
  S+"NY_RPL_227.txt", ("the lessee or occupant may, if the destruction or injury occurred without his or her fault or neglect", "rent for the time subsequent to the surrender.")),
 ("RPL 227-a", "state", "statute", "S2 rent stops (senior / disability)", "Tenant 62+ or with disability entering care/family residence may terminate; released from rent after the termination date.",
  S+"NY_RPL_227-A.txt", r"to release the lessee or tenant from any liability to pay to the lessor or owner, rent or other payments in lieu of rent for the time subsequent to the date of termination[^;]*"),
 ("RPL 227-c", "state", "statute", "S2 rent stops (domestic violence)", "DV victim may terminate on court order; released from rent after termination date.",
  S+"NY_RPL_227-C.txt", r"to be released from any liability to pay to the lessor or owner, rent or other payments in lieu of rent for the time subsequent to the date of termination of such lease in accordance with subdivision two of this section\."),
 ("RPL 227-d", "state", "statute", "S21 anti-discrimination", "Owner/manager may not discriminate in terms or conditions because of domestic violence victim status.",
  S+"REVIEW4A_NY_RPL_227-D_nysenate.txt", r"\(a\) No person, firm or corporation owning or managing any building used for dwelling purposes[^;]*"),
 ("RPL 227-e", "state", "statute", "S5 charges (lease-break rent)", "Landlord must mitigate in good faith; new tenant's lease at FMV or agreed rent terminates the prior lease; burden on the party seeking damages; waiver void.",
  S+"NY_RPL_227-E.txt", ("the new tenant's lease shall, once in effect, terminate the previous tenant's lease", "The burden of proof shall be on the party seeking to recover damages.")),
 ("RPL 228", "state", "statute", "S2 tenancy end", "Tenancy at will or by sufferance ends by 30-day written notice served as specified.",
  S+"NY_RPL_228.txt", r"A tenancy at will or by sufferance, however created, may be terminated by a written notice of not less than thirty days[^;]*"),
 ("RPL 229", "state", "statute", "S5 charges (holdover)", "Tenant who gave notice to quit and holds over owes double rent while in possession.",
  S+"NY_RPL_229.txt", r"If a tenant gives notice of his intention to quit the premises held by him[^.]*\."),
 ("RPL 232", "state", "statute", "S2 tenancy end", "NYC agreement not stating duration: runs to the next October 1.",
  S+"REVIEW2_NY_RPL_232_nysenate.txt", r"[^.]*until the first day of October next[^.]*\."),
 ("RPL 232-a", "state", "statute", "S2 tenancy end", "NYC monthly tenancy: landlord must serve notice for the 226-c period (residential) before removal for holding over.",
  S+"NY_RPL_232-A.txt", r"unless pursuant to the notice period required by subdivision two of section two hundred twenty-six-c of this article"),
 ("RPL 232-c", "state", "statute", "S2 tenancy end", "Acceptance of rent after a term >1 month creates a month-to-month tenancy absent other agreement.",
  S+"NY_RPL_232-C.txt", r"the tenancy created by the acceptance of such rent shall be a tenancy from month to month commencing on the first day after the expiration of such term\."),
 ("RPL 234", "state", "statute", "S10 fees", "A lease clause giving landlord attorneys' fees implies a reciprocal covenant for the tenant.",
  S+"NY_RPL_234.txt", r"there shall be implied in such lease a covenant by the landlord to pay to the tenant the reasonable attorneys' fees[^,]*"),
 ("RPL 234-a", "state", "statute", "S5 charges", "No fee or charge for legal services (court fees, attorney fees, notary, administrative fees) may be assessed on a residential tenant without a court order.",
  S+"NY_RPL_234-A.txt", ("(a) An owner, lessor or agent thereof shall be prohibited from assessing a lessee any fee, surcharge or other charges for legal services", "pursuant to a court order.")),
 ("RPL 235-b", "state", "statute", "S5 credits (habitability)", "Warranty of habitability; waivers void; damages (abatement) need no expert proof.",
  S+"NY_RPL_235-B.txt", r"2\. Any agreement by a lessee or tenant of a dwelling waiving or modifying his rights as set forth in this section shall be void as contrary to public policy\."),
 ("RPL 235-c", "state", "statute", "S5 charges", "Court may refuse to enforce an unconscionable lease clause.",
  S+"NY_RPL_235-C.txt", r"1\. If the court as a matter of law finds a lease or any clause of the lease to have been unconscionable[^.]*\."),
 ("RPL 235-e(d)", "state", "statute", "S5 charges / S10 procedure", "Rent not received within 5 days of due date: lessor must send certified-mail notice; failure is an affirmative defense in a nonpayment proceeding.",
  S+"NY_RPL_235-E.txt", ("(d) If a lessor, or an agent of a lessor authorized to receive rent, fails to receive payment for rent within five days", "stating the failure to receive such rent payment.")),
 ("RPL 235-f", "state", "statute", "S3 who owes", "Occupants are not tenants; lease construed to allow tenant, family, one additional occupant and dependents.",
  S+"NY_RPL_235-F.txt", r"\(b\) \"Occupant\" means a person, other than a tenant or a member of a tenant's immediate family, occupying a premises with the consent of the tenant or tenants\."),
 ("RPL 235-g", "state", "statute", "S7 payment method", "Landlord may not require electronic payment as the only method nor charge a fee to a tenant who does not use it; waiver void.",
  S+"NY_RPL_235-G.txt", ("1. A landlord shall not require a lessee or tenant to use an electronic billing and/or payment system", "that chooses not to use an electronic billing and/or payment system.")),
 ("RPL 235-i", "state", "statute", "S5 charges", "Key reproduction fee capped at 110% of actual cost (unless >3 reproductions a year).",
  S+"NY_RPL_235-I.txt", r"A landlord shall not charge a tenant a fee for the reproduction of keys[^.]*\."),
 ("RPL 236", "state", "statute", "S16 death", "Deceased tenant's representative may request assignment/sublet; landlord's unreasonable refusal releases the estate from the lease.",
  S+"NY_RPL_236.txt", r"the executor, administrator or legal representative of a deceased tenant under such a lease, may request the landlord thereunder to consent to the assignment of such a lease, or to the subletting of the premises demised thereby\."),
 ("RPL 236-a", "state", "statute", "S16 death / S2 tenancy end", "Estate may terminate the lease on notice (registered/certified mail) plus surrender, with co-tenant/guarantor written consent; estate owes rent and damages before termination but no penalty for inadequate notice.",
  S+"NY_RPL_236-A.txt", ("the executor, administrator or legal representative of a deceased tenant under such a lease shall have the option to terminate such a lease upon notice given to the landlord", "breach of inadequate notice as a result of terminating a lease under this section.")),
 ("RPL 238-a(1)(a)", "state", "statute", "S5 charges", "No fee at or before the tenancy except background/credit check capped at actual cost or $20.",
  S+"NY_RPL_238-A.txt", r"no more than the actual cost of the background check and credit check or twenty dollars, whichever is less"),
 ("RPL 238-a(2)", "state", "statute", "S5 charges (late fee)", "Late fee only after 5 days and capped at the lesser of $50 or 5% of monthly rent.",
  S+"NY_RPL_238-A.txt", ("2. No landlord, lessor, sub-lessor or grantor may demand any payment, fee, or charge for the late payment of rent", "fifty dollars or five percent of the monthly rent, whichever is less")),
 ("RPL 211 (Good Cause definitions)", "state", "statute", "S2 non-renewal", "Good Cause Eviction definitions (local rent standard etc.) apply to covered NYC housing.",
  S+"NY_RPL_211_justia.txt", r"8\. The term \"local rent standard\" shall mean a rent increase equal to the inflation index or ten percent, whichever is lower\."),
 ("RPL 214", "state", "statute", "S2 non-renewal", "Good Cause exemptions (e.g., small landlord, rent above 245% FMR) decide whether the unit is covered.",
  S+"REVIEW1_NY_RPL_214_nysenate.txt", r"[^.]*two hundred forty-five percent[^.]*\."),
 ("RPL 215-216", "state", "statute", "S2 non-renewal", "Covered tenant may not be removed or denied renewal without good cause listed in 216.",
  S+"REVIEW1_NY_RPL_215_nysenate.txt", r"No landlord shall, by action to evict or to recover possession, by exclusion from possession, by failure to renew any lease, or otherwise, remove any tenant from housing accommodations covered by se[^.]*\."),
 ("RPL 218", "state", "statute", "S2 non-renewal", "Waivers of Good Cause rights are void.",
  S+"REVIEW5A_NY_RPL_218.txt", r"Section 218 Waiver of rights void .{0,300}?public policy\."),
 ("RPL 440-a / 440(1)", "state", "statute", "S13 licensing", "Collecting rent for another for a fee requires a real estate broker licence.",
  S+"SWEEP_NY_RPL_440_nysenate.txt", r"[^.]*collects or offers or attempts to collect rent for the use of real estate[^.]*"),
 ("RPL 442-d", "state", "statute", "S13 licensing", "Unlicensed person cannot sue to recover compensation for broker services.",
  S+"SWEEP_NY_RPL_442-D_nysenate.txt", r"No person, copartnership, limited liability company or corporation shall bring or maintain an action[^.]*\."),
 ("RPL 441-c", "state", "statute", "S13 licensing", "DOS may revoke/suspend/fine a licensee for untrustworthiness, incompetency or fraud.",
  S+"REVIEW5A_NY_RPL_441-c.txt", r"[^.]*untrustworth[^.]*\."),
 ("RPAPL 702", "state", "statute", "S5 charges", "In residential summary proceedings, rent is only the monthly amount; fees, charges and penalties are not rent.",
  S+"NY_RPAPL_702.txt", ("the term \"rent\" shall mean the monthly or weekly amount charged", "notwithstanding any language to the contrary in any lease or rental agreement.")),
 ("RPAPL 711(2)", "state", "statute", "S2 tenancy end (nonpayment)", "Nonpayment proceeding requires a written 14-day rent demand.",
  S+"REVIEW5A_NY_RPAPL_711.txt", r"[^.]*fourteen days[^.]*\."),
 ("RPAPL 744", "state", "statute", "S18 domestic violence", "No eviction or refusal to renew because the tenant is a DV victim.",
  S+"REVIEW5A_NY_RPAPL_744.txt", r"1\. A tenant shall not be removed from possession of a residential unit pursuant to this article because of such person.s domestic violence victim status"),
 ("RPAPL 749(3)", "state", "statute", "S2 rent stops / S9 balance", "After a summary proceeding, landlord may recover by action sums payable at commencement plus reasonable use and occupancy to the warrant.",
  S+"REVIEW5A_NY_RPAPL_749.txt", ("Petitioner may recover by action any sum of money which was payable at the time when the special proceeding was commenced", "make any provision for payment of rent.")),
 ("RPAPL 768", "state", "statute", "S2 tenancy end (self-help)", "Evicting a 30-day occupant without a warrant (including removing possessions or changing locks) is unlawful: class A misdemeanor and $1,000-$10,000 civil penalty per violation.",
  S+"REVIEW5A_NY_RPAPL_768.txt", ("(b) Such person shall also be subject to a civil penalty of not less than one thousand", "for each violation.")),
 ("RPAPL 853", "state", "statute", "S2 tenancy end (self-help)", "Forcible or unlawful removal entitles the occupant to treble damages.",
  S+"REVIEW5A_NY_RPAPL_853.txt", ("If a person is disseized, ejected, or put out of real property in a forcible or unlawful manner", "he is entitled to recover treble damages in an action therefor against the wrong-doer.")),
 ("RPAPL 769-778 (art. 7-A)", "state", "statute", "S3 who may collect", "In a 7-A proceeding rents are paid to the court-appointed administrator, not the owner.",
  S+"SWEEP_NY_RPAPL_778_nysenate.txt", r"to demand, collect and receive the rents from the tenants"),
 ("RPAPL 1305", "state", "statute", "S3 successor (foreclosure)", "Successor in interest after foreclosure takes subject to residential tenancies; notice rules.",
  S+"REVIEW4A_NY_RPAPL_1305_nysenate.txt", r"\(b\) \"Successor in interest\" shall mean any person or entity who or which acquires title in a residential real property as a result of a judgment of foreclosure and sale[^,]*"),
 ("22 NYCRR 208.42(g)", "state", "rule", "S10 preconditions", "Summary-proceeding petition must allege MD registration status (MDL 325; Admin. Code 27-2097).",
  S+"SWEEP_NY_22NYCRR_208.42_LII.txt", ("In every summary proceeding brought to recover possession of real property pursuant to section 711", "there is a currently effective registration statement on file")),
]
