"""IR5A universe items, part 1: GOL art. 7 (deposit), other GOL, UCC. Quote spec: regex (str) or (start, end) anchors."""
S = "sources/"
ITEMS = [
 ("GOL 7-108(1)", "state", "statute", "S0 routing", "7-108 governs every dwelling unit not referred to in 7-107 (rent-stabilized); a market-rate NYC unit is under 7-108.",
  S+"NY_GOL_7-108_nysenate.txt", r"This section shall apply to all dwelling units in residential premises, unless such dwelling unit is specifically referred to in section 7-107 of this title"),
 ("GOL 7-108(1-a) preamble", "state", "statute", "S0 routing", "Subdivision 1-a does not reach rent-controlled units, CCRCs, assisted living, adult care, senior offering-plan communities and certain NFP retirement communities.",
  S+"NY_GOL_7-108_nysenate.txt", ("1-a. Except in dwelling units subject to the city rent and rehabilitation law", "meals to their residents:")),
 ("GOL 7-108(1-a)(a)", "state", "statute", "S1 move-in / S4 deposit", "Deposit or advance capped at one month's rent (seasonal and owner-occupied co-op exceptions).",
  S+"NY_GOL_7-108_nysenate.txt", ("(a) No deposit or advance shall exceed the amount of one month's rent", "subdivision six of this section.")),
 ("GOL 7-108(1-a)(b)", "state", "statute", "S5 charges", "Only four heads may be kept from the deposit (unpaid rent, tenant damage beyond normal wear, lease utility charges payable to landlord, moving/storage of belongings); never wear and tear or prior-tenant damage.",
  S+"NY_GOL_7-108_nysenate.txt", ("(b) The entire amount of the deposit or advance shall be refundable", "damage caused by a prior tenant.")),
 ("GOL 7-108(1-a)(c)", "state", "statute", "S1 move-in", "Landlord must offer a pre-occupancy inspection; conditions noted in the signed agreement cannot be charged at move-out.",
  S+"NY_GOL_7-108_nysenate.txt", ("(c) After initial lease signing but before the tenant begins occupancy", "noted in such agreement.")),
 ("GOL 7-108(1-a)(d)", "state", "statute", "S2 pre-vacate inspection", "After either party's notice of termination (unless tenant gives <2 weeks), landlord must give written notice of the right to a pre-vacate inspection; inspection 1-2 weeks before end, 48h notice, itemized proposed deductions, opportunity to cure.",
  S+"NY_GOL_7-108_nysenate.txt", ("(d) Within a reasonable time after notification of either party's intention to terminate the tenancy", "before the end of the tenancy.")),
 ("GOL 7-108(1-a)(e)", "state", "statute", "S6 statement / S8 miss", "Itemized statement and refund within 14 days after vacatur; failure forfeits any right to retain any portion.",
  S+"NY_GOL_7-108_nysenate.txt", ("(e) Within fourteen days after the tenant has vacated the premises", "forfeit any right to retain any portion of the deposit.")),
 ("GOL 7-108(1-a)(f)", "state", "statute", "S8 dispute", "Landlord bears the burden of proving the reasonableness of any amount retained.",
  S+"NY_GOL_7-108_nysenate.txt", ("(f) In any action or proceeding disputing", "reasonableness of the amount retained.")),
 ("GOL 7-108(1-a)(g)", "state", "statute", "S8 miss", "Violation: actual damages; willful violation: punitive damages up to twice the deposit.",
  S+"NY_GOL_7-108_nysenate.txt", ("(g) Any person who violates the provisions of this subdivision", "twice the amount of the deposit or advance.")),
 ("GOL 7-108(2)", "state", "statute", "S3 successor", "Grantee/assignee with actual knowledge is also liable for the deposit plus interest when not turned over; knowledge deemed from bank deposit within 6 months, lease acknowledgment or tenant documentary evidence; 30-day no-record notice procedure.",
  S+"NY_GOL_7-108_nysenate.txt", ("2. (a) In circumstances where any sum of money", "as to which such grantee or assignee has actual knowledge.")),
 ("GOL 7-103(1)", "state", "statute", "S4 trust", "Deposit remains tenant's money, held in trust, not commingled or an asset of the landlord.",
  S+"NY_GOL_7-103_nysenate.txt", ("such money, with interest accruing thereon, if any, until repaid or so applied", "may be disposed of as provided in section 7-105 of this chapter.")),
 ("GOL 7-103(2)", "state", "statute", "S4 custody / interest", "If banked: written notice to tenant of bank name, address and amount; NY bank; 1% per annum administration fee in lieu of all other expenses; balance of interest is tenant's, held in trust or paid annually.",
  S+"NY_GOL_7-103_nysenate.txt", ("If the person depositing such security money in a banking organization shall deposit same in an interest bearing account", "annually paid to the person making the deposit of security money.")),
 ("GOL 7-103(2-a)", "state", "statute", "S4 interest", "Property with six or more family dwelling units: deposit must be in an interest-bearing NY account at the prevailing rate.",
  S+"NY_GOL_7-103_nysenate.txt", ("2-a. Whenever the money so deposited or advanced is for the rental of property containing six or more family dwelling units", "made with banking organizations in such area.")),
 ("GOL 7-103(2-b)", "state", "statute", "S4 interest at termination", "Lease ending between bank interest dates: landlord pays the interest it is able to collect at termination.",
  S+"NY_GOL_7-103_nysenate.txt", ("2-b. In the event that a lease terminates", "at the date of such lease termination.")),
 ("GOL 7-103(3)", "state", "statute", "S4 waiver", "Any lease waiver of 7-103 is absolutely void.",
  S+"NY_GOL_7-103_nysenate.txt", ("3. Any provision of such a contract or agreement whereby a person who so deposits", "is absolutely void.")),
 ("GOL 7-105", "state", "statute", "S3 successor / transfer", "On conveyance, lease assignment, foreclosure receiver or referee sale, deposit must be turned over within 5 days with registered/certified-mail notice to tenant; turning over relieves the transferor.",
  S+"NY_GOL_7-105_nysenate.txt", ("Turn over to his or its grantee or assignee", "name and address of such grantee, assignee, purchaser or receiver.")),
 ("GOL 5-328 as amended by L.2025 c.431", "state", "statute", "S5 charges", "Dishonored rent check fee: residential landlord may charge only the greater of actual cost or $20, and only if the lease provides for it.",
  S+"REVIEW4A_NY_A00056_Assembly_2025-26.txt", r"may only charge a tenant the Greater of the actual cost of a dishonored check or \$20, provided the charge was contr"),
 ("GOL 5-905", "state", "statute", "S2 tenancy end", "Lease auto-renewal clause is unenforceable unless landlord gives the tenant written notice 15-30 days before the renewal-notice date.",
  S+"REVIEW1_NY_GOL_5-905_nysenate.txt", r"No provision of a lease[^.]*shall be operative unless the lessor[^.]*\."),
 ("GOL 5-703(1)", "state", "statute", "S2 surrender", "A lease interest over one year can be surrendered only in writing or by operation of law.",
  S+"SWEEP_NY_GOL_5-703_nysenate.txt", r"An estate or interest in real property, other than a lease for a term not exceeding one year[^.]*\."),
 ("GOL 5-701(a)(1)-(2)", "state", "statute", "S3 who owes (guarantor)", "Guaranty ('special promise to answer for the debt ... of another') and agreements not performable within a year are void unless in a signed writing.",
  S+"REVIEW4A_NY_GOL_5-701_nysenate.txt", r"special promise to answer for the debt, default or miscarriage of another person"),
 ("GOL 15-104", "state", "statute", "S9 co-tenant settlement", "Releasing one co-obligor with express reservation of rights keeps the claim against co-obligors, reduced by the amount paid.",
  S+"REVIEW5A_NY_GOL_15-104.txt", r"Section 15-104 Discharge of one obligor, with reservations .{0,700}?\. "),
 ("GOL 15-105", "state", "statute", "S9 co-tenant settlement", "Release of one co-tenant without express reservation satisfies the claim against the others to the released obligor's share (known contribution share, or lesser of fractional share and contribution share).",
  S+"REVIEW5A_NY_GOL_15-105.txt", ("1. If an obligee releasing or discharging an obligor without express reservation of rights", "was bound by his contract or relation with the co-obligor to pay.")),
 ("GOL 15-301(1)", "state", "statute", "S2 surrender / modification", "A lease with a no-oral-modification clause cannot be changed by an executory oral agreement.",
  S+"REVIEW5A_NY_GOL_15-301.txt", r"1\. A written agreement or other written instrument which contains a provision to the effect that it cannot be changed orally, cannot be changed by an executory agreement unless such executory agreement is in writing and signed by the party against whom enforcement of the change is sought or by his agent\."),
 ("GOL 15-501", "state", "statute", "S9 settlement", "A payment-plan or settlement agreement with the former tenant is an executory accord and is enforceable as a defense or claim even though discharge occurs later.",
  S+"REVIEW5A_NY_GOL_15-501.txt", ("2. An executory accord shall not be denied effect as a defense", "was to occur at a time after the makin")),
 ("UCC 1-308", "state", "statute", "S9 partial payment marked in full", "Cashing a payment tendered as full satisfaction with an explicit reservation of rights ('without prejudice', 'under protest') preserves the balance claim.",
  S+"REVIEW5A_NY_UCC_1-308.txt", ("A party that with explicit reservation of rights performs", "are sufficient.")),
 ("Horn Waterproofing Corp. v Bushwick Iron & Steel Co., 66 NY2d 321 (1985)", "state", "case", "S9 partial payment marked in full", "Court of Appeals: the UCC reservation-of-rights section lets a creditor cash a full-payment check under protest without accord and satisfaction.",
  S+"REVIEW5A_NY_CASE_Horn_Waterproofing_v_Bushwick_1985_CoA.txt", r"[^.]*1-207[^.]*full payment check[^.]*\."),
 ("GOL 17-101", "state", "statute", "S11 limitations", "Acknowledgment or promise that revives/extends limitations must be in a signed writing.",
  S+"REVIEW4A_NY_GOL_17-101_nysenate.txt", r"An acknowledgment or promise contained in a writing signed by the party to be charged thereby is the only competent evidence of a new or continuing contract"),
 ("GOL 17-103", "state", "statute", "S11 limitations", "Written promise after accrual not to plead the statute is effective for the statutory period from the promise; pre-accrual waivers in the lease are unenforceable.",
  S+"REVIEW5A_NY_GOL_17-103.txt", ("1. A promise to waive, to extend, or not to plead the statute of limitation applicable", "or within such shorter time as may be provided in the promise.")),
 ("GOL 5-702", "state", "statute", "S1 lease form", "Residential lease must be plain-language; violation gives actual damages plus $50 but does not void the lease.",
  S+"REVIEW5A_NY_GOL_5-702.txt", ("b. A violation of the provisions of subdivision a of this section shall not render any such agreement void or voidable", "for breach of such agreement.")),
]
