"""IR5A universe items, part 4: GBL, Judiciary, SSL, ABP, SCPA, Military, Executive, entity capacity, NY regulations."""
S = "sources/"
def sent(k):
    return r"[^.;]*" + k + r"[^.;]*[.;]"
ITEMS = [
 ("GBL 349 as amended by L.2025 c.708 (FAIR Business Practices Act, eff. 2026-02-17)", "state", "statute", "S5 charges / S13 collection conduct", "Unfair, deceptive or abusive business acts are unlawful (AG enforcement for unfair/abusive, no consumer-oriented limit); private action stays limited to deceptive practices (actual damages or $50, trebling to $1,000, fees).",
  S+"REVIEW5A_NY_GBL_349.txt", ("(a) Unfair, deceptive, or abusive acts or practices in the conduct of any business, trade or commerce", "are hereby declared unlawful.")),
 ("GBL 349(h)", "state", "statute", "S8 exposure", "Private right of action only for deceptive acts.",
  S+"REVIEW5A_NY_GBL_349.txt", ("(h) In addition to the right of action granted to the attorney general pursuant to this section, any person who has been injured by reason of any deceptive act or deceptive practice", "whichever is greater, or both such actions.")),
 ("L.2025 c.708 s.6", "state", "statute", "S5/S13 effective date", "FAIR Act took effect on the 60th day after 2025-12-19 signature.",
  S+"REVIEW5A_NY_A08427A_S08416_FAIR_Act_L2025c708_Assembly.txt", r"§ 6\. This act shall take effect on the sixtieth day after it shall 29 have become a law\."),
 ("GBL 600(1)", "state", "statute", "S13 collection conduct (scope)", "NY Fair Debt Collection Practices (art. 29-H) reaches only 'consumer claims' arising from credit offered or extended; a lease balance for rent already due is not credit.",
  S+"NY_GBL_600.txt", sent(r"\"Consumer claim\" means any obligation of a natural person")),
 ("GBL 601", "state", "statute", "S13 collection conduct", "Principal creditors and agents collecting consumer claims may not simulate law enforcement, collect unlawful amounts, threaten, harass, etc.",
  S+"NY_GBL_601.txt", r"No principal creditor, as defined by this article, or his agent shall:"),
 ("GBL 604-aa(3) (coerced debt), L.2025 c.710 as amended by L.2026 c.90", "state", "statute", "S18 coerced debt", "A debt from a personal/household transaction incurred through coercion in intimate/family relationships is coerced debt; creditor enforcement barred after adequate documentation; applies to debts incurred on or after the 180th day after 2025-12-19.",
  S+"REVIEW4A_NY_GBL_604-AA_nysenate.txt", sent(r"\"Coerced debt\" means a debt arising out of a transaction primarily for personal, family or household purposes")),
 ("L.2026 c.90 (A9460/S8830) effective-date amendment", "state", "statute", "S18 coerced debt (date)", "Coerced-debt article effective on the 180th day after it became law and applies to debts incurred on or after that date.",
  S+"REVIEW5A_NY_A09460_Assembly_2025-26.txt", r"shall take effect on the \[ninetieth day\] one hundred 10 eightieth day after it shall have become a law and shall apply to debts 11 incurred on or after such date\."),
 ("GBL 604-a (identity theft)", "state", "statute", "S18 identity theft", "On police/FTC identity-theft report plus statement, principal creditor must cease collection pending review (consumer claims only).",
  S+"REVIEW5A_NY_GBL_604-A.txt", ("1. Upon receipt from a debtor of the following, a principal creditor shall cease collection activities", "until completion of the review provided in subdivision five of this section")),
 ("GBL 130(9)", "state", "statute", "S10 capacity", "Business carried on under an assumed name without a filed certificate cannot maintain an action on contracts made in that name until it files.",
  S+"REVIEW5A_NY_GBL_130.txt", sent(r"shall be prohibited from maintaining any action or proceeding in any court in this state on any contract")),
 ("GBL 399-h", "state", "statute", "S20 data (closing records)", "Records with personal identifying information may be disposed of only by shredding, destroying or making the information unreadable.",
  S+"REVIEW5A_NY_GBL_399-H.txt", ("shall dispose of a record containing personal identifying information unless", "c. modifies the record to make the personal identifying information unreadable")),
 ("GBL 399-ddd", "state", "statute", "S20 data", "SSN may not be printed on mailed materials or otherwise exposed.",
  S+"REVIEW5A_NY_GBL_399-DDD.txt", ("(e) Print an individual’s social security account number on any materials that are mailed to the individual", "to be on the document to be mailed.")),
 ("GBL 899-aa", "state", "statute", "S20 data breach", "Breach of private information: notify affected residents in the most expedient time possible and within 30 days of discovery (plus AG/DOS/State Police; DFS for covered entities).",
  S+"REVIEW5A_NY_GBL_899-AA.txt", sent(r"within thirty days after the breach has been discovered")),
 ("GBL 899-bb", "state", "statute", "S20 data security", "Any business holding NY residents' private information must maintain reasonable safeguards, including disposal.",
  S+"REVIEW4A_NY_GBL_899-BB_nysenate.txt", sent(r"shall develop, implement and maintain reasonable safeguards")),
 ("Judiciary Law 489", "state", "statute", "S9 hand-off (assignment)", "A collection business or corporation may not take an assignment of a claim with intent and purpose to sue on it ($500,000 aggregate-price safe harbor); fine / misdemeanor.",
  S+"REVIEW5A_NY_JUD_489.txt", ("1. No person or co-partnership, engaged directly or indirectly in the business of collection and adjustment of claims", "with the intent and for the purpose of bringing an action or proceeding thereon")),
 ("Justinian Capital SPC v WestLB AG, 28 NY3d 160 (2016)", "state", "case", "S9 hand-off (assignment)", "Court of Appeals: an assignment taken for the primary purpose of suing is champertous; the safe harbor needs a binding $500,000 purchase-price obligation.",
  S+"REVIEW5A_NY_CASE_Justinian_Capital_v_WestLB_2016_CoA.txt", sent(r"primary purpose")),
 ("Judiciary Law 495", "state", "statute", "S10 who may sue / appear", "A corporation may not practice or appear as attorney for another person in court.",
  S+"REVIEW5A_NY_JUD_495.txt", ("1. No corporation or voluntary association shall (a) practice or appear as an attorney-at-law for any person in any court in this state", "for any person, in any of said courts")),
 ("Judiciary Law 478", "state", "statute", "S10 who may sue / appear", "Non-lawyers may not appear as attorney for another in a court of record.",
  S+"REVIEW5A_NY_JUD_478.txt", r"It shall be unlawful for any natural person to practice or appear as an attorney-at-law or as an attorney and counselor-at-law for a person other than himself or herself in a court of record in this state"),
 ("SSL 143-b(5)", "state", "statute", "S10 preconditions (public-assistance tenant)", "No money judgment against a public-assistance tenant for rent withheld during periods of reported dangerous/hazardous violations.",
  S+"REVIEW5A_NY_SSL_143-B.txt", ("(b) In any such action or proceeding the plaintiff or landlord shall not be entitled to an order or judgment", "detrimental to life or health.")),
 ("ABP 1315", "state", "statute", "S14 unclaimed funds", "Unclaimed amounts held by a business for three years are abandoned property reportable to the Comptroller.",
  S+"NY_ABP_1315.txt", sent(r"has remained unclaimed by the owner of such amount for three years")),
 ("ABP 1422", "state", "statute", "S14 unclaimed funds", "Holder must mail first-class owner notice at least 90 days before reporting.",
  S+"REVIEW2_NY_ABP_1422_justia.txt", sent(r"not less than ninety days prior to the applicable reporting date")),
 ("ABP 1400", "state", "statute", "S14 unclaimed funds", "Expiry of a limitations period does not relieve the holder of the duty to report and pay unclaimed property.",
  S+"REVIEW5A_NY_ABP_1400.txt", sent(r"The expiration of any period of time specified by law")),
 ("ABP 1412", "state", "statute", "S14 unclaimed funds (miss)", "Wilful failure to report: $100 per day forfeiture, plus interest on late-paid property.",
  S+"REVIEW5A_NY_ABP_1412.txt", sent(r"one hundred dollars for each da")),
 ("ABP 1412-a", "state", "statute", "S14 records", "Keep reporting records five years after the report year.",
  S+"REVIEW5A_NY_ABP_1412-A.txt", sent(r"shall retain for a period of five years")),
 ("SCPA 1310", "state", "statute", "S16 death (payee)", "Payment without administration (spouse up to $30,000 etc.) is limited to the debts 1310(1)(a) lists (bank deposits, insurance, public payments, wages); a landlord's deposit refund is not among them, so it goes to a fiduciary or SCPA 1301 voluntary administrator.",
  S+"REVIEW4A_NY_SCPA_1310_nysenate.txt", sent(r"not more than thirty thousand dollars of the debt")),
 ("SCPA 1802", "state", "statute", "S16 death (claim)", "Claim not presented within 7 months of letters: fiduciary not chargeable for good-faith payments made before presentation (present the balance claim early).",
  S+"REVIEW4A_NY_SCPA_1802_nysenate.txt", ("If any claim is not presented within 7 months from the date of issue of letters, the fiduciary shall not be chargeable", "before such claim was presented.")),
 ("EPTL 11-1.1", "state", "statute", "S16 death", "Fiduciary powers to settle and pay debts of the estate.",
  S+"SWEEP_NY_EPTL_11-1.1_nysenate.txt", sent(r"compromise")),
 ("Military Law 309", "state", "statute", "S17 military", "No eviction or distress against a person in military service (or dependents) for dwelling premises within the rent limit without court leave.",
  S+"REVIEW5A_NY_MIL_309.txt", sent(r"No eviction or distress shall be made during the period of military service")),
 ("Military Law 310", "state", "statute", "S17 military (termination)", "Service member may terminate a pre-service lease by written notice; monthly lease ends 30 days after the next rent date.",
  S+"NY_MIL_310.txt", ("2. Any such lease may be terminated by notice in writing delivered to the lessor", "at any time following the date of the beginning of such military service.")),
 ("Military Law 308", "state", "statute", "S17 military (tolling)", "Period of military service excluded from limitations.",
  S+"REVIEW4A_NY_MIL_308_nysenate.txt", sent(r"The period of military service shall not be included in computing any period")),
 ("Military Law 323-a", "state", "statute", "S17 military (interest)", "Pre-service obligations capped at 6% interest during service.",
  S+"REVIEW4A_NY_MIL_323-A_nysenate.txt", sent(r"bearing interest at a rate in excess of six percent per year")),
 ("Military Law 306", "state", "statute", "S17 military (procedure)", "Court may stay actions against persons in service before, during or within 60 days after service.",
  S+"REVIEW5A_NY_MIL_306.txt", r"In any action or proceeding commenced in any court.{0,400}?or within sixty days thereafter"),
 ("Executive Law 292(36)", "state", "statute", "S21 anti-discrimination", "Lawful source of income includes public assistance and housing assistance (vouchers).",
  S+"REVIEW5A_NY_EXC_292.txt", sent(r"The term “lawful source of income” shall include")),
 ("Executive Law 296(5)(a)", "state", "statute", "S21 anti-discrimination", "Owners/managers/agents may not discriminate in terms, conditions or privileges of rental on protected grounds incl. DV status and lawful source of income.",
  S+"REVIEW4A_NY_EXEC_296_nysenate.txt", r"status as a victim of domestic violence, lawful source of income or familial status in the terms, conditions or privileges of the sale, rental or lease of any such housing accommodation"),
 ("LLC Law 206", "state", "statute", "S10 capacity", "LLC that fails the publication requirement has its authority to do business suspended (cured by publication).",
  S+"REVIEW3_NY_LLC_206_nysenate.txt", sent(r"shall be suspended, effective as of the expiration of such one hundred twenty day period")),
 ("LLC Law 808", "state", "statute", "S10 capacity", "Unauthorized foreign LLC may not maintain an action until it obtains authority.",
  S+"REVIEW3_NY_LLC_808_nysenate.txt", sent(r"may not maintain any action, suit or special proceeding")),
 ("BCL 1312", "state", "statute", "S10 capacity", "Unauthorized foreign corporation may not maintain an action until authorized and taxes paid.",
  S+"REVIEW3_NY_BCL_1312_nysenate.txt", sent(r"shall not maintain any action or special proceeding in this state")),
 ("23 NYCRR 1.1(d)", "state", "regulation", "S13 collection conduct (scope)", "DFS debt-collection rule covers only debts from transactions in which credit was extended; a lease balance for rent is outside it.",
  S+"REVIEW2_NY_23NYCRR_1.1_justia.txt", ("(d) Debt means any obligation or alleged obligation of a consumer", "primarily for personal, family or household purposes.")),
 ("23 NYCRR 1.2-1.6", "state", "regulation", "S13 collection conduct", "Where it applies: 5-day disclosures, SOL disclosures, substantiation, written settlement confirmation, e-mail only with consent.",
  S+"REVIEW5A_NY_23NYCRR_1.6.txt", ("(a) After mailing a consumer written disclosures as required under section 1.2 of this Part, a debt collector may provide subsequent correspondence", "consented in writing to receive electronic mail correspondence from the debt collector in reference to a specific debt.")),
 ("19 NYCRR 175.1", "state", "regulation", "S4 custody (broker agent)", "Broker holding a principal's (incl. tenant) money must not commingle and must deposit in a separate special account within three business days.",
  S+"REVIEW4A_NY_19NYCRR_175.1_LII.txt", sent(r"A real estate broker shall not commingle the money or other property of his principal with his own")),
 ("16 NYCRR 96.2", "state", "regulation", "S5 charges (electricity)", "Submetered electric service to residential units only as authorized by PSC order and Part 96; otherwise no submetering charges.",
  S+"REVIEW5A_NY_16NYCRR_96.2.txt", ("(1) Electric service shall only be provided to a multi-unit residential premises in which individual dwelling units in the premises receive submetered electric service if the submetering", "authorized by commission order where a commission order was necessary")),
]
