"""IR5A universe items, part 6: federal statutes and regulations."""
S = "sources/"
def sent(k):
    return r"[^.;]*" + k + r"[^.;]*[.;]"
ITEMS = [
 ("15 USC 1692a(5)", "federal", "statute", "S13 collection (scope)", "FDCPA 'debt' = consumer obligation arising from a transaction primarily for personal/household purposes (rent included; no credit requirement).",
  S+"US_15USC_1692a.txt", sent(r"The term .debt. means any obligation or alleged obligation of a consumer to pay money arising out of a transaction")),
 ("15 USC 1692a(6)", "federal", "statute", "S13 collection (scope)", "'Debt collector' = principal purpose collection or regularly collecting debts owed another; creditor using another name included; exclusions (F).",
  S+"US_15USC_1692a.txt", sent(r"regularly collects or attempts to collect, directly or indirectly, debts owed or due or asserted to be owed or due another")),
 ("15 USC 1692c", "federal", "statute", "S13 collection conduct", "Communication limits: times/places, represented consumers, third parties, cease on written request.",
  S+"US_15USC_1692c.txt", sent(r"the convenient time for communicating with a consumer is after 8 o.clock antemeridian and before 9 o.clock postmeridian")),
 ("15 USC 1692e", "federal", "statute", "S13 collection conduct", "No false, deceptive or misleading representation (character, amount, legal status).",
  S+"US_15USC_1692e.txt", sent(r"false, deceptive, or misleading representation or means in connection with the collection of any debt")),
 ("15 USC 1692f(1)", "federal", "statute", "S5 charges / S13", "Collecting any amount not expressly authorized by the agreement or permitted by law is unfair.",
  S+"US_15USC_1692f.txt", sent(r"unless such amount is expressly authorized by the agreement creating the debt or permitted by law")),
 ("15 USC 1692g", "federal", "statute", "S13 collection conduct", "Validation notice within five days of initial communication; 30-day dispute window; verification before resuming.",
  S+"US_15USC_1692g.txt", sent(r"Within five days after the initial communication with a consumer")),
 ("15 USC 1692i", "federal", "statute", "S10 forum", "Debt collector suit must be brought where the consumer signed the contract or resides.",
  S+"US_15USC_1692i.txt", sent(r"in which such consumer signed the contract sued upon")),
 ("15 USC 1692k", "federal", "statute", "S8 exposure", "Actual damages plus statutory damages up to $1,000, fees; one-year limitation; bona fide error defense.",
  S+"US_15USC_1692k.txt", sent(r"not exceeding \$1,000")),
 ("12 CFR 1006.14(b)(2)", "federal", "regulation", "S13 collection conduct", "Call-frequency presumption: more than seven calls in seven days, or within seven days after a conversation.",
  S+"US_12CFR_1006.txt", r"\(A\) More than seven times within seven consecutive days; nor \(B\) Within a period of seven consecutive days after having had a telephone conversation with the person"),
 ("12 CFR 1006.26(b)", "federal", "regulation", "S11 limitations (time-barred)", "Debt collector must not sue or threaten to sue on a time-barred debt.",
  S+"US_12CFR_1006.txt", sent(r"A debt collector must not bring or threaten to bring a legal action against a consumer to col")),
 ("12 CFR 1006.30(a)", "federal", "regulation", "S20 credit reporting", "No furnishing to a CRA before communicating with the consumer (passive reporting bar).",
  S+"US_12CFR_1006.txt", r"a debt collector must not furnish to a consumer reporting agency, as defined in section 603\(f\) of the Fair Credit Reporting Act \(15 U\.S\.C\. 1681a\(f\)\), information about a debt before the debt collector:"),
 ("12 CFR 1006.34", "federal", "regulation", "S13 validation", "Validation information content incl. itemization date and itemized interest, fees, payments, credits.",
  S+"US_12CFR_1006.txt", r"\(3\) Itemization date means any one of the following five reference dates for which a debt collector can ascertain the amount of the debt:"),
 ("12 CFR 1006.100", "federal", "regulation", "S13 records", "Debt collector keeps records of compliance for three years after last collection activity.",
  S+"US_12CFR_1006.txt", sent(r"three years after the debt collector.s last collection activity on the debt")),
 ("12 USC 5481(15)(A)(ii)", "federal", "statute", "S13 scope (CFPA)", "Residential lease is not a 'consumer financial product' unless a financial lease; Reg F's CFPA-dependent parts optional.",
  S+"US_12USC_5481.txt", sent(r"on a non-operating basis")),
 ("15 USC 1681b(a)(3)(A)", "federal", "statute", "S20 credit reporting", "Pulling a consumer report is permitted to review or collect an account of the consumer.",
  S+"REVIEW5A_US_15USC_1681b.txt", sent(r"review or collection of an account of, the consumer")),
 ("15 USC 1681c(a)(4),(c)", "federal", "statute", "S20 credit reporting", "Collection/charged-off accounts reportable only seven years, running from 180 days after delinquency commencement.",
  S+"REVIEW5A_US_15USC_1681c.txt", sent(r"Accounts placed for collection or charged to profit and loss which antedate the report by more than seven years")),
 ("15 USC 1681s-2(a)", "federal", "statute", "S20 credit reporting", "Furnisher duties: accuracy, notice of dispute, delinquency date within 90 days of furnishing; no private action for (a).",
  S+"US_15USC_1681s-2.txt", sent(r"shall not furnish any information relating to a consumer to any consumer reporting agency if the person knows or has reasonable cause to believe that the information is inaccurate")),
 ("12 CFR 1022.42", "federal", "regulation", "S20 credit reporting", "Furnishers must have written accuracy/integrity policies.",
  S+"US_12CFR_1022.42.txt", sent(r"must establish and implement reasonable written policies and procedures")),
 ("47 USC 227(b)(1)(A)(iii)", "federal", "statute", "S13 collection conduct (calls/texts)", "Calls/texts to a cell phone using an autodialer or artificial/prerecorded voice need prior express consent; $500-$1,500 per call.",
  S+"REVIEW5A_US_47USC_227_TCPA.txt", sent(r"to any telephone number assigned to a paging service, cellular telephone service")),
 ("47 CFR 64.1200(a)(10)", "federal", "regulation", "S13 collection conduct (consent revocation)", "Called party may revoke consent by any reasonable means; honor within ten business days.",
  S+"REVIEW5A_US_47CFR_64.1200.txt", sent(r"revoke prior express consent")),
 ("Facebook, Inc. v Duguid, 592 US 395 (2021)", "federal", "case", "S13 collection conduct (calls/texts)", "An autodialer must use a random or sequential number generator; ordinary stored-number dialing is not an ATDS (prerecorded-voice rule still applies).",
  S+"REVIEW5A_US_CASE_Facebook_v_Duguid_2021_SCOTUS.txt", sent(r"random or sequential number generator")),
 ("15 USC 7001(a),(c)", "federal", "statute", "S6 delivery (electronic)", "Where law requires information be provided to a consumer in writing, electronic delivery satisfies it only after the consumer's affirmative E-SIGN consent with required disclosures.",
  S+"REVIEW5A_US_15USC_7001_ESIGN.txt", sent(r"the consumer has affirmatively consented to such use and has not withdrawn such consent")),
 ("50 USC 3955", "federal", "statute", "S17 military (termination)", "Servicemember may terminate residential lease on PCS/deployment; rent prorated; prepaid rent refunded within 30 days; no early termination charge.",
  S+"US_50USC_3955.txt", sent(r"within 30 days of the effective date of the termination of the lease")),
 ("50 USC 3931", "federal", "statute", "S17 military (default judgment)", "Before any default judgment, plaintiff must file an affidavit on the defendant's military service.",
  S+"US_50USC_3931.txt", sent(r"the court, before entering judgment for the plaintiff, shall require the plaintiff to file with the court an affidavit")),
 ("50 USC 3936", "federal", "statute", "S17 military (tolling)", "Period of military service not counted in limitations.",
  S+"REVIEW4A_US_50USC_3936_uscode.txt", sent(r"period of a servicemember.s military service may not be included in computing any period limited by law")),
 ("50 USC 3937", "federal", "statute", "S17 military (interest)", "Pre-service obligations capped at 6% during service on written notice.",
  S+"REVIEW4A_US_50USC_3937_uscode.txt", sent(r"6 percent per year")),
 ("50 USC 3958", "federal", "statute", "S17 military (belongings)", "No enforcement of a storage lien on a servicemember's property during service without court order.",
  S+"US_50USC_3958.txt", sent(r"may not, during any period of military service of the servicemember and for 90 days thereafter, foreclose or enforce any lien")),
 ("50 USC 3951", "federal", "statute", "S17 military (eviction)", "Eviction of servicemember/dependents below the rent threshold needs court order; stay available.",
  S+"US_50USC_3951.txt", sent(r"Except by court order, a landlord")),
 ("42 USC 3604(b),(f)(3)(B)", "federal", "statute", "S21 anti-discrimination", "No discrimination in terms/conditions; refusal of reasonable accommodation is discrimination.",
  S+"US_42USC_3604.txt", sent(r"To discriminate against any person in the terms, conditions, or privileges of sale or rental of a dwelling")),
 ("42 USC 3617", "federal", "statute", "S21 anti-discrimination", "Coercion, intimidation, threats or interference because of fair housing rights is unlawful (collection conduct included).",
  S+"REVIEW5A_US_42USC_3617.txt", sent(r"It shall be unlawful to coerce, intimidate, threaten, or interfere with any person")),
 ("24 CFR 100.7", "federal", "regulation", "S21 liability (manager)", "Direct liability for own conduct and for failing to correct agents' discrimination; vicarious liability for agents.",
  S+"REVIEW5A_US_24CFR_100.7.txt", sent(r"is vicariously liable")),
 ("24 CFR 100.65", "federal", "regulation", "S21 anti-discrimination", "Different terms, conditions, privileges, services or facilities because of protected class are prohibited.",
  S+"REVIEW4A_US_24CFR_100.65_ecfr.txt", sent(r"to impose different terms, conditions or privileges relating to the sale or rental of a dwelling")),
 ("34 USC 12491", "federal", "statute", "S18 domestic violence (HCV tenant)", "Covered housing (incl. tenant-based HCV): no denial/termination because of DV status; lease bifurcation allowed.",
  S+"REVIEW5A_US_34USC_12491_VAWA.txt", sent(r"bifurcate a lease")),
 ("24 CFR 982.313(c)-(e)", "federal", "regulation", "S5/S6 voucher tenant", "HCV unit: owner may use deposit for unpaid rent/damage, must give written list of each item and refund unused balance promptly; may seek excess from tenant.",
  S+"US_24CFR_982.313.txt", ("(d) The owner must give the tenant a written list of all items charged against the security deposit", "refund promptly the full amount of the unused balance to the tenant.")),
 ("24 CFR 982.311(d)(1)", "federal", "regulation", "S2 rent stops (HAP)", "HAP stops after the move-out month; owner keeps HAP for the move-out month.",
  S+"US_24CFR_982.311.txt", ("(1) If the family moves out of the unit, the PHA may not make any housing assistance payment to the owner for any month after the month when the family moves out.", "for the month when the family moves out of the unit.")),
 ("11 USC 362(a)", "federal", "statute", "S15 bankruptcy", "Filing stays collection acts and setoff against the debtor.",
  S+"US_11USC_362.txt", sent(r"the setoff of any debt owing to the debtor that arose before the commencement of the case")),
 ("11 USC 541, 542", "federal", "statute", "S15 bankruptcy (payee)", "Deposit refund is estate property payable to the trustee.",
  S+"REVIEW1_US_11USC_542.txt", sent(r"shall deliver to the trustee")),
 ("11 USC 553", "federal", "statute", "S15 bankruptcy (setoff)", "Mutual prepetition debts may be set off (subject to stay).",
  S+"US_11USC_553.txt", sent(r"this title does not affect any right of a creditor to offset")),
 ("11 USC 502(b)(6)", "federal", "statute", "S15 bankruptcy (claim cap)", "Lessor's claim for termination damages capped at greater of one year or 15% (max three years) of remaining rent plus unpaid prepetition rent.",
  S+"REVIEW4A_US_11USC_502_uscode.txt", sent(r"15 percent, not to exceed three years")),
 ("11 USC 524(a)", "federal", "statute", "S15 bankruptcy (discharge)", "Discharge enjoins collection of discharged debts.",
  S+"US_11USC_524.txt", sent(r"operates as an injunction against the commencement or continuation of an action")),
 ("11 USC 1301", "federal", "statute", "S15 bankruptcy (co-debtor)", "Chapter 13 co-debtor stay protects consumer-debt co-obligors (e.g., co-tenant, guarantor).",
  S+"REVIEW4A_US_11USC_1301_uscode.txt", sent(r"a creditor may not act, or commence or continue any civil action, to collect all or any part of a consumer debt of the debtor from any individual that is liable on such debt with the debtor")),
 ("Fed. R. Bankr. P. 3002(c)", "federal", "rule", "S15 bankruptcy (claim deadline)", "In chapter 7/13 a proof of claim is timely only within 70 days after the petition (with listed exceptions).",
  S+"REVIEW5A_US_FRBP_3002.txt", sent(r"the proof of claim is timely if filed within 70 days after the order for relief")),
 ("11 USC 108(c)", "federal", "statute", "S11 tolling (bankruptcy)", "Limitations on claims against the debtor extended to 30 days after the stay ends if it would otherwise expire.",
  S+"REVIEW4A_US_11USC_108_uscode.txt", sent(r"30 days after notice of the termination or expiration of the stay")),
 ("26 USC 6050P", "federal", "statute", "S19 information reporting", "1099-C only by 'applicable entities' (financial lenders, agencies); a landlord or manager writing off a lease balance files none.",
  S+"REVIEW4A_US_26USC_6050P_uscode.txt", sent(r"applicable entity")),
 ("26 USC 6041 / 26 CFR 1.6041-1", "federal", "statute", "S19 information reporting", "Information return threshold is now $2,000 (Pub. L. 119-21) for fixed or determinable payments in a trade or business; returning a tenant's own deposit or deposit interest below threshold needs none.",
  S+"REVIEW5A_US_26USC_6041.txt", r"of \$2,000 or more in any calendar year"),
 ("26 USC 166 / 26 CFR 1.166-1(e)", "federal", "regulation", "S19 tax (write-off)", "Unpaid rent is deductible as a bad debt only if previously included in income.",
  S+"REVIEW5A_US_26CFR_1.166-1.txt", r"\(e\) Prior inclusion in income required\. Worthless debts arising from unpaid wages, salaries, fees, rents, and similar items of taxable income shall not be allowed as a deduction under section 166 unless the income such items represent has been included in the return of income"),
 ("IRS Publication 527", "federal", "guidance", "S19 tax", "Security deposit kept because tenant failed to meet lease terms is income when kept.",
  S+"REVIEW4A_US_IRS_Pub527_2025.txt", sent(r"keep part or all of the security deposit")),

]
