"""IR5A universe items, part 5: NYC Admin Code, RCNY, city programs, routing."""
S = "sources/"
def sent(k):
    return r"[^.;]*" + k + r"[^.;]*[.;]"
ITEMS = [
 ("Admin. Code 26-504", "city", "statute", "S0 routing", "Rent stabilization reaches pre-1974 buildings with six or more units and tax-benefit units; such units leave this engine.",
  S+"NYC_ADC_26-504.txt", r"containing six or more dwelling units which:"),
 ("Admin. Code 8-107(5)(a)", "city", "statute", "S21 anti-discrimination", "NYC HRL bars housing discrimination incl. lawful source of income in terms, conditions or privileges (charges and collection).",
  S+"REVIEW4A_NYC_ADC_8-107.txt", r"or because of any lawful source of income of such person or persons, or because children are, may be or would be residing with such person or persons:"),
 ("Admin. Code 20-489", "city", "statute", "S13 licensing (scope)", "NYC 'debt collection agency' = business whose principal purpose is to regularly collect debts owed to another (plus debt buyers).",
  S+"NYC_ADC_20-489.txt", r"a\. \"Debt collection agency\" shall mean a person engaged in business the principal purpose of which is to regularly collect or attempt to collect debts owed or due or asserted to be owed or due to another"),
 ("Admin. Code 20-490", "city", "statute", "S13 licensing", "Debt collection agency must hold a DCWP licence.",
  S+"NYC_ADC_20-490.txt", sent(r"license")),
 ("Admin. Code 20-493.1", "city", "statute", "S13 collection conduct", "Licensed agency must give call-back number, agency name, originating creditor, etc., and written settlement confirmation.",
  S+"NYC_ADC_20-493.1.txt", r"a\. In any permitted communication with the consumer, provide:"),
 ("Admin. Code 20-493.2", "city", "statute", "S13 collection conduct", "Agency must stop collecting after a verification request until documentation is furnished; SOL disclosures for time-barred debt.",
  S+"NYC_ADC_20-493.2.txt", r"a\. Attempt to collect or contact a consumer regarding a debt after such consumer requests verification for such debt until such agency furnishes such consumer written documentation"),
 ("6 RCNY 5-76", "city", "rule", "S13 collection conduct (scope)", "DCWP debt-collection rules define 'creditor' broadly and 'debt' as consumer obligations.",
  S+"NYC_RCNY6_5-76.txt", sent(r"The term \"creditor\" means any person, firm, corporation or organization to whom a debt is owed")),
 ("6 RCNY 5-77", "city", "rule", "S13 collection conduct", "Debt collectors: more than two contacts in seven days presumed excessive; other conduct rules.",
  S+"NYC_RCNY6_5-77.txt", sent(r"more than twice during a seven-calendar-day period is excessively frequent")),
 ("6 RCNY 2-191", "city", "rule", "S13 collection conduct", "Agency collecting a debt beyond the limitations period must include the SOL rights disclosure in every communication.",
  S+"NYC_RCNY6_2-191.txt", sent(r"shall be included in every permitted communication for each debt")),
 ("6 RCNY 2-192", "city", "rule", "S9 settlement", "Written confirmation of payment schedule/settlement identifying originating creditor, amounts etc.",
  S+"REVIEW4A_NYC_RCNY6_2-192.txt", sent(r"shall identify the originating creditor of the debt")),
 ("6 RCNY 2-193", "city", "rule", "S13 records", "Agency keeps a searchable file per debt.",
  S+"REVIEW4A_NYC_RCNY6_2-193.txt", sent(r"shall maintain a separate file for each debt")),
 ("DCWP SHIELD rule (adopted 2026-02-26; effective 2027-01-01)", "city", "pending", "S13 collection conduct (from 2027)", "Amended 6 RCNY debt-collection rules; 'debt collector' continues to include original creditors; effective date moved to 2027-01-01.",
  S+"NYC_CROL_DCWP_SHIELD_ChangeEffDate_2026-07-22.txt", sent(r"will go into effect on January 1, 2027")),
 ("DCWP SHIELD NOA (original creditors)", "city", "pending", "S13 collection conduct (from 2027)", "DCWP states the rule's 'debt collector' applies to original creditors.",
  S+"NYC_DCWP_SHIELD_NOA_2026.txt", sent(r"the term “debt collector” continues to apply to original creditors")),
 ("Admin. Code 20-699.21 (FARE Act)", "city", "statute", "S5 charges / credits", "Landlord's agent may not impose or collect any fee from a tenant related to the rental (except 238-a(1) checks); listing agent likewise.",
  S+"NYC_ADC_20-699.21.txt", r"1\. a landlord’s agent shall not impose any fee on, or collect any fee from, a tenant related to the rental of residential real property"),
 ("Admin. Code 20-699.22", "city", "statute", "S1 move-in", "Total fee disclosure in listings and before lease execution.",
  S+"NYC_ADC_20-699.22.txt", sent(r"Every listing related to the rental of residential real property shall disclose")),
 ("6 RCNY 6-89", "city", "rule", "S8 exposure", "DCWP penalty schedule for rental-fee (FARE) violations.",
  S+"REVIEW5A_NYC_RCNY_6-89_0-0-0-131279.txt", r"§ 6-89 Fees for Rental of Residential Property Penalty Schedule\."),
 ("Admin. Code 20-700, 20-701", "city", "statute", "S5 charges / S13 collection", "Deceptive or unconscionable trade practices in leasing consumer goods/services or collecting consumer debts are unlawful.",
  S+"NYC_ADC_20-700.txt", r"No person shall engage in any deceptive or unconscionable trade practice in the sale, lease, rental or loan or in the offering for sale, lease, rental, or loan of any consumer goods or services, or in the collection of consumer debts\."),
 ("Admin. Code 26-3002(c)", "city", "statute", "S20 data (tenant data)", "Smart-access buildings: vacated tenant's reference data removed/anonymized within 90 days; authentication data destroyed within 90 days.",
  S+"REVIEW4A_NYC_ADC_26-3002.txt", ("c. Reference data for any tenant who has permanently vacated a smart access building shall be removed", "no later than 90 days after such tenant has permanently vacated such building.")),
 ("Admin. Code 26-3003(a)(1)", "city", "statute", "S20 data (tenant data)", "Smart-access data may not be sold or disclosed except listed exceptions.",
  S+"REVIEW5A_NYC_ADC_26-3003.txt", r"1\. sell, lease or otherwise disclose such data to another person except:"),
 ("Admin. Code 26-3006", "city", "statute", "S20 data (exposure)", "Occupants have a private right of action for unlawful sale of smart-access data.",
  S+"REVIEW5A_NYC_ADC_26-3006.txt", r"a\. A lawful occupant of a dwelling unit, or a group of such occupants, in a smart access building may bring an action alleging an unlawful sale of data"),
 ("Admin. Code 26-521, 26-523", "city", "statute", "S2 tenancy end (self-help)", "NYC unlawful eviction (incl. removing possessions, changing locks) of a 30-day occupant: misdemeanor and $1,000-$10,000 civil penalty per violation.",
  S+"REVIEW5A_NYC_ADC_26-523.txt", sent(r"civil penalty of not less than one thousand nor more than ten thousand dollars for each violation")),
 ("Admin. Code 27-2013(b)", "city", "statute", "S5 charges (painting)", "Owner must repaint every three years; repainting on that cycle is an owner cost.",
  S+"NYC_ADC_27-2013.txt", sent(r"every three years")),
 ("Admin. Code 27-2017.5", "city", "statute", "S5 charges (turnover)", "Before reoccupancy owner must remediate mold/pests and clean owner-provided carpet/furniture (owner cost).",
  S+"NYC_ADC_27-2017.5.txt", sent(r"Prior to the reoccupancy of any vacant dwelling unit in a multiple dwelling")),
 ("Admin. Code 27-2056.8", "city", "statute", "S5 charges (turnover)", "Lead-paint turnover work in pre-1960 multiple dwellings (owner cost).",
  S+"NYC_ADC_27-2056.8.txt", sent(r"Upon the earlier of \(i\) turnover of any dwelling unit")),
 ("Admin. Code 27-2045", "city", "statute", "S5 charges (detectors)", "Occupant reimburses detector cost only in listed cases and up to $25/$50 caps.",
  S+"SWEEP_NYC_ADC_27-2045.txt", r"shall reimburse the owner for the cost of providing and installing such device an amount not to exceed \(i\) \$25"),
 ("Admin. Code 27-2107(b)", "city", "statute", "S10 preconditions", "Unregistered owner: no possession for nonpayment during noncompliance; court may stay rent recovery.",
  S+"REVIEW1_NYC_ADC_27-2107.txt", sent(r"shall be denied the right to recover possession of the premises for nonpayment of rent")),
 ("68 RCNY 10-14(c) (CityFHEPS)", "city", "rule", "S4 deposit (voucher tenant)", "CityFHEPS unit: landlord must accept HRA security voucher in lieu of cash and may not request other security.",
  S+"NYC_RCNY68_10-14.txt", sent(r"Landlords must accept the HRA security voucher in lieu of a cash security deposit")),
 ("HRA Security Voucher W-147N", "city", "guidance", "S9 voucher claim", "Claim against the HRA security voucher must be filed with proof within three months after the tenant vacates.",
  S+"NYC_HRA_W-147N_SecurityVoucher_2025-05-07.txt", sent(r"The Agency will only make a payment if the claim is submitted within three months after the tenant has vacated")),
]
