"""IR5A universe items, part 3: MDL, CPLR, CCA, time/e-records, court rules."""
S = "sources/"
def sent(k):
    return r"[^.;]*" + k + r"[^.;]*[.;]"
ITEMS = [
 ("MDL 4(7)", "state", "statute", "S0 routing / S10 preconditions", "Multiple dwelling = occupied as residence of three or more families living independently.",
  S+"REVIEW2_NY_MDL_4_nysenate.txt", sent(r"three or more families living independently")),
 ("MDL 301-302(1)(b)", "state", "statute", "S10 preconditions (rent bar)", "No rent recoverable for a multiple dwelling occupied without a certificate of occupancy for the period of unlawful occupancy.",
  S+"REVIEW2_NY_MDL_302_nysenate.txt", sent(r"No rent shall be recovered by the owner of such premises")),
 ("MDL 302-a", "state", "statute", "S10 preconditions (rent bar)", "Rent-impairing violation uncorrected six months after notice: tenant owes no rent for that period.",
  S+"NY_MDL_302-A_nysenate.txt", sent(r"no rent shall be recovered")),
 ("MDL 302-c", "state", "statute", "S5 credits", "Tenant who buys heating oil after the owner's failure may deduct the payment from rent if the statutory steps were followed.",
  S+"REVIEW5A_NY_MDL_302-c.txt", r"Any payment so made shall be deductible from rent providing the following provisions have been substantially complied with by the tenant or someone acting on his behalf"),
 ("MDL 325(2)", "state", "statute", "S10 preconditions (rent bar)", "Unregistered multiple dwelling: no rent recovery until registered.",
  S+"REVIEW2_NY_MDL_325_nysenate.txt", sent(r"rent")),
 ("MDL 51-c", "state", "statute", "S5 charges", "Tenant may add own lock (duplicate key on request); lease charge for that right is void.",
  S+"REVIEW5A_NY_MDL_51-c.txt", ("every provision of any lease hereafter made or entered into which reserves or provides for the payment by such tenant", "wholly unenforceable")),
 ("CPLR 105(f),(u)", "state", "statute", "S11 limitations / S12 interest", "'Consumer credit transaction' requires credit extended; definitions used by 214-i and 3016.",
  S+"NY_CPLR_105.txt", ("The term \"consumer credit transaction\" means a transaction wherein credit is extended to an individual", "primarily for personal, family or household purposes.")),
 ("CPLR 203", "state", "statute", "S11 limitations", "Limitations runs from accrual to interposition of the claim.",
  S+"REVIEW4A_NY_CPLR_203_nysenate.txt", sent(r"computed from the time the cause of action accrued")),
 ("CPLR 204(a)", "state", "statute", "S11 tolling", "Time a statutory prohibition or injunction (e.g., bankruptcy stay) bars suit is not counted.",
  S+"REVIEW5A_NY_CPLR_204.txt", sent(r"statutory prohibition")),
 ("CPLR 205(a)", "state", "statute", "S11 tolling", "Timely action dismissed other than on the merits/for neglect/by voluntary discontinuance: six months to recommence.",
  S+"REVIEW5A_NY_CPLR_205.txt", sent(r"six months after the termination")),
 ("CPLR 207", "state", "statute", "S11 tolling", "Absence from state or false residence tolls unless jurisdiction could be obtained without personal delivery.",
  S+"REVIEW5A_NY_CPLR_207.txt", sent(r"departs from the state")),
 ("CPLR 208", "state", "statute", "S11 tolling", "Infancy or insanity of the person entitled to sue extends the time.",
  S+"REVIEW5A_NY_CPLR_208.txt", sent(r"under a disability because of infancy or insanity")),
 ("CPLR 210(b)", "state", "statute", "S11 tolling / S16 death", "Death of the person liable: 18 months added.",
  S+"REVIEW4A_NY_CPLR_210_nysenate.txt", sent(r"eighteen months")),
 ("CPLR 211(b)", "state", "statute", "S9 judgment life", "Money judgment is conclusively presumed paid after 20 years unless acknowledged or partly paid.",
  S+"REVIEW5A_NY_CPLR_211.txt", sent(r"A money judgment is presumed to be paid and satisfied after the expiration of twenty years")),
 ("CPLR 213(2)", "state", "statute", "S11 limitations", "Contract (lease) claims: six years.",
  S+"NY_CPLR_213.txt", sent(r"upon a contractual obligation or liability")),
 ("CPLR 214(4)", "state", "statute", "S11 limitations", "Injury to property (tort theory): three years.",
  S+"REVIEW4A_NY_CPLR_214_nysenate.txt", sent(r"injury to property")),
 ("CPLR 214-i", "state", "statute", "S11 limitations", "Consumer credit transactions: three years (a lease balance is not one).",
  S+"NY_CPLR_214-I.txt", sent(r"An action arising out of a consumer credit transaction where a purchaser, borrower or debtor is a defendant must be commenced within three years")),
 ("CPLR 321(a)", "state", "statute", "S10 capacity", "A corporation or LLC must appear by attorney (small/commercial claims excepted as provided).",
  S+"REVIEW5A_NY_CPLR_321.txt", sent(r"corporation or voluntary association shall appear by attorney")),
 ("CPLR 1201, 1203", "state", "statute", "S10 procedure (incapacity)", "Infant or adult incapable of defending appears by guardian; no default judgment against them without guardian ad litem.",
  S+"REVIEW5A_NY_CPLR_1203.txt", sent(r"No judgment by default")),
 ("CPLR 1015", "state", "statute", "S16 death", "On a party's death the court orders substitution of the proper party.",
  S+"REVIEW5A_NY_CPLR_1015.txt", sent(r"substitution of the proper parties")),
 ("CPLR 3015(e)", "state", "statute", "S10 preconditions (licensed plaintiff)", "Plaintiff whose business must be licensed by DCWP/state must plead its licence number in a consumer suit.",
  S+"SWEEP_NY_CPLR_3015_nysenate.txt", sent(r"licensed")),
 ("CPLR 3012", "state", "statute", "S10 procedure", "Pleading/answer timing.",
  S+"REVIEW4A_NY_CPLR_3012_nysenate.txt", sent(r"answer")),
 ("CPLR 3215(g)(3)", "state", "statute", "S10 procedure (default)", "Default on nonpayment of a contractual obligation against a natural person needs an additional mailing of the summons at least 20 days before entry.",
  S+"REVIEW4A_NY_CPLR_3215_nysenate.txt", sent(r"additional notice")),
 ("CPLR 4544", "state", "statute", "S1 lease form", "Residential lease portions in print smaller than eight points (ten for some) cannot be enforced against the tenant.",
  S+"REVIEW4A_NY_CPLR_4544_nysenate.txt", sent(r"eight points")),
 ("CPLR 5001", "state", "statute", "S12 interest", "Prejudgment interest on contract breach from the earliest ascertainable date.",
  S+"NY_CPLR_5001_nysenate.txt", sent(r"Interest shall be recovered upon a sum awarded because of a breach of performance of a contract")),
 ("CPLR 5003-a", "state", "statute", "S8 settlement payment timing", "Settling defendant must pay within 21 days of tender of release and stipulation or owe costs, interest and fees.",
  S+"REVIEW5A_NY_CPLR_5003-A.txt", sent(r"twenty-one days")),
 ("CPLR 5004", "state", "statute", "S12 interest", "Interest 9% per annum, but 2% on a consumer-debt judgment against a natural person.",
  S+"REVIEW1_NY_CPLR_5004_nysenate.txt", sent(r"two per centum")),
 ("CPLR 5014", "state", "statute", "S9 judgment life", "Renewal judgment action allowed in the tenth year after docketing.",
  S+"REVIEW5A_NY_CPLR_5014.txt", sent(r"renewal judgment|ten years")),
 ("CPLR 5020", "state", "statute", "S9 closing the account", "On satisfaction of a judgment the creditor must execute and file a satisfaction-piece within 20 days; failure exposes it to a $100 penalty and damages.",
  S+"REVIEW5A_NY_CPLR_5020.txt", sent(r"twenty days")),
 ("CPLR 5205(l)", "state", "statute", "S9 recovery value", "If exempt payments were direct-deposited in the prior 45 days, $2,500 in the account is exempt (other bank-account exemptions under 5222(i) and 5205).",
  S+"REVIEW5A_NY_CPLR_5205.txt", ("then two thousand five hundred dollars in the judgment debtor’s account is exempt", "satisfaction of a money judgment.")),
 ("CPLR 5222(e)", "state", "statute", "S9 recovery value", "Restraining notice on a natural person's bank account must be served with the exemption notice and claim forms.",
  S+"REVIEW5A_NY_CPLR_5222.txt", sent(r"a copy of the restraining notice together with the notice to judgment debtor or obligor shall be mailed")),
 ("CPLR 5231(b)", "state", "statute", "S9 recovery value", "Income execution limited to 10% of gross income subject to wage floor.",
  S+"REVIEW5A_NY_CPLR_5231.txt", sent(r"ten percent")),
 ("CPLR 5208", "state", "statute", "S16 death", "No execution after judgment debtor's death without leave of the surrogate's court.",
  S+"REVIEW5A_NY_CPLR_5208.txt", sent(r"surrogate")),
 ("CCA 1801", "state", "statute", "S10 forum", "NYC Civil Court small claims part: claims up to $10,000.",
  S+"REVIEW4A_NY_CCA_1801_nysenate.txt", sent(r"ten thousand dollars")),
 ("CCA 1809", "state", "statute", "S10 forum / capacity", "Corporations, partnerships, associations and assignees may not bring small claims.",
  S+"REVIEW1_NY_CCA_1809_nysenate.txt", ("1. No corporation, except a municipal corporation", "shall institute an action or proceeding under this article")),
 ("CCA 1801-A, 1803-A", "state", "statute", "S10 forum / preconditions", "Commercial claims part for entities (limit $10,000); consumer transaction claims need a demand letter at least 10 days (and no more than 180 days) before filing.",
  S+"REVIEW1_NY_CCA_1803-A_nysenate.txt", sent(r"demand letter")),
 ("CCA 1812", "state", "statute", "S9 recovery", "Unpaid small/commercial claims judgment: treble damages action when three+ unsatisfied judgments.",
  S+"REVIEW4A_NY_CCA_1812_nysenate.txt", sent(r"treble")),
 ("GCN 20", "state", "statute", "S6 timing", "Period after an event excludes the event day.",
  S+"NY_GCN_20.txt", sent(r"day from which")),
 ("GCN 25-a", "state", "statute", "S6 timing", "Deadline on Saturday/Sunday/public holiday moves to the next business day.",
  S+"NY_GCN_25-A_nysenate.txt", ("1. When any period of time, computed from a certain day", "such act may be done on the next succeeding business day")),
 ("State Technology Law 304-305", "state", "statute", "S6 delivery (electronic)", "Electronic record/signature has the same force as writing; use of e-records is voluntary.",
  S+"NY_STT_304.txt", sent(r"The use of an electronic signature shall have the same validity and effect")),
 ("22 NYCRR 208.6", "state", "rule", "S10 procedure", "Civil Court filing and default-judgment rules (consumer credit affidavits apply only to consumer credit transactions).",
  S+"REVIEW5A_NY_22NYCRR_208.6.txt", sent(r"consumer credit")),
]
