"""IR5A findings, part 2 (major and minor)."""
S = "sources/"
FINDINGS = [
 dict(id="R5A-15", kind="gap", severity="major", rule_ids=["NY:RPL-226-c(2)", "NY:RPL-215"],
  step="S2 non-renewal / tenancy end", universe=["U5A-032"],
  finding="No rule states RPL 223-b. A notice to quit, non-renewal or action for possession within a year after a tenant's good-faith complaint to a governmental authority or to the landlord, or tenant-organization activity, raises a rebuttable presumption of retaliation; the landlord is liable for damages and fees. This conditions the 'notice that the tenancy is ending' for every market-rate unit (owner-occupied buildings of fewer than four units excepted).",
  correct_rule="Before serving a non-renewal notice or notice to quit on a tenant who, within the preceding year, made a good-faith complaint (to an agency or in writing to the landlord) about a violation or habitability, or joined a tenant group, record a non-retaliatory reason: in any proceeding the tenant's showing of such activity and the landlord's notice raises a rebuttable presumption of retaliation; a retaliating landlord is liable for damages, attorney's fees and costs, and may be enjoined. Exception: owner-occupied premises with fewer than four units.",
  extra=[]),
 dict(id="R5A-16", kind="gap", severity="major", rule_ids=["NY:CASE-Riverside-surrender-by-operation", "NY:COMMONLAW-NYC-monthly-tenant-surrender"],
  step="S2 surrender / when rent stops", universe=["U5A-019", "U5A-023"],
  finding="Surrender by operation of law is stated (Riverside) but not the writing requirement for a consensual early termination of a lease for more than one year (GOL 5-703(1)) or the no-oral-modification rule (GOL 15-301(1)). An oral 'you can leave early' agreement does not end a two-year lease or stop rent unless the parties' conduct amounts to surrender by operation of law.",
  correct_rule="An agreement ending a lease for a term over one year before its end is effective only if in a writing signed by the landlord (or its agent authorized in writing) or if a surrender by operation of law occurs (conduct of both parties inconsistent with the continuing tenancy, e.g., landlord's acceptance of keys as surrender and reletting for its own account). Where the lease bars oral modification, an unexecuted oral agreement to change its terms is unenforceable. Rent stops on the effective surrender date.",
  extra=[]),
 dict(id="R5A-17", kind="gap", severity="major", rule_ids=["NY:GOL-17-101-acknowledgment", "NY:CPLR-213(2)"],
  step="S11 limitations (extension agreements)", universe=["U5A-028"],
  finding="GOL 17-101 (acknowledgment) is stated but not GOL 17-103: a post-accrual written promise to waive, extend or not plead the statute of limitations is effective for a new period measured from the promise; a lease clause waiving limitations made before accrual has no effect.",
  correct_rule="A payment plan or settlement letter signed by the former tenant after the balance accrued that promises not to plead limitations (or extends it) lets the landlord sue within the six-year period running from the date of the promise (or any shorter period stated). A lease term made before accrual that waives or extends limitations is ineffective.",
  extra=[]),
 dict(id="R5A-18", kind="gap", severity="major", rule_ids=["NY:CCA-1809(1)", "NY:CCA-1801-A(a)-eligibility", "NY:HANDOFF-broker-config-collects-rent"],
  step="S10 capacity and who may appear", universe=["U5A-090", "U5A-129", "U5A-130"],
  finding="The rules decide which court part an entity may use but not who may appear. CPLR 321(a) requires a corporation or LLC owner to appear by attorney (outside the small/commercial claims provisions); Judiciary Law 495 bars a corporation (e.g., Handoff) from appearing as attorney for another or practising law, and Judiciary Law 478 bars non-lawyer individuals from appearing for another in a court of record. A manager or Handoff cannot file or appear in the owner's Civil Court action.",
  correct_rule="Suit on the balance: (a) owner is a natural person: may sue pro se or by attorney; (b) owner is a corporation, LLC or partnership: must appear by a licensed attorney, except that in the commercial claims part a corporation may appear by an authorized officer, director or employee of the corporation itself (CCA 1809-A(d)) — not by an outside manager or Handoff; (c) Handoff or a manager (entity) may prepare evidence for counsel but may not appear, sign pleadings as attorney, or hold out legal services for the owner (JUD 495; for its individual staff, JUD 478); violation is a misdemeanor and the papers are a nullity.",
  extra=[(S+"REVIEW4A_NY_CCA_1809-A_nysenate.txt", "(d) A corporation may appear as a party in any action brought pursuant to this article by an attorney as well as by any authorized officer, director or employee of the corporation", "requisite authority to bind the corporatio")]),
 dict(id="R5A-19", kind="gap", severity="major", rule_ids=["NY:LLC-808(a)-foreign-authority", "NY:BCL-1312(a)-foreign-authority"],
  step="S10 capacity (assumed name)", universe=["U5A-122"],
  finding="Capacity rules cover foreign LLCs/corporations and LLC publication but not GBL 130: an owner or manager doing business under an assumed name (the name on the lease, e.g., 'Maple Properties' when the entity is 'Maple 12 LLC') without a filed certificate cannot maintain an action on contracts made in that name until it files.",
  correct_rule="If the lease or collection correspondence was made in a name other than the owner's legal name, confirm a GBL 130 assumed-name certificate is on file before suing; if not, the action cannot be maintained until filed (filing cures; knowing failure is a misdemeanor).",
  extra=[]),
 dict(id="R5A-20", kind="gap", severity="major", rule_ids=[],
  step="S9 closing the account after judgment", universe=["U5A-101"],
  finding="No rule states CPLR 5020. When a money judgment is fully satisfied, the judgment creditor must execute and file a satisfaction-piece and mail a copy to the debtor within ten days after filing; for a judgment under $5,000, failure or refusal within 20 days after full satisfaction subjects it to a $100 penalty recoverable by the debtor.",
  correct_rule="On full payment of a judgment against a former tenant: execute and file the satisfaction-piece with the clerk within 20 days after receiving full satisfaction and mail a copy to the debtor within ten days after filing; for judgments below $5,000 the penalty for failure is $100 recoverable by the debtor (larger judgments carry the further consequences 5020(c) states).",
  extra=[]),
 dict(id="R5A-21", kind="gap", severity="major", rule_ids=["NY:CPLR-5004(a)-consumer-2pct"],
  step="S9 pursue or write off (recovery value)", universe=["U5A-102", "U5A-103", "U5A-104", "U5A-086"],
  finding="The decision to pursue a balance to judgment turns on what can be collected, but no rule states the enforcement limits: exempt bank-account amounts (CPLR 5205(l): $2,500 where exempt payments were direct-deposited in the prior 45 days; 5222(i) exempt amount), mandatory exemption notices with restraints (5222(e), 5222-a), income executions capped at 10% of gross income (5231(b)), and the 20-year presumption of payment (CPLR 211(b)).",
  correct_rule="Expected recovery on a judgment against a natural person is limited by: exempt funds in bank accounts (5205(l) and 5222(i)), income execution of no more than 10% of gross income subject to the minimum-wage floor (5231(b)), exemption notice and claim-form service with every restraining notice (5222(e); 5222-a), and the judgment's presumption of payment after 20 years (211(b)); the renewal action is available in the tenth year (5014).",
  extra=[]),
 dict(id="R5A-22", kind="gap", severity="major", rule_ids=["NY:GBL-899-bb-safeguards"],
  step="S20 data (closing the file)", universe=["U5A-123"],
  finding="GBL 399-h governs how the tenant file is disposed of when the account closes: records containing personal identifying information may be disposed of only by shredding, destroying the information or making it unreadable. Not stated in the rules.",
  correct_rule="When the settlement file (applications, IDs, bank or card details, SSNs) is disposed of by the owner, manager or Handoff, shred it or destroy or render unreadable the personal identifying information (or use a method consistent with accepted industry practice reasonably believed to ensure no unauthorized access).",
  extra=[]),
 dict(id="R5A-23", kind="gap", severity="major", rule_ids=["US:24CFR982.313(d)", "US:24CFR982.311(d)(1)"],
  step="S18 domestic violence (voucher tenant) / S2 tenancy end", universe=["U5A-214"],
  finding="The HCV rules are stated but not VAWA (34 USC 12491), which covers tenant-based HCV tenancies in market-rate units: an owner may not terminate or deny tenancy because the tenant is a victim of domestic violence, dating violence, sexual assault or stalking, and may bifurcate the lease to remove the perpetrator while the victim stays.",
  correct_rule="HCV-assisted unit: criminal activity directly relating to domestic violence against the tenant is not cause to terminate the victim's tenancy; the owner may bifurcate the lease to evict the perpetrator; the victim's tenancy continues. Charges arising from the perpetrator's acts follow the lease and state law against the liable party.",
  extra=[]),
 dict(id="R5A-24", kind="gap", severity="major", rule_ids=["US:15USC1681s-2(a)(1)(A)", "US:12CFR1006.30(a)"],
  step="S20 credit reporting (pulling a report for collection)", universe=["U5A-196", "U5A-197"],
  finding="Furnishing duties are stated, but not the permissible purpose to obtain a former tenant's consumer report (FCRA 1681b(a)(3)(A): review or collection of the consumer's account) nor the seven-year reporting limit on collection accounts (1681c(a)(4), running from 180 days after delinquency, 1681c(c)).",
  correct_rule="The owner or its collector may obtain a former tenant's consumer report to locate or evaluate collection of that tenant's account (1681b(a)(3)(A)); obtaining it for another purpose is unlawful. A collection account may be reported by a CRA for seven years from 180 days after the delinquency began; the furnisher reports the date of first delinquency (1681s-2(a)(5)).",
  extra=[]),
 # minor
 dict(id="R5A-25", kind="gap", severity="minor", rule_ids=["NY:RPL-215"], step="S2 non-renewal", universe=["U5A-060"],
  finding="RPL 218 (waiver of Good Cause rights void) is not stated.", correct_rule="Any lease term waiving or modifying Good Cause rights is void.", extra=[]),
 dict(id="R5A-26", kind="gap", severity="minor", rule_ids=["NY:RPL-440(1)-rent-collection"], step="S13 licensing (exposure)", universe=["U5A-063"],
  finding="RPL 441-c (DOS may revoke, suspend or fine a licensee for untrustworthiness or incompetency, e.g., mishandling deposits or collections) is not stated.",
  correct_rule="A licensed broker-manager's mishandling of tenant funds or collections exposes its licence to revocation, suspension or fine by DOS.", extra=[]),
 dict(id="R5A-27", kind="gap", severity="minor", rule_ids=["NY:RPL-227-d-dv-status"], step="S18 domestic violence", universe=["U5A-066"],
  finding="RPAPL 744 (no removal because of domestic violence victim status) is not stated.", correct_rule="A tenant may not be removed from possession in a summary proceeding because of domestic violence victim status.", extra=[]),
 dict(id="R5A-28", kind="gap", severity="minor", rule_ids=["NY:MDL-325(2)", "NYC:ADC-27-2107(b)-rent-stay"], step="S10 preconditions (pleading)", universe=["U5A-072"],
  finding="22 NYCRR 208.42(g) (petition must allege multiple-dwelling registration status) is not stated.", correct_rule="Every RPAPL 711 petition alleges either that the premises are not a multiple dwelling or that a current HPD registration naming the managing agent is on file.", extra=[]),
 dict(id="R5A-29", kind="gap", severity="minor", rule_ids=["NY:RPL-238-a(1)-no-move-in-fees"], step="S5 charges", universe=["U5A-078"],
  finding="MDL 51-c (tenant's own lock; lease charge for it void) is not stated.", correct_rule="No charge may be made or kept for the tenant's installing its own additional lock; the tenant must give a duplicate key on request.", extra=[]),
 dict(id="R5A-30", kind="gap", severity="minor", rule_ids=["US:11USC108(c)-extension", "US:50USC3936-tolling", "NY:CPLR-210-death"], step="S11 tolling", universe=["U5A-081", "U5A-082", "U5A-083", "U5A-084", "U5A-142"],
  finding="State tolling rules other than CPLR 210 are not stated: 204(a) (stays), 205(a) (six-month savings), 207 (absence), 208 (infancy/insanity of the claimant) and Military Law 308 (NY militia service).",
  correct_rule="Add to the limitations computation: time a court or statutory stay prevented suit is excluded (204(a)); a timely action dismissed other than on the merits/neglect/voluntary discontinuance/lack of jurisdiction may be recommenced within six months (205(a)); defendant's 4-month absence tolls only where personal jurisdiction could not otherwise be obtained (207); NY military service is excluded (MIL 308).", extra=[]),
 dict(id="R5A-31", kind="gap", severity="minor", rule_ids=["NY:CPLR-3215(g)(3)"], step="S10 procedure (incapacity, death)", universe=["U5A-091", "U5A-092", "U5A-105"],
  finding="CPLR 1203 (no default against an infant or adjudicated incompetent without guardian), 1015 (substitution on death) and 5208 (execution after the debtor's death needs surrogate's leave) are not stated.",
  correct_rule="No default judgment against an infant or adjudicated incompetent unless its representative appeared or 20 days after a guardian ad litem's appointment; on a party's death, substitute the representative; after the judgment debtor's death, enforce only with surrogate's court leave.", extra=[]),
 dict(id="R5A-32", kind="gap", severity="minor", rule_ids=[], step="S8 settlement of a tenant's deposit suit", universe=["U5A-098"],
  finding="CPLR 5003-a (settling defendant must pay within 21 days of tender of release and stipulation, else costs, interest and fees) is not stated.", correct_rule="When the landlord settles a tenant's deposit action, pay within 21 days after the tenant tenders the release and stipulation of discontinuance, or judgment may be entered for the settlement plus interest, costs and fees.", extra=[]),
 dict(id="R5A-33", kind="gap", severity="minor", rule_ids=["NY:GBL-600(1)", "NY:23NYCRR-1.1(d)-not-lease"], step="S13 collection scope", universe=["U5A-121", "U5A-124"],
  finding="GBL art. 29-HH (identity-theft cease-collection, 604-a) is not addressed; like art. 29-H it reaches only consumer claims arising from credit, so it does not govern a lease balance. GBL 399-ddd (no SSN on mailed materials) is not stated.",
  correct_rule="GBL 604-a does not apply to a residential lease balance (no credit extended). Do not print the tenant's SSN on any mailed statement or collection letter (399-ddd).", extra=[]),
 dict(id="R5A-34", kind="gap", severity="minor", rule_ids=["NY:ABP-1315(2)", "NY:ABP-1422"], step="S14 unclaimed funds", universe=["U5A-134", "U5A-135", "U5A-136"],
  finding="ABP 1400 (limitations no bar to reporting), 1412 ($100/day forfeiture for wilful failure to report; interest) and 1412-a (keep records five years after the report year) are not stated.",
  correct_rule="Report and pay unclaimed refunds even if the tenant's claim is time-barred; keep supporting records five years after the report year; wilful failure to report forfeits $100 per day, and late-paid property bears interest at 10% per annum.", extra=[]),
 dict(id="R5A-35", kind="gap", severity="minor", rule_ids=["US:50USC3951(a)(1)(B)", "NY:MIL-310(2)"], step="S17 military", universe=["U5A-140", "U5A-144"],
  finding="NY Military Law 309 (no eviction or distress against a person in military service without court leave) and 306 (discretionary stay of actions up to 60 days after service) are not stated.",
  correct_rule="Eviction or distress against a NY military-service tenant or dependents needs court leave (MIL 309); actions against them may be stayed during service and for 60 days after (MIL 306).", extra=[]),
 dict(id="R5A-36", kind="gap", severity="minor", rule_ids=["NY:EXEC-296(5)(a)(2)-terms"], step="S21 exposure", universe=["U5A-263"],
  finding="Executive Law 297(9) remedies (court action for damages, including punitive damages in housing cases) are not stated.", correct_rule="A tenant subjected to discriminatory charges or collection may sue for compensatory and punitive damages and fees.", extra=[]),
 dict(id="R5A-37", kind="gap", severity="minor", rule_ids=["NYC:ADC-26-3002(c)-moveout-data"], step="S20 tenant data", universe=["U5A-172", "U5A-173"],
  finding="Admin. Code 26-3003(a)(1) (no sale or disclosure of smart-access data except as listed) and 26-3006 (private action for unlawful sale) are not stated.", correct_rule="Smart-access data of a departed tenant may not be sold or disclosed (e.g., to a collector) except as 26-3003 allows; unlawful sale is actionable by occupants.", extra=[]),
 dict(id="R5A-38", kind="gap", severity="minor", rule_ids=["US:26USC6050P-no-1099C", "US:IRS-Pub527-deposit-income"], step="S19 tax", universe=["U5A-226", "U5A-227"],
  finding="IRC 6041's threshold (now $2,000 under Pub. L. 119-21) and Treas. Reg. 1.166-1(e) (unpaid rent deductible as bad debt only if previously included in income) are not stated.",
  correct_rule="Writing off a lease balance yields a bad-debt deduction only for rent the owner previously reported as income (accrual basis); a cash-basis owner has none. No 1099 is due for returning a tenant's own deposit.", extra=[]),
 dict(id="R5A-39", kind="gap", severity="minor", rule_ids=["NY:RPL-214", "NY:RPL-215"], step="S1 lease form / S10 predicate notices", universe=["U5A-258"],
  finding="RPL 231-c (Good Cause notice in leases) and its RPAPL 741(5-a) consequence (petition must append it) are not stated.", correct_rule="Covered leases and renewals carry the 231-c notice; a summary-proceeding petition must append or incorporate it.", extra=[]),
 dict(id="R5A-40", kind="gap", severity="minor", rule_ids=["NY:GOL-5-905"], step="S1 lease form", universe=["U5A-029"],
  finding="GOL 5-702 (plain language) is not stated: violation gives actual damages plus $50 but does not void the lease or supply a defense.", correct_rule="A non-plain-language residential lease remains enforceable; the tenant may recover actual damages plus $50.", extra=[]),
 dict(id="R5A-41", kind="gap", severity="minor", rule_ids=["NYC:RS-status", "NYC:RSC-2520.11(p)"], step="S0 routing (pending)", universe=["U5A-255"],
  finding="S9650/A659 (passed both houses 2026, not delivered) would penalize incorrect decontrol statements in 421-a (Affordable New York) leases; not recorded as a dated future rule.",
  correct_rule="Pending: if signed, from its 60th day, leases/renewals of 421-a units with incorrect decontrol information carry a $1,000 violation; routing is unchanged (421-a units remain stabilized and outside this engine).", extra=[]),
]
