import csv, json
from pathlib import Path

columns = ['provider','category','segments','lifecycle_coverage','capabilities_observed','evidence_kind','price_observed','access_observed','limitations_or_unknowns','competitive_implication','source_urls','source_date','checked_date']
rows = [
['AppFolio','Core PMS + native AI','US rental; associations; commercial','leasing;resident_service;maintenance;inspections;turns;accounting;payments',
'Realm-X Assistant, Messages, Flows and agentic Performers; published plans include accounting, leasing, inspections and turns.',
'Vendor product and pricing documentation; performance unverified',
'Quote; Core minimum 50 units and minimum spend. Plus minimums apply.',
'Plus lists AppFolio API as read-only. Stack standard/premium integrations vary by plan.',
'Read-only customer API is not blanket write authority; partner access and per-object actions need confirmation.',
'Native distribution and data access are strong advantages; do not pitch generic AppFolio AI overlay.',
'https://www.appfolio.com/pricing|https://www.appfolio.com/ai|https://www.appfolio.com/stack|https://www.appfolio.com/newsroom/appfolio-ai-agents','2025-06-11 announcement; live pages undated'],
['Yardi','Core PMS + native AI','Global residential; commercial; affordable; senior','leasing;resident_service;maintenance;accounting;payments;asset_management;compliance',
'Voyager ecosystem; Virtuoso agents, agent marketplace, no-code Composer and centralized agent management.',
'Vendor product and interfaces documentation; performance unverified',
'Enterprise pricing not published on reviewed pages.',
'Third-party interface program; partner/application-specific interfaces.',
'Exact interface categories, writes, approval, fees and rollout require vendor diligence.',
'Building an agent orchestration layer alone is already a native product proposition.',
'https://www.yardi.com/|https://www.yardi.com/virtuoso/|https://www.yardi.com/company/interfaces/','Undated live pages'],
['RealPage','Core PMS + native AI','US multifamily; specialized housing; portfolio investors','leasing;resident_service;maintenance;accounting;payments;procurement;asset_management;compliance',
'OneSite and Lumina; seven marketed AI agents across leasing, resident engagement, operations, facilities, finance, spend and analytics.',
'Vendor announcement/product documentation; deployment and performance unverified',
'Not published on reviewed pages.',
'Embedded in RealPage stack; open model access advertised in Lumina suite.',
'Open model access does not establish unrestricted external transaction API access.',
'Shared-context operating intelligence is directly contested by an incumbent.',
'https://www.realpage.com/|https://www.realpage.com/lp/lumina-ai-workforce/|https://www.realpage.com/news/realpage-introduces-lumina-ai-suite/','2026-08-10 suite announcement'],
['Buildium','Core PMS + native AI','US small/midsize rental; associations; mixed portfolios','leasing;resident_service;maintenance;inspections;turns;accounting;payments;owner_onboarding',
'Accounting, maintenance, leasing, Lumina AI, workflow automation; inspections powered by HappyCo.',
'Vendor pricing and API documentation; performance unverified',
'Essential starts $62/month; Growth $192; Premium $400. Other transaction and service fees apply.',
'Open API included in Premium; marketplace integrations.',
'Starting prices are not full portfolio quotes; verify required endpoints and permissions.',
'API-tier uplift can dominate a small pilot; compare configuration of purchased tools before new build.',
'https://www.buildium.com/pricing/|https://www.buildium.com/features/open-api/','Undated live pages'],
['MRI Software','Core PMS + native AI','Global commercial; residential; social/affordable housing','leasing;resident_service;maintenance;accounting;asset_management;compliance',
'Agora combines intelligence and workflow execution; Orchestrator, rule-governed workflows and role-specific signals.',
'Vendor product documentation; deployment and performance unverified',
'Not published on reviewed pages.',
'Partner ecosystem advertised; endpoint-level access not established here.',
'Cross-product availability and exact automation scope require live demonstration.',
'An AI layer that understands real estate and runs workflows is already explicitly marketed.',
'https://www.mrisoftware.com/|https://www.mrisoftware.com/mri-agora/','Undated live pages'],
['Entrata','Core PMS + native AI','Multifamily; student; affordable; military; commercial','leasing;resident_service;maintenance;turns;payments;accounting;renewals;compliance',
'ELI+ leasing/payments/renewals; Maintenance AI categorizes, troubleshoots and updates tickets; facilities routing and make-ready boards.',
'Vendor announcement and product documentation; performance unverified',
'Not published on reviewed pages.',
'Native transaction context; specific external API rights not established.',
'Entrata Pro homepage launch on 2026-09-15 is a new announcement, not longitudinal operating evidence.',
'A new entrant must outperform existing AI plus operator setup, not an imagined static legacy PMS.',
'https://www.entrata.com/|https://www.entrata.com/press/ai-powered-maintenance|https://www.entrata.com/products/leasing-ai','2025-06-11 maintenance announcement; 2026-09-15 Pro homepage'],
['Rent Manager','Core PMS + integrations','Residential; commercial; manufactured housing','leasing;resident_service;maintenance;turns;accounting;payments',
'Accounting, reporting, marketing, service issues, make-ready boards and custom workflows.',
'Vendor product/API documentation',
'No numeric price established from reviewed bundle page.',
'Public customization page explicitly describes read and write API access to Rent Manager Online database.',
'Partner fees, rate limits, endpoint semantics and commercial approval not established.',
'Potentially useful pilot platform because read/write is explicit; still test required operations.',
'https://www.rentmanager.com/|https://www.rentmanager.com/software-customization/|https://www.rentmanager.com/pricing/','Undated live pages'],
['EliseAI','Resident lifecycle AI + CRM','Multifamily; student; SFR; affordable','leasing;screening;move_in;resident_service;maintenance;turns;inspections;renewals;collections;compliance',
'AI leasing, tours, lease audits, maintenance, renewals and delinquency; payment-plan communications include guarantors.',
'Vendor product documentation plus public implementation help; outcomes unverified',
'Not published on reviewed pages.',
'Maintenance integrations include Yardi, Entrata, RealPage, ResMan and AppFolio; RealPage requires leasing integration for unit details.',
'Contact changes can take about 24 hours to sync; cancellations may need source PMS; emergency setup review required.',
'Resident communication and routine follow-up are crowded; integration behavior offers concrete diligence tests.',
'https://eliseai.com/platform-overview|https://eliseai.com/delinquency|https://support.meetelise.com/hc/en-us/articles/39887009308301-Getting-Started-with-MaintenanceAI','2026-07-09 help update; product pages undated'],
['Funnel','Leasing CRM + AI','Multifamily operators','leasing;screening;move_in;resident_service;renewals;payments',
'Renter-centric CRM across properties; centralized specialized teams, tours, omnichannel communication, workflow builder and prospect/resident AI.',
'Vendor product/package documentation; performance unverified',
'Packages published; no numeric quote on reviewed page.',
'PMS integrations advertised; exact actions not verified.',
'Case-study savings are selected vendor claims, not representative causal effects.',
'Centralizing roles across properties is already an operating-model product, not untapped conceptual novelty.',
'https://funnelleasing.com/products/next-generation-crm|https://funnelleasing.com/products/packages','Undated live pages'],
['Property Meld','Maintenance operations + AI','SFR; multifamily; HOA; student','maintenance;procurement;accounting',
'MAX intake, scheduling, follow-up and on-call; decision guidance; TrueCost expected repair costs and billing validation.',
'Vendor product/pricing documentation; accuracy and savings claims unverified',
'Monthly Core $1.60/unit; Ops $2.00/unit; MAX On-Call add-on $1.50/unit.',
'PMS integrations advertised; detailed permissions not established here.',
'No causal validation of cost/renewal claims; package minimums and contract need confirmation.',
'Both coordination and maintenance cost checking have direct specialist competition.',
'https://propertymeld.com/pricing/|https://propertymeld.com/max-intelligence/|https://propertymeld.com/truecost/','Undated live pages'],
['Latchel','AI front office + maintenance service','Growing residential property managers','leasing;owner_onboarding;resident_service;maintenance',
'AI call handling, troubleshooting, trip bundling, dispatch and voice-based vendor interaction, with human escalation.',
'Vendor product documentation; performance unverified',
'No numeric price on reviewed page.',
'Full integrations and lighter data pipelines explicitly distinguished by PMS.',
'Coverage and exact write semantics vary; intake resolution claims do not prove safe avoided repairs.',
'A low-friction voice coordinator and human fallback already exist; execution quality must be measured.',
'https://latchel.com/','Undated live page'],
['Lula','Managed maintenance network + software','Residential property managers','maintenance;turns;procurement',
'Maintenance coordination and service network; software plus technicians, scheduling and after-hours support.',
'Vendor service documentation; scale/performance claims unverified',
'Homepage markets no subscription fee for managed-maintenance offer; service charges require quote.',
'Can be assigned work as a vendor in existing PMS; integrated coordination offer also marketed.',
'Local capacity, service price, SLA and responsibility vary; free software is not free repairs.',
'Competes by delivering physical work, not just generating a better task list.',
'https://lula.life/|https://lula.life/property-managers','Undated live pages'],
['HappyCo','Maintenance + inspections + procurement','Multifamily operators','maintenance;inspections;turns;procurement;asset_management',
'Inspections, maintenance workflows, AI assignment, preventative planning, inventory and AI-assisted procurement; JoyAI triage.',
'Vendor product documentation; performance unverified',
'Not published on reviewed page.',
'Ecosystem distribution includes Buildium inspection integration.',
'Exact AI availability, data capture burden and procurement scope need verification.',
'Inspection-to-maintenance-to-spend is already a specialist expansion path.',
'https://happy.co/|https://www.buildium.com/pricing/','Undated live pages'],
['Lessen','Managed property services + AI','Residential owners; commercial occupiers; enterprise portfolios','maintenance;turns;procurement;accounting;asset_management',
'Service network and facilities platforms; Aiden assists diagnosis, dispatch, updates and draft technician invoicing.',
'Vendor service/product documentation; performance unverified',
'Not published on reviewed pages.',
'Platform/network model; announced HappyCo integration 2026-05-19.',
'Not evidence that all physical jobs are autonomously completed; contractor review and field execution remain.',
'Managed outcome competition includes vendor labor supply and payment, not only software.',
'https://www.lessen.com/|https://www.lessen.com/aiden','2026-05-19 integration noted on homepage; Aiden undated'],
['RentCheck','Inspections + condition records','Residential rental managers','inspections;maintenance;move_in;move_out',
'Resident/staff/vendor inspections, time-stamped capture, comparisons, workflows, AI Damage Assist and deduction reports.',
'Vendor pricing/product documentation; performance unverified',
'Starts $1 Launch, $1.25 Accelerate, $1.75 Velocity per unit/month.',
'PMS and work-order integrations; Accelerate limited API; higher-tier advanced integrations.',
'An image and deduction report do not establish legal chargeability; validate completeness and resident participation.',
'Photo comparison, resident self-inspection and inspection follow-up are established products.',
'https://www.getrentcheck.com/plan-pricing','Undated live page'],
['zInspector','Inspections + condition records','Residential managers','inspections;move_in;move_out;maintenance',
'Property inspections and zTenant guided resident inspections with signatures and reminders.',
'Vendor product documentation; performance unverified',
'Numeric pricing not verified.',
'Integration details not inspected in this review.',
'Coverage of inaccessible spaces, hidden defects and truth of resident submissions remains an operational issue.',
'A condition record or guided capture app alone is a well-served category.',
'https://zinspector.com/','Undated live page'],
['Zego','Payments + utility operations','Multifamily; HOA; student; manufactured; BTR','payments;accounting;resident_service;move_out;renewals',
'Digital rent/dues payments, utility AP and resident billing, vacant-unit cost recovery and resident payouts.',
'Vendor product documentation; savings claims unverified',
'Request pricing.',
'PMS/accounting integrations advertised.',
'Transaction cost, recovery rules and full accounting reconciliation scope need diligence.',
'Payment routing, utility recovery and deposit payout workflows already have scaled specialists.',
'https://www.gozego.com/','Undated live page'],
['PayProp','Payments + trust accounting','Rental managers; US/UK/Canada/South Africa','payments;accounting;collections;maintenance;resident_service',
'Bank-connected rental collections, reconciliation, distributions and arrears reminders.',
'Vendor product/pricing documentation; performance unverified',
'US page: service fee less than 1% processing volume; setup $660-$2250; license $40/pm as displayed.',
'Public page describes documented API and third-party integrations.',
'Confirm US-specific plan/meaning of license unit; website includes cross-region examples.',
'Trust-money automation already has bank-embedded alternatives; geography changes delivery requirements.',
'https://www.payprop.com/us|https://www.payprop.com/us/pricing','Undated live pages'],
['Flex','Rent payment financing','US renters and property partners','payments;collections',
'Renter pays in two installments while eligible rent is paid in full to property.',
'Vendor product documentation; efficacy unverified',
'Exact renter membership and transaction charges not verified in reviewed page.',
'Payment product rather than general workflow API.',
'Eligibility, financing terms, fees and risk allocation need product-specific diligence.',
'Changing cash timing can solve an underlying payment problem better than adding reminders.',
'https://getflex.com/','Undated live page'],
['Vantaca','Association PMS + vendor operations','HOA/community association managers','hoa_governance;accounting;payments;resident_service;procurement;compliance',
'Community-association management; vendor procurement, onboarding, compliance, invoice processing and payments.',
'Vendor product documentation; performance unverified',
'Not published on reviewed pages.',
'Native Vantaca vendor product; external API details not verified.',
'Association decisions require board/management authority distinctions absent from rental-only products.',
'HOA is a distinct buyer/workflow, already served by focused vendors.',
'https://www.vantaca.com/|https://www.vantaca.com/vendor','Undated live pages'],
['VTS','Commercial leasing + asset/tenant platform','Commercial owners; brokers; asset/property managers','leasing;asset_management;resident_service;maintenance',
'Commercial lease pipeline, lease abstraction, asset intelligence, property operations and tenant engagement.',
'Vendor product documentation; performance unverified',
'Not published on reviewed page.',
'Integration scope not verified here.',
'Commercial lease economics and negotiated obligations differ materially from apartment leasing.',
'Commercial data unification and lease intelligence are established, not empty adjacent markets.',
'https://www.vts.com/','Undated live page'],
['Building Engines','Commercial building operations','Office; retail; industrial','maintenance;inspections;procurement;compliance;resident_service',
'Prism work orders, preventive maintenance, bids, inspections, incidents, contracts, tenant compliance and AI.',
'Vendor product documentation; performance unverified',
'Numeric pricing not verified.',
'Partner ecosystem; Jones integration listed.',
'Confirm rights and depth of system integration for any proposed overlay.',
'Commercial operations coordination and compliance already have specialized systems.',
'https://www.buildingengines.com/','Undated live page'],
['Facilio','Facilities operations + AI','Global commercial portfolios; FM services; retail; healthcare','maintenance;inspections;asset_management;procurement;compliance',
'Connected CMMS, asset lifecycle, preventive maintenance, inspections, work orders and AI agents.',
'Vendor product documentation; performance unverified',
'Numeric pricing not verified.',
'Connected-operations platform; exact connector access not verified.',
'Building-system connectivity and deployed asset metadata can be costly prerequisites.',
'Cross-industry facilities automation can be a supplier or competitor to property-specific tools.',
'https://facilio.com/','Undated live page'],
['PetScreening','Pet policy management','Rental housing operators','screening;resident_service;compliance',
'Pet-policy management platform for housing operators.',
'Vendor product documentation; performance unverified',
'Pricing not verified.',
'Exact integration rights not verified.',
'Assistance-animal accommodation decisions require distinct treatment; product branding is not legal validation.',
'Small but administratively intensive resident subworkflows can sustain specialist vendors.',
'https://www.petscreening.com/','Undated live page'],
['Obligo','Deposit alternatives + administration AI','Rental owners; managers; renters','move_in;payments;move_out;compliance',
'Deposit options and digital charge/refund flow; Deposit Agent announced for requirements, charges, refunds and disputes.',
'Vendor product documentation + announcement; AI rollout not confirmed',
'Pricing not verified.',
'Announcement promises platform/API/MCP access for customers and embedded PMS partners.',
'June 15 announcement said availability in coming months; do not classify as proven generally available execution.',
'Deposit disposition is directly targeted by a funded adjacent specialist; validate actual feature gap before building.',
'https://www.obligo.com/|https://www.obligo.com/blog/obligo-introduces-the-first-ai-agent-for-security-deposits','2026-06-15 agent announcement'],
['TheGuarantors','Lease guarantee + insurance','Multifamily; SFR; student; independent owners','screening;move_in;collections;compliance',
'Renter underwriting paired with lease guarantees; default/damage/vacancy coverage and renters-insurance compliance.',
'Vendor product documentation; outcomes unverified',
'Product-specific pricing not verified.',
'Lease Guarantee API and PMS integrations listed.',
'Insurance exclusions, claim requirements and renter pricing matter more than headline automation.',
'Risk transfer can change who qualifies and loss economics, not merely speed existing checks.',
'https://www.theguarantors.com/','Undated live page'],
['Findigs','Screening + rental decisioning','Rental housing operators','screening;leasing;compliance',
'Application verification, automated decisions and policy management; advertises individualized assessment and audit trail.',
'Vendor product claims; fairness/compliance/outcomes not independently validated',
'Pricing not verified.',
'Integration details not established from reviewed homepage.',
'Do not treat vendor claims as proof of legal compliance, lower bad debt or fair outcomes.',
'Automating eligibility decisions is already offered; differentiation needs measured outcomes and defensible review.',
'https://www.findigs.com/','Undated live page'],
['LeadSimple','Owner CRM + workflow/communications','Residential fee managers','owner_onboarding;leasing;move_in;resident_service;maintenance;inspections;turns;renewals',
'Owner CRM, shared phone/inbox, timed workflows, escalation and AI; operations templates span owner onboarding to make-ready.',
'Vendor product/pricing documentation; performance unverified',
'Operations $1.35/door/month ($200 min; $1.55 monthly); Platform $2.99 ($500 min annual; $3.49 monthly).',
'PMS triggers/integrations; Rent Manager help specifies hourly one-way object sync.',
'A connection logo does not prove bidirectional real-time workflow execution.',
'Generic follow-up and cross-workflow task coordination are already inexpensive specialist products.',
'https://www.leadsimple.com/pricing|https://training.leadsimple.com/en/articles/8899456-detailed-overview-of-our-direct-api-integration-with-rent-manager','2024-02-02 integration help article; live pricing undated'],
['Jones','Insurance compliance automation','Commercial real estate; construction','procurement;compliance',
'Collects insurance documents, checks coverage against requirements, follows up on gaps and tracks renewals.',
'Vendor product documentation; accuracy claims unverified',
'Pricing not verified.',
'MRI partner page describes embedded requests, audits and expiration monitoring.',
'COI collection alone does not resolve all contractual insurance or actual coverage questions.',
'Document-driven third-party compliance with external follow-up already has strong focused competition.',
'https://getjones.com/|https://www.mrisoftware.com/partners/jones-software/','Undated live pages'],
['Fixflo','Repairs + planned maintenance','UK lettings; blocks; BTR; commercial','maintenance;procurement;compliance;resident_service',
'Repair reporting, communications, planned maintenance and contractor instructions; contractor marketplace.',
'Vendor product/pricing documentation; performance unverified',
'Quoted portfolio pricing plus software fee; exact current plan fee should be reconfirmed.',
'Integrations marketed; exact API rights not inspected.',
'UK service standards/regulation and contractor geography do not automatically transfer to US.',
'UK block/commercial repair practices supply useful comparisons, not an assumption of US whitespace.',
'https://www.fixflo.com/features|https://www.fixflo.com/pricing/lettings|https://www.fixflo.com/features/contractor-marketplace','Undated live pages'],
]
records = [dict(zip(columns, row+['2026-09-15'])) for row in rows]
out = Path(__file__).parent
(out/'competitors.json').write_text(json.dumps(records, indent=2)+'\n')
with (out/'competitors.csv').open('w', newline='') as f:
    writer=csv.DictWriter(f, fieldnames=columns)
    writer.writeheader(); writer.writerows(records)
assert len(records)==30
assert all(len(r)==len(columns) for r in records)
print(f'Wrote {len(records)} providers.')
