"""Scope decisions for the Stage A source register: which units of each instrument go to section-level classification,
and the reason every other unit is excluded. Read by build_instruments.py (register/instruments.json) and by the
text savers. Units are kept generously: a unit whose heading is not plainly outside the chain is IN.

The chain (STAGE_A.md 'Chain (aperture)', this register's brief): from facts fixed at move-in and the notice that a
market-rate NYC residential tenancy is ending, to the account closed, including collection, suit, judgment,
enforcement and write-off, unclaimed funds, bankruptcy, death, military service, disability, domestic violence,
coerced debt, tax and information reporting, data and privacy, credit reporting and anti-discrimination.
Out of aperture: rent-stabilized and rent-controlled units, public, project-based or subsidized housing, Virginia,
places outside NYC, commercial tenancies.
"""

DEFAULT_OUT = ("Heading shows subject matter outside the chain ({h}); it imposes no duty, bar, deadline, amount or "
               "consequence on a landlord, managing agent, collector or tenant settling a market-rate NYC tenancy.")
REPEALED_OUT = "Repealed or reserved unit ({h}); no operative text."
RS = "Out of aperture: rent stabilization regime (operative rules for stabilized units, not the routing test)."
RC = "Out of aperture: rent control regime (operative rules for controlled units, not the routing test)."
OUTSIDE_NYC = "Out of aperture: applies only to places outside New York City."
SUBSIDIZED = "Out of aperture: public, project-based or subsidized housing program."
COMMERCIAL = "Out of aperture: commercial tenancies or commercial property."

# ------------------------------------------------------------------------------------------------ NY statutes
# Out-reasons for units adjacent to the chain (others take DEFAULT_OUT). Keys: article number, or 'article/sub'.
NY_OUT = {
    "GOL": {
        "5/4": "Wagering contracts; no tenancy term or collection step is a wager.",
        "5/14": "Choice-of-law/forum clauses enforceable only in transactions of $250,000 or more (5-1401); a residential lease balance never qualifies.",
        "5/15-a": "Designation of a person in parental relation for a child; no bearing on a tenancy account.",
        "5/16": "Continuity of contract after currency or benchmark changes (euro, LIBOR); not a tenancy term.",
        "5/17": "Structured settlement transfers; no tenancy money is a structured settlement.",
        "7/2": "Sale of licensed taxicabs.",
        "7/3": "Liability of sureties on court undertakings; a lease guaranty or deposit is not an undertaking.",
        "7/4": "Buyer's right of redemption of pledged goods.",
        "9": "Duties of care of landowners to recreational users and similar tort limits; not the tenancy account.",
        "12": "Civil liability of drug dealers.",
        "18": "Ski safety code.", "18-a": "Employer/employee liability specifications (workplace).",
        "18-b": "Agricultural tourism safety.", "18-c": "LIBOR discontinuance in financial contracts.",
        "19": "Laws repealed (no operative text).",
    },
    "RPL": {
        "2": "Tenure and capacity to hold real property (aliens, corporations); no duty in the tenancy settlement.",
        "4": "Uses and trusts of land.", "4-a": "Trust indentures.", "6": "Dower and curtesy (abolished estates).",
        "7a": "Portable kerosene heaters (sale and use rules); no settlement duty.",
        "9": "Recording of conveyances and mortgages; the chain needs no recorded instrument.",
        "9-a": "Subdivided lands.", "9-b": "Condominium Act (unit owners and boards); the tenancy account is governed by art. 7 and GOL art. 7 whether or not the unit is a condominium.",
        "9-c": "Solar rights.", "9-d": "Electric vehicle charging rights of owners.",
        "9-e": "Manufactured homes as real property.", "10": "Ancient mortgages.", "12": "Torrens title registration.",
        "12-b": "Home inspection professional licensing (sales).",
        "12-c": "Apartment information vendors (fee-charging listing services used by prospective tenants before a lease); outside the chain.",
        "12-d": "Short-term rental units (stays under 30 days) registration; not a residential tenancy.",
        "13": "Cemetery lands.", "14": "Property condition disclosure in sales of residential real property.",
        "15": "Private transfer fee obligations on conveyances.", "16": "Waiting period for sales of 1-2 family homes to institutional purchasers.",
        "20": "Laws repealed.",
    },
    "RPAPL": {
        "3": "Evidence of title and presumptions in real property actions.", "4": "Valuing interests in real property.",
        "5": "Adverse possession.", "7-b": "Removal of abandoned manufactured homes.", "9": "Partition.",
        "10": "Dower.", "11": "Death of a tenant for life (life estates).", "12": "Actions between co-owners or successive owners.",
        "15": "Actions to determine claims to real property (quiet title).", "16": "Judicial authorization of sales/leases of real property.",
        "17": "Disposition of real property of infants and incompetents.", "18": "Release of claims against the State.",
        "19": "Discharge of encumbrances.", "19-a": "Conveyance of abandoned dwellings to municipalities.",
        "19-b": "Conveyance of abandoned commercial and industrial property.", "20": "Enforcement of covenants and easements.",
        "20-a": "Homeowners' association liens.", "21": "Effective date (no operative duty).",
    },
    "MDL": {
        "4": "Construction standards for fireproof multiple dwellings.", "5": "Construction standards for non-fireproof multiple dwellings.",
        "5-a": "Garden-type maisonette projects (construction).", "6": "Converted dwellings (construction standards).",
        "7": "Old-law tenement construction and alteration standards.", "7-a": "Temporary provisions (expired).",
        "7-b": "Joint living-work quarters for artists (loft conversion standards); occupancy regulated under art. 7-C when residential.",
        "7-c": "Out of aperture: interim multiple dwellings (Loft Law) regime; covered units become rent-stabilized.",
        "10": "Owner penalties where a dwelling is used for prostitution.", "11": "Laws repealed.",
    },
    "CPLR": {
        "3-a": "Conflict of laws in actions about legally protected health activity.",
        "4": "Special proceedings (general procedure); the chain's suits are actions or summary proceedings under RPAPL art. 7.",
        "6": "Joinder and severance of claims (court procedure, no party duty).", "9": "Class actions.",
        "11": "Poor-person fee waivers (court fees).", "13": "Actions by the State.", "13-a": "Crime proceeds forfeiture.",
        "13-b": "Civil remedies for crimes.", "14": "Contribution among tortfeasors.", "14-a": "Comparative fault in personal injury.",
        "16": "Limited liability of joint tortfeasors for non-economic loss.", "21-a": "E-filing mechanics.",
        "23": "Subpoenas.", "24": "Publication of notices.", "25": "Undertakings (bonds) in litigation.",
        "26": "Property paid into court.", "27": "Disposition of property in litigation.", "31": "Disclosure (discovery procedure).",
        "34": "Calendar practice.", "40": "Trial generally (court procedure).", "41": "Jury trial.", "42": "Trial by the court.",
        "43": "Trial by referee.", "44": "Trial motions.", "50-a": "Periodic payment of malpractice judgments.",
        "50-b": "Periodic payment of personal injury judgments.",
        "53": "Recognition of foreign-country money judgments.",
        "54": "Enforcement in NY of other states' judgments; the chain's judgments are NY judgments.",
        "55": "Appeals.", "56": "Appeals to the Court of Appeals.", "57": "Appeals to the Appellate Division.",
        "63": "Injunctions.", "63-a": "Extreme risk protection orders.", "65": "Notice of pendency (real property title actions).",
        "70": "Habeas corpus.", "71": "Replevin of chattels.", "72": "Recovery of penalties or forfeitures by the State.",
        "75": "Arbitration (no arbitration step in the chain; an arbitration clause is a contract term, not a statute of the chain).",
        "75-a": "Health care arbitration.", "76": "Agreements to determine an issue.", "77": "Express trust proceedings.",
        "78": "Proceedings against public bodies or officers.", "86": "Counsel fees in actions against the State.",
        "90": "Adjournment of court terms.", "94": "Admission to practice.", "97": "Records of court clerks.",
        "98": "Actions against villages.", "100": "Repeal.",
    },
    "GBL": {
        "3": "Auctioneers.", "7": "Private investigators and guards.", "8": "Process servers outside NYC.",
        "8-a": "Licensing of process servers in NYC; the server's licence duty is the server's, not a step the landlord decides.",
        "11": "Employment agencies.", "12": "Hotels and boarding houses (innkeepers' duties, not tenancies).",
        "12-b": "Online retailers.", "24-a": "Fair trade (resale price) law.",
        "28-b": "Budget planning (debt adjusters).", "28-bb": "Credit services businesses (credit repair).",
        "29-a": "Unauthorized use of credit and debit cards (criminal).", "29-g": "Receipts for personal property.",
        "29-i": "Storage of household goods by warehousemen; a landlord holding a former tenant's belongings is not a storage business.",
        "34": "Creditor billing errors under open-end consumer credit plans; a lease is not such a plan.",
        "34-a": "Consumer credit balances of creditors under open-end plans; not a lease.",
        "34-b": "Annual credit interest statements.", "36-c": "Down payments in residential real estate purchases.",
        "36-e": "Unfair real estate service agreements (sales listings).", "37": "Deposits on construction of new homes.",
        "39-ff": "Child data protection (online services to minors).",
        "39-g": "Document destruction contractors (licensing of shredding businesses).",
        "39-h": "Third-party litigation financing.", "46": "Laws repealed.",
    },
    "JUD": {
        "2": "General provisions on courts and judges (court administration).", "5-a": "City Court of the City of New York (historic article).",
        "13": "Sheriffs and constables (office rules); enforcement steps and fees the chain uses are in CPLR arts. 52 and 80 and CCA arts. 15-16.",
        "19": "Contempt powers of courts.", "23": "Laws repealed.",
    },
    "UCC": {
        "2": "Sales of goods.", "2-a": "Leases of goods (personal property), not real property leases.",
        "4": "Bank deposits and collections between banks and customers; the landlord's duty to a payee who does not cash a refund check is governed by ABP arts. 13-14.",
        "4-a": "Funds transfers between banks.", "5": "Letters of credit.", "7": "Documents of title.", "8": "Investment securities.",
        "9": "Secured transactions; excludes interests in real property leases and rents (9-109(d)(11)).",
        "11": "Transition from original article 9.", "12": "Controllable electronic records.",
        "12-a": "Transition provisions for UCC amendments.", "13": "Effective date and repealer.",
    },
    "ABP": {
        "2": "Escheat of real property.", "3": "Unclaimed property held by banking organizations (the bank's own reporting duty).",
        "4": "Unclaimed utility deposits and refunds (utility corporations).", "5": "Unclaimed property held for security holders.",
        "5-a": "Unclaimed property held by brokers.", "6": "Unclaimed court funds.", "7": "Unclaimed life insurance funds.",
        "10": "Unclaimed condemnation awards.", "12": "Property deposited in federal courts.",
        "12-a": "Property held by the United States.", "15": "Laws repealed.",
    },
    "EPTL": {
        "2": "Rules governing dispositions (validity and effect of wills and trusts).", "3": "Substantive law of wills.",
        "5": "Family rights (elective share, exempt property of the family).", "6": "Classification of estates in property (future interests).",
        "7": "Trusts.", "8": "Charitable trusts.", "9": "Perpetuities and accumulations.", "10": "Powers of appointment.",
        "11-a": "Principal and income allocation by fiduciaries.", "13/2": "Statute of frauds for estates and trusts.",
        "13/4": "Transfer-on-death security registration.", "13-a": "Fiduciary access to digital assets.", "14": "Repealer.",
    },
    "EXEC": {"6-e": "Real estate appraisers.", "21-b": "Manufactured homes (parks and installers).",
             "18": "Uniform Fire Prevention and Building Code (construction standards)."},
    "LLC": {"3": "Service of process on LLCs; the chain's defendant is the individual tenant.",
            "10": "Mergers.", "12": "Professional service LLCs.", "13": "Foreign professional service LLCs.",
            "1": "Short title and definitions (definitions are read with arts. 2 and 8 where those sections are stated).",
            "4": "Management of LLCs (internal governance).", "5": "Contributions and distributions (internal).",
            "6": "Members and membership (internal).", "7": "Dissolution.", "11": "Miscellaneous.", "14": "Savings clauses."},
    "BCL": {"3": "Corporate name and service of process on corporations.", "10": "Non-judicial dissolution.",
            "11": "Judicial dissolution.", "12": "Receivership of corporations (corporate insolvency)."},
    "GCN": {"3": "Ancient statutes and resolutions.", "6": "Effect of the consolidated laws (1909 consolidation).",
            "8": "Laws repealed."},
    "STT": {"1": "Office of Information Technology Services (state agency).",
            "2": "Internet Security and Privacy Act (state agencies' websites only).",
            "4": "Automated employment decisions in state government.", "5": "Automated decision-making in state agencies."},
    "SSL": {"5/2": "State reimbursement of districts for public assistance.", "5/3": "Home relief (repealed program).",
            "5/11": "Medical assistance (Medicaid).", "2-a": "Shelter and supported housing programs operated by the State.",
            "6-a": "Domestic violence prevention act (state services programs); victim protections in tenancies are RPL 227-c and 34 USC 12491."},
    "DCL": {"2": "General assignments for the benefit of creditors (commercial insolvency).",
            "2-a": "Secured creditors' rights in assignments.", "3": "Insolvent's discharge (obsolete state insolvency procedure).",
            "4": "Exemption from arrest (obsolete).", "5": "Discharge from imprisonment for debt (obsolete).",
            "7": "Trustees for insolvent and imprisoned debtors (obsolete).",
            "10": "Voidable transactions (creditor remedies against transfers); no settlement step turns on it.",
            "11": "Laws repealed."},
    "PTR": {"1": "Short title and definitions of partnership law.", "2": "Nature of a partnership.",
            "3": "Partners' liability to third persons; the chain's landlord-side capacity to sue is in arts. 8-A and 8-B.",
            "4": "Relations of partners to one another.", "5": "Property rights of partners.", "6": "Dissolution.",
            "7": "Business and partnership names (assumed names are GBL 130).", "8": "Old limited partnerships (pre-1991 law).",
            "9": "Laws repealed."},
    "MHY": {"a": "Organization of the Department of Mental Hygiene.", "b": "Mental health services.",
            "c": "Developmental disabilities services.", "d": "Addiction services."},
    "NPCL": {},
    "MIL": {},
}
NY_SUB_OUT_DEFAULT = "Title/part of an in-scope article whose heading shows subject matter outside the chain ({h})."
MHY_E_OUT = "Mental Hygiene Law title E article other than 81 ({h}): facility, patient-rights or program rules; only art. 81 guardianship decides who acts for a tenant."

# CCA and SCPA (archived nysenate.gov): articles in scope and out-reasons
CCA_IN = ["A1", "A2", "A3", "A4", "A8", "A9", "A14", "A15", "A16", "A18", "A18-A", "A19", "A21"]
CCA_OUT = {"A7": "Mandates (form of court process); no party decision.", "A10": "Motion practice (court procedure).",
           "A11": "Disclosure procedure.", "A12": "Subpoenas.", "A13": "Trial procedure.", "A17": "Appeals.",
           "A22": "Transition from former courts (1963)."}
SCP_IN = ["A1", "A7", "A10", "A11", "A13", "A16", "A17", "A17-A", "A18", "A21"]
SCP_OUT = {"A2": "Surrogate's Court jurisdiction and powers (court's own competence).",
           "A3": "Pleadings and process in Surrogate's Court.", "A4": "Appearance and protection of persons under disability in Surrogate's Court proceedings.",
           "A5": "Trials and hearings.", "A6": "Orders and decrees.", "A8": "Fiduciary bonds.",
           "A9": "Temporary administration for absentees and internees.",
           "A12": "Public administrators outside New York City.", "A14": "Probate and will construction.",
           "A15": "Testamentary trusts.", "A19": "Disposition of a decedent's real property.",
           "A20": "Opening a decedent's safe deposit box.", "A22": "Judicial accounting by fiduciaries.",
           "A23": "Costs, allowances and commissions.", "A24": "Court fees.", "A25": "Court records.",
           "A26": "Surrogate's Court officers.", "A27": "Appeals.", "A28": "Repeal and savings clause."}

# ------------------------------------------------------------------------------------------------ NYC XML
# Admin Code units: (title, chapter[, subchapter/article]) -> in, keyed by heading substrings.
ADC_TITLES_IN = ["8", "20", "26", "27"]
ADC_IN = {  # title -> list of unit-heading prefixes (chapter or chapter > subchapter[/article]) that are IN
    "8": ["Chapter 1: Commission on Human Rights", "Chapter 4:", "Chapter 5:", "Chapter 6:"],
    "20": ["Chapter 1: License Enforcement", "Chapter 2: Licenses > Subchapter 30:",
           "Chapter 4: Regulation of Commodities and Services > Subchapter 15:",
           "Chapter 5: Unfair Trade Practices > Subchapter 1:", "Chapter 5: Unfair Trade Practices > Subchapter 16:"],
    "26": ["Chapter 3: Rent Control", "Chapter 4: Rent Stabilization", "Chapter 5: Unlawful Eviction",
           "Chapter 11:", "Chapter 12:", "Chapter 13: Certification of Certain Rent Payment", "Chapter 24:", "Chapter 29:",
           "Chapter 30: Tenant Data Privacy", "Chapter 34:", "Chapter 39:"],
    "27": ["Chapter 2: Housing Maintenance Code > Subchapter 1:",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 1:",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 2:",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 3:",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 4:",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 11:",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 12:",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 14:",
           "Chapter 2: Housing Maintenance Code > Subchapter 3: Physical and Occupancy Standards for Dwelling Units > Article 5:",
           "Chapter 2: Housing Maintenance Code > Subchapter 4: Administration > Article 1:",
           "Chapter 2: Housing Maintenance Code > Subchapter 4: Administration > Article 2:",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 1:",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 5:",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 6:",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 7:",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 8:",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 10:"],
}
# Unit depth per title/chapter: HMC at article level, title 20 chs. 2/4/5 at subchapter level, else chapter.
ADC_OUT = {
    "8": {"Chapter 2:": "Blockbusting and similar real estate sales practices (8-201 et seq.); no settlement step.",
          "Chapter 3:": "Protection of civil rights demonstrations.", "Chapter 7:": "Discriminatory boycotts by businesses.",
          "Chapter 8:": "Police search and force.", "Chapter 9:": "City anti-discrimination hotline (agency duty)."},
    "26": {"Chapter 2:": "City relocation services for displaced occupants (agency program).",
           "Chapter 6:": "Rent increases in city-aided projects (1940s emergency provision).",
           "Chapter 7:": "Out of aperture: SCRIE/DRIE rent-increase exemptions apply only to rent-regulated and Mitchell-Lama units.",
           "Chapter 8:": "Cooperative and condominium conversions (sponsor/tenant purchase rights).",
           "Chapter 9:": "Right of first refusal on sales of certain buildings (sales).",
           "Chapter 10:": "HPD reporting on housing development projects (agency duty).",
           "Chapter 13: Provision of Legal Services": "City program providing counsel to tenants in eviction proceedings (agency duty).",
           "Chapter 15:": "Out of aperture: 421-a affordability audits (subsidized units).",
           "Chapter 16:": "Out of aperture: 421-a rent registration audits (regulated units).",
           "Chapter 21: Short-Term": "Short-term residential rentals (stays under 30 days); not a residential tenancy.",
           "Chapter 31:": "Registration of short-term rentals (stays under 30 days).",
           "Chapter 32:": "Booking services for short-term rentals.",
           "Chapter 33:": "Out of aperture: zoning affordability requirements (regulated affordable units).",
           "Chapter 35:": "Universal design units in new construction.",
           "Chapter 37: Sales": "Sales of cooperative apartments.",
           "Chapter 38:": "Hiring standards on city-assisted construction."},
    "27": {"Chapter 1:": "1968 Building Code (construction standards); no settlement step.",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 5:": "Collection of building waste (owner service duty); not a tenant charge or settlement step.",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 6:": "Water supply service standards.",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 7:": "Sewer and drainage standards.",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 8:": "Heat, cooling and hot water service standards (owner service duty during occupancy).",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 9:": "Gas appliance standards.",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 10:": "Artificial lighting of public areas.",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 13:": "Janitorial services in multiple dwellings.",
           "Chapter 2: Housing Maintenance Code > Subchapter 2: Maintenance, Services, and Utilities > Article 15:": "Steam radiator inspections.",
           "Chapter 2: Housing Maintenance Code > Subchapter 3: Physical and Occupancy Standards for Dwelling Units > Article 1:": "Light and ventilation standards.",
           "Chapter 2: Housing Maintenance Code > Subchapter 3: Physical and Occupancy Standards for Dwelling Units > Article 2:": "Sanitary facility standards.",
           "Chapter 2: Housing Maintenance Code > Subchapter 3: Physical and Occupancy Standards for Dwelling Units > Article 3:": "Kitchen standards.",
           "Chapter 2: Housing Maintenance Code > Subchapter 3: Physical and Occupancy Standards for Dwelling Units > Article 4:": "Room size and occupancy standards (occupancy limits during a tenancy).",
           "Chapter 2: Housing Maintenance Code > Subchapter 3: Physical and Occupancy Standards for Dwelling Units > Article 6:": "Vacant multiple dwellings (sealing).",
           "Chapter 2: Housing Maintenance Code > Subchapter 4: Administration > Article 3:": "Speculation watch list (HPD publication).",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 2:": "HPD civil penalties against owners for violations (owner-city liability).",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 3:": "Criminal penalties for violations.",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 4:": "Injunctions by HPD.",
           "Chapter 2: Housing Maintenance Code > Subchapter 5: Legal Remedies and Enforcement > Article 9:": "Withdrawal of SRO units from the rental market."},
    "20": {"Chapter 2: Licenses > Subchapter 22:": "Home improvement contractor licensing; the contractor's licence is the contractor's duty.",
           "Chapter 2: Licenses > Subchapter 23:": "Process server licensing (server's own duty).",
           "Chapter 2: Licenses > Subchapter 28:": "Storage warehouse licensing; a landlord holding belongings is not a warehouse.",
           "Chapter 2: Licenses > Subchapter 39:": "Self-storage facility licensing.",
           "Chapter 5: Unfair Trade Practices > Subchapter 15: Payday": "Payday loans.",
           "Chapter 3:": "Weights and measures."},
}
RCNY_TITLES_IN = ["6", "28", "31", "47", "68"]
RCNY_IN = {
    "6": ["Chapter 1: License Enforcement", "Chapter 2: Licenses > Subchapter S:",
          "Chapter 5: Unfair Trade Practices > Subchapter A: Consumer Protection Law > Part 1:",
          "Chapter 5: Unfair Trade Practices > Subchapter A: Consumer Protection Law > Part 3:",
          "Chapter 5: Unfair Trade Practices > Subchapter A: Consumer Protection Law > Part 4:",
          "Chapter 5: Unfair Trade Practices > Subchapter A: Consumer Protection Law > Part 6:",
          "Chapter 5: Unfair Trade Practices > Subchapter O:",
          "Chapter 6: Administrative Hearings > Subchapter B:"],
    "28": ["Chapter 1: Rules and Regulations", "Chapter 11:", "Chapter 12:", "Chapter 20:",
           "Chapter 25: Multiple Dwellings > Subchapter F:", "Chapter 25: Multiple Dwellings > Subchapter H:",
           "Chapter 25: Multiple Dwellings > Subchapter Q:", "Chapter 43:", "Chapter 54:", "Chapter 59:"],
    "31": ["Chapter 5:"],
    "47": ["Chapter 2:"],
    "68": ["Chapter 7:", "Chapter 9:", "Chapter 10: City Fighting Homelessness and Eviction Prevention Supplement (CityFHEPS)",
           "Chapter 10: City Fighting Homelessness and Eviction Prevention Supplement (CityFHEPS) > Subchapter A:"],
}
RCNY_OUT = {
    "28": {"Chapter 2:": SUBSIDIZED, "Chapter 3:": SUBSIDIZED, "Chapter 4:": SUBSIDIZED,
           "Chapter 5:": "Out of aperture: J-51 tax benefits (benefit units are rent-stabilized).",
           "Chapter 6:": "Out of aperture: 421-a tax exemption (benefit units are rent-stabilized).",
           "Chapter 14:": SUBSIDIZED, "Chapter 19:": SUBSIDIZED, "Chapter 21:": SUBSIDIZED, "Chapter 22:": SUBSIDIZED,
           "Chapter 24:": SUBSIDIZED, "Chapter 26:": COMMERCIAL, "Chapter 29:": SUBSIDIZED, "Chapter 30:": SUBSIDIZED,
           "Chapter 34:": SUBSIDIZED, "Chapter 35:": SUBSIDIZED, "Chapter 41:": SUBSIDIZED,
           "Chapter 60:": "Out of aperture: CityFHEPS repair program for rent-stabilized units."},
    "68": {"Chapter 8:": REPEALED_OUT.format(h="CITYFEPS/SEPS, repealed"),
           "Chapter 10: City Fighting Homelessness and Eviction Prevention Supplement (CityFHEPS) > Subchapter B:": "Out of aperture: project-based rental assistance.",
           "Chapter 10: City Fighting Homelessness and Eviction Prevention Supplement (CityFHEPS) > Subchapter C:": "Out of aperture: repair program for rent-stabilized units."},
}
ADC_OTHER_TITLE_OUT = ("Admin. Code title outside the chain ({h}); its chapters regulate city government or subjects "
                       "other than a residential tenancy, its money or collection from a former tenant.")
ADC_TITLE_OUT = {"28": "Construction Codes (building work standards; the certificate of occupancy bar on rent is MDL 301-302).",
                 "11": "Taxation and finance (city taxes; no tenancy-settlement duty).",
                 "17": "Health code administration (lead and pest duties that reach tenancies are in HMC, title 27 ch. 2).",
                 "7": "Legal affairs of the city (claims against the city)."}
RCNY_OTHER_TITLE_OUT = "RCNY title of an agency whose rules do not reach the tenancy settlement chain ({h})."
RCNY_TITLE_OUT = {"29": "Out of aperture: Loft Board rules (interim multiple dwelling regime).",
                  "30": "Out of aperture: Rent Guidelines Board orders (rent-stabilized rents).",
                  "1": "Department of Buildings rules (construction and certificate-of-occupancy procedure; the rent bar is MDL 301-302).",
                  "19": "Department of Finance rules (city taxes, parking, SCRIE/DRIE benefits for regulated units).",
                  "24": "Health Department rules (Health Code); tenancy lead and pest duties are in HMC and 28 RCNY."}

# ------------------------------------------------------------------------------------------------ Federal: USC
# Each instrument: USLM title, path filter (substring of the joined path), unit depth (number of path elements after
# the filter element that form the unit), IN unit-label substrings, OUT reasons by unit-label substring.
USC = [
    {"id": "US:11USC", "name": "Bankruptcy Code, 11 U.S.C.", "title": "11", "filter": "Title 11— BANKRUPTCY", "depth": 2,
     "in": ["CHAPTER 1—", "CHAPTER 3—", "CHAPTER 5—", "CHAPTER 7— LIQUIDATION > subchapter SUBCHAPTER I—",
            "CHAPTER 7— LIQUIDATION > subchapter SUBCHAPTER II—", "CHAPTER 11— REORGANIZATION > subchapter SUBCHAPTER I—",
            "CHAPTER 11— REORGANIZATION > subchapter SUBCHAPTER II—", "CHAPTER 11— REORGANIZATION > subchapter SUBCHAPTER III—",
            "CHAPTER 11— REORGANIZATION > subchapter SUBCHAPTER V—", "CHAPTER 13—"],
     "out": {"SUBCHAPTER III— STOCKBROKER": "Stockbroker liquidation.", "SUBCHAPTER IV— COMMODITY": "Commodity broker liquidation.",
             "SUBCHAPTER V— CLEARING BANK": "Clearing bank liquidation.", "CHAPTER 9—": "Municipal debt adjustment.",
             "RAILROAD": "Railroad reorganization.", "CHAPTER 12—": "Family farmer and fisherman debt adjustment; a residential tenant filing is under ch. 7, 11 or 13.",
             "CHAPTER 15—": "Cross-border insolvency (foreign main proceedings)."}},
    {"id": "US:FRBP", "name": "Federal Rules of Bankruptcy Procedure (11 U.S.C. appendix)", "title": "11a",
     "filter": "FEDERAL RULES OF BANKRUPTCY PROCEDURE", "depth": 1, "level": "court rule",
     "in": ["(rules before Part I)", "PART III—", "PART IV—", "PART IX—"],
     "out": {"PART I—": "Commencing a case and the petition (debtor and court procedure).",
             "PART II—": "Court officers, notices issued by the court, meetings and trustee administration; the creditor's own steps are Parts III-IV.",
             "PART V—": "Courts and clerks.", "PART VI—": "Estate administration by the trustee (procedure); the substantive rules are 11 U.S.C. chs. 3, 5.",
             "PART VII—": "Adversary proceeding procedure; the dischargeability deadline the landlord must meet is Rule 4007 (Part IV).",
             "PART VIII—": "Bankruptcy appeals."}},
    {"id": "US:15USC-ch41", "name": "Consumer Credit Protection Act, 15 U.S.C. ch. 41", "title": "15", "filter": "CHAPTER 41— CONSUMER CREDIT PROTECTION", "depth": 2,
     "in": ["Part A— General Provisions", "SUBCHAPTER II— RESTRICTIONS ON GARNISHMENT", "SUBCHAPTER III— CREDIT REPORTING",
            "SUBCHAPTER V— DEBT COLLECTION", "SUBCHAPTER VI— ELECTRONIC FUND"],
     "out": {"Part B— Credit Transactions": "TILA credit-transaction disclosures; a residential lease is not a credit transaction.",
             "Part C— Credit Advertising": "Credit advertising and credit card fees.",
             "Part D— Credit Billing": "Open-end credit billing disputes; a lease account is not an open-end credit plan.",
             "Part E— Consumer Leases": "Leases of personal property (1667(1)); not real property.",
             "SUBCHAPTER II–A— CREDIT REPAIR": "Credit repair organizations.",
             "SUBCHAPTER IV— EQUAL CREDIT": "Credit applications and credit decisions (ECOA); the settlement chain involves no extension of credit."}},
    {"id": "US:15USC-ch96", "name": "Electronic Signatures in Global and National Commerce Act, 15 U.S.C. ch. 96", "title": "15",
     "filter": "CHAPTER 96— ELECTRONIC SIGNATURES", "depth": 1, "in": ["SUBCHAPTER I—"],
     "out": {"SUBCHAPTER II—": "Transferable records (electronic notes secured by real property).",
             "SUBCHAPTER III—": "Federal promotion of international electronic commerce."}},
    {"id": "US:42USC-ch45", "name": "Fair Housing Act, 42 U.S.C. 3601-3631", "title": "42", "filter": "CHAPTER 45— FAIR HOUSING", "depth": 1,
     "in": ["SUBCHAPTER I—", "SUBCHAPTER II—"], "out": {}},
    {"id": "US:50USC-ch50", "name": "Servicemembers Civil Relief Act, 50 U.S.C. 3901-4043", "title": "50", "filter": "CHAPTER 50— SERVICEMEMBERS CIVIL RELIEF", "depth": 1,
     "in": ["(sections before subchapter I)", "SUBCHAPTER I—", "SUBCHAPTER II—", "SUBCHAPTER III—", "SUBCHAPTER VI—", "SUBCHAPTER VII—", "SUBCHAPTER VIII—"],
     "out": {"SUBCHAPTER IV— LIFE INSURANCE": "Protection of servicemembers' life insurance.",
             "SUBCHAPTER V— TAXES": "Taxes and public lands (tax sales, residence for tax purposes)."}},
    {"id": "US:47USC227", "name": "Telephone Consumer Protection Act, 47 U.S.C. 227", "title": "47", "filter": "Part I— Common Carrier Regulation", "depth": 0,
     "sections": ["227"], "in": ["section 227"],
     "out": {"*": "Other sections of 47 U.S.C. ch. 5 subch. II pt. I regulate common carriers (rates, interconnection, call authentication); only 227 reaches a caller collecting from a former tenant."}},
    {"id": "US:26USC-6041-6050", "name": "Internal Revenue Code, information returns (26 U.S.C. ch. 61 subch. A pt. III)", "title": "26",
     "filter": "PART III— INFORMATION RETURNS", "depth": 1, "in": ["Subpart B—"],
     "out": {"Subpart A—": "Information returns about persons subject to special provisions (foreign entities, partnerships' own returns).",
             "Subpart C—": "Wage statements to employees.", "Subpart D—": "Health insurance coverage reporting.",
             "Subpart E—": "Pension plan registration.", "Subpart F—": "Tax return preparers."}},
    {"id": "US:26USC166", "name": "Internal Revenue Code 166 (bad debts)", "title": "26",
     "filter": "PART VI— ITEMIZED DEDUCTIONS FOR INDIVIDUALS AND CORPORATIONS", "depth": 0, "sections": ["166"], "in": ["section 166"],
     "out": {"*": "Other itemized deductions of 26 U.S.C. ch. 1 subch. B pt. VI (interest, taxes, depreciation, etc.); only 166 governs writing off an uncollectible tenancy balance."}},
    {"id": "US:12USC5481", "name": "Consumer Financial Protection Act, 12 U.S.C. ch. 53 subch. V", "title": "12",
     "filter": "SUBCHAPTER V— BUREAU OF CONSUMER FINANCIAL PROTECTION", "depth": 1,
     "in": ["(sections before Part A)", "Part B— General Powers", "Part C— Specific Bureau Authorities"],
     "out": {"Part A—": "Establishment and administration of the CFPB (agency structure).",
             "Part D—": "Preservation of state law (relation of federal and state consumer law generally).",
             "Part E—": "CFPB enforcement powers and procedure.", "Part F—": "Transfer of functions to the CFPB.",
             "Part G—": "Regulatory improvements (agency reporting)."}},
    {"id": "US:12USC5220note", "name": "Protecting Tenants at Foreclosure Act (12 U.S.C. 5220 note)", "title": "12",
     "filter": "note", "depth": 0, "note_of": "5220", "note_heading": "Effect of Foreclosure on Preexisting Tenancy",
     "in": ["PTFA"], "out": {}},
    {"id": "US:34USC-VAWA", "name": "Violence Against Women Act housing protections, 34 U.S.C. ch. 121 subch. III pt. L", "title": "34",
     "filter": "Part L— Addressing the Housing Needs of Victims", "depth": 1, "in": ["subpart 2— housing rights"],
     "out": {"subpart 1— grant programs": "Federal grant programs for victim housing services (grantee duties)."}},
]

# ------------------------------------------------------------------------------------------------ Federal: CFR
ECFR = [
    {"id": "US:12CFR1006", "name": "Regulation F (Debt Collection Practices), 12 CFR part 1006", "title": "12", "part": "1006",
     "in": ["SUBPART A", "SUBPART B", "SUBPART D", "(appendices)"], "out": {}},
    {"id": "US:12CFR1005", "name": "Regulation E (Electronic Fund Transfers), 12 CFR part 1005", "title": "12", "part": "1005",
     "in": ["SUBPART A", "(appendices)"],
     "out": {"SUBPART B": "Remittance transfers abroad by remittance transfer providers."}},
    {"id": "US:12CFR1022", "name": "Regulation V (Fair Credit Reporting), 12 CFR part 1022", "title": "12", "part": "1022",
     "in": ["SUBPART A", "SUBPART E", "SUBPART F", "SUBPART I", "(appendices)"],
     "out": {"SUBPART C": "Affiliate marketing opt-outs.", "SUBPART D": "Creditors' use of medical information in credit eligibility.",
             "SUBPART H": "Risk-based pricing notices by creditors.", "SUBPART M": "Consumer reporting agencies' identity theft duties.",
             "SUBPART N": "Consumer reporting agencies' disclosures.", "SUBPART O": "Consumer reporting agencies' miscellaneous duties."}},
    {"id": "US:24CFR100", "name": "Fair Housing Act regulations, 24 CFR part 100", "title": "24", "part": "100",
     "in": ["SUBPART A", "SUBPART B", "SUBPART D", "SUBPART F", "SUBPART G", "SUBPART H"],
     "out": {"SUBPART C": "Discrimination in residential real estate-related transactions (lending, appraisal, brokerage of sales).",
             "SUBPART E": "Housing for older persons exemption (55+/62+ communities)."}},
    {"id": "US:24CFR982", "name": "Section 8 Housing Choice Voucher program (tenant-based), 24 CFR part 982", "title": "24", "part": "982",
     "in": ["SUBPART A", "SUBPART G", "SUBPART H", "SUBPART I", "SUBPART J", "SUBPART K", "SUBPART L"],
     "out": {"SUBPART B": "HUD requirements for PHA plans (agency administration).", "SUBPART C": "PHA funding.",
             "SUBPART D": "Annual contributions contract and PHA administration.", "SUBPART E": "Admission of families to the program.",
             "SUBPART M": "Special housing types (SRO, congregate, group, shared, cooperative, manufactured home, homeownership); not a conventional market-rate unit lease."}},
    {"id": "US:24CFR5", "name": "HUD general program requirements, 24 CFR part 5", "title": "24", "part": "5",
     "in": ["SUBPART A", "SUBPART D", "SUBPART L"],
     "out": {"SUBPART B": "SSN disclosure and income verification by program applicants.",
             "SUBPART C": SUBSIDIZED + " (pet ownership in elderly/disabled assisted projects and public housing)",
             "SUBPART E": "Noncitizen eligibility for assistance.", "SUBPART F": "Family income and rent computation (PHA/owner eligibility calculations).",
             "SUBPART G": "Physical inspection of HUD real estate.", "SUBPART H": "Financial reporting of HUD program participants.",
             "SUBPART I": "Admission and termination for criminal activity in assisted housing (eviction grounds, not settlement).",
             "SUBPART J": "PHA access to criminal records.", "SUBPART K": "Grant application requirements.",
             "SUBPART M": "Core-based statistical areas."}},
    {"id": "US:47CFR64L", "name": "FCC TCPA rules, 47 CFR part 64 subpart L", "title": "47", "part": "64",
     "in": ["SUBPART L"], "out": {"*": "Other subparts of 47 CFR part 64 regulate common carriers' services (not callers collecting a debt)."}},
    {"id": "US:26CFR1-info", "name": "Treasury Regulations on bad debts and information returns (26 CFR 1.166, 1.6041, 1.6049, 1.6050P)", "title": "26", "part": "1",
     "sections": ["1.166-1", "1.166-2", "1.166-3", "1.166-4", "1.166-5", "1.166-6", "1.166-7", "1.166-8", "1.166-9", "1.166-10",
                  "1.6041-1", "1.6041-2", "1.6041-3", "1.6041-4", "1.6041-5", "1.6041-6", "1.6041-7", "1.6041-8", "1.6041-9", "1.6041-10",
                  "1.6049-1", "1.6049-2", "1.6049-3", "1.6049-4", "1.6049-5", "1.6049-6", "1.6049-7", "1.6049-8", "1.6049-9", "1.6049-10",
                  "1.6050P-0", "1.6050P-1", "1.6050P-2"],
     "in": ["*"], "out": {}},
]
# Rule-file instruments that are out of aperture as a whole (all units out).
ECFR_EXCLUDED = [
    ("US:24CFR966", "24", "966", "Public housing lease and grievance procedure", SUBSIDIZED),
    ("US:24CFR960", "24", "960", "Public housing admission and occupancy", SUBSIDIZED),
    ("US:24CFR880", "24", "880", "Section 8 new construction (project-based)", SUBSIDIZED),
    ("US:24CFR881", "24", "881", "Section 8 substantial rehabilitation (project-based)", SUBSIDIZED),
    ("US:24CFR882", "24", "882", "Section 8 moderate rehabilitation", SUBSIDIZED),
    ("US:24CFR883", "24", "883", "Section 8 state housing agencies", SUBSIDIZED),
    ("US:24CFR884", "24", "884", "Section 8 new construction set-aside for Section 515 rural housing", SUBSIDIZED),
    ("US:24CFR886", "24", "886", "Section 8 special allocations (loan management, property disposition)", SUBSIDIZED),
    ("US:24CFR891", "24", "891", "Section 202 and 811 supportive housing", SUBSIDIZED),
    ("US:24CFR983", "24", "983", "Project-based voucher program", SUBSIDIZED),
    ("US:24CFR92", "24", "92", "HOME Investment Partnerships program", SUBSIDIZED),
    ("US:7CFR3560", "7", "3560", "USDA Rural Development direct multi-family housing", SUBSIDIZED + " (also outside NYC: rural)"),
]

# ------------------------------------------------------------------------------------------------ NYCRR
NYCRR = {
    "9NYCRR": {"name": "9 NYCRR (Executive Department: Division of Human Rights; DHCR rent regulation scope parts; ESRA regulations)",
               "in_parts": ["part-466", "part-2520", "part-2200", "part-540"],
               "out": {"part-2521": RS, "part-2522": RS, "part-2523": RS, "part-2524": RS, "part-2525": RS, "part-2526": RS,
                       "part-2527": RS, "part-2528": RS, "part-2529": RS, "part-2530": RS, "part-2531": RS,
                       "part-2201": RC, "part-2202": RC, "part-2203": RC, "part-2204": RC, "part-2205": RC, "part-2206": RC,
                       "part-2207": RC, "part-2208": RC, "part-2209": RC, "part-2210": RC, "part-2211": RC,
                       "part-465": "Division of Human Rights rules of practice (agency procedure)."}},
    "19NYCRR": {"name": "19 NYCRR (Department of State)", "in_parts": ["part-175"], "out": {}},
    "22NYCRR": {"name": "22 NYCRR (Judiciary: Uniform Rules for the Trial Courts)", "in_parts": ["part-202", "part-208"],
                "out": {"part-210": OUTSIDE_NYC + " (city courts outside NYC)", "part-212": OUTSIDE_NYC + " (district courts)",
                        "part-214": OUTSIDE_NYC + " (town and village courts)", "part-207": "Surrogate's Court rules (probate procedure).",
                        "part-205": "Family Court rules.", "part-206": "Court of Claims rules."}},
    "23NYCRR": {"name": "23 NYCRR (Financial Services)", "in_parts": ["part-1"], "out": {}},
    "16NYCRR": {"name": "16 NYCRR (Public Service)", "in_parts": ["part-96"], "out": {}},
    "18NYCRR": {"name": "18 NYCRR (Social Services)", "in_parts": ["part-352"], "out": {}},
}
