functionsGradleVersion = 0.85.0
functionsRuneVersion = 0.86.0
functionsTypescriptRuntimeVersion = 0.347.0
functionsTypescriptVersion = 0.1339.0
nodeInstallationVersion = 24.16.0
orchestratorLocalVersion = 0.586.0
repositoryName = Deposit Closeout Core — TypeScript v2
repositoryOrg = owenwassmer-c8c047
repositoryProject = Handoff
repositoryRid = ri.stemma.main.repository.40ca55f8-0251-478b-95fc-0b2e5126641e
