import json,re
from pathlib import Path
P=Path(__file__).parent
def save(n,x):P.joinpath(n).write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
supp={u['unit']:u for u in json.loads((P/'jc_supplement.json').read_text())['units_in_scope']}
pairs=[('WG-007','EJ-165','jc_alias_remaining_evidence.json','https://courts.ca.gov/sites/default/files/courts/default/2024-11/wg007.pdf'),('WG-018','EJ-138','jc_alias_remaining_evidence.json','https://courts.ca.gov/documents/ej138.pdf'),('APP-015-INFO','FW-015-INFO','jc_alias_remaining_evidence.json',None),('APP-016','FW-016','jc_alias_evidence.json','https://courts.ca.gov/sites/default/files/courts/default/2024-11/fw016.pdf'),('APP-016-GC','FW-016-GC','jc_alias_final_evidence.json','https://courts.ca.gov/sites/default/files/courts/default/2024-11/fw016gc.pdf'),('CIV-010','FL-935','jc_alias_evidence.json','https://courts.ca.gov/sites/default/files/courts/default/2024-11/fl935.pdf'),('CIV-011','FL-936','jc_alias_final_evidence.json','https://courts.ca.gov/documents/civ011.pdf'),('DE-350','GC-100','jc_alias_final_evidence.json','https://courts.ca.gov/sites/default/files/courts/default/2024-11/de350.pdf'),('DE-351','GC-101','jc_alias_attachments_evidence.json',None),('GC-210(A-PF)','GC-310(A-PF)','jc_alias_evidence.json','https://courts.ca.gov/sites/default/files/courts/default/2024-11/gc210apf.pdf'),('DISC-003','UD-106','jc_alias_attachments_evidence.json','https://courts.ca.gov/sites/default/files/courts/default/2024-11/ud106.pdf'),('POS-050(D)','EFS-050(D)','jc_alias_last_evidence.json','https://courts.ca.gov/documents/pos050d.pdf'),('POS-050(P)','EFS-050(P)','jc_alias_last_evidence.json','https://www.courts.ca.gov/documents/efs050p.pdf')]
for a,b in [('WG-010','EJ-175'),('WG-015','EJ-135'),('WG-017','EJ-137'),('EFS-050','POS-050')]:
 u=supp[a];pairs.append((a,b,u['target_evidence'],u['section_list'][0]['ref']))
save('jc_alias_map.json',{'merge_instruction':'Acquire each physical form once per language/edition; retain both IDs, reasons/functions and all language variants. Record alias identity does not authorize replacing a current edition with an older alias PDF.','alias_groups':[{'form_ids':[a,b],'evidence':e,'observed_direct_pdf':url,'edition_caution':'Validate against recorded current index date; alias evidence establishes shared identity. APP015 legacyPDF is not asserted current2026; DE351 identity supported by official publisher2024materials, current record supplies acquisition.' if url is None else 'Use recorded current edition metadata and actual PDF footer.'} for a,b,e,url in pairs]})
base='https://www.ecfr.gov/api/versioner/v1/full/2026-09-28/title-47.xml?part=76'
units=[]
for sub,title,sections,reason in [('M','Cable Inside Wiring',[('76.800','Definitions'),('76.801','Scope'),('76.802','Disposition of cable home wiring'),('76.804','Disposition of home run wiring'),('76.805','Access to molding'),('76.806','Pre-termination access to cable home wiring')],'Conditional subscriber/MDU wiring ownership, provider access, removal/restoration, purchase, notices and safe replacement work.'),('X','Access to MDUs',[('76.2000','Exclusive access to multiple dwelling units generally')],'Conditional provider/owner contract exclusivity, revenue-sharing and marketing terms for covered multiple dwelling units.')]:
 units.append({'unit':'Subpart '+sub,'heading':title,'toc_url':base+'&subpart='+sub,'reason':reason,'section_list':[{'number':n,'heading':h,'ref':base+'&section='+n} for n,h in sections]})
heads={}
for f in ['fcc76_toc_routes.json','fcc76_other_heading_evidence.json']:
 for m in re.finditer(r'## Subpart ([A-Z]+)(?:—([^\n]+)| (\[Reserved\]))',json.loads((P/f).read_text())):heads[m[1]]=m[2] or m[3]
why={'A':'General definitions/procedure are incorporated when selected M/X provisions require them; unrelated FCC petition/lockbox administration is not an independent operating task.','B':'Cable-system registration administration, not property owner wiring disposition or provider contract.','C':'Government cable franchising process; ordinary residential operator is not acting as franchise authority.','D':'Broadcast carriage arrangements, not premises wiring/property authority.','E':'Cable operator employment reporting, not covered residential work performance or account.','F':'Broadcast programming rights and blackouts, distinct from MDU provider-access exclusivity.','G':'Cablecasting program content, not physical premises work or MDU contract.','H':'Customer-service standards are not selected wholesale in this bounded wiring/MDU review; incorporated normal-operating-conditions definition remains a named dependency.','I':'Reserved.','J':'Ownership of cable systems; do not confuse cable business ownership with MDU/property ownership.','K':'Retain incorporated signal-leakage/capping technical provisions as named dependencies; remainder is general transmission engineering beyond selected property work.','L':'Public/educational/governmental and leased programming channel access, distinct from access to premises.','N':'Regulation of cable service rates, rather than rent, physical-work price or MDU exclusivity.','O':'Competitive access to programming supply, distinct from premises access.','P':'Navigation-device availability regime, not the identified fixed home-wiring disposition task.','Q':'Channel carriage agreement regulation, distinct from owner/provider MDU agreements.','R':'Telecommunications Act implementation outside identified wiring and MDU-access provisions.','S':'Open-video-system certification and administration, not residential operator acting as MDU owner.','T':'Cable provider subscriber/channel notices outside identified M/X notices; not a blanket conclusion that such notice can never matter to an actual provider-customer dispute.','U':'Cable operator public inspection-file duties rather than residential work/account record duties.','V':'Cable operator reports/filings rather than residential operator/account workflow.','W':'Encoding/content protection rather than premises access or wiring ownership.'}
entry={'id':'US:47CFR76','jurisdiction':'US','name':'FCC cable inside wiring and multiple-dwelling-unit provider access','level':'regulation','adapter':'ecfr','version_date':'2026-09-28','toc_source_url':base,'functions':['provider_contracts','work_standards','payments','landlord_tenant'],'units_in_scope':units,'units_out':[{'unit':'Subpart '+l,'heading':h,'reason':why[l]} for l,h in sorted(heads.items()) if l in why],'acquisition':{'text_adapter':'ecfr','enumeration':'Enumerate complete selected M and X sections from dated official eCFR XML, preserving all conditions and exceptions. No acquired XML bytes asserted.'},'incorporated_dependencies':[{'ref':'47 CFR 76.309(c)(4)(ii)','reason':'M incorporates normal operating conditions definition.'},{'ref':'47 CFR 76.605(a)(13) and 76.610–76.617','reason':'M expressly incorporates signal leakage/capping standards for wiring disconnection/reconnection.'},{'ref':'47 USC 522(13)','reason':'MVPD definition incorporated by76.800(c).'},{'ref':'47 USC 548','reason':'X identifies covered MVPD service through this statutory scope.'}],'source_evidence':['fcc76_official_subparts.json','fcc76_x_evidence.json','fcc76_other_heading_evidence.json','fcc76_toc_routes.json'],'currency_note':'Selected M/X source pages display September28 2026, last title amendmentSeptember25. The separately fetched whole-part page displaysSeptember29 and a September29 title amendment. This entry fixes the requestedSeptember28 snapshot; it does not claim that date is latest title currency. Parent should reconcile later release if using one.','scope_note':'Bounded correction of concrete MDU wiring/property-work/provider-contract dependencies. Other TOC decisions apply to this operating aperture, not a statement that all cable consumer law is irrelevant.'}
save('fcc76_proposed_instrument.json',entry)
save('federal_legacy_audit.json',{'finding':'US:47CFR64L was omitted from federal_programs replacements by the whole-ID numeric-part regular expression.','cause_file':'j1/lanes/federal_programs/build_proposals.py:217','cause_regex':r'US:(7|12|16|24|28|29|40|47)CFR(\d+)','active_legacy_orphans':['US:47CFR64L'],'not_orphan':{'US:26USC6050W':'Empty selection and explicit duplicate pointer;26USC-6041-6050 replacement retains reportingSubpartB.','US court rules/fees':'Separate courts-lane ownership and current source review.'},'concrete_fix':'Explicitly replace part64 scoped subparts and route; verify every active legacy CFR instrument is replaced or expressly dispositioned regardless of suffix. Parent performing64P/Z/BB scope correction. Add separately proposed47CFR76 M/X and incorporated dependencies.','no_shared_edits':True})
print('Saved17aliasgroups andFCC76M/X sevensectiontargets,',len(entry['units_out']),'otherTOCdecisions')
