/** Wire vocabulary, not an implemented legal ruleset or workflow engine. */
export const SCHEMA_VERSION = "1.0.0";
export const MAX_SAFE_INTEGER = 9_007_199_254_740_991;
export const SYNTHETIC_RULE_RELEASE_ID = "NC_SYNTHETIC_DEMO_V1";

export const VOCABULARY = {
  origin: ["CONSTRUCTED", "PUBLIC_RECONSTRUCTION", "AUTHORIZED_OPERATOR"],
  factState: ["UNCONFIRMED", "ACCEPTED", "DISPUTED", "NOT_APPLICABLE"],
  dateKey: ["NOTICE", "INTENDED_DEPARTURE", "AGREEMENT_END", "VACANCY", "KEY_RETURN", "LEGAL_POSSESSION", "ACCOUNTING_TRIGGER"],
  scopeState: ["SUPPORTED", "UNSUPPORTED", "MISSING_FACTS", "INTERPRETATION_REQUIRED"],
  sourceClass: ["CASE_RECORD", "AGREEMENT", "LAW", "PROCEDURE", "TEST_ASSUMPTION", "MODEL_PROPOSAL"],
  recordKind: ["AGREEMENT", "CONDITION_OBSERVATION", "SERVICE_REQUEST", "WORK_COMPLETION", "ESTIMATE", "INVOICE", "BALANCE_RECORD", "SOURCE_EVENT", "RECIPIENT_INSTRUCTIONS", "AUTHORITY_RECORD", "FACT_ASSERTION", "MODEL_PROPOSAL"],
  role: ["MANAGER", "ACCOUNTANT", "AUTHORITY_ADMIN", "OWNER", "RESIDENT", "SIGNATORY", "CUSTODIAN", "REVIEWER", "DEMO_TESTER", "AUTOMATION"],
  amountState: ["KNOWN", "UNKNOWN", "DISPUTED", "NOT_APPLICABLE"],
  allocation: ["TENANT", "OWNER", "SPLIT", "OTHER", "UNRESOLVED"],
  allowability: ["SUPPORTED", "DISALLOWED", "UNRESOLVED", "NOT_EVALUATED"],
  choice: ["NOT_DECIDED", "CHOSEN", "WAIVED", "NOT_APPLICABLE"],
  balanceBasis: ["SNAPSHOT_WITH_EXPLICIT_INCLUDED_TRANSACTIONS", "UNRECONCILED"],
  reconciliation: ["RECONCILED", "UNRECONCILED", "CONFLICT"],
  moneyKind: ["DEPOSIT_RECEIPT", "DEPOSIT_TRANSFER_IN", "DEPOSIT_TRANSFER_OUT", "DEPOSIT_APPLICATION", "DEPOSIT_APPLICATION_REVERSAL", "CHARGE_POSTING", "CHARGE_POSTING_REVERSAL", "REFUND_INITIATED", "REFUND_SETTLED", "REFUND_FAILED", "REFUND_RETURNED", "CORRECTION"],
  moneyStatus: ["PENDING", "SETTLED", "FAILED", "RETURNED", "REVERSED", "UNKNOWN"],
  recipientState: ["VERIFIED", "MISSING", "DISPUTED", "REVIEW_REQUIRED"],
  track: ["DECISIONS", "COMMUNICATIONS", "APPROVALS", "MONEY", "RELATED_ACCOUNT"],
  outcomeState: ["OPEN", "BLOCKED", "READY", "PENDING", "FULFILLED", "FAILED", "REOPENED", "NOT_APPLICABLE"],
  dueKind: ["LEGAL", "INTERNAL", "UNCONFIRMED"],
  statementKind: ["INTERIM", "FINAL", "CORRECTION"],
  approvalDecision: ["APPROVED", "REJECTED", "REVOKED"],
  requestState: ["READY", "CLAIMED", "REQUESTED", "ACKNOWLEDGED", "OUTCOME_UNKNOWN", "SUCCEEDED", "FAILED", "CANCELLED", "SUPERSEDED"],
  executionKind: ["COMMAND_RECEIPT", "ATTEMPT", "RESULT", "RECONCILIATION", "MANUAL_CONFIRMATION", "ADMINISTRATIVE", "EFFORT"],
  actionAvailability: ["AVAILABLE", "BLOCKED", "NOT_APPLICABLE"],
  ruleStatus: ["SYNTHETIC_ONLY", "REVIEWED_FOR_SCOPE"],
  implementationStatus: ["NOT_IMPLEMENTED", "IMPLEMENTED_NOT_EVALUATED", "EVALUATED"],
  phase: ["A", "B", "C", "D", "E", "F", "G", "H"],
  actionKind: ["OPEN_CASE", "ADD_EVIDENCE", "ACCEPT_OR_CORRECT_FACT", "SET_OR_REVOKE_AUTHORITY", "RECORD_CHARGE_DECISION", "CHOOSE_OR_WAIVE_CHARGE", "SET_RECIPIENT_INSTRUCTIONS", "RECONCILE_MONEY_RECORD", "PREPARE_STATEMENT", "APPROVE_EXACT_VERSION", "REJECT_OR_REVOKE_APPROVAL", "REQUEST_STATEMENT_DISPATCH", "REQUEST_REFUND", "REQUEST_LEDGER_POSTING", "RECORD_DEMO_OUTCOME", "RECORD_MANUAL_CONFIRMATION", "RESOLVE_UNKNOWN_RESULT", "AUTHORIZE_REPLACEMENT_ATTEMPT", "ASSIGN_WORK", "RECORD_RELATED_TASK_RESULT", "RECHECK_CASE", "ADVANCE_DEMO_CLOCK"],
} as const;
