from q2_lib import *

COSTS_NOTE = "Recovered only as the judgment awards them; nothing is put on the final account before judgment (NY:RPL-234-a)."
rows = [
    D("NY:CPLR 8011", "new_rule",
      "Sets the sheriff's fixed fees for executions, income executions, attachments and service, largely payable in advance; an enforcement cost in the pursue-or-write-off estimate, recovered from the tenant through the execution.",
      proposed=[R("NY:CPLR-8011-sheriff-fees", "NY:CPLR 8011", "CPLR 8011(a)-(d), (h)", "landlord (judgment creditor)", "rule",
                  "The landlord uses a sheriff to serve process on, attach property of, or enforce a judgment against a former tenant.",
                  "Fixed fees include: property execution, $20 to receive (not in advance for a small-claims or commercial-claims judgment), $20 to levy, $20 for an inventory, plus mileage; income execution, $20 to receive and $20 to serve on the tenant or to levy on its employer, plus mileage unless by mail; attachment, $20 to receive, $50 per levy, $20 per service; summons or subpoena service, $20; most payable in advance. Fees not in the landlord's bill of costs are collected from the tenant under the execution (NY:CPLR-8014-fees-collected-on-execution); poundage is separate (NY:CPLR-8012-poundage).",
                  "For the services specified, a sheriff is entitled to the following fees", "Mileage for service covered in paragraph two of this subdivision, unless such execution is served by mail.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-8012-poundage", "NY:CPLR-8014-fees-collected-on-execution"])]),
    D("NY:CPLR 8012", "new_rule",
      "The sheriff takes 5% poundage in NYC on sums collected, and on a settlement after levy is owed poundage on the lesser of the judgment or the settlement; a settlement with the former tenant after a levy carries this cost.",
      proposed=[R("NY:CPLR-8012-poundage", "NY:CPLR 8012", "CPLR 8012(a)-(b), (d)", "landlord (judgment creditor); former tenant", "rule",
                  "A sheriff collects on, or has levied under, the landlord's execution or order of attachment against a former tenant.",
                  "The sheriff earns poundage of 5% of the sum collected in the counties of New York City (elsewhere 5% of the first $250,000 and 3% above). If the landlord and tenant settle after a levy under an execution, income execution or attachment, poundage is due on the lesser of the judgment and the settlement amount; if the execution or attachment is vacated after levy, on the value levied (up to the amount stated), and the court may order the responsible party to pay it. Mileage in New York City is a flat $35. Operator step: a settlement after a levy provides for the poundage.",
                  "(a) Mileage fees.", "such fee shall be thirty-five dollars.",
                  severity="major", walk_step="8.12")]),
    D("NY:CPLR 8013", "no_decision",
      "The sheriff's reimbursable expenses (publication, appraisal, custody) and its right to advance payment; these are recovered through the execution under CPLR 8014 and add no step or amount decision of their own."),
    D("NY:CPLR 8014", "new_rule",
      "Sheriff's fees on a property execution not in the creditor's bill of costs are collected from the judgment debtor under the execution; so they fall on the former tenant, not the landlord, when collection succeeds.",
      proposed=[R("NY:CPLR-8014-fees-collected-on-execution", "NY:CPLR 8014", "CPLR 8014", "landlord (judgment creditor); former tenant", "rule",
                  "A sheriff enforces the landlord's execution against a former tenant's property.",
                  "The sheriff's fees that no statute puts on a particular person and that are not in the landlord's bill of costs are collected by the execution from the tenant in the same way as the judgment sum.",
                  "The fees of a sheriff, upon an execution against property,", "in the same manner as the sum therein directed to be collected.",
                  severity="minor", walk_step="8.12")]),
    D("NY:CPLR 8101", "new_rule",
      "The party that wins judgment gets costs unless a statute says otherwise or the court finds it inequitable; decides whether costs are added to the landlord's balance judgment or the tenant's deposit judgment.",
      proposed=[R("NY:CPLR-8101-costs-to-prevailing-party", "NY:CPLR 8101", "CPLR 8101", "prevailing party (landlord or former tenant)", "rule",
                  "Judgment is entered in an action between the landlord and a former tenant.",
                  "The party in whose favor judgment is entered is entitled to costs (amounts: NY:CPLR-8201-costs-amount in Supreme Court, NY:CCA-1901-costs-amount in Civil Court) and disbursements, unless a statute provides otherwise (for example NY:CPLR-8102-costs-limit-higher-court, NY:CCA-1905-no-costs-bankruptcy-defense, NY:CPLR-1205-no-costs-against-incapacitated) or the court finds costs inequitable in all the circumstances. Costs are not attorney's fees. " + COSTS_NOTE,
                  "The party in whose favor a judgment is entered is entitled to costs in the action,", "would not be equitable, under all of the circumstances.",
                  severity="major", walk_step="8.10", determinacy="MIXED", judgment_terms=["would not be equitable under all of the circumstances"], dependencies=["NY:RPL-234-a"])]),
    D("NY:CPLR 8102", "new_rule",
      "A landlord that sues in Supreme Court in NYC for what the Civil Court could hear gets no costs unless it recovers $6,000 or more; a cost consequence of forum choice.",
      proposed=[R("NY:CPLR-8102-costs-limit-higher-court", "NY:CPLR 8102", "CPLR 8102(1)", "landlord (plaintiff) or former tenant (plaintiff)", "limit",
                  "A party sues in the Supreme Court in a New York City county on a claim over the tenancy that the NYC Civil Court could have heard except for the amount claimed.",
                  "The plaintiff gets no costs unless it recovers $6,000 or more.",
                  "A plaintiff is not entitled to costs:", "unless he shall recover six thousand dollars or more;",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-202-money-limit"])]),
    D("NY:CPLR 8103", "new_rule",
      "Where the landlord recovers on the balance but the tenant prevails on a distinct claim (for example its deposit counterclaim), the court may award costs to both; changes the net costs in a mixed result.",
      proposed=[R("NY:CPLR-8103-split-costs", "NY:CPLR 8103", "CPLR 8103", "landlord; former tenant", "rule",
                  "The landlord recovers judgment on one claim and the former tenant prevails on a different claim in the same action (for example the landlord wins rent and the tenant wins its deposit counterclaim or defeats a damage claim).",
                  "The court may award costs to the tenant without denying costs to the landlord if the claim the tenant won is not substantially the same as a claim on which the landlord recovered.",
                  "Upon the recovery of a judgment in favor of the plaintiff,", "is not substantially the same as any cause of action upon which the plaintiff recovered the judgment.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-8101-costs-to-prevailing-party"])]),
    D("NY:CPLR 8104", "no_decision",
      "Costs in consolidated, severed or removed actions; an allocation rule for unusual procedural postures that changes no settlement step."),
    D("NY:CPLR 8105", "no_decision",
      "Several winning parties share one set of costs unless ordered otherwise; an allocation detail that changes no step or recoverable amount decision in the settlement."),
    D("NY:CPLR 8106", "no_decision",
      "Motion costs are discretionary; their amount is capped by CPLR 8202 (proposed) and in Civil Court by CCA 1906 (proposed). Adds nothing of its own."),
    D("NY:CPLR 8107", "no_decision",
      "Costs on appeal; appellate practice."),
    D("NY:CPLR 8108", "no_decision",
      "Where a court's denial or award of costs must be stated; drafting mechanics for the court."),
    D("NY:CPLR 8110", "new_rule",
      "Costs awarded against a fiduciary (a deceased tenant's executor, or an owner's estate or receiver) are charged to the estate, not personally, unless for mismanagement or bad faith; changes who pays costs after a death.",
      proposed=[R("NY:CPLR-8110-costs-against-fiduciary", "NY:CPLR 8110", "CPLR 8110", "landlord; fiduciary of a deceased former tenant", "rule",
                  "Costs are awarded against a fiduciary in a case over the tenancy (the executor or administrator of a deceased former tenant, or a fiduciary acting for the owner).",
                  "They are chargeable only on the estate, fund or person the fiduciary represents, unless the court directs personal payment for mismanagement or bad faith in prosecuting or defending the action. Claims against a deceased tenant's estate: NY:ADJ-tenant-death-payee.",
                  "Where costs are awarded against a fiduciary,", "for mismanagement or bad faith in the prosecution or defense of the action.",
                  severity="minor", walk_step="2.5", dependencies=["NY:ADJ-tenant-death-payee"])]),
    D("NY:CPLR 8201", "new_rule",
      "Fixes Supreme Court costs ($200 before note of issue, $200 after, $300 per trial or inquest); an amount added to a balance or deposit judgment in Supreme Court.",
      proposed=[R("NY:CPLR-8201-costs-amount", "NY:CPLR 8201", "CPLR 8201", "prevailing party (landlord or former tenant)", "rule",
                  "Costs are awarded in a Supreme Court action between the landlord and a former tenant.",
                  "They are $200 for all proceedings before a note of issue, plus $200 for proceedings after the note of issue and before trial, plus $300 for each trial, inquest or assessment of damages, with disbursements added (NY:CPLR-8301-disbursements). " + COSTS_NOTE,
                  "Costs awarded in an action shall be in the amount of:", "three hundred dollars for each trial, inquest or assessment of damages.",
                  severity="major", walk_step="8.10", dependencies=["NY:CPLR-8101-costs-to-prevailing-party", "NY:RPL-234-a"])]),
    D("NY:CPLR 8202", "new_rule",
      "Motion costs are fixed by the court up to $100; a cost either side may owe or recover in a Supreme Court case.",
      proposed=[R("NY:CPLR-8202-motion-costs", "NY:CPLR 8202", "CPLR 8202", "landlord; former tenant", "limit",
                  "The Supreme Court awards costs on a motion in a case over the tenancy.",
                  "The amount is fixed by the court and may not exceed $100.",
                  "Costs awarded on a motion shall be in an amount fixed by the court, not exceeding one hundred dollars.", severity="minor", walk_step="8.10")]),
    D("NY:CPLR 8301", "new_rule",
      "Lists the disbursements a party awarded costs taxes in Supreme Court (witness and officer fees, publication, certified copies, docketing, one execution's sheriff fees, deposition transcripts up to $250, searches), and allows disbursements to a party recovering $50 or more without costs.",
      proposed=[R("NY:CPLR-8301-disbursements", "NY:CPLR 8301", "CPLR 8301", "prevailing party (landlord or former tenant)", "rule",
                  "A party is awarded costs in a Supreme Court action over the tenancy, or recovers $50 or more in a money action without costs.",
                  "It taxes its necessary disbursements: legal fees of witnesses, referees and other officers; commissioners' reasonable compensation; publication fees where ordered; certified copies used at trial; judges' opinions; printing where required; prospective entry and docketing charges; the sheriff's fees for receiving and returning one execution; examination-before-trial transcripts up to $250; title and official searches; the cost of a stay undertaking on a judgment later reversed; other reasonable and necessary expenses taxable by practice, law or order. The court may allow reasonable motion expenses and may let a party not awarded costs tax disbursements, and must where it recovers $50 or more in a money action. A private service charge is allowed at the reasonable usual rate even above the public officer's fee. " + COSTS_NOTE,
                  "(a) Disbursements in action or on appeal.", "although it is in excess of the fee allowed a public officer.",
                  severity="major", walk_step="8.10", dependencies=["NY:CPLR-8101-costs-to-prevailing-party", "NY:RPL-234-a"])]),
    D("NY:CPLR 8302", "no_decision",
      "Additional allowances in mortgage foreclosure, partition and real-property claim actions; a lease balance or deposit action is none of these."),
    D("NY:CPLR 8303", "new_rule",
      "The court may award up to 5% (max $3,000) in a difficult or extraordinary contested case, and on a motion to enforce a judgment the greater of 5% of the judgment or $50; an amount a landlord may recover for enforcement motions.",
      proposed=[R("NY:CPLR-8303-additional-allowance", "NY:CPLR 8303", "CPLR 8303(a)(2), (b)", "landlord (judgment creditor); prevailing party", "rule",
                  "Branch (a): an action over the tenancy is a difficult or extraordinary case in which a defense was interposed. Branch (b): the landlord moves to enforce a money judgment against a former tenant (for example a turnover or installment-payment motion).",
                  "Branch (a): on motion, the court may award any party up to 5% of the sum recovered or claimed (or of the subject's value), not exceeding $3,000, whether or not costs were awarded. Branch (b): the court may award the judgment creditor up to the greater of 5% of the judgment or $50. These are court-ordered allowances, so NY:RPL-234-a's court-order condition is met; they are recovered only through the court's award.",
                  "2. to any party to a difficult or extraordinary case,", "a sum not exceeding five per cent of the judgment or fifty dollars, whichever is more.",
                  severity="minor", walk_step="8.12", determinacy="MIXED", judgment_terms=["difficult or extraordinary case"], dependencies=["NY:RPL-234-a"])]),
    D("NY:CPLR 8303-A", "new_rule",
      "In an action for injury to property, a frivolous claim, counterclaim or defense brings costs and attorney's fees up to $10,000 against the party or its attorney; applies to a landlord's property-damage claim and a tenant's frivolous defense or counterclaim to it.",
      proposed=[R("NY:CPLR-8303-a-frivolous-property-claim", "NY:CPLR 8303-A", "CPLR 8303-a", "landlord; former tenant; their attorneys", "rule",
                  "The landlord sues a former tenant to recover damages for injury to property (damage to the unit pleaded as injury to property), and a claim, counterclaim, defense or cross-claim in that action is found frivolous.",
                  "The court must award the successful party costs and reasonable attorney's fees up to $10,000, against the party, its attorney or both, in addition to any other judgment. Frivolous means commenced, used or continued in bad faith solely to delay, harass or maliciously injure, or in bad faith without any reasonable basis in law or fact and not supportable by a good-faith argument for changing the law; prompt discontinuance once the lack of basis was or should have been known can negate bad faith. Operator step: sue for unit damage only on charges the settlement file supports (itemized cost beyond wear and tear).",
                  "(a) If in an action to recover damages for personal injury, injury to property or wrongful death,", "the court may find that the party or the attorney did not act in bad faith.",
                  severity="major", walk_step="8.10", determinacy="MIXED", judgment_terms=["frivolous", "bad faith", "reasonable basis in law or fact"],
                  dependencies=["NY:GOL-7-108(1-a)(b)-refundable"])]),
    D("NY:CPLR 8401", "new_rule",
      "The clerk taxes costs and disbursements on application and strikes any disbursement not shown by affidavit to be necessary and reasonable; this is how the landlord's litigation costs enter a Supreme Court judgment.",
      proposed=[R("NY:CPLR-8401-clerk-taxation", "NY:CPLR 8401", "CPLR 8401", "prevailing party (landlord or former tenant)", "obligation",
                  "A party entitled to costs in a Supreme Court action over the tenancy applies to have them taxed.",
                  "The clerk taxes costs, disbursements and allowances, examines the bill whether or not objected to, strikes any disbursement (other than prospective charges allowed by law) not supported by an affidavit that it was necessarily incurred and reasonable, and inserts the total in the judgment. Taxation with notice requires at least five days' notice with the itemized bill, except against a defendant who defaulted in appearing (CPLR 8402); costs taxed without notice are served at once and may be retaxed on five days' notice (CPLR 8403).",
                  "Costs, disbursements and additional allowances shall be taxed by the clerk", "The clerk shall insert in the judgment the total of the amount taxed as costs, disbursements and additional allowances.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-8301-disbursements"])]),
    D("NY:CPLR 8402", "no_decision",
      "Notice mechanics for taxing costs (five days, itemized bill; none to a defaulting defendant); folded into proposed NY:CPLR-8401-clerk-taxation and changes no amount."),
    D("NY:CPLR 8403", "no_decision",
      "Taxation without notice and retaxation on five days' notice; folded into proposed NY:CPLR-8401-clerk-taxation and changes no amount."),
    D("NY:CPLR 8501", "new_rule",
      "A defendant may obtain security for costs as of right against a plaintiff that is not a New York resident, domestic corporation or licensed foreign corporation (a former tenant who moved away, an unlicensed foreign owner), and in the court's discretion against executors, receivers and similar plaintiffs.",
      proposed=[R("NY:CPLR-8501-security-for-costs", "NY:CPLR 8501", "CPLR 8501", "landlord or former tenant (defendant)", "permission",
                  "A party is sued over the tenancy. Branch (a): no plaintiff is a New York resident, a domestic corporation or a foreign corporation licensed to do business here when the motion is made (for example a former tenant who has moved out of state suing for the deposit, or an owner entity organized and unauthorized elsewhere). Branch (b): the plaintiff sues as executor or administrator, trustee, receiver, bankruptcy debtor in possession, committee, conservator or guardian ad litem.",
                  "Branch (a): on the defendant's motion without notice, the court must order the plaintiff to give security for costs (unless it proceeds as a poor person). Branch (b): the court may order security on motion with notice or on its own. The undertaking is $500 in New York City counties (NY:CPLR-8503-undertaking-amount; in NYC Civil Court at least $200: NY:CCA-1900-security-for-costs); proceedings are stayed until it is given and the complaint may be dismissed after 30 days (NY:CPLR-8502-stay-dismissal).",
                  "(a) As of right.", "a guardian ad litem, or a receiver.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-8503-undertaking-amount", "NY:CPLR-8502-stay-dismissal"])]),
    D("NY:CPLR 8502", "new_rule",
      "Until ordered security for costs is posted, the plaintiff's action is stayed, and after 30 days it may be dismissed with costs; a deadline that can end a claim.",
      proposed=[R("NY:CPLR-8502-stay-dismissal", "NY:CPLR 8502", "CPLR 8502", "plaintiff (landlord or former tenant)", "obligation",
                  "The court orders a plaintiff in a case over the tenancy to give security for costs (NY:CPLR-8501-security-for-costs).",
                  "All proceedings except review or vacatur of the order are stayed until security is given; if not given within 30 days of the order, the court may dismiss the complaint on the defendant's motion and award it costs.",
                  "Until security for costs is given pursuant to the order of the court,", "the court may dismiss the complaint upon motion by the defendant, and award costs in his favor.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-8501-security-for-costs"])]),
    D("NY:CPLR 8503", "new_rule",
      "Security for costs is an undertaking of $500 in New York City counties (more if the court fixes it); in NYC Civil Court the minimum is $200 under CCA 1900.",
      proposed=[R("NY:CPLR-8503-undertaking-amount", "NY:CPLR 8503", "CPLR 8503", "plaintiff (landlord or former tenant)", "rule",
                  "A plaintiff in a case over the tenancy is ordered to give security for costs.",
                  "It gives an undertaking of $500 in New York City counties ($250 elsewhere), or a greater amount the court fixes, to pay all legal costs awarded to the defendant; in the NYC Civil Court the minimum is $200 (NY:CCA-1900-security-for-costs).",
                  "Security for costs shall be given by an undertaking", "that the plaintiff shall pay all legal costs awarded to the defendant.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-1900-security-for-costs"])]),
]
write(rows)
