from q2_lib import *

MECH = "in-suit litigation mechanics that change no amount, deadline, precondition or payee in settling the account or deciding to pursue it."
rows = [
    D("NY:CPLR 1017", "no_decision", "The court substitutes proper parties when a party gets a receiver or a corporate party dissolves; a court act that adds no step for the settlement (who collects under a receiver is stated at NY:CPLR-6401-foreclosure-receiver)."),
    D("NY:CPLR 1019", "no_decision", "Substitution of public officers; no public officer is a party to a market-rate tenancy settlement."),
    D("NY:CPLR 1020", "no_decision", "Substitution of an indemnitor for a sheriff sued over a levied chattel; officer litigation outside the chain."),
    D("NY:CPLR 1024", "no_decision", "Suing a party whose name is unknown under a partial description; " + MECH),
    D("NY:CPLR 1025", "no_decision", "Partnerships sue and are sued in the firm name; it adds no step (partnership service is at proposed NY:CPLR-310-partnership)."),
    D("NY:CPLR 103", "no_decision", "One form of civil action, and actions versus special proceedings; no settlement step turns on it."),
    D("NY:CPLR 104", "no_decision", "Liberal construction of the CPLR; a canon that adds no step or amount."),
    D("NY:CPLR 1202", "partial",
      "The parties rule bars a default against an infant or incompetent until a guardian ad litem is appointed; 1202 adds that the landlord, as another party, may move for the appointment if no relative or representative moves within ten days after service, with notice to the representative or household and the proposed guardian's consent.",
      atoms=["NY:CPLR-1203-1015-5208-parties"],
      proposed=[R("NY:CPLR-1202-guardian-ad-litem-motion", "NY:CPLR 1202", "CPLR 1202", "landlord (plaintiff)", "permission",
                  "The landlord has served a former tenant who is an infant, adjudicated incompetent or conservatee, or an adult incapable of defending its rights (NY:CPLR-1201-representation), and no guardian ad litem has been appointed.",
                  "The court may appoint a guardian ad litem at any stage on its own motion or on the motion of the infant over 14, a relative, friend, guardian, committee or conservator, or, if none of them moves within ten days after service is complete, any other party, including the landlord. Notice goes to the person's guardian, committee or conservator, or else the person it lives with, and to the person itself if over 14 and not adjudicated incompetent. The appointment takes effect only when the guardian's written consent and affidavit of ability to answer for its negligence are filed. A default may then be taken only as NY:CPLR-1203-1015-5208-parties allows.",
                  "(a) By whom motion made.", "showing his ability to answer for any damage sustained by his negligence or misconduct.",
                  severity="minor", walk_step="8.9", amends="NY:CPLR-1203-1015-5208-parties", dependencies=["NY:CPLR-1201-representation", "NY:CPLR-1203-1015-5208-parties"])]),
    D("NY:CPLR 1209", "no_decision",
      "A controversy involving an infant or incapacitated person goes to arbitration only by court order; no arbitration route is part of this chain (the small-claims arbitration rule already excludes such parties)."),
    D("NY:CPLR 2002", "no_decision", "Harmless-error rule for court rulings; appellate and trial review, no settlement step."),
    D("NY:CPLR 2101", "no_decision", "Form, language, caption and signing of court papers; " + MECH),
    D("NY:CPLR 2102", "no_decision", "Where papers are filed and that clerks accept them; " + MECH),
    D("NY:CPLR 2106", "new_rule",
      "Any person may sign a statement affirmed under penalty of perjury in the statutory form instead of a notarized affidavit; the manager's or Handoff's affidavits of facts, service or non-military status may be affirmations.",
      proposed=[R("NY:CPLR-2106-affirmation", "NY:CPLR 2106", "CPLR 2106(a)", "landlord, managing agent, Handoff staff, process server", "permission",
                  "A person with knowledge signs a sworn statement for a New York case over the tenancy (an affidavit of facts or amount due for a default judgment, a non-military affidavit, an affidavit of service or mailing, a verification).",
                  "The statement may be subscribed and affirmed as true under penalty of perjury, wherever made, in the statutory form ('I affirm this ___ day of ______, ____, under the penalties of perjury under the laws of New York, which may include a fine or imprisonment, that the foregoing is true, except as to matters alleged on information and belief and as to those matters I believe it to be true, and I understand that this document may be filed in an action or proceeding in a court of law.'), with the same force as an affidavit; no notary is needed. It does not replace a deposition or an oath required before a specified officer other than a notary. A false affirmation is perjury.",
                  "(a) The statement of any person wherever made,", "I understand that this document may be filed in an action or proceeding in a court of law.",
                  severity="minor", walk_step="8.9")]),
    D("NY:CPLR 212", "no_decision", "Ten- and fifteen-year periods for recovering real property, annulled patents and mortgage redemption; none is a claim in the settlement chain."),
    D("NY:CPLR 213-B", "new_rule",
      "A crime victim may sue the convicted defendant within seven years of the crime; a landlord whose unit was damaged or property stolen by a former tenant convicted of that crime has seven years, longer than the six-year contract period.",
      proposed=[R("NY:CPLR-213-b-crime-victim", "NY:CPLR 213-B", "CPLR 213-b", "landlord (crime victim)", "rule",
                  "A former tenant (or occupant) was convicted of a crime (for example criminal mischief damaging the unit, or larceny of the owner's fixtures or money) whose loss the landlord seeks to recover.",
                  "The landlord, as crime victim, may sue the convicted tenant for the injury or loss within seven years of the date of the crime (or, for a specified crime under Executive Law 632-a, within ten years of conviction), notwithstanding any shorter period. Without a conviction, the ordinary periods apply (NY:CPLR-213(2); three years for property damage in tort).",
                  "Notwithstanding any other limitation set forth in this article", "within ten years of the date the defendant was convicted of such specified crime.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-213(2)"])]),
    D("NY:CPLR 213-C", "no_decision", "Limitation periods for civil claims arising from sexual offenses; not a claim in the settlement chain."),
    D("NY:CPLR 213-D", "no_decision", "Three-year limit on medical debt actions by hospitals and health professionals; not a lease balance."),
    D("NY:CPLR 214-F", "no_decision", "Personal injury from superfund-site exposure; not a claim in the settlement chain."),
    D("NY:CPLR 214-J", "no_decision", "Revival window for certain sexual-offense claims; not a claim in the settlement chain."),
    D("NY:CPLR 217", "no_decision",
      "Four-month limit for proceedings against bodies or officers (article 78) and union fair-representation claims; review of agency determinations is not a step in settling a market-rate tenancy."),
    D("NY:CPLR 2214", "no_decision", "Motion papers and service times; " + MECH),
    D("NY:CPLR 2215", "no_decision", "Cross-motions; " + MECH),
    D("NY:CPLR 2218", "no_decision", "Trial of an issue raised on a motion; " + MECH),
    D("NY:CPLR 2219", "no_decision", "Time and form of orders; " + MECH),
    D("NY:CPLR 2220", "no_decision", "Entry, filing and service of orders; " + MECH),
    D("NY:CPLR 2221", "no_decision", "Motions to renew or reargue; " + MECH),
    D("NY:CPLR 2223", "no_decision", "An enforcement officer's duties on receiving a mandate (receipt, copy, return); officer mechanics."),
    D("NY:CPLR 3001", "no_decision", "Supreme Court declaratory judgments; no declaratory claim is a step in settling the account."),
    D("NY:CPLR 301", "no_decision",
      "Preserves general personal jurisdiction as it existed before the CPLR (domiciliaries, entities at home here); reaching a former tenant who moved away is decided at proposed NY:CPLR-302-long-arm and NY:CCA-404-long-arm."),
    D("NY:CPLR 3011", "no_decision", "Kinds of pleadings; " + MECH),
    D("NY:CPLR 3013", "no_decision", "Pleadings must give notice of the transactions and elements; " + MECH),
    D("NY:CPLR 3019", "new_rule",
      "A defendant may counterclaim any claim against the plaintiff, and counterclaims are permissive; where a collector or other nominal plaintiff sues on the owner's balance, the tenant's deposit claim against the owner is allowed as a counterclaim up to the plaintiff's claim.",
      proposed=[R("NY:CPLR-3019-counterclaims", "NY:CPLR 3019", "CPLR 3019(a), (c)", "landlord; former tenant; collector suing in its name", "rule",
                  "A claim over the tenancy is sued on. Branch (a): the owner (or the tenant) is the plaintiff. Branch (b): the plaintiff is a trustee or a nominal plaintiff with no actual interest in the lease, suing for the owner (for example an assignee for collection).",
                  "Branch (a): the defendant may counterclaim any cause of action it has against the plaintiff (the tenant's deposit and double-damages claims, or the landlord's balance); a counterclaim is not compulsory, so one not asserted may be sued on later, subject to claim preclusion where the later claim would impair the first judgment (NY:CCA-1808-preclusion). Branch (b): a claim against the nominal plaintiff itself is not allowed as a counterclaim, but the tenant's claim against the owner who is beneficially interested is allowed as a counterclaim to the extent of the plaintiff's claim (an offset, not an affirmative recovery against the collector). Limitations on counterclaims: NY:CPLR-203(d)-counterclaim-offset.",
                  "(a) Subject of counterclaims.", "if it might have been so allowed in an action brought by the person beneficially interested.",
                  severity="major", walk_step="7.6", dependencies=["NY:CPLR-203(d)-counterclaim-offset", "NY:CCA-1808-preclusion", "NY:JUD-489-champerty"])]),
    D("NY:CPLR 302", "new_rule",
      "New York courts have personal jurisdiction over a non-domiciliary on a claim arising from its owning, using or possessing real property in New York, or transacting business here; a former tenant who moved out of state can be sued in New York for the balance, and an out-of-state owner for the deposit.",
      proposed=[R("NY:CPLR-302-long-arm", "NY:CPLR 302", "CPLR 302(a), (c)", "landlord; former tenant", "rule",
                  "A party to a claim over an NYC tenancy is not domiciled in New York when sued. Branch (a): the landlord sues a former tenant who moved out of state, for rent, damage or other lease charges. Branch (b): the tenant sues an owner (individual or entity) domiciled elsewhere, for the deposit or damages.",
                  "A court may exercise personal jurisdiction over a non-domiciliary (or its executor or administrator) on a cause of action arising from its transacting business in New York or contracting to supply goods or services here, committing a tortious act here (not defamation), or owning, using or possessing real property in New York, in person or through an agent. Branch (a): the tenant's lease of the NYC unit is use and possession of New York real property and a transaction here, so the Supreme Court has jurisdiction and the tenant is served outside the state (NY:CPLR-313-service-outside-state); in NYC Civil Court the equivalent is NY:CCA-404-long-arm. Branch (b): the owner owns New York property and leased it here. An appearance does not extend jurisdiction to unrelated claims.",
                  "(a) Acts which are the basis of jurisdiction.", "owns, uses or possesses any real property situated within the state.",
                  severity="critical", walk_step="8.10", dependencies=["NY:CPLR-313-service-outside-state", "NY:CCA-404-long-arm"])]),
]
write(rows)
