from q2_lib import *

EL = "NY:CPLR-5205-5231-enforcement-limits"
rows = [
    D("NY:CPLR 5203", "new_rule",
      "A docketed money judgment is a lien on the former tenant's real property in that county for ten years (extendable for stays or a pending sale); decides what enforcement against a tenant who owns property yields.",
      proposed=[R("NY:CPLR-5203-real-property-lien", "NY:CPLR 5203", "CPLR 5203(a)-(b)", "landlord (judgment creditor)", "rule",
                  "The landlord's money judgment against a former tenant is docketed with the clerk of a county where the tenant owns real property (NY:CPLR-5018-docketing).",
                  "From docketing until ten years after the judgment-roll was filed (or from filing a notice of levy under an execution until the execution is returned), no transfer of the tenant's interest in that real property is effective against the landlord, except a transfer on a judicial or execution sale for an earlier docketed judgment or levy, a transfer satisfying a purchase-money mortgage, a sale to a purchaser for value at a judicial sale, or where the judgment was entered after the tenant's death. On motion with notice to the tenant, the court may extend the lien beyond ten years only for the time the landlord was stayed from enforcing, or to finish a sale under an execution delivered before the ten years ran. Longer protection needs a renewal judgment (NY:CPLR-5014-renewal-judgment). The homestead exemption limits what the lien yields (NY:CPLR-5206-homestead).",
                  "(a) Priority and lien on docketing judgment.", "and an appropriate entry is made upon the docket of the judgment.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-5018-docketing", "NY:CPLR-5014-renewal-judgment", "NY:CPLR-5206-homestead"])]),
    D("NY:CPLR 5204", "no_decision",
      "Release of a judgment lien or levy when the debtor posts an appeal undertaking; appellate practice that changes no settlement or collection step."),
    D("NY:CPLR 5206", "partial",
      "The enforcement-limits rule covers bank and wage exemptions but not the homestead: a former tenant's owned and occupied home is exempt up to $150,000 of equity in NYC (adjusted under CPLR 5253), which caps recovery from real property.",
      atoms=[EL],
      proposed=[R("NY:CPLR-5206-homestead", "NY:CPLR 5206", "CPLR 5206(a)-(e)", "landlord (judgment creditor)", "limit",
                  "The landlord enforces a money judgment against a former tenant who owns and occupies as its principal residence a house, co-op shares, a condominium unit or a mobile home.",
                  "Equity above liens and encumbrances is exempt up to $150,000 where the home is in Kings, Queens, New York, Bronx, Richmond, Nassau, Suffolk, Rockland, Westchester or Putnam County; $125,000 in Dutchess, Albany, Columbia, Orange, Saratoga or Ulster; $75,000 elsewhere, each as adjusted every three years under CPLR 5253 (NY:CPLR-5253-exemption-adjustment), unless the judgment was wholly for the home's purchase price. The judgment lien attaches only to the surplus; to reach it the landlord brings a special proceeding in the home's county for a sale by sheriff or receiver, and the exempt amount paid to the tenant from the proceeds stays exempt for a year. The exemption continues after death for a surviving spouse and minor children, and ends if the home stops being occupied as a residence (except up to a year after casualty). The pursue-or-write-off estimate counts only non-exempt equity.",
                  "(a) Exemption of homestead.", "or be otherwise disposed of as justice requires.",
                  severity="major", walk_step="8.12", amends=EL, dependencies=[EL, "NY:CPLR-5253-exemption-adjustment"])]),
    D("NY:CPLR 5209", "new_rule",
      "When a creditor of the former tenant levies on or restrains the deposit refund the landlord owes the tenant, paying the sheriff or creditor under the execution or order discharges the landlord to that extent; decides who the refund is paid to.",
      proposed=[R("NY:CPLR-5209-landlord-as-garnishee", "NY:CPLR 5209", "CPLR 5209; CPLR 5232(a)", "landlord (garnishee of the former tenant's refund)", "rule",
                  "A judgment creditor of the former tenant (not the landlord) serves the landlord with an execution, restraining notice or turnover order reaching the deposit refund or other money the landlord owes the tenant.",
                  "The landlord pays or delivers the refund, as the execution or order directs, to the sheriff, marshal, receiver or judgment creditor, and is discharged from its obligation to the tenant to the extent of that payment. Until then it holds the sum and does not pay the tenant (a levy binds for 90 days: NY:CPLR-5232-levy). The 14-day itemized statement still goes to the tenant (NY:GOL-7-108(1-a)(e)), showing the amount paid under legal process and to whom.",
                  "A person who, pursuant to an execution or order, pays or delivers,", "is discharged from his obligation to the judgment debtor to the extent of the payment or delivery.",
                  severity="critical", walk_step="6.1", dependencies=["NY:CPLR-5232-levy", "NY:GOL-7-108(1-a)(e)"])]),
    D("NY:CPLR 5210", "no_decision",
      "Gives enforcement courts contempt power over enforcement procedures; it adds no step, amount or deadline for the landlord or tenant (the subpoena warning is in CPLR 5223)."),
    D("NY:CPLR 5211", "no_decision",
      "Lets a court confer criminal-law immunity on a witness in an enforcement examination on notice to the district attorney; no settlement or collection decision turns on it."),
    D("NY:CPLR 5221", "new_rule",
      "An enforcement proceeding on an NYC Civil Court judgment against a tenant who lives or works in the city is brought in the Civil Court; otherwise in Supreme or County Court where the tenant lives or works. Decides where the landlord enforces.",
      proposed=[R("NY:CPLR-5221-enforcement-forum", "NY:CPLR 5221", "CPLR 5221(a)(3)-(4), (b)", "landlord (judgment creditor)", "rule",
                  "The landlord brings a special proceeding under CPLR article 52 (turnover, installment order, receiver) or issues enforcement notices or subpoenas on a judgment against a former tenant.",
                  "Branch (a): the judgment is from the NYC Civil Court and the tenant resides, is regularly employed or does business in person in the city: the proceeding is brought in the Civil Court. Branch (b): any other case (including a tenant who has left the city): in the Supreme Court or a county court in a county where the tenant resides, works or does business, or if none, where it may be served or where judgment was entered. Notices and subpoenas may issue, and motions be made, in any court where such a proceeding could be brought against the person served.",
                  "3. If the judgment sought to be enforced was entered in the municipal court of the city of New York,", "could be commenced if the person served with the notice, subpoena or notice of motion were respondent.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CCA-1508-enforcement-powers"])]),
    D("NY:CPLR 5223", "new_rule",
      "Until the judgment is satisfied, the landlord may compel disclosure of anything relevant to collecting it by a subpoena stating the parties, judgment and amount due, and warning of contempt; the tool for finding a former tenant's assets.",
      proposed=[R("NY:CPLR-5223-disclosure-subpoena", "NY:CPLR 5223", "CPLR 5223", "landlord (judgment creditor) or its attorney", "permission",
                  "The landlord holds an unsatisfied, unvacated money judgment against a former tenant.",
                  "It may compel disclosure of all matter relevant to satisfying the judgment by serving a subpoena on any person (the tenant, its bank, its new landlord or employer). The subpoena names all parties, the judgment date and court, the judgment amount and the amount then due, and states that false swearing or failure to comply is punishable as contempt. Kinds of subpoena and limits: NY:CPLR-5224-enforcement-subpoenas.",
                  "At any time before a judgment is satisfied or vacated,", "is punishable as a contempt of court.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-5224-enforcement-subpoenas"])]),
    D("NY:CPLR 5224", "new_rule",
      "The enforcement subpoenas the landlord may serve (deposition, documents, information subpoena by certified mail with 7-day answers), the reasonable-belief certification without which a third-party information subpoena is void, and the one-year bar on re-examining the tenant.",
      proposed=[R("NY:CPLR-5224-enforcement-subpoenas", "NY:CPLR 5224", "CPLR 5224", "landlord (judgment creditor) or its attorney", "rule",
                  "The landlord uses subpoenas to find assets of a former tenant against whom it holds a money judgment.",
                  "It may serve a subpoena for a deposition, a subpoena duces tecum, or an information subpoena with written questions (original and copy) and a prepaid return envelope, which may be served by registered or certified mail and must be answered under oath within seven days after receipt; with written consent, an electronic information subpoena. An information subpoena to anyone other than the tenant may be served only if the landlord or its attorney reasonably believes the recipient has information that will help collect, and must carry the signed certification of CPLR 5224 and GBL 601; without it the subpoena is void. A subpoena duces tecum reaches materials held inside or outside the state. The tenant and information-subpoena recipients get no fee; other witnesses get travel expenses and a day's fee in advance. Examinations need at least ten days' notice, during business hours; the landlord pays for any translation. The tenant cannot be compelled to appear again on the same judgment within one year after a prior examination without leave of court.",
                  "(a) Kinds and service of subpoena.", "within one year after the conclusion of a previous examination of him with respect to the same judgment.",
                  severity="major", walk_step="8.12", dependencies=["NY:22NYCRR-208.39-enforcement-subpoenas"])]),
    D("NY:CPLR 5225", "new_rule",
      "Turnover: the court orders the former tenant, or a third party holding the tenant's money or property, to pay or deliver it to satisfy the landlord's judgment; an enforcement route against a tenant with identifiable funds.",
      proposed=[R("NY:CPLR-5225-turnover", "NY:CPLR 5225", "CPLR 5225", "landlord (judgment creditor)", "permission",
                  "The landlord holds a money judgment and shows that the former tenant, or a third person (including a transferee from the tenant), holds money or personal property in which the tenant has an interest.",
                  "Branch (a) held by the tenant: on motion served like a summons or by registered or certified mail, the court orders the tenant to pay the money to the landlord up to the judgment, and deliver other property to a sheriff. Branch (b) held by a third person: by special proceeding against that person, with notice to the tenant, the court orders payment or delivery where the tenant is entitled to possession or the landlord's rights are superior to a transferee's; a holder that did not dispute the tenant's interest pays no costs. Exempt property stays exempt (NY:CPLR-5205-5231-enforcement-limits).",
                  "(a) Property in the possession of judgment debtor.", "The court may order any person to execute and deliver any document necessary to effect payment or delivery.",
                  severity="minor", walk_step="8.12", dependencies=[EL])]),
    D("NY:CPLR 5226", "new_rule",
      "The court may order a former tenant with income to pay the judgment in installments fixed with regard to its and its dependents' reasonable needs; the main route against a tenant with income but no leviable assets.",
      proposed=[R("NY:CPLR-5226-installment-order", "NY:CPLR 5226", "CPLR 5226", "landlord (judgment creditor)", "permission",
                  "The landlord holds a money judgment against a former tenant who receives or will receive money from any source (for example self-employment income beyond an income execution's reach), or who is working for inadequate pay to impede collection.",
                  "On motion served like a summons or by registered or certified mail, the court orders specified installment payments to the landlord, fixed after considering the reasonable requirements of the tenant and its dependents, payments it makes on other judgments and wage assignments, the amount due and the amount it receives (or the reasonable value of its services). The pursue-or-write-off estimate uses what such an order would yield.",
                  "Upon motion of the judgment creditor, upon notice to the judgment debtor,", "the reasonable value of the services rendered.",
                  severity="major", walk_step="8.12", determinacy="MIXED", judgment_terms=["reasonable requirements of the judgment debtor and his dependents"], dependencies=[EL])]),
    D("NY:CPLR 5227", "new_rule",
      "By special proceeding the court may order anyone who owes the former tenant money to pay it to the landlord up to the judgment, or enter judgment against that person; reaches the tenant's receivables.",
      proposed=[R("NY:CPLR-5227-debts-owed-to-tenant", "NY:CPLR 5227", "CPLR 5227", "landlord (judgment creditor)", "permission",
                  "The landlord holds a money judgment and shows that a person is or will become indebted to the former tenant.",
                  "By special proceeding against that person, with notice to the tenant, the court may order it to pay the debt to the landlord on maturity up to the judgment, or enter judgment against it for the landlord; a debtor that did not dispute the debt pays no costs. (When the landlord is itself the one owing the tenant, the discharge rule is NY:CPLR-5209-landlord-as-garnishee.)",
                  "Upon a special proceeding commenced by the judgment creditor, against any person who it is shown is or will become indebted", "may determine his rights in accordance with section 5239.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-5209-landlord-as-garnishee"])]),
    D("NY:CPLR 5228", "new_rule",
      "The court may appoint a receiver to collect or sell the former tenant's property to satisfy the judgment, at up to 5% commission (none if the landlord itself is receiver); an enforcement option with its cost.",
      proposed=[R("NY:CPLR-5228-receiver", "NY:CPLR 5228", "CPLR 5228(a)", "landlord (judgment creditor)", "permission",
                  "The landlord holds a money judgment against a former tenant with property that cannot be reached efficiently by execution (for example an interest in a business or a rental property).",
                  "On motion, the court may appoint a receiver to administer, collect, lease, repair or sell the tenant's real or personal property or do other acts to satisfy the judgment, with notice where practicable to the tenant and its other judgment creditors. The receiver gets necessary expenses and commissions of up to 5% of sums received and disbursed; a judgment creditor appointed receiver gets no compensation; it cannot hire counsel without court authorization.",
                  "(a) Appointment of receiver.", "Sections 6402, 6403, 6404 and 6405 are applicable to receivers appointed under this subdivision.",
                  severity="minor", walk_step="8.12")]),
    D("NY:CPLR 5229", "new_rule",
      "After a decision in the landlord's favor and before judgment is entered, the trial judge may order the former tenant examined and restrained as if a post-judgment restraining notice had been served; stops dissipation of assets.",
      proposed=[R("NY:CPLR-5229-pre-judgment-restraint", "NY:CPLR 5229", "CPLR 5229", "landlord (prevailing party)", "permission",
                  "A verdict or decision has been rendered for the landlord against a former tenant (or for the tenant against the landlord), and judgment has not yet been entered.",
                  "On the prevailing party's motion, the trial judge may order examination of the other party and restrain it with the same effect as a restraining notice served after judgment (CPLR 5222, subject to its exemptions: NY:CPLR-5205-5231-enforcement-limits). Small claims counterpart: NY:CCA-1805-small-claims-remedies.",
                  "In any court, before a judgment is entered,", "with the same effect as if a restraining notice had been served upon him after judgment.",
                  severity="minor", walk_step="8.12", dependencies=[EL])]),
]
write(rows)
