from q2_lib import *

rows = [
    D("NY:CCA 1507", "new_rule",
      "Bars a levy on an evicted tenant's property for 24 hours after a nonpayment dispossess; changes when a landlord holding a money judgment may enforce against the departing tenant's belongings.",
      proposed=[R("NY:CCA-1507-no-levy-24h", "NY:CCA 1507", "CCA 1507", "landlord (judgment creditor), marshal", "prohibition",
                  "The tenant was dispossessed from its residence for non-payment of rent (summary proceeding) and the landlord holds an execution on a money judgment against it.",
                  "No levy may be made on the tenant's property under any execution within twenty-four hours after the dispossess. After 24 hours the execution may be levied on property that is not exempt (NY:CPLR-5205-5231-enforcement-limits); belongings left in the unit remain the tenant's and are not held for rent (NY:COMMONLAW-belongings-owner-keeps).",
                  "No levy shall be made on the property of a tenant dispossessed", "was his residence.", severity="major", walk_step="8.12",
                  dependencies=["NY:CPLR-5205-5231-enforcement-limits", "NY:COMMONLAW-belongings-owner-keeps"])]),
    D("NY:CCA 1803", "new_rule",
      "Sets how a tenant's small-claims deposit suit reaches the landlord (mail to the rent-payment address, presumed received after 21 days) and the landlord's counterclaim window; changes what the landlord must do when sued.",
      proposed=[R("NY:CCA-1803-small-claims-notice-counterclaim", "NY:CCA 1803", "CCA 1803(a), (c)", "landlord; former tenant", "obligation",
                  "A small claim is filed in the NYC Civil Court. Branch (a): the former tenant sues the owner over the tenancy or lease. Branch (b): an owner who is a natural person sues the former tenant (NY:CCA-1809(1) bars entity owners).",
                  "The claim is commenced by paying a $15 filing fee (claims of $1,000 or less) or $20 (over $1,000), without a summons; the clerk mails notice by ordinary first-class and certified mail to the defendant's NYC residence if known, else its NYC office or place of employment, and, for a tenant's claim about the tenancy that cannot be sent either way, to any place in the state where the tenant may mail or deliver rent. If the first-class mailing is not returned undeliverable within 21 days, the defendant is presumed to have received notice. Branch (a): the landlord is presumed notified through its rent-payment address. The landlord may counterclaim for the balance (rent, damage beyond the deposit) by filing a statement with the clerk within five days after receiving the notice and paying $5 plus mailing costs; a later counterclaim is still allowed, but the tenant may then take an adjournment. Branch (b): the same fee and mailing apply; the tenant may counterclaim for the deposit on the same terms.",
                  "(a) Small claims shall be commenced upon the payment by the claimant of a filing fee", "The claimant may reply to the counterclaim but shall not be required to do so.",
                  severity="major", walk_step="7.6", dependencies=["NY:CCA-1801-tenant-claim", "NY:CCA-1809(1)"])]),
    D("NY:CCA 1811", "partial",
      "1811(d): a judgment debtor that pays must present proof of satisfaction to the court or the judgment stays indexed as unpaid, which feeds the CCA 1812 treble-damages count; the notice contents in (a)-(c) are the court's duty and the appeal time is appellate practice.",
      atoms=["NY:CCA-1812-treble"],
      proposed=[R("NY:CCA-1811(d)-satisfaction-proof", "NY:CCA 1811", "CCA 1811(d)", "landlord (small-claims judgment debtor)", "obligation",
                  "A former tenant obtained an NYC small-claims judgment against the landlord and the landlord pays it.",
                  "Unsatisfied small-claims judgments are indexed under the judgment debtor's name; on paying, the landlord presents proof of satisfaction to the court so the record shows it satisfied. A judgment left on the index as unsatisfied counts toward the three unsatisfied judgments that expose a business to treble damages (NY:CCA-1812-treble).",
                  "(d) All wholly or partially unsatisfied small claims court judgments", "the court shall indicate such in the records.",
                  severity="minor", walk_step="7.6", amends="NY:CCA-1812-treble", dependencies=["NY:CCA-1812-treble"])]),
    D("NY:CCA 1906-A", "new_rule",
      "Fixes the only costs a landlord recovers in an NYC summary proceeding against the tenant; changes what the possession judgment awards and what may be carried to the final account.",
      proposed=[R("NY:CCA-1906-A-summary-costs", "NY:CCA 1906-A", "CCA 1906-a; RPAPL 747", "landlord (petitioner)", "limit",
                  "A summary proceeding to recover possession preceded the move-out and ended in a judgment for the landlord.",
                  "The costs awarded are exclusive: $5 for each necessary respondent served with the notice of petition by someone other than a sheriff or marshal, $5 for securing the non-military affidavit if the respondent defaulted, and the index-number fee paid under CCA 1911(k) as a disbursement, plus any additional costs RPAPL 747(3) allows. Only costs the judgment awards are recoverable; no other court or legal cost may be put on the final account without a court order (NY:RPL-234-a).",
                  "In a summary proceeding to recover possession of real property,", "pursuant to subdivision three of said section.",
                  severity="major", walk_step="3.8", dependencies=["NY:RPL-234-a", "NY:RPAPL-749(3)-after-proceeding"])]),
    D("NY:CPLR 203", "new_rule",
      "Fixes when a limitation period starts and stops (accrual to interposition) for the landlord's balance suit and the tenant's deposit suit, and saves a time-barred counterclaim from the same lease as a setoff; no rule states this.",
      proposed=[
          R("NY:CPLR-203-accrual-interposition", "NY:CPLR 203", "CPLR 203(a)-(c), (f), (g)(1)", "landlord; former tenant", "rule",
            "Computing whether a claim between the landlord and a former tenant is timely (NY:CPLR-213(2), NY:ADJ-tenant-deposit-claim-limitations).",
            "The period runs from accrual of the claim to its interposition. Branch (a): in Supreme Court or NYC Civil Court (commenced by filing: CPLR 304, CCA 400), a claim in the complaint is interposed when the summons and complaint are filed with the clerk. Branch (b): in an action commenced by service (a court not of record), it is interposed on service, on completed publication under an order, on a provisional-remedy order followed by service within 30 days, or on an attachment order with service under CPLR 6213; delivering the summons to an officer for service in the defendant's county also counts if the summons is served within 60 days after the period would otherwise have expired (with a 60-day window after letters if the defendant dies). Branch (c): a claim added by amendment dates back to the original pleading if the original gave notice of the transactions to be proved. Branch (d): where the period runs from discovery, the action is timely within two years after actual or imputed discovery or the ordinary period from accrual, whichever is longer.",
            "(a) Accrual of cause of action and interposition of claim.", "computed from the time the cause of action accrued, whichever is longer.", severity="critical", walk_step="8.10",
            dependencies=["NY:CPLR-213(2)", "NY:ADJ-tenant-deposit-claim-limitations"]),
          R("NY:CPLR-203(d)-counterclaim-offset", "NY:CPLR 203", "CPLR 203(d), (e)", "landlord; former tenant", "rule",
            "One side sues within its period and the other asserts a counterclaim or defense. Branch (a): the counterclaim arises from the same lease or tenancy (the landlord's rent or damage claim against the tenant's deposit claim, or the reverse). Branch (b): it arises from something else.",
            "A counterclaim is interposed when the pleading containing it is served, and is not barred if it was not barred when the plaintiff's claim was interposed. Branch (a): even if already time-barred then, it may be used to the extent of the plaintiff's demand (an offset that reduces or wipes out the recovery, with no affirmative judgment beyond it). So a landlord sued for the deposit may offset a time-barred lease balance up to the tenant's demand, and a tenant sued for a balance may offset a time-barred deposit claim. Branch (b): a counterclaim already barred when the complaint was interposed is barred. If the plaintiff's action ends by its death, dismissal or voluntary discontinuance after the answer was served, the time the action was pending is not counted against the counterclaim.",
            "(d) Defense or counterclaim. A defense or counterclaim is interposed", "within which the defense or counterclaim may be interposed in another action brought by the plaintiff or his successor in interest.",
            severity="critical", walk_step="7.6", dependencies=["NY:CPLR-203-accrual-interposition", "NY:ADJ-forfeiture-claims-survive"])]),
    D("NY:CPLR 215", "partial",
      "215(7) sets a one-year limit on a tenant's RPL 223-b(3) retaliation action, which the retaliation rule does not state; the other subdivisions (sheriff liability, assault, penalty to informer, arbitration award, interest overcharge) decide nothing in this chain.",
      atoms=["NY:RPL-223-b-retaliation"],
      proposed=[R("NY:CPLR-215(7)-retaliation-one-year", "NY:CPLR 215", "CPLR 215(7)", "former tenant; landlord", "limit",
                  "A tenant claims the landlord's non-renewal, notice to quit or proceeding was retaliatory (NY:RPL-223-b-retaliation) and sues under RPL 223-b(3).",
                  "The tenant's action must be commenced within one year. Operator step: keep the non-renewal record and the stated non-retaliatory reason at least one year after the act, and longer where another claim's period is longer.",
                  "7. an action by a tenant pursuant to subdivision three of section two hundred twenty-three-b of the real property law.",
                  severity="major", walk_step="3.8", amends="NY:RPL-223-b-retaliation", dependencies=["NY:RPL-223-b-retaliation"])]),
    D("NY:CPLR 5003", "partial",
      "The 2% rule names post-judgment interest but no rule states that a money judgment bears interest from entry (or a docketed money order from docketing).",
      atoms=["NY:CPLR-5004(a)-consumer-2pct", "NY:CPLR-5001(a)-(b)"],
      proposed=[R("NY:CPLR-5003-judgment-interest", "NY:CPLR 5003", "CPLR 5003", "landlord; former tenant", "rule",
                  "A money judgment is entered for either side on a claim between the landlord and a former tenant, or an order directing payment is docketed as a judgment.",
                  "The judgment bears interest from the date of entry (the order, from docketing) until paid, at the rate of NY:CPLR-5004(a)-consumer-2pct (2% against a natural person on a consumer debt, 9% otherwise). A landlord owing a judgment to a former tenant pays this interest too.",
                  "Every money judgment shall bear interest from the date of its entry.", "shall bear interest from the date of such docketing.",
                  severity="critical", walk_step="8.10", amends="NY:CPLR-5004(a)-consumer-2pct", dependencies=["NY:CPLR-5004(a)-consumer-2pct"])]),
    D("NY:CPLR 5102", "no_decision",
      "Enforces a judgment awarding possession by execution; in this chain possession is back when the tenant leaves, and an NYC eviction is enforced by an RPAPL warrant, not a CPLR 5102 execution."),
    D("NY:CPLR 5230", "partial",
      "The enforcement-limits rule covers exemptions; no rule states the execution's required contents (the 2% consumer rate, last known address, exemption notices), who issues it, or its 60-day return.",
      atoms=["NY:CPLR-5205-5231-enforcement-limits"],
      proposed=[R("NY:CPLR-5230-execution", "NY:CPLR 5230", "CPLR 5230(a)-(c)", "landlord (judgment creditor) or its attorney", "obligation",
                  "The landlord enforces a money judgment against a natural-person former tenant by execution.",
                  "The execution states the entry date, court, judgment amount, the applicable interest rate (and, where the 2% consumer-debt rate applies, that rate and the date it applies from) and the amount due, the parties, and the tenant's last known address; it reaches only property of, and debts owed to, a named judgment debtor who is not deceased (a deceased debtor: NY:CPLR-1203-1015-5208-parties); it carries the notices that $2,500 of an account holding identifiable exempt deposits and the 5222(i) wage-based amount are exempt. A judgment of a court other than the Supreme or County Court states the date its transcript was filed with the county clerk. It may be issued at any time before the judgment is satisfied or vacated, by the clerk or the creditor's attorney as officer of the court. It is returned within 60 days unless served under CPLR 5231 or 5232(a), extendable in writing by the attorney for up to 60 days at a time.",
                  "(a) Form. An execution shall specify the date that the judgment or order was entered", "unless another execution against the same judgment debtor or obligor has been delivered to the same enforcement officer and has not been returned.",
                  severity="major", walk_step="8.12", amends="NY:CPLR-5205-5231-enforcement-limits",
                  dependencies=["NY:CPLR-5205-5231-enforcement-limits", "NY:CPLR-5004(a)-consumer-2pct", "NY:CPLR-1203-1015-5208-parties"])]),
    D("NY:CPLR 5232", "partial",
      "The enforcement-limits rule states the bank exemption; 5232 adds the levy's 90-day life, the 4-day notice to a natural-person debtor, the 27-day bank hold with exemption forms, and the creditor's liability for naming a third party's property.",
      atoms=["NY:CPLR-5205-5231-enforcement-limits"],
      proposed=[R("NY:CPLR-5232-levy", "NY:CPLR 5232", "CPLR 5232(a), (c), (e)-(g)", "landlord (judgment creditor); enforcement officer", "rule",
                  "The landlord levies on a natural-person former tenant's bank account or other personal property under an execution.",
                  "The levy is made by serving the execution on the garnishee (bank, employer, other holder), or by seizure of property capable of delivery. It binds property and debts then held or later coming due until transferred to the enforcement officer, and is void 90 days after service except as to what was transferred or is in a CPLR 5225/5227 turnover proceeding, unless the court extends it on the creditor's motion. The officer mails or delivers to the tenant, within four days after serving a garnishee, the execution with the CPLR 5222(e) exemption notice unless it was served within the prior year, to the residence, else in a 'personal and confidential' envelope to the workplace, else any known address. On a bank account: $2,500 is untouchable where identifiable exempt payments were deposited in the prior 45 days, plus the minimum-wage-based amount; the exemption notice and two claim forms are served with the execution; the bank holds the funds at least 27 days and may transfer after 30 days if no claim form or order arrives; no bank fee where the account holds only exempt funds. A creditor that names in its notice property or a debt belonging to someone other than the tenant is liable to that person for damages from the levy.",
                  "(a) Levy by service of execution.", "the banking institution shall charge no fee to the judgment debtor regardless of any terms of agreement, or schedule of fees, or other contract between the judgment debtor and the banking institution.",
                  severity="major", walk_step="8.12", amends="NY:CPLR-5205-5231-enforcement-limits",
                  dependencies=["NY:CPLR-5205-5231-enforcement-limits", "NY:CPLR-5230-execution"])]),
]
write(rows)
