from q2_lib import *

MECH = "in-suit litigation mechanics that change no amount, deadline, precondition or payee in settling the account or deciding to pursue it."
rows = [
    D("NY:CCA 1802-A", "no_decision", "Establishes the commercial claims parts and evening sessions; access and procedure are stated at NY:CCA-1801-A(a)-eligibility, NY:CCA-1803-A(b) and the proposed 22 NYCRR 208.41-a rule."),
    D("NY:CCA 1804-A", "new_rule",
      "In the commercial claims part an itemized paid invoice, or two itemized estimates, is prima facie proof of the reasonable value and necessity of repairs; sets how an entity owner proves a damage charge against the former tenant there.",
      proposed=[R("NY:CCA-1804-A-commercial-claims-proof", "NY:CCA 1804-A", "CCA 1804-A", "entity owner (claimant); former tenant", "rule",
                  "An entity owner brings a commercial claim against a former tenant that includes damage to the unit (eligibility: NY:CCA-1801-A(a)-eligibility).",
                  "The court decides to do substantial justice under the substantive law, not bound by rules of practice, pleading or evidence except privilege and the dead-man rule. An itemized bill or invoice, receipted or marked paid, or two itemized estimates for services or repairs, are admissible and prima facie evidence of the reasonable value and necessity of the work; the owner still bears the burden on amounts kept from the deposit (NY:GOL-7-108(1-a)(f)). Disclosure only by court order.",
                  "The court shall conduct hearings upon commercial claims in such manner", "in case of conflict, the provisions of this article shall control.",
                  severity="major", walk_step="7.4", dependencies=["NY:GOL-7-108(1-a)(f)", "NY:CCA-1801-A(a)-eligibility"])]),
    D("NY:CCA 1805-A", "new_rule",
      "Commercial-claims remedies: conditional judgment, pre-judgment examination and restraint, transfer, and counterclaims only within the part's limit; changes where a tenant's larger counterclaim goes.",
      proposed=[R("NY:CCA-1805-A-commercial-claims-remedies", "NY:CCA 1805-A", "CCA 1805-A(a)-(c)", "entity owner; former tenant", "rule",
                  "An entity owner's commercial claim against a former tenant is decided in the commercial claims part.",
                  "The court directs judgment on its findings and may condition its entry on just terms; before judgment it may order the tenant examined and restrained as if a post-judgment restraining notice had been served. It may transfer the claim to another part. The tenant's counterclaim (for example for the deposit or double damages) is allowed only within the part's monetary limit ($10,000); a larger claim is brought in a court of competent jurisdiction.",
                  "(a) Upon determination of a commercial claim,", "Any other claim sought to be maintained against the claimant may be filed in any court of competent jurisdiction.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-1801-A(a)-eligibility"])]),
    D("NY:CCA 1811-A", "new_rule",
      "Unsatisfied commercial-claims judgments are indexed under the debtor's name; a landlord that pays a tenant's counterclaim judgment there must present proof of satisfaction to clear the record.",
      proposed=[R("NY:CCA-1811-A-satisfaction-proof", "NY:CCA 1811-A", "CCA 1811-A", "entity owner (judgment debtor on a counterclaim); former tenant", "obligation",
                  "A judgment in the commercial claims part over the tenancy is paid (the tenant's counterclaim judgment against the owner, or the owner's judgment against the tenant).",
                  "Unsatisfied commercial-claims judgments are indexed alphabetically and chronologically under the debtor's name; the paying debtor presents proof of satisfaction to the court, which notes it in the records.",
                  "All wholly or partially unsatisfied commercial claims part judgments", "the court shall indicate such in the records.",
                  severity="minor", walk_step="7.6", dependencies=["NY:CCA-1811(d)-satisfaction-proof"])]),
    D("NY:CCA 1815*2", "no_decision",
      "Lets senior, disabled and evening-working claimants have a small claim heard in the daytime pro se part; a scheduling option for the tenant that adds no step or amount for either side."),
    D("NY:CCA 1912", "no_decision", "Fee waivers for employees' wage claims and state or city penalty actions; neither is a claim over the tenancy."),
    D("NY:CCA 1914", "no_decision", "Stenographer's fees for transcripts on appeal; appellate practice."),
    D("NY:CCA 1915", "new_rule",
      "New York City marshals and the city sheriff enforcing Civil Court judgments get the same fees as a Supreme Court sheriff (fixed fees and 5% poundage); an enforcement cost for the landlord's Civil Court judgment.",
      proposed=[R("NY:CCA-1915-marshal-fees", "NY:CCA 1915", "CCA 1915", "landlord (judgment creditor); former tenant", "rule",
                  "A city marshal or the New York City sheriff serves process or enforces the landlord's NYC Civil Court judgment against a former tenant.",
                  "They are paid the same fees a sheriff receives for like services in the Supreme Court: the CPLR 8011 fixed fees and CPLR 8012 poundage (NY:CPLR-8011-sheriff-fees, NY:CPLR-8012-poundage), collected from the tenant under the execution where the law allows (NY:CPLR-8014-fees-collected-on-execution).",
                  "In performing a function within their respective jurisdiction and powers", "the same fees to which a sheriff would be entitled for like services in supreme court.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-8011-sheriff-fees", "NY:CPLR-8012-poundage"])]),
    D("NY:CCA 201", "new_rule",
      "The Civil Court's $50,000 limit is measured exclusive of interest and costs, so a balance of $50,000 plus interest and costs stays in Civil Court.",
      proposed=[R("NY:CCA-201-limit-excludes-interest", "NY:CCA 201", "CCA 201", "landlord; former tenant", "rule",
                  "Deciding whether a claim over the tenancy is within the NYC Civil Court's $50,000 limit (NY:CCA-202-money-limit).",
                  "The $50,000 figure is exclusive of interest and costs; only the principal claimed counts toward the limit.",
                  "The court shall have jurisdiction as set forth in this article", "shall be taken to mean \"$50,000 exclusive of interest and costs\".",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-202-money-limit"])]),
    D("NY:CCA 203", "no_decision",
      "Civil Court jurisdiction over real-property actions (partition, mortgage, ejectment, housing-standard penalty and violation actions); a balance or deposit claim is a money action under CCA 202."),
    D("NY:CCA 207", "no_decision", "Confers small claims jurisdiction as article 18 defines it; the article 18 rules are stated (NY:CCA-1801-tenant-claim) or proposed in this batch."),
    D("NY:CCA 210", "no_decision", "Applies Supreme Court contempt law in the Civil Court; a court power that adds no step for the parties."),
    D("NY:CCA 2102", "stated",
      "Makes the CPLR apply in the NYC Civil Court where not in conflict with the CCA; the stated CPLR rules on default mailing, interest and limitations already apply to Civil Court suits on that basis.",
      atoms=["NY:CPLR-3215(g)(3)", "NY:CPLR-5001(a)-(b)", "NY:CPLR-5004(a)-consumer-2pct", "NY:CPLR-213(2)"]),
    D("NY:CCA 212", "no_decision", "Gives the Civil Court the Supreme Court's powers in like cases; it adds no step or amount."),
    D("NY:CCA 212-A", "no_decision", "Declaratory judgments on insurers' duties and Part 137 attorney-fee arbitration; neither arises in the settlement chain."),
    D("NY:CCA 213", "no_decision", "Civil Court jurisdiction to rescind or reform transactions up to $50,000; rescission is not a step in settling an ended tenancy."),
    D("NY:CCA 305", "new_rule",
      "For Civil Court venue an assignee is treated as the original owner, and a corporation or association resides in any county where it does business or has an office; decides in which county an owner entity or its collector may sue the former tenant.",
      proposed=[R("NY:CCA-305-venue-residence", "NY:CCA 305", "CCA 305", "landlord (plaintiff); assignee", "rule",
                  "Venue of a Civil Court balance action is fixed under CCA 301 by where a party resides.",
                  "A corporation, joint-stock or unincorporated association resides in any county where it transacts business, keeps an office, has an agency or is established by law, so an entity owner may sue in any such county within the city. If the plaintiff is an assignee of the claim, the original owner is treated as the plaintiff for venue. The pending S9760 would require suit in the tenant's county of residence or of the transaction (NY:S9760-venue).",
                  "(a) If the plaintiff is an assignee of the cause of action,", "or is established by law.",
                  severity="minor", walk_step="8.10", dependencies=["NY:S9760-venue", "NY:22NYCRR-208.8-wrong-county"])]),
    D("NY:CCA 307", "no_decision", "Lets court rules designate parts for classes of cases; administrative, no step for the parties."),
    D("NY:CCA 407", "new_rule",
      "In Civil Court, service on the attorney or clerk designated as agent under CPLR 303 (a moved-away tenant who sued the landlord) may be made anywhere; extends the landlord's ability to serve its separate balance action.",
      proposed=[R("NY:CCA-407-service-on-303-agent", "NY:CCA 407", "CCA 407", "landlord (plaintiff)", "permission",
                  "The landlord brings a Civil Court action against a former tenant by serving the tenant's attorney or the clerk as agent under CPLR 303 (NY:CPLR-303-plaintiff-designates-agent).",
                  "The service may be made in any manner and at any place, regardless of city lines, that would give the Supreme Court jurisdiction.",
                  "In any action in this court to be commenced by service of summons upon an attorney or a clerk as agent,", "as would confer jurisdiction on the supreme court in a like case.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-303-plaintiff-designates-agent"])]),
    D("NY:CCA 408", "new_rule",
      "A Civil Court summons may be served anywhere on a defendant who is a New York domiciliary and city resident (for example a former tenant temporarily away) and on added parties; widens where the landlord can serve.",
      proposed=[R("NY:CCA-408-service-outside-city", "NY:CCA 408", "CCA 408(a)-(f)", "landlord (plaintiff)", "permission",
                  "The landlord's Civil Court action is against a former tenant who is domiciled in New York and resides in the city but is found outside it, or brings in a third-party defendant, counterclaim or cross-claim defendant, interpleaded claimant or court-joined party.",
                  "The summons may be served in any manner and at any place, regardless of city or state lines, that would give the Supreme Court jurisdiction. A former tenant who no longer resides in the city is served outside it under CCA 404 instead (NY:CCA-404-long-arm).",
                  "A summons may be served in such manner and at such place, regardless of city or state lines,", "(f) a defendant who is a domiciliary of the state and a resident of the city.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-404-long-arm"])]),
    D("NY:CCA 901", "no_decision", "Lists the pleadings in Civil Court (complaint, answer, reply when ordered); " + MECH),
    D("NY:CCA 903", "no_decision", "Formal-pleading requirements do not apply to an endorsed summons; the endorsed-summons rule is proposed at NY:CCA-902-pleading-form."),
    D("NY:CPLR 1002", "no_decision",
      "Permits joining co-tenants, occupants and guarantors as defendants in one action; who is liable is decided by the lease and NY:GOL-5-701(a)(2)-guaranty, and joinder adds no step or amount."),
    D("NY:CPLR 1003", "no_decision", "Nonjoinder and misjoinder of parties and adding parties; " + MECH),
    D("NY:CPLR 1004", "no_decision",
      "An executor, guardian or trustee may sue or be sued without joining beneficiaries; who is paid or sued after a tenant's death is stated at NY:ADJ-tenant-death-payee."),
    D("NY:CPLR 1006", "new_rule",
      "A landlord facing conflicting claims to a deposit refund (co-tenants, an estate and a relative, a trustee and the tenant) may interplead the claimants, pay the refund into court and be discharged, owing interest only at the Federal Reserve discount rate absent agreement; decides how it pays safely.",
      proposed=[R("NY:CPLR-1006-interpleader", "NY:CPLR 1006", "CPLR 1006(a)-(b), (f)-(g)", "landlord (stakeholder)", "permission",
                  "The landlord owes a refund (the deposit balance) and two or more persons claim it adversely, exposing the landlord to double liability (for example co-tenants who disagree on shares where records show separate contributions, a relative and an estate fiduciary, a bankruptcy trustee and the tenant, a creditor with process and the tenant).",
                  "The landlord, as stakeholder, may bring an interpleader action against the claimants, or if sued by one may bring in the others by a summons and interpleader complaint. After the time to plead expires it may move to be discharged on proof of its allegations; the court may order the sum paid into court or to a designated person, and the landlord is discharged from liability to every claimant once it complies. Before or after suit it may move to pay the sum into court as the basis of jurisdiction. The court may charge just expenses and costs against the fund. Where a claimant is found entitled to interest and the landlord agreed no rate, the landlord owes interest to discharge at no more than the Federal Reserve Bank of New York's lowest discount rate. The 14-day statement still goes to each co-tenant or claimant (NY:ADJ-cotenants-payee); Civil Court jurisdiction up to $50,000: NY:CCA-205-interpleader.",
                  "(a) Stakeholder; claimant; action of interpleader.", "at a rate no greater than the lowest discount rate of the Federal Reserve Bank of New York",
                  severity="major", walk_step="6.6", dependencies=["NY:ADJ-cotenants-payee", "NY:CCA-205-interpleader"])]),
    D("NY:CPLR 1007", "no_decision", "Third-party practice (for example a sued tenant impleading a roommate); " + MECH),
    D("NY:CPLR 1008", "no_decision", "Answer of a third-party defendant; " + MECH),
    D("NY:CPLR 1009", "no_decision", "Plaintiff's claim against a third-party defendant; " + MECH),
    D("NY:CPLR 1010", "no_decision", "Dismissal or separate trial of a third-party complaint; " + MECH),
    D("NY:CPLR 1011", "no_decision", "Successive third-party proceedings; " + MECH),
    D("NY:CPLR 1012", "no_decision", "Intervention as of right (for example a co-tenant joining a deposit suit); " + MECH),
    D("NY:CPLR 1013", "no_decision", "Permissive intervention; " + MECH),
    D("NY:CPLR 1014", "no_decision", "Proposed pleading on intervention; " + MECH),
    D("NY:CPLR 1016", "no_decision",
      "The court substitutes a committee or conservator for a party adjudicated incompetent; a court act, with representation stated at the proposed NY:CPLR-1201-representation."),
]
write(rows)
