from q2_lib import *

MECH = "in-suit litigation mechanics (motion, calendar, conference, trial or papers practice) that change no amount, deadline, precondition or payee in settling the account or deciding to pursue it."
rows = [
    D("NY:22 NYCRR 202.71", "no_decision", "Recognition of tribal court judgments; no tribal judgment arises in settling an NYC market-rate tenancy."),
    D("NY:22 NYCRR 202.8", "no_decision", "Supreme Court motion procedure; " + MECH),
    D("NY:22 NYCRR 202.8-d", "no_decision", "When motions go by order to show cause; " + MECH),
    D("NY:22 NYCRR 202.8-f", "no_decision", "Oral argument of motions; " + MECH),
    D("NY:22 NYCRR 202.8-g", "no_decision", "Statements of material facts on summary judgment, repealed effective 2025-07-07; " + MECH),
    D("NY:22 NYCRR 202.9", "no_decision", "Special proceedings are heard like unassigned motions; " + MECH),
    D("NY:22 NYCRR 208.10", "no_decision", "Civil Court motion calendaring and notice-of-motion form; " + MECH),
    D("NY:22 NYCRR 208.11", "no_decision", "Civil Court motion parts and procedure; " + MECH),
    D("NY:22 NYCRR 208.14-a", "no_decision",
      "Default-judgment proof rules for consumer credit transactions, defined as revolving or open-end credit from a financial institution; a residential lease balance is not one (NY:ADJ-lease-balance-not-consumer-credit)."),
    D("NY:22 NYCRR 208.16", "new_rule",
      "After an NYC Civil Court action is discontinued (for example on settlement with the former tenant), the plaintiff's attorney must file the stipulation or statement of discontinuance within 20 days, or before any scheduled court date; a closing step for a settled suit.",
      proposed=[R("NY:22NYCRR-208.16-file-discontinuance", "NY:22 NYCRR 208.16", "22 NYCRR 208.16", "landlord's attorney (plaintiff)", "obligation",
                  "The landlord's (or tenant's) action over the tenancy in NYC Civil Court is discontinued, for example after a settlement (NY:CPLR-2104-stipulations, NY:CPLR-3217-discontinuance).",
                  "The plaintiff's attorney files the stipulation or statement of discontinuance with the clerk within 20 days of the discontinuance, or before any judicial activity scheduled within those 20 days.",
                  "In any discontinued action, the attorney for the plaintiff shall file a stipulation", "the stipulation or statement shall be filed before the date scheduled for such activity.",
                  severity="minor", walk_step="8.1b", dependencies=["NY:CPLR-2104-stipulations", "NY:CPLR-3217-discontinuance"])]),
    D("NY:22 NYCRR 208.18", "no_decision", "Civil Court trial calendars; " + MECH),
    D("NY:22 NYCRR 208.20", "no_decision", "Trial preferences in Civil Court; " + MECH),
    D("NY:22 NYCRR 208.21", "no_decision", "Objections to trial preferences in Civil Court; " + MECH),
    D("NY:22 NYCRR 208.22", "no_decision", "Pretrial and pre-arbitration conferences in Civil Court; the default and dismissal consequences of non-attendance are those of the calendar-default rule (proposed NY:22NYCRR-208.14-calendar-default)."),
    D("NY:22 NYCRR 208.24", "no_decision", "Day-certain trial applications; " + MECH),
    D("NY:22 NYCRR 208.25", "no_decision", "Adjournments for counsel's engagement; " + MECH),
    D("NY:22 NYCRR 208.27", "no_decision", "Papers submitted for trial; " + MECH),
    D("NY:22 NYCRR 208.31", "no_decision", "Restoring a case after a mistrial or new-trial order; " + MECH),
    D("NY:22 NYCRR 208.36", "new_rule",
      "A settlement of a claim by an infant or adjudicated incapacitated person in NYC Civil Court must follow CPLR 1207-1208 court approval; a settlement with such a former tenant (or co-occupant) is not binding without it.",
      proposed=[R("NY:22NYCRR-208.36-incapacitated-settlement", "NY:22 NYCRR 208.36", "22 NYCRR 208.36", "landlord; representative of an infant or incapacitated former tenant", "precondition",
                  "The landlord settles, in NYC Civil Court, a claim brought by or on behalf of an infant or a judicially declared incapacitated person (including an incompetent or conservatee), for example a deposit claim of a tenant under guardianship.",
                  "The settlement must comply with CPLR 1207 and 1208 (court approval on the representative's application: NY:CPLR-1207-incapacitated-settlement), 22 NYCRR 202.67 and, for an infant, Judiciary Law 474; until approved it does not bind the infant or incapacitated person.",
                  "The settlement of an action by an infant or judicially declared incapacitated person", "with section 474 of the Judiciary Law.",
                  severity="minor", walk_step="8.1b", dependencies=["NY:CPLR-1207-incapacitated-settlement"])]),
    D("NY:22 NYCRR 208.38", "no_decision", "Civil Court appeals; appellate practice."),
    D("NY:22 NYCRR 208.40", "no_decision", "Civil Court arbitration follows 22 NYCRR Part 28 or CPLR article 75; the compulsory program's reach is stated at proposed NY:CCA-206-compulsory-arbitration."),
    D("NY:22 NYCRR 208.7", "no_decision", "Civil Court pleading form and one ex parte 10-day extension to answer; " + MECH),
    D("NY:22 NYCRR 208.9", "no_decision", "Civil Court preliminary conferences in designated classes of cases; " + MECH),
    D("NY:CCA 1503", "no_decision", "Executions on judgments against marshals or sheriffs; not a landlord-tenant judgment."),
    D("NY:CCA 1509", "no_decision", "Statewide service of the court's contempt process; a court power that adds no step for the landlord or tenant."),
    D("NY:CCA 1802", "no_decision",
      "Establishes the small claims parts, evening sessions and an informal procedure alternative to a summons action; the right to use the part and its procedure are stated at NY:CCA-1801-tenant-claim and the proposed CCA 1803-1805 and 22 NYCRR 208.41 rules."),
]
write(rows)
