from q2_lib import *

ATT = "NY:CPLR-6201-attachment-grounds"
rows = [
    D("NY:CPLR 6202", "no_decision",
      "Defines attachable property by reference to CPLR 5201 (proposed NY:CPLR-5201-reachable-property); it adds nothing of its own."),
    D("NY:CPLR 6203", "no_decision",
      "Priority of an attaching creditor over later transferees of the defendant's property; a contest with third parties, not a settlement or collection step."),
    D("NY:CPLR 6204", "new_rule",
      "When a creditor of the former tenant attaches the refund the landlord owes the tenant, paying the sheriff under the order of attachment discharges the landlord to that extent; decides who the refund is paid to.",
      proposed=[R("NY:CPLR-6204-landlord-garnishee-attachment", "NY:CPLR 6204", "CPLR 6204", "landlord (garnishee)", "rule",
                  "A creditor of the former tenant serves the landlord with an order of attachment reaching the deposit refund or other money the landlord owes the tenant.",
                  "The landlord pays or delivers it to the sheriff as the order directs and is discharged from its obligation to the tenant to the extent of the payment; it serves the garnishee's statement within ten days (NY:CPLR-6219-garnishee-statement) and does not pay the tenant while the levy binds (NY:CPLR-6214-attachment-levy). The 14-day itemized statement to the tenant still issues, showing the sum paid under the attachment.",
                  "A person who, pursuant to an order of attachment, pays or delivers to the sheriff", "is discharged from his obligation to the defendant to the extent of the payment or delivery.",
                  severity="major", walk_step="6.1", dependencies=["NY:CPLR-5209-landlord-as-garnishee", "NY:GOL-7-108(1-a)(e)"])]),
    D("NY:CPLR 6211", "new_rule",
      "An attachment granted without notice must be confirmed on motion within 5 days after levy (10 days for a nondomiciliary defendant), or it lapses; a deadline that decides whether the landlord keeps its security.",
      proposed=[R("NY:CPLR-6211-confirmation", "NY:CPLR 6211", "CPLR 6211", "landlord (plaintiff)", "obligation",
                  "The landlord obtains an order of attachment against a former tenant without notice (grounds: NY:CPLR-6201-attachment-grounds).",
                  "The order states the amount secured (including interest, costs and sheriff's fees), bears the attorney's name and address, and directs the sheriff of the county (or New York City) where property or a garnishee is located to levy. Unless granted because the tenant is a nondomiciliary residing outside the state, the landlord moves to confirm within five days after levy, on notice to the tenant, garnishee and sheriff; on the nondomiciliary ground, the garnishee's statement is due within five days and the landlord moves to confirm within ten days after levy (one extension of up to ten days if the statement was not served). If the landlord does not move in time, the attachment and levy have no further effect and are vacated on motion. On confirmation the landlord bears the burden in NY:CPLR-6223-vacate-burden.",
                  "(a) When granted; contents.", "may provide that the sheriff refrain from taking any property levied upon into his actual custody, pending further order of the court.",
                  severity="minor", walk_step="8.10", dependencies=[ATT, "NY:CPLR-6223-vacate-burden"])]),
    D("NY:CPLR 6212", "new_rule",
      "To attach, the landlord must show probable success and that its claim exceeds known counterclaims (for example the deposit), post an undertaking of at least $500, file within ten days, and is liable for all damages and attorney's fees if the attachment was wrongful; decides whether attaching is worth it.",
      proposed=[R("NY:CPLR-6212-attachment-motion", "NY:CPLR 6212", "CPLR 6212", "landlord (plaintiff)", "obligation",
                  "The landlord moves for, or to confirm, an order of attachment against a former tenant.",
                  "It shows by affidavit and written evidence a cause of action, that it will probably succeed, a CPLR 6201 ground, and that the amount demanded exceeds all counterclaims known to it (including the tenant's deposit claim and any forfeiture offset). It gives an undertaking fixed by the court of at least $500, part securing the tenant's costs and damages including reasonable attorney's fees and part the sheriff's fees. Within ten days after the order it files the order, supporting papers and the summons and complaint, or the order is invalid. On the tenant's written demand after levy it serves the papers within one day. If the tenant wins or the attachment is finally held improper, the landlord is liable for all costs and damages, including reasonable attorney's fees, without limit to the undertaking.",
                  "(a) Affidavit; other papers.", "Plaintiff’s liability shall not be limited by the amount of the undertaking.",
                  severity="major", walk_step="8.10", dependencies=[ATT])]),
    D("NY:CPLR 6213", "new_rule",
      "An attachment granted before the former tenant is served is valid only if the summons is served (or publication begun and completed) within 60 days; a deadline on the landlord's security.",
      proposed=[R("NY:CPLR-6213-serve-within-60-days", "NY:CPLR 6213", "CPLR 6213", "landlord (plaintiff)", "obligation",
                  "The landlord obtains an order of attachment before serving the summons on the former tenant.",
                  "The order is valid only if, within 60 days after it is granted, the summons is served on the tenant (or publication under an order is begun and then completed); if the tenant dies first, the summons is served on its executor or administrator within 60 days after letters issue. On good cause shown before the time runs, the court may extend it by up to 60 days. This service also interposes the claim for limitations (NY:CPLR-203-accrual-interposition).",
                  "An order of attachment granted before service is made on the defendant", "provided that the application for extension is made before the expiration of the time fixed.",
                  severity="minor", walk_step="8.10", dependencies=[ATT, "NY:CPLR-203-accrual-interposition"])]),
    D("NY:CPLR 6214", "new_rule",
      "How an attachment levy binds a garnishee: it must hold and turn over the defendant's property or debts for 90 days; binds a landlord holding a former tenant's refund when the tenant's creditor attaches, and sets the 90-day life of the landlord's own levy.",
      proposed=[R("NY:CPLR-6214-attachment-levy", "NY:CPLR 6214", "CPLR 6214(a)-(b), (d)-(e)", "landlord (as attaching plaintiff or as garnishee)", "rule",
                  "An order of attachment is served on a person holding property of, or owing a debt to, the defendant. Branch (a): the landlord attached the former tenant's property held by a bank or other garnishee. Branch (b): a creditor of the former tenant served the landlord, which owes the tenant the refund.",
                  "The levy binds property and debts then held or later coming due until transferred to the sheriff, up to the amount of the order; the garnishee must transfer or pay them to the sheriff and may not otherwise pay or transfer them for 90 days after service (or longer by order). After 90 days the levy is void except as to what the sheriff has collected or what is subject to a turnover proceeding against the garnishee, unless the court extends it on the plaintiff's motion. Branch (a): the landlord may bring a special proceeding to compel the garnishee to pay, and is liable to a non-debtor owner for property it named in its notice. Branch (b): the landlord holds the refund, pays it to the sheriff (NY:CPLR-6204-landlord-garnishee-attachment), and may assert against the attaching creditor any defense it has against the tenant (for example its lawful deductions).",
                  "(a) Method of levy.", "or as to which a proceeding under subdivision (d) has been commenced.",
                  severity="minor", walk_step="6.1", dependencies=["NY:CPLR-6204-landlord-garnishee-attachment"])]),
    D("NY:CPLR 6215", "no_decision",
      "Levy by the sheriff's physical seizure on the plaintiff's direction and indemnity; officer mechanics that add no settlement step beyond the attachment rules proposed at CPLR 6201-6214."),
    D("NY:CPLR 6216", "no_decision",
      "The sheriff levies an attachment on real property by filing a notice with the county clerk; officer mechanics."),
    D("NY:CPLR 6218", "no_decision",
      "The sheriff's custody of attached property in an interest-bearing trust account and inventory; officer duties, not the landlord's."),
    D("NY:CPLR 6219", "new_rule",
      "A garnishee served with an order of attachment must within ten days serve the sheriff a statement of its debts to and property of the defendant; binds a landlord served by a former tenant's creditor while holding the tenant's refund.",
      proposed=[R("NY:CPLR-6219-garnishee-statement", "NY:CPLR 6219", "CPLR 6219", "landlord (garnishee)", "obligation",
                  "A creditor of the former tenant serves the landlord with an order of attachment while the landlord owes the tenant a refund or holds its property (belongings, deposit).",
                  "Within ten days after service (or a shorter time the court sets), the landlord serves on the sheriff a statement of every debt it owes the tenant and when due, and all property of the tenant in its possession, with amounts and values; if it owes at least the attachment amount, it may state only that fact.",
                  "Within ten days after service upon a garnishee of an order of attachment,", "he may limit his statement to that fact.",
                  severity="minor", walk_step="6.1", dependencies=["NY:CPLR-6204-landlord-garnishee-attachment"])]),
    D("NY:CPLR 6221", "no_decision",
      "Adverse claimants to attached property may have their rights decided; it mirrors CPLR 5239 (proposed NY:CPLR-5239-adverse-claims) for attachment, and the landlord's damages exposure for a wrongful attachment is stated at proposed NY:CPLR-6212-attachment-motion."),
    D("NY:CPLR 6222", "no_decision",
      "Lets the defendant free attached property by posting an undertaking for its value; the tenant's option, adding no step for the landlord."),
    D("NY:CPLR 6223", "new_rule",
      "The former tenant, a garnishee or any interested person may move to vacate an attachment, and the landlord bears the burden of proving the grounds, the need for the levy and probable success; after the tenant appears the court vacates an attachment that is unnecessary for security.",
      proposed=[R("NY:CPLR-6223-vacate-burden", "NY:CPLR 6223", "CPLR 6223", "landlord (plaintiff)", "rule",
                  "The landlord holds an attachment against a former tenant's property and the tenant, a garnishee or another interested person moves to vacate or modify it.",
                  "The landlord bears the burden of establishing the CPLR 6201 grounds, the need to continue the levy and probable success on the merits; the court may let it cure defects. After the tenant has appeared, the court vacates the attachment if it is unnecessary to the landlord's security (for example the tenant can now be served and has assets here).",
                  "(a) Motion to vacate or modify.", "the need for continuing the levy and the probability that he will succeed on the merits.",
                  severity="minor", walk_step="8.10", determinacy="MIXED", judgment_terms=["unnecessary to the security of the plaintiff"], dependencies=[ATT])]),
    D("NY:CPLR 6224", "no_decision",
      "An attachment ends automatically when the action is discontinued, the judgment is satisfied, or the defendant wins; no step for the landlord."),
    D("NY:CPLR 6226", "no_decision",
      "After execution issues, attached property is handled as if levied under the execution, with priority by delivery (CPLR 5234); officer mechanics."),
]
write(rows)
