from q2_lib import *

EL = "NY:CPLR-5205-5231-enforcement-limits"
rows = [
    D("NY:CPLR 5233", "no_decision",
      "How the sheriff conducts an execution sale of personal property (auction, notice, unsaleable goods); the officer's duties, not a step or amount for the landlord or tenant."),
    D("NY:CPLR 5234", "new_rule",
      "Proceeds of a levy go to the judgment creditor after fees, excess to the former tenant, not before 15 days after service; competing executions are paid in delivery order. Decides when and in what order the landlord is paid.",
      proposed=[R("NY:CPLR-5234-distribution-priority", "NY:CPLR 5234", "CPLR 5234(a)-(c)", "landlord (judgment creditor)", "rule",
                  "The sheriff or marshal collects money on the landlord's execution against a former tenant (for example from a bank levy), possibly with other creditors' executions outstanding.",
                  "After fees, expenses and taxes, the proceeds go to the judgment creditor and any excess to the tenant; nothing is distributed until 15 days after service of the execution unless the court orders. Executions delivered to the same officer are paid in the order delivered (child-support executions first); where different officers hold executions, the levying officer's execution is paid first, then others that demanded before distribution. A turnover or receivership order filed before a levy outranks the levy, but loses priority if payment is not completed within 60 days of filing unless extended. Operator step: deliver the execution promptly, because priority runs from delivery.",
                  "(a) Distribution of proceeds of personal property.", "unless otherwise specified in the order or in an extension order filed within the sixty days.",
                  severity="minor", walk_step="8.12")]),
    D("NY:CPLR 5235", "no_decision",
      "The sheriff's method of levying on real property after the ten-year docketing lien lapses (a filed notice of levy); officer mechanics. The landlord's real-property rights are stated at the proposed NY:CPLR-5203-real-property-lien and NY:CPLR-5014-renewal-judgment."),
    D("NY:CPLR 5236", "no_decision",
      "The sheriff's procedure for an execution sale of real property (notice, publication, deed, distribution); a former tenant's residence is reached only through the homestead special proceeding (proposed NY:CPLR-5206-homestead), and the sale mechanics add no settlement step."),
    D("NY:CPLR 5239", "new_rule",
      "Anyone claiming an interest in levied property (a joint account holder, a spouse, the former tenant) may bring a proceeding to decide it, and the court may void the levy and award damages; changes the landlord's exposure when it levies property that is not only the tenant's.",
      proposed=[R("NY:CPLR-5239-adverse-claims", "NY:CPLR 5239", "CPLR 5239", "landlord (judgment creditor); former tenant; third-party claimant", "rule",
                  "The landlord's execution or order reaches property or a debt in which someone other than the landlord claims an interest (a joint bank account with a co-occupant, property the tenant says is exempt or belongs to another), before the sheriff or receiver applies it.",
                  "Any interested person may bring a special proceeding against the landlord to determine rights, served on the landlord and the sheriff or receiver like a notice of motion, in the county of the levy or a CPLR 5221 court. The court may vacate the execution, void the levy, direct disposition of the property, or award damages; disputed facts get a separate trial. A claimant whose claim is found fraudulent may be made to pay the landlord's reasonable expenses, including attorneys' fees. The landlord is also liable to a non-debtor owner for property it specified in a levy notice (NY:CPLR-5232-levy).",
                  "Prior to the application of property or debt by a sheriff or receiver", "The court may permit any interested person to intervene in the proceeding.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-5232-levy"])]),
    D("NY:CPLR 5240", "no_decision",
      "General power of the court to limit or condition any enforcement procedure on request; judicial supervision that adds no step, amount or deadline of its own."),
    D("NY:CPLR 5242", "no_decision",
      "Income deduction orders for child and spousal support; not a landlord's judgment."),
    D("NY:CPLR 5250", "new_rule",
      "A court may order the arrest of a judgment debtor about to leave the state or in hiding with property, to bring it in for examination; an extraordinary enforcement step against a departing former tenant.",
      proposed=[R("NY:CPLR-5250-arrest-of-debtor", "NY:CPLR 5250", "CPLR 5250", "landlord (judgment creditor)", "permission",
                  "The landlord holds a money judgment against a former tenant who is about to leave New York or is concealing itself here, and there is reason to believe it holds property in which it has an interest.",
                  "On motion without notice the court may issue a warrant for the sheriff to arrest the tenant and bring it before the court, which may require an undertaking that it will attend an examination and obey a restraining notice. Only a court may order this; a landlord or collector may not threaten arrest or imprisonment for non-payment (US:15USC1692e(5), NYC:RCNY6-5-77(d)(17)-GBL601).",
                  "Upon motion of the judgment creditor without notice,", "and that he will obey the terms of any restraining notice contained in the order.",
                  severity="minor", walk_step="8.12", dependencies=["US:15USC1692e(5)"])]),
    D("NY:CPLR 5251", "new_rule",
      "Disobeying an enforcement subpoena, restraining notice or order, or false swearing on an examination, is contempt; this binds a landlord served with a restraining notice on a former tenant's refund, and a tenant that ignores the landlord's subpoena.",
      proposed=[R("NY:CPLR-5251-disobedience-contempt", "NY:CPLR 5251", "CPLR 5251", "landlord (as garnishee or judgment creditor); former tenant", "rule",
                  "Branch (a): a creditor of the former tenant serves the landlord with a restraining notice, subpoena or order reaching money the landlord owes the tenant (the deposit refund). Branch (b): the landlord serves the former tenant (or its bank) with an enforcement subpoena or restraining notice.",
                  "Refusal or willful neglect to obey a subpoena, restraining notice or order under CPLR article 52, false swearing on an examination or in answering written questions, and willful removal of a posted sale notice are each punishable as contempt. Branch (a): the landlord must not pay the restrained refund to the tenant; it pays as the process directs (NY:CPLR-5209-landlord-as-garnishee). Branch (b): the landlord may move to hold the tenant or garnishee in contempt.",
                  "Refusal or willful neglect of any person to obey a subpoena or restraining notice issued,", "shall each be punishable as a contempt of court.",
                  severity="major", walk_step="6.1", dependencies=["NY:CPLR-5209-landlord-as-garnishee"])]),
    D("NY:CPLR 5252", "no_decision",
      "Bars employers from discriminating against employees over wage assignments or income executions; it binds the tenant's employer, not the landlord's settlement or collection."),
    D("NY:CPLR 5253", "partial",
      "The enforcement-limits rule states the exemptions at their statutory amounts; 5253 makes the CPLR 5205 and 5206 dollar exemptions adjust every three years from April 1, 2012 by the published CPI figure, not applying to restraints or executions made before an adjustment.",
      atoms=[EL],
      proposed=[R("NY:CPLR-5253-exemption-adjustment", "NY:CPLR 5253", "CPLR 5253", "landlord (judgment creditor)", "rule",
                  "The landlord estimates or enforces recovery against a former tenant's exempt property under CPLR 5205 or 5206.",
                  "The dollar amounts of those exemptions are adjusted on April 1, 2012 and every three years after (2015, 2018, 2021, 2024, 2027), by the change in the CPI-U for New York-Northern New Jersey-Long Island over the prior three calendar years, rounded to the nearest $25, as published by the Superintendent of Financial Services with the next adjustment date. The amount in effect when a restraining notice is served or an execution levied governs it; later adjustments do not apply to earlier restraints or executions. Operator input: the current published amounts replace the statutory figures in NY:CPLR-5205-5231-enforcement-limits and NY:CPLR-5206-homestead.",
                  "(a) Beginning on April first, two thousand twelve,", "Nothing in this section limits the judgment debtor’s exemption rights in this section or under any other law.”",
                  severity="major", walk_step="8.12", amends=EL, dependencies=[EL, "NY:CPLR-5206-homestead"])]),
    D("NY:CPLR 6201", "new_rule",
      "Grounds for a pre-judgment order of attachment against a former tenant: it lives outside New York, cannot be served despite diligence, or is hiding or moving assets to defeat a judgment; an option to secure the balance against a tenant who has left the state.",
      proposed=[R("NY:CPLR-6201-attachment-grounds", "NY:CPLR 6201", "CPLR 6201", "landlord (plaintiff)", "permission",
                  "The landlord sues a former tenant for a money judgment (the balance) and wants to secure the tenant's property in New York before judgment.",
                  "An order of attachment may be granted when: (1) the tenant is a nondomiciliary residing outside New York (for example it moved away), or a foreign corporation not qualified here; (2) the tenant lives in New York but cannot be personally served despite diligent efforts; (3) the tenant, intending to defraud creditors or frustrate a judgment, has assigned, disposed of, encumbered, hidden or removed property from the state, or is about to; or (5) the claim is on a judgment entitled to full faith and credit. The motion, undertaking and levy follow CPLR 6210-6226 (in NYC Civil Court also CCA 209 and 801: NY:CCA-209-provisional-remedies). Exempt property cannot be attached.",
                  "An order of attachment may be granted in any action, except a matrimonial action,", "or on a judgment which qualifies for recognition under the provisions of article 53.",
                  severity="major", walk_step="8.10", determinacy="MIXED", judgment_terms=["diligent efforts", "intent to defraud creditors or frustrate enforcement"],
                  dependencies=["NY:CCA-209-provisional-remedies"])]),
]
write(rows)
