from q2_lib import *

COSTS_NOTE = "Costs and disbursements are recovered only as the judgment awards them; none goes on the final account before judgment (NY:RPL-234-a)."
rows = [
    D("NY:CCA 1401", "no_decision",
      "Says who drafts the judgment document (the winner's attorney or the clerk, the loser after 30 days); it changes no amount, deadline or step in settling or collecting the account."),
    D("NY:CCA 1402", "partial",
      "The 3215 rules state the default mailing and limitations affidavit; no rule states that in NYC Civil Court a default judgment may be entered on a summons endorsed with the amount and the nature of the claim, without a formal complaint.",
      atoms=["NY:CPLR-3215(g)(3)", "NY:CPLR-3215(j)-sol-affidavit"],
      proposed=[R("NY:CCA-1402-default-on-endorsed-summons", "NY:CCA 1402", "CCA 1402", "landlord (plaintiff) or its attorney", "permission",
                  "The landlord sues a former tenant for the balance in NYC Civil Court and the tenant does not appear or answer.",
                  "A default judgment is entered under CPLR 3215. A summons that states the amount for which the landlord will take judgment on default and the nature and substance of the claim, or a summons served with a formal complaint, counts as the summons and complaint for CPLR 3215(e) proof. The 3215(g)(3) additional mailing, the limitations affidavit and the military affidavit still apply (NY:CPLR-3215(g)(3), NY:CPLR-3215(j)-sol-affidavit, US:50USC3931(b)(1)).",
                  "A judgment by default may be entered as provided in CPLR § 3215.", "referred to in subdivision (e) of said section.",
                  severity="major", walk_step="8.9", amends="NY:CPLR-3215(g)(3)",
                  dependencies=["NY:CPLR-3215(g)(3)", "NY:CPLR-3215(j)-sol-affidavit", "US:50USC3931(b)(1)"])]),
    D("NY:CCA 1403", "new_rule",
      "Makes a former tenant's confession of judgment (CPLR 3218) enterable and enforceable in NYC Civil Court for a balance within its jurisdiction; a settlement and payment-plan option.",
      proposed=[R("NY:CCA-1403-confession-civil-court", "NY:CCA 1403", "CCA 1403", "landlord", "permission",
                  "A former tenant signs an affidavit confessing judgment for a balance within the NYC Civil Court's monetary jurisdiction (the affidavit's requisites and filing limits: NY:CPLR-3218-confession).",
                  "The affidavit is filed with the Civil Court clerk in the county (in place of the county clerk named in CPLR 3218(b)); the judgment is entered in the Civil Court and enforced like any Civil Court judgment.",
                  "The provisions of CPLR § 3218, relating to judgment by confession,", "shall be enforcible in the same manner and with the same effect as a judgment in an action in this court.",
                  severity="major", walk_step="8.1b", dependencies=["NY:CPLR-3218-confession"])]),
    D("NY:CCA 1501", "new_rule",
      "Says who issues an execution on an NYC Civil Court judgment (the creditor's attorney, or the clerk if the creditor has no attorney) and that Supreme Court time limits apply; changes how a self-represented owner enforces.",
      proposed=[R("NY:CCA-1501-who-issues-execution", "NY:CCA 1501", "CCA 1501", "landlord (judgment creditor)", "rule",
                  "The landlord enforces an NYC Civil Court money judgment (or an order directing payment of money) against a former tenant.",
                  "The execution, including an income execution, is issued by the landlord's attorney or, if the landlord has no attorney (an individual owner in small claims), by the clerk of the court in the county where the judgment was entered, within the time allowed in the Supreme Court (at any time before satisfaction: NY:CPLR-5230-execution).",
                  "An execution, including an income execution, upon a judgment may be issued", "shall be deemed to include an order directing the payment of money.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-5230-execution"])]),
    D("NY:CCA 1502", "new_rule",
      "To reach real property, or to enforce through county clerks and sheriffs outside the city, the landlord must obtain the Civil Court transcript and docket it with the county clerk; this decides where a moved-away tenant can be pursued.",
      proposed=[R("NY:CCA-1502-transcript", "NY:CCA 1502", "CCA 1502", "landlord (judgment creditor)", "rule",
                  "The landlord holds an NYC Civil Court judgment against a former tenant and wants to docket it with a county clerk (to create a lien on the tenant's real property or to enforce outside New York City).",
                  "On the landlord's application the clerk delivers a transcript of the judgment; docketing with the county clerk and then with other county clerks follows the CPLR (CPLR 5018). Only a docketed judgment reaches real property (NY:CCA-1505-real-property).",
                  "(a) Upon application of a judgment-creditor the clerk must deliver to him a transcript of the judgment.", "shall be governed by the CPLR.",
                  severity="minor", walk_step="8.12")]),
    D("NY:CCA 1504", "new_rule",
      "An NYC Civil Court execution reaches only the tenant's personal property, goes to a city marshal or the city sheriff, and may be levied anywhere in the city without docketing; this sets the reach of enforcement.",
      proposed=[R("NY:CCA-1504-civil-court-execution", "NY:CCA 1504", "CCA 1504", "landlord (judgment creditor) or its attorney", "rule",
                  "The landlord issues an execution out of the NYC Civil Court on a judgment against a former tenant.",
                  "It may be levied only on the tenant's personal property (bank accounts, wages by income execution, other personal property), is directed to a city marshal or the New York City sheriff (delivered to the sheriff's office in the county of levy), is signed by the clerk of the county where judgment was entered or by the creditor's attorney, bears its delivery date and the CPLR 5230 contents, and may be levied anywhere in New York City without docketing the judgment with a county clerk. Property outside the city, or real property, requires a transcript docketed with the county clerk (NY:CCA-1502-transcript, NY:CCA-1505-real-property).",
                  "An execution issued out of this court may be levied only against personal property", "it is not necessary that the judgment have been docketed with any county clerk.",
                  severity="major", walk_step="8.12", dependencies=["NY:CPLR-5230-execution"])]),
    D("NY:CCA 1505", "new_rule",
      "A Civil Court execution cannot reach real property; a transcript must be filed with the county clerk first, after which the judgment is a lien and enforceable against real property.",
      proposed=[R("NY:CCA-1505-real-property", "NY:CCA 1505", "CCA 1505", "landlord (judgment creditor)", "precondition",
                  "The landlord holds an NYC Civil Court judgment against a former tenant who owns real property.",
                  "No execution out of the Civil Court may be levied on real property. The landlord first files a transcript with the county clerk of the county where judgment was entered (NY:CCA-1502-transcript); CPLR 5018(a) then applies and the judgment is enforced against real property accordingly (subject to the homestead exemption, CPLR 5206). A Civil Court execution against personal property may still issue after transcripting.",
                  "An execution out of this court may not be levied against real property.", "pursuant and subject to § 1504 of this act, after such transcripting.",
                  severity="minor", walk_step="8.12")]),
    D("NY:CCA 1506", "new_rule",
      "Where the tenant's real property was attached before judgment, execution must issue out of Supreme Court after docketing; changes the enforcement route in that case.",
      proposed=[R("NY:CCA-1506-attached-real-property", "NY:CCA 1506", "CCA 1506", "landlord (judgment creditor)", "rule",
                  "The landlord obtained an order of attachment levied on the former tenant's real property that has not been vacated, and then an NYC Civil Court judgment.",
                  "Execution may not issue out of the Civil Court; the landlord files and dockets a transcript with the county clerk and the execution issues out of the Supreme Court.",
                  "Where the real property of the judgment-debtor has been duly attached", "the execution issued out of supreme court.",
                  severity="minor", walk_step="8.12")]),
    D("NY:CCA 1508", "new_rule",
      "Lets the NYC Civil Court grant injunctions, restraining notices and receivers in an enforcement proceeding within CPLR 5221, with statewide service; an enforcement option against a tenant who moved away.",
      proposed=[R("NY:CCA-1508-enforcement-powers", "NY:CCA 1508", "CCA 1508", "landlord (judgment creditor)", "permission",
                  "The landlord enforces an NYC Civil Court money judgment in an enforcement proceeding of which the Civil Court has jurisdiction under CPLR 5221.",
                  "The court may issue an injunction, restraining order or restraining notice and appoint a receiver in furtherance of enforcing the money judgment; its papers may be served anywhere, regardless of city or state lines, as in the Supreme Court, and a receiver's powers extend throughout the state.",
                  "(a) An injunction or restraining order or notice may issue out of or by", "shall extend throughout the state.",
                  severity="minor", walk_step="8.12")]),
    D("NY:CCA 1804", "new_rule",
      "In small claims an itemized paid invoice, or two itemized estimates, is prima facie proof of the reasonable value and necessity of repairs; this sets how the landlord proves a damage charge (or the tenant disproves it) and what the settlement file must hold.",
      proposed=[R("NY:CCA-1804-small-claims-proof", "NY:CCA 1804", "CCA 1804", "landlord; former tenant", "rule",
                  "A claim between the landlord and a former tenant (a tenant's deposit claim, or an individual owner's damage claim) is heard in the NYC small claims part.",
                  "The court decides to do substantial justice under the substantive law and is not bound by rules of practice, pleading or evidence, except privilege and the dead-man rule. An itemized bill or invoice, receipted or marked paid, or two itemized estimates for services or repairs, are admissible and are prima facie evidence of the reasonable value and necessity of the work; the landlord keeps the burden of proving the amount kept was reasonable (NY:GOL-7-108(1-a)(f)). Disclosure is available only by court order on proper circumstances. Where the claim arises from the defendant's business, the judge identifies its licensing authority and business associations. Operator step: for each damage charge keep the itemized paid invoice, or two itemized estimates where the work is not yet done (NY:CASE-Toporek-estimate).",
                  "The court shall conduct hearings upon small claims in such manner", "in case of conflict, the provisions of this article shall control.",
                  severity="major", walk_step="7.4", dependencies=["NY:GOL-7-108(1-a)(f)", "NY:CASE-Toporek-estimate"])]),
    D("NY:CCA 1805", "new_rule",
      "Small-claims remedies: conditional judgments, pre-judgment examination and restraint of the defendant, transfer, and a bar on counterclaims beyond the small-claims limit; changes whether a landlord sued for the deposit can counterclaim the balance there.",
      proposed=[R("NY:CCA-1805-small-claims-remedies", "NY:CCA 1805", "CCA 1805(a)-(c), (e)", "landlord; former tenant", "rule",
                  "A small claim between the landlord and a former tenant is decided in the NYC small claims part.",
                  "The court directs judgment on its findings and may condition its entry on just terms; before judgment it may order the defendant examined and restrain it as if a post-judgment restraining notice had been served (CPLR 5229). It may transfer the claim to another part. A counterclaim is allowed only if it is within the small-claims monetary limit ($10,000); a landlord sued for the deposit whose balance claim exceeds the limit brings that claim in a court of competent jurisdiction instead. If the defendant appears to act fraudulently or illegally in a licensed business (for example a licensed broker-manager), the court advises the licensing authority or tells the claimant to, and keeps the case.",
                  "(a) Upon determination of a small claim,", "but shall retain jurisdiction over the small claim.",
                  severity="major", walk_step="7.6", dependencies=["NY:CCA-1801-tenant-claim"])]),
    D("NY:CCA 1806", "new_rule",
      "A landlord sued in small claims may move the case to a jury part by demand, fee, affidavit and a $50 undertaking; the claimant waives a jury and may get up to $25 costs after transfer.",
      proposed=[R("NY:CCA-1806-small-claims-jury", "NY:CCA 1806", "CCA 1806", "landlord (defendant); former tenant (claimant)", "rule",
                  "A former tenant brings a small claim against the landlord (or an individual owner brings one against the tenant).",
                  "The claimant waives a jury unless the case is removed to a regular part. The defendant may, before the day it must appear, file a jury demand with an affidavit specifying the issues of fact and stating good faith, the jury fee, and a $50 undertaking (or $50 cash) securing costs payable within 30 days of entry; the case is then transferred and may require pleadings. If a transferred claim succeeds, the court may award the claimant costs up to $25.",
                  "A person commencing an action upon a small claim under this article", "the court may award costs up to twenty-five dollars to the plaintiff if he prevails.",
                  severity="minor", walk_step="7.6")]),
    D("NY:CCA 1806-A", "new_rule",
      "The commercial-claims counterpart: the former tenant sued in the commercial claims part may demand a jury with fee, affidavit and $50 undertaking; the owner may get up to $25 costs after transfer.",
      proposed=[R("NY:CCA-1806-A-commercial-claims-jury", "NY:CCA 1806-A", "CCA 1806-A", "entity owner (claimant); former tenant (defendant)", "rule",
                  "An entity owner brings a commercial claim against a former tenant.",
                  "The owner waives a jury unless the case is removed to a regular part. The tenant may, before the day it must appear, file a jury demand with an affidavit of the issues and good faith, the jury fee and a $50 undertaking (or $50 cash); the case is transferred and may require pleadings. If the owner prevails on a transferred claim, the court may award it costs up to $25.",
                  "A claimant commencing an action upon a commercial claim under this article", "the court may award costs up to twenty-five dollars to the claimant if the claimant prevails.",
                  severity="minor", walk_step="8.10")]),
    D("NY:CCA 1807", "no_decision",
      "Limits appeal from a small-claims judgment to substantial-justice review; appellate practice, which changes no settlement or collection step."),
    D("NY:CCA 1807-A", "new_rule",
      "In the commercial claims part the clerk mails notice of a default judgment and the defaulting tenant may seek vacatur in writing with a reasonable excuse under CPLR 5015; changes whether a default judgment on the balance holds. The appeal limit in (a) is appellate practice.",
      proposed=[R("NY:CCA-1807-A-commercial-default", "NY:CCA 1807-A", "CCA 1807-A(b), (c)", "entity owner (claimant); former tenant", "rule",
                  "An entity owner obtains a default judgment against a former tenant in the commercial claims part.",
                  "The clerk mails notice of the default judgment by first-class mail to both parties, telling the tenant of its obligation to pay, that non-payment may lead to garnishment and seizure, and that with a reasonable excuse it may apply in writing to vacate the default. Proceedings on default follow CPLR 5015 (NY:CPLR-5015-relief-from-judgment).",
                  "(b) The clerk shall mail notice of the default judgment", "section five thousand fifteen of the civil practice law and rules.",
                  severity="major", walk_step="8.9", dependencies=["NY:CPLR-5015-relief-from-judgment"])]),
    D("NY:CCA 1808", "new_rule",
      "Fixes what a small-claims judgment between landlord and tenant does to later suits: no issue preclusion, claim preclusion as usual, and a later judgment on the same facts reduced by the small-claims award. Decides whether the loser can sue again and what a split claim costs.",
      proposed=[R("NY:CCA-1808-preclusion", "NY:CCA 1808", "CCA 1808", "landlord; former tenant", "rule",
                  "A small-claims judgment was entered between the landlord and a former tenant (for example on the tenant's deposit claim, or an individual owner's damage claim), and a party later sues in another action or court over the same tenancy.",
                  "Branch (a) issue preclusion: no fact found in the small-claims judgment binds either party in another action. Branch (b) claim preclusion: the small-claims judgment bars a later claim by the same claimant against the same adversary arising from the same transaction or series of transactions (the tenancy's account), so an owner that sues in small claims for part of the balance cannot later sue for the rest, and a claimant that lost cannot sue again on the same claim (Simmons v Trans Express Inc., 37 NY3d 107 [2021], answering a certified question). Branch (c) set-off: a later judgment in another action involving the same facts, issues and parties is reduced by the small-claims award. Branch (d) the defendant's own claim: a landlord sued in small claims for the deposit that did not counterclaim is not barred from suing later for its balance, because New York has no compulsory counterclaim (CPLR 3019), unless the later claim would impair the rights the small-claims judgment established; the tenant's facts found there do not bind it.",
                  "A judgment obtained under this article shall not be deemed an adjudication", "shall be reduced by the amount of a judgment awarded under this article.",
                  severity="critical", walk_step="7.6", determinacy="MIXED", judgment_terms=["same transaction or series of transactions", "would impair rights established by the prior judgment"],
                  dependencies=["NY:CCA-1801-tenant-claim", "NY:CCA-1809(1)"])]),
    D("NY:CCA 1808-A", "new_rule",
      "The commercial-claims counterpart of 1808: an entity owner's commercial-claims judgment has no issue preclusion, carries claim preclusion, and reduces a later judgment on the same facts.",
      proposed=[R("NY:CCA-1808-A-preclusion", "NY:CCA 1808-A", "CCA 1808-A", "entity owner; former tenant", "rule",
                  "A commercial-claims judgment was entered between an entity owner and a former tenant, and a party later sues over the same tenancy.",
                  "No fact found there binds either party in another action; the judgment bars a later claim by the same claimant against the same tenant arising from the same transaction (the tenancy's account), so the owner cannot split its balance between the commercial claims part and a later action (the Court of Appeals' reading of the identical 1808 text in Simmons v Trans Express Inc., 37 NY3d 107 [2021]); a later judgment involving the same facts, issues and parties is reduced by the commercial-claims award. A tenant that did not counterclaim for its deposit may sue for it later unless that would impair the rights the judgment established.",
                  "A judgment obtained under this article shall not be deemed an adjudication", "shall be reduced by the amount of a judgment awarded under this article.",
                  severity="critical", walk_step="8.10", determinacy="MIXED", judgment_terms=["same transaction or series of transactions", "would impair rights established by the prior judgment"],
                  dependencies=["NY:CCA-1801-A(a)-eligibility"])]),
    D("NY:CCA 1810", "new_rule",
      "The clerk and court may deny the small claims part to a claimant re-filing a claim already adjudicated or filed to harass; changes whether a losing party can re-file there.",
      proposed=[R("NY:CCA-1810-harassing-refiling", "NY:CCA 1810", "CCA 1810", "former tenant or individual owner (claimant)", "limit",
                  "A claimant files a small claim that it previously brought and lost after a hearing, or that the clerk finds is brought to oppress or harass.",
                  "The clerk may require the claimant to apply to the court for leave; if the court finds the claim already adjudicated, or brought solely to oppress or harass and not under color of right, it may deny use of the small claims part for that claim.",
                  "If the clerk shall find that the procedures of the small claims part", "denying the claimant the use of the small claims part to prosecute the claim.",
                  severity="minor", walk_step="7.6", determinacy="MIXED", judgment_terms=["for purposes of oppression or harassment", "under color of right"])]),
    D("NY:CCA 1810-A", "new_rule",
      "The commercial-claims counterpart of 1810: an owner re-filing an adjudicated or harassing commercial claim may be denied the part.",
      proposed=[R("NY:CCA-1810-A-harassing-refiling", "NY:CCA 1810-A", "CCA 1810-A", "entity owner (claimant)", "limit",
                  "An entity owner files a commercial claim against a former tenant that it previously brought and lost after a hearing, or that the clerk finds is brought to oppress or harass.",
                  "The clerk may require the owner to apply for leave; if the court finds the claim already adjudicated, or brought solely to oppress or harass and not under color of right, it may deny use of the commercial claims part for that claim.",
                  "If the clerk shall find that the procedures of the commercial claims part", "denying the claimant the use of the commercial claims part to prosecute the claim.",
                  severity="minor", walk_step="8.10", determinacy="MIXED", judgment_terms=["for purposes of oppression or harassment", "under color of right"])]),
    D("NY:CCA 1812-A", "new_rule",
      "An unpaid commercial-claims judgment lets the owner get information subpoenas from the clerk at nominal cost with help preparing them; a cost and step in enforcing against the former tenant.",
      proposed=[R("NY:CCA-1812-A-information-subpoenas", "NY:CCA 1812-A", "CCA 1812-A", "entity owner (judgment creditor)", "permission",
                  "An entity owner's commercial-claims judgment against a former tenant remains unsatisfied.",
                  "On request the commercial claims clerk issues information subpoenas (CPLR 5224) at nominal cost and helps the owner prepare and use them.",
                  "Where a judgment has been entered in a commercial claims part and remains unsatisfied,", "provide the creditor with assistance on their preparation and use.",
                  severity="minor", walk_step="8.12")]),
    D("NY:CCA 1813", "new_rule",
      "A landlord business sued in small claims must pay the judgment in its true name or any business name; one entered under another name and unpaid 35 days after notice lets the tenant sue for the judgment, costs, attorney's fees and $100, and a licensed business risks its licence.",
      proposed=[R("NY:CCA-1813-duty-to-pay", "NY:CCA 1813", "CCA 1813", "landlord or managing agent (small-claims judgment debtor)", "obligation",
                  "A former tenant obtains a small-claims judgment against the landlord, managing agent or other business on a claim arising from its business activities (the deposit, rent paid).",
                  "It must pay the judgment, whether entered in its true name (legal name, or the name under which it is licensed, registered or incorporated) or in any name in which it conducts business (signs, advertising, contracts, invoices, receipts, checks). If entered in a name other than its true name and unpaid 35 days after it receives notice of entry, the tenant may sue in small claims or any court, regardless of the court's monetary limit, for the judgment, costs, reasonable attorney's fees and $100. If the business is licensed (for example a real estate broker managing the building) and the judgment relates to licensed activity, is not stayed or appealed, and is unpaid 35 days after notice, the licensing authority considers a deliberate or patterned failure to pay in revoking, suspending, conditioning or refusing the licence. Treble damages for repeated unpaid judgments: NY:CCA-1812-treble.",
                  "(a) Any person, partnership, firm or corporation which is sued in a small claims court", "Nothing herein shall be construed to preempt an authority's existing policy if it is more restrictive.",
                  severity="major", walk_step="7.6", dependencies=["NY:CCA-1812-treble", "NY:RPL-441-c-licence-discipline"])]),
    D("NY:CCA 1813-A", "new_rule",
      "The commercial-claims counterpart of 1813: a business judgment debtor in the commercial claims part must pay in any name it uses; a tenant with a counterclaim judgment may sue for the judgment, costs, fees and $100 if unpaid 35 days.",
      proposed=[R("NY:CCA-1813-A-duty-to-pay", "NY:CCA 1813-A", "CCA 1813-A", "entity owner (judgment debtor on a counterclaim)", "obligation",
                  "A former tenant obtains a judgment in the commercial claims part (for example on a deposit counterclaim) against the owner or another business on a claim arising from its business activities.",
                  "It must pay the judgment in its true name or any name in which it conducts business. If entered in another name and unpaid 35 days after notice of entry, the tenant may sue in any competent court, regardless of monetary limit, for the judgment, costs, reasonable attorney's fees and $100; a licensed business's deliberate or patterned non-payment of a judgment on licensed activity counts against its licence.",
                  "(a) Any person, partnership, firm or corporation which is sued in a commercial claims part", "Nothing herein shall be construed to preempt an authority's existing policy if it is more restrictive.",
                  severity="major", walk_step="7.6")]),
    D("NY:CCA 1814", "new_rule",
      "A tenant may sue the landlord in small claims under any business name it uses, and a landlord seeking to vacate a small-claims judgment must disclose its true and business names.",
      proposed=[R("NY:CCA-1814-defendant-name", "NY:CCA 1814", "CCA 1814", "landlord or managing agent (defendant)", "rule",
                  "A former tenant sues the landlord or managing agent in small claims without knowing its true legal name.",
                  "The tenant may name it by any name it uses in conducting business; the clerk amends the papers when the true name becomes known before the hearing, and the judge determines the true name at the hearing. A landlord that moves under CPLR 5015 to vacate the judgment must disclose its true name and every name it does or did business under at the time of the tenancy.",
                  "(a) A party who is ignorant, in whole or in part, of the true name", "All subsequent proceedings and papers shall be amended to conform to such disclosure.",
                  severity="minor", walk_step="7.6")]),
    D("NY:CCA 1814-A", "new_rule",
      "The commercial-claims counterpart of 1814: a business party may be named by its business name, the judge fixes the true name, and a judgment debtor seeking vacatur must disclose its names.",
      proposed=[R("NY:CCA-1814-A-defendant-name", "NY:CCA 1814-A", "CCA 1814-A", "entity owner; former tenant", "rule",
                  "A party to a commercial claim over the tenancy is a business whose true name is unknown to the other side.",
                  "It may be named by any name it uses in business; the clerk amends the papers when the true name is known, the judge determines the true name at the hearing, and a party seeking CPLR 5015 relief from the judgment discloses its true and business names.",
                  "(a) A party who is ignorant, in whole or in part, of the true name", "All subsequent proceedings and papers shall be amended to conform to such disclosure.",
                  severity="minor", walk_step="8.10")]),
    D("NY:CCA 1815", "partial",
      "The appearance rule states who may appear for owners and bars Handoff; 1815 adds that a disabled party (a tenant or an individual owner) may, with leave, appear through an unpaid relative.",
      atoms=["NY:CPLR-321-JUD-495-appearance"],
      proposed=[R("NY:CCA-1815-relative-representative", "NY:CCA 1815", "CCA 1815 (first of two sections so numbered)", "individual owner; former tenant", "permission",
                  "A party to an NYC Civil Court case over the tenancy is a natural person who, because of age, mental or physical capacity or other disability, asks that a relative appear for it.",
                  "The court may permit a relative by blood or marriage to appear for that party in the interests of justice. The representative may not charge a fee or accept any remuneration, so Handoff or a paid manager can never appear this way.",
                  "The court may permit, upon the request of a party,", "be allowed to accept any form of remuneration for such services.",
                  severity="minor", walk_step="8.10", amends="NY:CPLR-321-JUD-495-appearance", dependencies=["NY:CPLR-321-JUD-495-appearance"])]),
    D("NY:CCA 1900", "new_rule",
      "Applies CPLR article 85 security for costs in NYC Civil Court with a $200 minimum undertaking; a plaintiff that is not a New York resident or domestic or licensed corporation (a tenant who moved away, a foreign owner) can be made to post security.",
      proposed=[R("NY:CCA-1900-security-for-costs", "NY:CCA 1900", "CCA 1900; CPLR 8501-8503", "plaintiff (landlord or former tenant)", "obligation",
                  "An action between the landlord and a former tenant is in NYC Civil Court and the defendant moves for security for costs (grounds: NY:CPLR-8501-security-for-costs).",
                  "CPLR article 85 applies, except that the minimum undertaking is $200 rather than the CPLR 8503 amount.",
                  "Article 85 of the CPLR, entitled \"security for costs\", shall apply in", "shall be $200 rather than the amount therein provided.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-8501-security-for-costs"])]),
    D("NY:CCA 1901", "new_rule",
      "Fixes the costs a prevailing party recovers in an NYC Civil Court action (not small claims or summary proceedings): $50/$100/$150 stages, or $20/$35/$60 when the money judgment is $6,000 or less.",
      proposed=[R("NY:CCA-1901-costs-amount", "NY:CCA 1901", "CCA 1901", "prevailing party (landlord or former tenant)", "rule",
                  "An action between the landlord and a former tenant ends in judgment in the NYC Civil Court regular or commercial claims part (not small claims, not a summary proceeding).",
                  "Branch (a): money judgment of $6,000 or less: costs are $20 for proceedings before a notice of trial, plus $35 after notice of trial and before trial, plus $60 for each trial, inquest or assessment of damages. Branch (b): any other action: $50, plus $100, plus $150 on the same stages. Disbursements are added (NY:CCA-1908-disbursements). " + COSTS_NOTE,
                  "(a) Ordinary costs.", "shall not apply to costs in a summary proceeding or in a small claims actions.",
                  severity="major", walk_step="8.10", dependencies=["NY:RPL-234-a", "NY:CPLR-8101-costs-to-prevailing-party"])]),
    D("NY:CCA 1903", "new_rule",
      "Makes the CPLR rules on who gets costs (8101 prevailing party, 8103 split issues, 8104 consolidated actions, 8105 multiple parties, 8106 motions) apply in NYC Civil Court.",
      proposed=[R("NY:CCA-1903-cplr-costs-apply", "NY:CCA 1903", "CCA 1903", "prevailing party", "rule",
                  "Costs are decided in an NYC Civil Court action or proceeding between the landlord and a former tenant.",
                  "CPLR 8101 (costs to the party in whose favor judgment is entered), 8103 (separate issues), 8104 (consolidated, severed or removed actions), 8105 (several plaintiffs or defendants) and 8106 (motions) apply.",
                  "The provisions of CPLR §§ 8101,", "shall apply in actions and proceedings in this court.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-8101-costs-to-prevailing-party"])]),
    D("NY:CCA 1904", "new_rule",
      "Adds to Civil Court costs the CPLR 8302/8303(a) allowances and the discretionary allowance on an enforcement motion (8303(b)); changes what a judgment creditor recovers for enforcement motions.",
      proposed=[R("NY:CCA-1904-additional-allowances", "NY:CCA 1904", "CCA 1904", "prevailing party; judgment creditor", "rule",
                  "Costs are computed in an NYC Civil Court action between the landlord and a former tenant, or the landlord moves to enforce a judgment.",
                  "Costs on appeal and those under CCA 1102 are added to ordinary costs. The CPLR 8302 allowance (certain real property actions) and the CPLR 8303(a) discretionary allowance apply and are added on top of ordinary costs. On a motion relating to enforcement of a judgment, the court may award costs under CPLR 8303(b) (NY:CPLR-8303-additional-allowance).",
                  "(a) Certain costs added.", "shall apply in this court without reference to the foregoing subdivisions of this section.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-8303-additional-allowance"])]),
    D("NY:CCA 1905", "new_rule",
      "A former tenant who wins on a bankruptcy-discharge defense recovers no costs; changes the cost exposure of a landlord that sues a discharged tenant.",
      proposed=[R("NY:CCA-1905-no-costs-bankruptcy-defense", "NY:CCA 1905", "CCA 1905", "former tenant (defendant); landlord", "rule",
                  "The landlord sues a former tenant in NYC Civil Court and the tenant wins on the defense of bankruptcy (discharge).",
                  "The tenant is not entitled to costs. The landlord's suit on a discharged balance still violates the discharge injunction (US:11USC524(a)(2)), which carries its own remedies.",
                  "Where the defendant recovers judgment upon the defense of bankruptcy,", "he shall not be entitled to costs.",
                  severity="minor", walk_step="8.8", dependencies=["US:11USC524(a)(2)"])]),
    D("NY:CCA 1906", "new_rule",
      "The court may impose up to $50 costs on a motion, amendment or trial adjournment; a cost the landlord or tenant may owe or recover in a Civil Court case.",
      proposed=[R("NY:CCA-1906-discretionary-costs", "NY:CCA 1906", "CCA 1906", "landlord; former tenant", "rule",
                  "In an NYC Civil Court case between the landlord and a former tenant, the court grants or denies a motion, allows a pleading amendment or adjourns a trial.",
                  "The court may impose costs of up to $50 in its discretion.",
                  "The court may in its discretion impose costs not exceeding fifty dollars", "(c) Upon adjournment of a trial.",
                  severity="minor", walk_step="8.10")]),
    D("NY:CCA 1907", "new_rule",
      "The clerk taxes costs and clerk and execution fees into the judgment; other disbursements need two days' notice and an affidavit and must have been necessarily incurred; this is how the landlord's suit costs enter a judgment.",
      proposed=[R("NY:CCA-1907-taxation", "NY:CCA 1907", "CCA 1907", "prevailing party (landlord or former tenant)", "obligation",
                  "Judgment is rendered in an NYC Civil Court action between the landlord and a former tenant.",
                  "The clerk taxes the costs, the fees paid to the clerk and the fee for issuing an execution to the sheriff or marshal, and inserts them in the judgment; a transcript includes the prospective county clerk and sheriff fees. Other taxable disbursements are taxed on two days' notice to the adverse party, verified by affidavit, and allowed only if necessarily incurred or performed.",
                  "Costs, together with fees paid to the clerk and the fee for issuing execution", "or that the services for which they are charged were necessarily performed.",
                  severity="minor", walk_step="8.10")]),
    D("NY:CCA 1908", "new_rule",
      "Lists the disbursements a prevailing party (including a self-represented one) recovers in NYC Civil Court: court, sheriff and marshal fees, private process-server cost, witness fees, certified copies, transcript and execution fees.",
      proposed=[R("NY:CCA-1908-disbursements", "NY:CCA 1908", "CCA 1908", "prevailing party (landlord or former tenant)", "rule",
                  "A party is awarded costs, or prevails having appeared in person, in an NYC Civil Court case over the tenancy.",
                  "Unless a law provides otherwise, it recovers its necessary disbursements: all fees paid to the clerk, sheriff or a marshal, including jury fees, and the reasonable expense of service by a private process server; witnesses' legal fees; fees for certified copies of recorded or filed papers necessarily used at trial; commissioners' reasonable compensation for depositions; prospective charges for filing a transcript and the sheriff's fees for an execution; and other expenses taxable under CPLR 8301. Attorney's fees are not disbursements. " + COSTS_NOTE,
                  "Except where the contrary is specifically provided by law,", "as are taxable pursuant to the provisions of CPLR § 8301.",
                  severity="major", walk_step="8.10", dependencies=["NY:RPL-234-a"])]),
    D("NY:CCA 1908-A", "new_rule",
      "If the tenant does not return a CPLR 312-a mail-service acknowledgment within 30 days, the landlord's cost of serving another way is taxed against the tenant; changes the cost of the mail-service route.",
      proposed=[R("NY:CCA-1908-A-unacknowledged-mail-service", "NY:CCA 1908-A", "CCA 1908-a", "landlord (plaintiff)", "rule",
                  "The landlord serves a former tenant by mail under CPLR 312-a in NYC Civil Court and the signed acknowledgment is not returned within 30 days after the tenant receives the papers.",
                  "The reasonable expense of serving by another method is taxed by the court as a disbursement payable to the landlord if the landlord is awarded costs.",
                  "In any action where service of process is made by mail pursuant to CPLR 312-a,", "if that party is awarded costs in the action or proceeding.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-312-a-mail-service"])]),
    D("NY:CCA 1909", "new_rule",
      "The clerk's taxation of costs can be reviewed only on motion within ten days; otherwise it cannot be challenged on appeal. A deadline for contesting the costs in a judgment.",
      proposed=[R("NY:CCA-1909-review-of-taxation", "NY:CCA 1909", "CCA 1909", "landlord; former tenant", "rule",
                  "A party disputes the costs or disbursements the clerk taxed into an NYC Civil Court judgment over the tenancy.",
                  "It moves for review within ten days on two days' notice; the court strikes items wrongly included or adds items wrongly omitted and credits a disallowed sum against any execution. Without that motion the taxation cannot be questioned on appeal.",
                  "Within ten days the clerk's taxation may be reviewed", "the clerk's taxation cannot be questioned on appeal.",
                  severity="minor", walk_step="8.10")]),
    D("NY:CCA 1910", "no_decision",
      "Costs on appeal from the Civil Court; appellate practice, outside the settlement and collection chain."),
    D("NY:CCA 1911", "new_rule",
      "Sets the NYC Civil Court fees the landlord pays to sue and enforce (summons or first paper $45, jury $70, satisfaction $6, notice of petition $45) and that the $95 consumer-credit surcharge does not apply to a lease balance; an input to the pursue-or-write-off cost and a recoverable disbursement.",
      proposed=[R("NY:CCA-1911-clerk-fees", "NY:CCA 1911", "CCA 1911", "landlord; former tenant", "rule",
                  "A party files in NYC Civil Court in a case over the tenancy.",
                  "Fees, prepaid: issuing a summons or attachment, or filing the summons with proof of service or the first paper in the county, $45 (once); notice of trial $40; entry of judgment on confession $45 unless a summons fee was paid; notice of appeal $30; satisfaction of judgment or certificate $6; jury demand $70, paid by the party demanding; exemplification $15; certified copy $6; notice of petition in a summary proceeding $45; other matters, the Supreme Court fee (not the CPLR 8020(a) motion fee or 8020(d) settlement or discontinuance fee). The added $95 fee on filing the first paper, or on filing a judgment, in an action arising from a consumer credit transaction (CPLR 105(f)) does not apply to a lease balance (NY:ADJ-lease-balance-not-consumer-credit). Fees paid are recoverable as disbursements only through the judgment (NY:CCA-1908-disbursements).",
                  "There shall be paid to the clerk the following sums as court fees in an action:", "All fees shall be prepaid before the service shall be performed.",
                  severity="major", walk_step="8.10", dependencies=["NY:ADJ-lease-balance-not-consumer-credit"])]),
    D("NY:CCA 1913", "no_decision",
      "Sets Civil Court witness fees by reference to Supreme Court witness fees (CPLR 8001, decided there); their recovery is the CCA 1908(b) disbursement. It adds no step or amount of its own."),
]
write(rows)
