from q2_lib import *

rows = [
    D("NY:CPLR 3005", "no_decision",
      "Removes the fact/law distinction when a court grants relief for mistake; whether a sum a tenant paid is refundable or credited is decided by the charge rules themselves (for example NY:RPL-238-a(1)-no-move-in-fees, NY:ADJ-no-fee-retention), so it adds no step to the account."),
    D("NY:CPLR 3012-B", "no_decision",
      "Certificate of merit in residential mortgage foreclosure of a home loan; not a landlord-tenant claim."),
    D("NY:CPLR 3017", "no_decision",
      "Pleading form for the demand for relief; the limit of a default judgment to the amount demanded is CPLR 3215(b). It adds no step in the chain."),
    D("NY:CPLR 3018", "new_rule",
      "Defenses such as the statute of limitations, payment, release, bankruptcy discharge and res judicata must be pleaded or are lost; changes what the landlord (defending a deposit suit) or the tenant (defending a balance suit) must raise.",
      proposed=[R("NY:CPLR-3018-affirmative-defenses", "NY:CPLR 3018", "CPLR 3018", "landlord; former tenant (answering party)", "obligation",
                  "A party answers a claim over the tenancy (the landlord answering a deposit suit; the tenant answering a balance suit).",
                  "It denies statements it knows or believes untrue and states lack of knowledge where it lacks it; other statements are deemed admitted. It pleads every matter that would otherwise surprise the other side, including arbitration and award, collateral estoppel, discharge in bankruptcy, illegality, fraud, infancy or other disability, payment, release, res judicata, statute of frauds and statute of limitations; a defense not pleaded (or raised by timely motion) is waived. Operator step: when the landlord is sued, put the limitations defense, payment, any signed release and the small-claims preclusion (NY:CCA-1808-preclusion) in the answer.",
                  "(a) Denials. A party shall deny those statements known or believed by him to be untrue.", "The application of this subdivision shall not be confined to the instances enumerated.",
                  severity="minor", walk_step="7.6", dependencies=["NY:CCA-1808-preclusion"])]),
    D("NY:CPLR 3020", "new_rule",
      "Says who may verify the landlord's pleading: the owner, an officer of a domestic corporation, or an agent (managing agent) where the owner is a foreign entity or out of county or the facts are within the agent's personal knowledge; decides whether the manager can sign the verification.",
      proposed=[R("NY:CPLR-3020-verification", "NY:CPLR 3020", "CPLR 3020(a), (d)", "landlord, its officer or managing agent", "rule",
                  "The landlord's complaint against a former tenant (or its answer to a deposit suit) is verified, for example so it can serve as proof on a default.",
                  "A verification is a statement affirmed under penalty of perjury that the pleading is true to the deponent's knowledge except matters on information and belief. It is made by the party; for a domestic corporation, by an officer. It may be made by an agent (the managing agent) or the attorney where the party is a foreign corporation, is not in the county where the attorney has its office, where the claim is founded on a written instrument for the payment of money only in the agent's or attorney's possession, or where all material allegations are within the agent's or attorney's personal knowledge. Once a pleading is verified, later pleadings must be verified too. A defense not involving the merits must be verified.",
                  "(a) Generally. A verification is a statement,", "the verification may be made by such agent or attorney.",
                  severity="minor", walk_step="8.9")]),
    D("NY:CPLR 3022", "no_decision",
      "Treats a defectively verified pleading as unverified and lets the opponent reject it on prompt notice; in-suit pleading mechanics with no settlement consequence."),
    D("NY:CPLR 3025", "no_decision",
      "Amending pleadings in a pending action; in-suit mechanics (relation back of an amended claim for limitations is stated at CPLR 203(f))."),
    D("NY:CPLR 3026", "no_decision",
      "Pleadings are construed liberally; a canon for the court that adds no step or amount."),
    D("NY:CPLR 303", "new_rule",
      "A party beyond New York's jurisdiction who sues here (a moved-away tenant suing for the deposit) designates its attorney, or the clerk, as agent to be served in the landlord's separate action on a claim that could have been a counterclaim; changes how the landlord can reach that tenant.",
      proposed=[R("NY:CPLR-303-plaintiff-designates-agent", "NY:CPLR 303", "CPLR 303", "landlord", "permission",
                  "A former tenant who is not otherwise subject to personal jurisdiction in New York sues the landlord in a New York court (for example over the deposit), and the landlord wants to sue it separately for the balance.",
                  "While the tenant's action is pending, its attorney in that action (or the clerk if it has none) is its agent for service of a summons under CPLR 308 in the landlord's separate action, if that action could have been a counterclaim in the Supreme Court.",
                  "The commencement of an action in the state by a person not subject to personal jurisdiction", "would have been permitted as a counterclaim had the action been brought in the supreme court.",
                  severity="minor", walk_step="8.10")]),
    D("NY:CPLR 3031", "no_decision",
      "Voluntary simplified procedure by a statement signed by all parties; a litigation-format option that changes no amount, deadline or precondition."),
    D("NY:CPLR 3033", "no_decision",
      "Enforces written contracts to use the simplified procedure; it concerns the forum format of a dispute both sides agreed to and changes no amount, deadline or precondition of the settlement."),
    D("NY:CPLR 3036", "no_decision",
      "How the court runs a simplified-procedure case (evidence rules relaxed, experts, default for failure to serve a statement); in-suit mechanics of a voluntary format."),
    D("NY:CPLR 3037", "no_decision",
      "Appeals in simplified-procedure cases; appellate practice."),
    D("NY:CPLR 306", "new_rule",
      "Sets what the proof of service must show (papers, person, date, time, address, manner, a physical description of the person served, and the prior attempts for nail-and-mail); a defective affidavit exposes a default judgment to vacatur.",
      proposed=[R("NY:CPLR-306-proof-of-service", "NY:CPLR 306", "CPLR 306", "landlord (plaintiff) and its process server", "obligation",
                  "The landlord serves a summons on a former tenant and files proof of service.",
                  "The proof states the papers served, the person served, the date, time, address (or place) and manner of service, and facts showing an authorized person served in an authorized manner. For delivery to an individual it describes the person (gender, race, hair color, approximate age, weight, height, other features). For affix-and-mail service it states the dates, addresses and times of the earlier attempts at personal and substituted service. It is a sheriff's or marshal's certificate, a server's affidavit, or the signed CPLR 312-a acknowledgment; a written admission of service by the tenant also suffices.",
                  "(a) Generally. Proof of service shall specify the papers served,", "A writing admitting service by the person to be served is adequate proof of service.",
                  severity="minor", walk_step="8.9", dependencies=["NY:CPLR-308-natural-person"])]),
    D("NY:CPLR 306-B", "new_rule",
      "In Supreme Court the summons must be served within 120 days after filing or the action is dismissed without prejudice unless extended; a deadline whose miss can end a claim filed near the limitations date.",
      proposed=[R("NY:CPLR-306-b-120-days", "NY:CPLR 306-B", "CPLR 306-b", "landlord (plaintiff) or former tenant (plaintiff)", "obligation",
                  "A party has commenced an action over the tenancy by filing in the Supreme Court (or another court applying CPLR 306-b).",
                  "It must serve the summons and complaint (or summons with notice) within 120 days after commencement. If it does not, the court on motion dismisses without prejudice as to that defendant, or extends the time for good cause or in the interest of justice. After the limitations period has run, a dismissal leaves only the CPLR 205(a) six-month recommencement where it applies (NY:CPLR-204-208-tolling). NYC Civil Court counterpart: NY:CCA-411-120-days.",
                  "Service of the summons and complaint, summons with notice,", "extend the time for service.",
                  severity="major", walk_step="8.10", dependencies=["NY:CPLR-204-208-tolling"])]),
    D("NY:CPLR 308", "new_rule",
      "The methods of serving a natural-person former tenant (personal delivery; delivery at its actual dwelling or business plus mailing; affix-and-mail after due diligence; court-directed); a former tenant's vacated unit is no longer its dwelling, so service there is void. Decides whether any judgment on the balance is valid.",
      proposed=[R("NY:CPLR-308-natural-person", "NY:CPLR 308", "CPLR 308", "landlord (plaintiff) and its process server", "obligation",
                  "The landlord serves a summons on a former tenant who is a natural person (in Supreme Court, or in Civil Court by CCA 403).",
                  "Service is made by: (1) delivering the summons to the tenant within the state; (2) delivering it within the state to a person of suitable age and discretion at the tenant's actual place of business, dwelling place or usual place of abode, and within 20 days mailing it to the tenant's last known residence, or first-class to its actual place of business in a 'personal and confidential' envelope not showing it is from an attorney or concerns an action, with proof filed within 20 days of the later act and service complete 10 days after filing; (3) delivering it to an agent designated under CPLR 318; (4) only where (1) and (2) cannot be made with due diligence, affixing it to the door of the tenant's actual place of business, dwelling place or usual place of abode within the state and mailing as in (2), with the same filing and completion rules; or (5) as the court directs on motion without notice where (1), (2) and (4) are impracticable (for example email or service on a relative when the tenant cannot be found). The vacated unit is no longer the former tenant's dwelling place or usual place of abode once it moved out, so substituted or affix-and-mail service there does not give jurisdiction and a default judgment on it is void; the landlord first locates the tenant's current residence or business, or obtains a court-directed method.",
                  "Personal service upon a natural person shall be made by any of the following methods:", "has held out as its place of business.",
                  severity="critical", walk_step="8.9", determinacy="MIXED", judgment_terms=["due diligence", "dwelling place or usual place of abode", "impracticable"],
                  dependencies=["NY:CCA-403-service-within-city", "NY:CPLR-306-proof-of-service"])]),
    D("NY:CPLR 309", "new_rule",
      "How to serve a former tenant who is an infant, an adjudicated incompetent or a conservatee (the parent, guardian, committee or conservator, and the person too); service otherwise gives no jurisdiction.",
      proposed=[R("NY:CPLR-309-infant-incompetent", "NY:CPLR 309", "CPLR 309", "landlord (plaintiff)", "obligation",
                  "The landlord sues a former tenant (or occupant liable under the lease) who is an infant, a person judicially declared incompetent with a committee, or a conservatee.",
                  "Infant: serve personally within the state a parent, guardian or person with legal custody (or an adult spouse it lives with, or else the person it lives with or its employer), and also the infant personally if 14 or older. Adjudicated incompetent: serve the committee and the incompetent (the court may dispense with the latter). Conservatee: serve the conservator and the conservatee (the court may dispense with the latter). Representation and default limits: NY:CPLR-1201-representation, NY:CPLR-1203-1015-5208-parties.",
                  "(a) Upon an infant.", "but the court may dispense with service upon the conservatee.",
                  severity="minor", walk_step="8.9", dependencies=["NY:CPLR-1201-representation"])]),
    D("NY:CPLR 310", "new_rule",
      "How a partnership owner (or partnership tenant) is served; a tenant suing a partnership landlord serves any partner or the managing agent at its office plus mailing.",
      proposed=[R("NY:CPLR-310-partnership", "NY:CPLR 310", "CPLR 310", "former tenant (plaintiff); landlord partnership", "rule",
                  "A party to a claim over the tenancy is a partnership (an owner partnership, or a company tenant organized as one).",
                  "Service is by personal service on any partner; or within the state by delivery to the managing or general agent or person in charge of its office there plus mailing to the partner's last known residence or the partnership's place of business, with proof filed within 20 days and service complete 10 days later; or, if those fail with due diligence, affixing to the door of its actual place of business plus mailing; or to an agent it appointed or designated in a writing filed with the county clerk; or as the court directs if impracticable.",
                  "(a) Personal service upon persons conducting a business as a partnership", "it may be made in such manner as the court, upon motion without notice directs.",
                  severity="minor", walk_step="7.6")]),
    D("NY:CPLR 311", "new_rule",
      "How a corporation is served (an officer, director, managing or general agent, or authorized agent, or the Secretary of State under BCL 306); fixes how a tenant sues a corporate owner and how the landlord sues a corporate tenant.",
      proposed=[R("NY:CPLR-311-corporation", "NY:CPLR 311", "CPLR 311(a)(1), (b)", "former tenant (plaintiff); landlord corporation; company tenant", "rule",
                  "A party to a claim over the tenancy is a domestic or foreign corporation (a corporate owner, or a company that was the tenant).",
                  "Service is by delivery to an officer, director, managing or general agent, cashier or assistant cashier, or another agent authorized by appointment or law; a business corporation may also be served through the Secretary of State under BCL 306 or 307. If service within the 120 days of CPLR 306-b is impracticable, the court may direct another method. Operator step: an owner keeps its registered and Secretary of State addresses current so a tenant's deposit suit reaches it and no default is taken.",
                  "(a) Personal service upon a corporation or governmental subdivision shall be made by delivering the summons as follows:", "may also be served pursuant to section three hundred six or three hundred seven of the business corporation law.",
                  severity="minor", walk_step="7.6")]),
    D("NY:CPLR 312-A", "new_rule",
      "Service by mail with acknowledgment: complete only when the tenant returns the signed acknowledgment (within 30 days), answer due 20 days later, and the tenant pays the cost of other service if it does not return it; decides whether the cheap mail route works.",
      proposed=[R("NY:CPLR-312-a-mail-service", "NY:CPLR 312-A", "CPLR 312-a", "landlord (plaintiff); former tenant", "rule",
                  "The landlord serves a former tenant (or the tenant serves the landlord) by first-class mail under CPLR 312-a instead of personal service.",
                  "The summons and complaint are mailed with two copies of the statutory statement of service and acknowledgment of receipt and a prepaid return envelope. Service is complete only when the defendant (or its authorized employee or attorney) mails or delivers the signed acknowledgment, which is due within 30 days after receipt; if the complaint was served, the answer is due 20 days after that. If no acknowledgment is returned within 30 days, the landlord serves by another permitted method, noting the earlier attempt, and the reasonable expense of that service is taxed against the defendant as a disbursement with immediate judgment for it (in Civil Court: NY:CCA-1908-A-unacknowledged-mail-service). A mailing alone, without the signed acknowledgment, gives no jurisdiction and supports no default.",
                  "(a) Service. As an alternative to the methods of personal service", "and the court shall direct immediate judgment in that amount.",
                  severity="major", walk_step="8.10")]),
    D("NY:CPLR 313", "new_rule",
      "A former tenant domiciled in New York or subject to its long-arm jurisdiction (CPLR 302, for a claim arising from its lease of NYC property) may be served outside the state in the same manner as within; decides whether a tenant who moved out of state can be sued in Supreme Court.",
      proposed=[R("NY:CPLR-313-service-outside-state", "NY:CPLR 313", "CPLR 313", "landlord (plaintiff)", "permission",
                  "The landlord sues in the Supreme Court a former tenant who has moved out of New York, on a claim arising from the lease of the NYC unit (long-arm: NY:CPLR-302-long-arm).",
                  "The tenant may be served outside the state in the same manner as within it (CPLR 308), by a New York resident authorized to serve, a person authorized by the law of the place of service, or a qualified local attorney. The Civil Court equivalent is NY:CCA-404-long-arm.",
                  "A person domiciled in the state or subject to the jurisdiction of the courts of the state", "or by any duly qualified attorney, solicitor, barrister, or equivalent in such jurisdiction.",
                  severity="major", walk_step="8.10", dependencies=["NY:CPLR-302-long-arm", "NY:CPLR-308-natural-person"])]),
    D("NY:CPLR 315", "no_decision",
      "Publication is authorized only in the in-rem and status actions of CPLR 314, not a personal action for a lease balance; an unlocatable former tenant is served by a court-directed method under CPLR 308(5)."),
    D("NY:CPLR 316", "no_decision",
      "Form and timing of publication once ordered under CPLR 315; no publication route exists for a personal balance action (see CPLR 315), so it adds no step."),
    D("NY:CPLR 317", "new_rule",
      "A former tenant served other than by personal delivery who defaulted may reopen the judgment within one year after learning of it (at most five years after entry) if it did not receive the summons and has a meritorious defense, with restitution; a default judgment on substituted or nail-and-mail service stays open to this risk.",
      proposed=[R("NY:CPLR-317-defend-after-default", "NY:CPLR 317", "CPLR 317", "former tenant (defendant); landlord", "rule",
                  "The landlord obtained a default judgment against a former tenant served other than by personal delivery to the tenant or its CPLR 318 agent (substituted service, affix-and-mail, court-directed service).",
                  "The court may allow the tenant to defend within one year after it learns of the judgment's entry, and never more than five years after entry, on finding that it did not personally receive notice of the summons in time to defend and has a meritorious defense (for example the deposit forfeiture offset, wear and tear, a statutory termination). If the defense succeeds, the court may order restitution of what was collected, as on a reversal. Operator step: sums collected on such a judgment are exposed to restitution for up to five years after entry.",
                  "A person served with a summons other than by personal delivery to him", "This section does not apply to an action for divorce, annulment or partition.",
                  severity="major", walk_step="8.9", determinacy="MIXED", judgment_terms=["did not personally receive notice of the summons in time to defend", "meritorious defense"],
                  dependencies=["NY:CPLR-308-natural-person", "NY:CPLR-5015-relief-from-judgment"])]),
    D("NY:CPLR 318", "no_decision",
      "Lets a person designate an agent for service by a filed, acknowledged writing; no settlement step turns on it (service on such an agent is a CPLR 308(3) method)."),
    D("NY:CPLR 320", "new_rule",
      "In Supreme Court the former tenant must appear within 20 days after personal delivery, or 30 days after service is complete for substituted, affix-and-mail, out-of-state or publication service; fixes when a default arises.",
      proposed=[R("NY:CPLR-320-appearance-time", "NY:CPLR 320", "CPLR 320(a)-(b)", "landlord (plaintiff); former tenant", "rule",
                  "The landlord serves a Supreme Court summons on a former tenant (or the tenant serves the landlord).",
                  "The defendant appears by serving an answer or notice of appearance, or by a motion that extends its time to answer. It must appear within 20 days after service by personal delivery, or within 30 days after service is complete where served under CPLR 303, 308(2)-(5), 313, 314 or 315 (by mail under 312-a, within 20 days after returning the acknowledgment). If the complaint was not served with the summons, the time may be extended under CPLR 3012(b). An appearance is equivalent to personal service unless a jurisdiction objection is raised by motion or in the answer. A default judgment is sought only after the time runs (NY:CPLR-3215(g)(3)). Civil Court counterpart: NY:CCA-402-answer-time.",
                  "(a) Requirement of appearance.", "is asserted by motion or in the answer as provided in rule 3211.",
                  severity="major", walk_step="8.9", dependencies=["NY:CPLR-3215(g)(3)"])]),
    D("NY:CPLR 3201", "no_decision",
      "Voids pre-default confessions of judgment only for installment purchases of consumer commodities of $1,500 or less; a lease balance is not such a purchase (confession for a lease balance is CPLR 3218)."),
]
write(rows)
