from q2_lib import *

EVID = "an evidentiary rule for a kind of record or proceeding that does not arise in settling a market-rate tenancy; no settlement, collection or record-keeping step turns on it."
rows = [
    D("NY:CPLR 4517", "no_decision", "Use of prior trial testimony; trial evidence, no settlement step."),
    D("NY:CPLR 4518", "new_rule",
      "The landlord proves the balance and each charge through business records (ledger, move-in record, inspection reports, invoices, the itemized statement, electronic records) made in the regular course of business at or near the time; this sets how Handoff and the manager must make and keep the settlement file.",
      proposed=[R("NY:CPLR-4518-business-records", "NY:CPLR 4518", "CPLR 4518(a)", "landlord, managing agent, Handoff (record keepers)", "rule",
                  "The landlord offers records to prove a former tenant's balance or to defend deductions from the deposit (rent ledger, move-in and pre-vacate inspection records, photographs log, work orders, vendor invoices, the itemized statement and its delivery record), including electronic records.",
                  "A record of an act, transaction or event is admissible to prove it if the judge finds it was made in the regular course of a business and that it was the regular course of that business to make it at the time of the event or within a reasonable time after. An electronic record (State Technology Law 302) is admitted as a tangible exhibit that truly and accurately represents it, and the court may consider how it was stored, maintained and retrieved. Lack of personal knowledge by the maker goes to weight, not admissibility. Records a business receives from another (for example Handoff's or a vendor's records held by the manager) are admitted through the receiving business only if it incorporated them and relied on them in its regular course, or through a witness from the business that made them. Operator step: each charge and event is recorded when it occurs by the business whose routine it is, stored so that the record can be retrieved unaltered, and a custodian who knows the record-keeping practice (manager or Handoff staff) is available to lay the foundation.",
                  "(a) Generally. Any writing or record, whether in the form of an entry in a book or otherwise,", "The term business includes a business, profession, occupation and calling of every kind.",
                  severity="major", walk_step="7.4", determinacy="MIXED", judgment_terms=["made in the regular course of business", "within a reasonable time", "true and accurate representation"],
                  dependencies=["NY:GOL-7-108(1-a)(f)", "NY:STT-305(3)"])]),
    D("NY:CPLR 4519", "new_rule",
      "The dead man's statute: after a former tenant dies, the landlord and its interested witnesses cannot testify against the estate about personal transactions or communications with the tenant; claims against the estate must be proved by documents and disinterested witnesses.",
      proposed=[R("NY:CPLR-4519-dead-mans-statute", "NY:CPLR 4519", "CPLR 4519", "landlord (claimant against a deceased tenant's estate)", "limit",
                  "The landlord pursues a balance against the estate of a deceased former tenant (or of a tenant adjudicated mentally ill with a committee), or the estate sues for the deposit.",
                  "At trial the landlord, and any person interested in the outcome or through whom it claims (including an assignor), may not testify in its own interest about a personal transaction or communication with the deceased tenant (for example an oral agreement, an admission of damage, a promise to pay), unless the estate opens the door by testifying to the same transaction. Proof comes from written records (NY:CPLR-4518-business-records), the lease, photographs and disinterested witnesses; a managing agent's employee with no interest in the outcome is not barred. Payee and claim rules after death: NY:ADJ-tenant-death-payee.",
                  "Upon the trial of an action or the hearing upon the merits of a special proceeding,", "concerning the same transaction or communication.",
                  severity="minor", walk_step="2.5", determinacy="MIXED", judgment_terms=["person interested in the event", "personal transaction or communication"],
                  dependencies=["NY:ADJ-tenant-death-payee", "NY:CPLR-4518-business-records"])]),
    D("NY:CPLR 4520", "no_decision", "Public officers' filed certificates are prima facie evidence; " + EVID),
    D("NY:CPLR 4521", "no_decision", "A custodian's statement of no record is prima facie evidence; " + EVID),
    D("NY:CPLR 4522", "no_decision", "Ancient filed maps and records affecting real property; " + EVID),
    D("NY:CPLR 4525", "no_decision", "Copies of UCC article 9 filings; " + EVID),
    D("NY:CPLR 4528", "no_decision", "Weather bureau records; " + EVID),
    D("NY:CPLR 4529", "no_decision", "USDA inspection certificates; " + EVID),
    D("NY:CPLR 4530", "no_decision", "Census certificates; " + EVID),
    D("NY:CPLR 4532", "no_decision", "Self-authentication of newspapers; " + EVID),
    D("NY:CPLR 4532-A", "no_decision", "Medical and diagnostic test images; " + EVID),
    D("NY:CPLR 4532-B", "no_decision", "Web mapping and satellite images are admissible if dated; " + EVID),
    D("NY:CPLR 4533-B", "no_decision", "Deduction of a joint tortfeasor's settlement (GOL 15-108) in injury cases; the release rules between co-obligors on a lease are stated at NY:GOL-15-104-105-cotenant-release."),
    D("NY:CPLR 4536", "no_decision", "Handwriting comparison; " + EVID),
    D("NY:CPLR 4537", "no_decision", "Proof of writings with subscribing witnesses; " + EVID),
    D("NY:CPLR 4539", "new_rule",
      "A scanned or electronic copy the business made in its regular course is as admissible as the original, and an image stored by a process that records any change is admissible when its tamper-protection is shown; governs keeping the settlement file digitally and discarding paper.",
      proposed=[R("NY:CPLR-4539-reproductions", "NY:CPLR 4539", "CPLR 4539", "landlord, managing agent, Handoff (record keepers)", "rule",
                  "The landlord's settlement records (signed lease, move-in condition record, inspection notice, itemized statement, receipts) are kept as scans, photographs or other reproductions, with or without the paper original.",
                  "A reproduction a business made in its regular course by a process that accurately reproduces the original or forms a durable medium for it is as admissible as the original, whether or not the original still exists, when satisfactorily identified. A stored image made by a process that does not allow additions, deletions or changes without leaving a record of them is as admissible as the original when authenticated by testimony or affidavit describing how tampering and degradation are prevented. Operator step: store the file in a system with an audit trail of changes, and be able to describe it in an affidavit.",
                  "(a) If any business, institution, or member of a profession or calling,", "shall be as admissible in evidence as the original.",
                  severity="minor", walk_step="7.4", dependencies=["NY:CPLR-4518-business-records"])]),
    D("NY:CPLR 4540", "no_decision", "Authentication of official records by attested copy; " + EVID + " (Registration and certificate-of-occupancy records are proved this way, but the step is the substantive check, stated at NY:MDL-301(1) and NY:MDL-325(2).)"),
    D("NY:CPLR 4540-A", "no_decision", "Material a party produces in disclosure is presumed authentic against it; in-suit evidence mechanics."),
    D("NY:CPLR 4541", "no_decision", "Proof of justice-of-the-peace proceedings; " + EVID),
    D("NY:CPLR 4542", "no_decision", "Proof of foreign records; " + EVID),
    D("NY:CPLR 4543", "no_decision", "Other lawful methods of proof are preserved; adds nothing."),
    D("NY:CPLR 4545", "new_rule",
      "In an action for injury to property, a loss replaced by a collateral source (such as the owner's property insurance) reduces the award, net of two years' premiums, except payments carrying a statutory right of reimbursement; changes what the landlord recovers from a former tenant for insured damage.",
      proposed=[R("NY:CPLR-4545-collateral-source", "NY:CPLR 4545", "CPLR 4545(a)", "landlord (plaintiff); former tenant", "limit",
                  "The landlord sues a former tenant to recover damages for injury to the unit or building (for example fire or water damage the tenant caused), and part or all of the repair cost was or will with reasonable certainty be paid by a collateral source such as the owner's property insurer.",
                  "The tenant may prove the collateral payment, and the court reduces the award by it, less the premiums the owner paid for that coverage in the two years before the claim accrued and the projected cost of keeping it; payments carrying a statutory right of reimbursement, and life insurance, are not deducted. The owner proves its full loss at trial and the deduction is made after verdict. The rule applies to a claim for damages for injury to property whether pleaded in tort or on the lease covenant, since the damages sought are for injury to property. Deposit deductions are governed by NY:GOL-7-108(1-a)(b)-refundable.",
                  "(a) Actions for personal injury, injury to property or wrongful death.", "irrespective of whether such sums will later have to be deducted from the plaintiff’s recovery.",
                  severity="minor", walk_step="8.10", determinacy="MIXED", judgment_terms=["replaced or indemnified with reasonable certainty"],
                  dependencies=["NY:GOL-7-108(1-a)(b)-refundable"])]),
    D("NY:CPLR 4549", "new_rule",
      "Statements by the landlord's authorized agent or employee (the managing agent, Handoff, a collector) on matters within the agency are admissible against the landlord; what Handoff or the manager writes to a former tenant about a charge binds the owner as evidence.",
      proposed=[R("NY:CPLR-4549-agent-statements", "NY:CPLR 4549", "CPLR 4549", "landlord; managing agent; Handoff; collector", "rule",
                  "A statement about the tenancy's account was made by a person the landlord authorized to speak on the subject, or by its agent or employee within the scope of the relationship while it existed (the managing agent, Handoff, a leasing agent, a collector), for example that damage was wear and tear, that a charge would be waived, or that the tenant vacated on a date.",
                  "The statement is not excluded as hearsay when the tenant offers it against the landlord; the same applies to statements of the tenant's agents offered against the tenant. Operator step: communications with the former tenant state only what the settlement file supports.",
                  "A statement offered against an opposing party shall not be excluded from evidence as hearsay", "during the existence of that relationship.",
                  severity="minor", walk_step="8.1b", dependencies=["NY:CPLR-4547-compromise-inadmissible"])]),
    D("NY:CPLR 4550", "no_decision", "Evidence of legally protected reproductive or gender-affirming health activity may not be used to show wrongdoing; no settlement step turns on it."),
    D("NY:CPLR 4551", "no_decision", "Presumed validity of the state voting and elections database; " + EVID),
    D("NY:CPLR 5012", "no_decision", "Judgment on part of a claim after severance; " + "in-suit mechanics."),
    D("NY:CPLR 502", "no_decision", "Resolving conflicting venue provisions on joinder; in-suit venue mechanics."),
    D("NY:CPLR 504", "no_decision", "Venue of actions against municipalities; not parties to the tenancy."),
    D("NY:CPLR 505", "no_decision", "Venue of actions involving public authorities; not parties to the tenancy."),
    D("NY:CPLR 506", "no_decision", "Where special proceedings (including article 78) are brought; article 52 enforcement proceedings follow CPLR 5221 (proposed NY:CPLR-5221-enforcement-forum)."),
    D("NY:CPLR 507", "no_decision", "Venue of actions affecting title to or possession of real property; a balance or deposit action is a money action."),
    D("NY:CPLR 508", "no_decision", "Venue of actions to recover a chattel; not a claim in the chain (belongings rules are stated)."),
    D("NY:CPLR 509", "no_decision", "The plaintiff's designated county governs until changed; the venue choice itself is decided by CPLR 503 and the proposed venue rules, and this adds no step."),
]
write(rows)
