from q2_lib import *

G108 = "register/texts/NY_GOL/7-108.txt"
rows = [
    D("NY:CPLR 1001", "no_decision",
      "The court's standard for compelling joinder of absent parties; who may be sued alone on a joint lease obligation is CPLR 1501-1502, and who is paid a joint refund is NY:ADJ-cotenants-payee. It adds no step to the settlement."),
    D("NY:CPLR 1018", "no_decision",
      "A pending action continues after a transfer of interest unless the court substitutes the transferee; who owns a pre-sale balance is decided by NY:RPL-223 and assignment limits by NY:JUD-489-champerty."),
    D("NY:CPLR 1021", "partial",
      "The parties rule states substitution on death; 1021 adds that substitution must be sought within a reasonable time or the action may be dismissed (not on the merits), and that on a party's death the court orders the estate's interested persons to show cause.",
      atoms=["NY:CPLR-1203-1015-5208-parties"],
      proposed=[R("NY:CPLR-1021-substitution-deadline", "NY:CPLR 1021", "CPLR 1021", "landlord; former tenant's estate", "obligation",
                  "A party to a pending action over the tenancy dies (for example the former tenant sued for the balance) or another event requires substitution.",
                  "Substitution is moved by the successors or representatives or by any party; a person who should be substituted and does not appear may be made a defendant. If the event occurs before final judgment and substitution is not made within a reasonable time, the action may be dismissed as to that party, not on the merits unless the court says so. On a party's death without timely substitution, the court, before proceeding, orders the persons interested in the estate to show cause why the action should not be dismissed. Operator step: when a sued former tenant dies, seek appointment of a fiduciary and substitution promptly (claims against the estate: NY:ADJ-tenant-death-payee).",
                  "A motion for substitution may be made by the successors", "why the action or appeal should not be dismissed.",
                  severity="minor", walk_step="8.9", amends="NY:CPLR-1203-1015-5208-parties", determinacy="MIXED", judgment_terms=["reasonable time"],
                  dependencies=["NY:CPLR-1203-1015-5208-parties", "NY:ADJ-tenant-death-payee"])]),
    D("NY:CPLR 1022", "no_decision",
      "Extends in-suit procedural deadlines until 15 days after substitution; litigation mechanics that change no step, amount or precondition of the settlement."),
    D("NY:CPLR 106", "no_decision",
      "A civil claim is not merged in a criminal prosecution for the same act; the landlord's damage claim survives any prosecution without any step by the landlord."),
    D("NY:CPLR 1201", "partial",
      "The parties rule bars a default against an infant or adjudicated incompetent; 1201 adds who appears for them and that an adult incapable of defending its rights appears by a guardian ad litem, which the landlord must obtain before pursuing an incapacitated former tenant.",
      atoms=["NY:CPLR-1203-1015-5208-parties"],
      proposed=[R("NY:CPLR-1201-representation", "NY:CPLR 1201", "CPLR 1201", "landlord (plaintiff); representative of the former tenant", "rule",
                  "The landlord sues a former tenant who is an infant, a person judicially declared incompetent, a conservatee, or an adult incapable of adequately prosecuting or defending its rights (or such a person sues the landlord for the deposit).",
                  "An infant appears by the guardian of its property, else a parent with legal custody, else another custodian, or, if married, an adult spouse living with it; an adjudicated incompetent appears by the committee of its property; a conservatee by the conservator. A guardian ad litem appears where there is no such representative, where the court so directs for conflict or other cause, or for an adult incapable of adequately prosecuting or defending its rights. The landlord seeks a guardian ad litem (CPLR 1202) before pursuing default against such a tenant (NY:CPLR-1203-1015-5208-parties).",
                  "Unless the court appoints a guardian ad litem,", "or if he is an adult incapable of adequately prosecuting or defending his rights.",
                  severity="major", walk_step="8.9", amends="NY:CPLR-1203-1015-5208-parties", determinacy="MIXED",
                  judgment_terms=["adult incapable of adequately prosecuting or defending his rights"], dependencies=["NY:CPLR-1203-1015-5208-parties"])]),
    D("NY:CPLR 1205", "partial",
      "An infant, incompetent, conservatee or guardian-ad-litem-represented former tenant (or its representative) is not liable for costs unless the court orders; changes the landlord's recoverable costs against such a tenant.",
      atoms=["NY:CPLR-1203-1015-5208-parties"],
      proposed=[R("NY:CPLR-1205-no-costs-against-incapacitated", "NY:CPLR 1205", "CPLR 1205", "landlord (plaintiff)", "limit",
                  "The landlord obtains judgment against a former tenant who is an infant, adjudicated incompetent, conservatee or represented by a guardian ad litem, or against its representative.",
                  "Neither the tenant nor its representative is liable for costs unless the court orders otherwise; the judgment carries the principal and interest, and costs only by order.",
                  "An infant, a person judicially declared to be incompetent,", "shall not be liable for costs unless the court otherwise orders.",
                  severity="minor", walk_step="8.10", amends="NY:CPLR-1203-1015-5208-parties", dependencies=["NY:CPLR-1201-representation"])]),
    D("NY:CPLR 1501", "new_rule",
      "On a joint lease obligation the landlord may proceed against the co-tenants it has served and take judgment against all named; changes how a balance owed by co-tenants (one unreachable) is pursued.",
      proposed=[R("NY:CPLR-1501-joint-obligors", "NY:CPLR 1501", "CPLR 1501", "landlord (plaintiff)", "permission",
                  "The landlord sues co-tenants (or a tenant and a guarantor) on a joint lease obligation and serves fewer than all of them.",
                  "It may proceed against those served unless the court directs otherwise, and a judgment for it may be taken against all the named defendants; the judgment reaches the unserved co-obligor's individually held property only through a later action under NY:CPLR-1502-later-action-co-obligor. Liability that is joint and several under the lease may instead be pursued against any one co-tenant alone.",
                  "Where less than all of the named defendants in an action based upon a joint obligation,", "it may be taken against all the defendants.",
                  severity="major", walk_step="8.10", dependencies=["NY:CPLR-1502-later-action-co-obligor", "NY:GOL-15-104-105-cotenant-release"])]),
    D("NY:CPLR 1502", "new_rule",
      "To reach an unserved co-tenant's own property after a joint judgment, the landlord must bring a second, verified action, in which the co-tenant keeps all its defenses; decides whether pursuing an absent co-tenant is worth it.",
      proposed=[R("NY:CPLR-1502-later-action-co-obligor", "NY:CPLR 1502", "CPLR 1502", "landlord (plaintiff)", "obligation",
                  "The landlord holds a judgment on a joint lease obligation taken against all co-tenants under CPLR 1501, and a co-tenant was not served in that action.",
                  "To obtain a judgment enforceable against that co-tenant's individually held property for the unpaid remainder, the landlord brings a later action with a verified complaint, treated as based on the same obligation for provisional remedies. The co-tenant may raise every defense and counterclaim it could have raised in the first action (for example its share of the deposit or wear and tear), objections to the first judgment, and defenses arising since.",
                  "A subsequent action against a co-obligor who was not summoned", "and defenses or counterclaims that have arisen since it was entered.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-1501-joint-obligors"])]),
    D("NY:CPLR 2001", "no_decision",
      "Lets the court correct or disregard filing mistakes in a pending case; in-suit discretion that changes no step, amount or deadline of the settlement."),
    D("NY:CPLR 2003", "no_decision",
      "Lets the court set aside a judicial sale within a year for defective notice or manner; it binds the enforcement officer's sale and changes no step or amount in the landlord's settlement or collection decision."),
    D("NY:CPLR 2004", "no_decision",
      "General judicial power to extend times set by statute or rule, except where the law expressly bars it (limitations periods cannot be extended: CPLR 201); it fixes no step or deadline of its own."),
    D("NY:CPLR 2005", "no_decision",
      "Allows a court to excuse law-office failure on a motion to vacate a default; court discretion inside CPLR 5015 and 3012(d), adding no step or deadline."),
    D("NY:CPLR 201", "partial",
      "The limitation rules state the periods; 201 adds that a shorter period may be set by written agreement and that no court may extend a limitation period. A lease clause shortening the tenant's time to sue over the deposit is void under GOL 7-108's anti-waiver clause.",
      atoms=["NY:CPLR-213(2)", "NY:ADJ-tenant-deposit-claim-limitations"],
      proposed=[R("NY:CPLR-201-agreed-shorter-period", "NY:CPLR 201", "CPLR 201", "landlord; former tenant", "rule",
                  "A lease or other written agreement between the landlord and the tenant sets a period for suing shorter than the statutory one. Branch (a): the clause limits the tenant's claims over the security deposit (return, forfeiture, double damages). Branch (b): the clause limits another claim between them (the landlord's balance, a tenant's non-deposit claim).",
                  "Every action must be begun within the statutory period unless a different period is prescribed by law or a shorter one by written agreement, and no court may extend a period fixed by law. Branch (a): the clause is void, because GOL 7-108 makes absolutely void any agreement by a tenant waiving or modifying its rights under that section, and a shortened time to enforce them modifies them (and GOL 7-103(3) voids any waiver of the trust section); the statutory periods of NY:ADJ-tenant-deposit-claim-limitations apply. Branch (b): the clause is enforced if the shortened period is reasonable. A promise to extend the period is governed by NY:GOL-17-103-limitations-promise.",
                  "An action, including one brought in the name or for the benefit of the state,", "No court shall extend the time limited by law for the commencement of an action.",
                  severity="critical", walk_step="7.6", amends="NY:ADJ-tenant-deposit-claim-limitations", determinacy="MIXED", judgment_terms=["reasonable shortened period"],
                  dependencies=["NY:ADJ-tenant-deposit-claim-limitations", "NY:CPLR-213(2)", "NY:GOL-17-103-limitations-promise", "NY:GOL-7-103(3)"],
                  construction=[{"source_file": G108, "quote": q(G108, "Any agreement by a lessee or tenant of a dwelling waiving or modifying his rights as set forth in this section shall be absolutely void.")}],
                  reasoning="CPLR 201 permits a shorter period by written agreement, but a specific statute voiding any agreement that modifies a tenant's deposit rights controls over the general permission for those rights; the remedy provisions of 7-108(1-a)(g) are rights set forth in the section.")]),
    D("NY:CPLR 202", "new_rule",
      "The borrowing statute: where a claim over the tenancy accrues outside New York in favor of a non-resident (an owner entity based out of state, a tenant who moved away before its claim accrued), the shorter of New York's and that place's period applies. Can bar the landlord's balance suit or the tenant's deposit suit early.",
      proposed=[R("NY:CPLR-202-borrowing", "NY:CPLR 202", "CPLR 202", "landlord; former tenant", "rule",
                  "A claim between the landlord and a former tenant is for economic loss (unpaid rent or damage; the deposit wrongly kept). Branch (a): the plaintiff is a New York resident when the claim accrues (an individual owner domiciled here; an entity with its principal place of business here; a tenant still living here). Branch (b): the plaintiff resides outside New York when the claim accrues (an owner entity organized and based elsewhere; a tenant who had moved out of state by the end of the 14 days).",
                  "An economic-loss claim accrues where the plaintiff resides and sustains the economic impact (Global Fin. Corp. v Triarc Corp., 93 NY2d 525 [1999]). Branch (a): New York's period alone applies (NY:CPLR-213(2), NY:ADJ-tenant-deposit-claim-limitations). Branch (b): the action must be timely under both New York's period and the period of the place where the plaintiff resided, including that place's tolling rules; the shorter controls, and a lease choice-of-law clause does not change this. An assignee or collector suing on the owner's claim stands in the owner's position (Portfolio Recovery Assoc., LLC v King, 14 NY3d 410 [2010]). Operator step: record the owner's place of residence (for an entity, where it sustains the loss, its principal place of business) and the tenant's residence at accrual.",
                  "An action based upon a cause of action accruing without the state", "the time limited by the laws of the state shall apply.",
                  severity="critical", walk_step="8.10", determinacy="MIXED", judgment_terms=["place where the plaintiff resides and sustains the economic impact of the loss"],
                  dependencies=["NY:CPLR-213(2)", "NY:ADJ-tenant-deposit-claim-limitations"])]),
    D("NY:CPLR 205-A", "no_decision",
      "Recommencement rules only for actions on instruments under CPLR 213(4) (mortgages and other real-property secured instruments); a lease balance or deposit claim is not one (its recommencement is CPLR 205(a), stated)."),
    D("NY:CPLR 206", "new_rule",
      "Where a lease makes a sum payable only on the landlord's demand, the period runs from when the landlord could first demand, not from the demand; a deposit held as trust money is not a 'special demand' deposit. Fixes accrual of such charges.",
      proposed=[R("NY:CPLR-206-demand-accrual", "NY:CPLR 206", "CPLR 206(a), (d)", "landlord; former tenant", "rule",
                  "Computing when a claim between the landlord and a former tenant accrued. Branch (a): the lease makes a charge (for example repair costs) payable on the landlord's demand or bill. Branch (b): the tenant's claim to the deposit. Branch (c): the parties' account.",
                  "Branch (a): where a demand is necessary to sue, the period runs from when the right to make the demand was complete (when the costs were incurred and billable), not from when the landlord chose to demand; delaying the bill does not extend the period. Branch (b): the deposit is repayable by statute within 14 days after vacating without any demand, so its period runs from the end of the 14 days (NY:ADJ-tenant-deposit-claim-limitations); the special-demand and fiduciary-discovery rules of 206(a)(1)-(2) do not move it. Branch (c): a rent ledger of charges and payments is not a mutual, open and current account with reciprocal demands, so the 'last transaction' rule of 206(d) does not apply; each rent installment accrues on its due date (a part payment's effect: NY:GOL-17-101-acknowledgment).",
                  "(a) Where demand necessary.", "shall be computed from the time of the last transaction in the account on either side.",
                  severity="major", walk_step="8.10", dependencies=["NY:ADJ-tenant-deposit-claim-limitations", "NY:GOL-17-101-acknowledgment"])]),
    D("NY:CPLR 209", "new_rule",
      "Tolls limitation periods while a party cannot sue because of a war between the United States and the country where it resides or of which it is a national; applies to a former tenant or owner in such a country.",
      proposed=[R("NY:CPLR-209-war-tolling", "NY:CPLR 209", "CPLR 209(b)-(c)", "landlord; former tenant", "rule",
                  "A party to a claim over the tenancy is a national of, or resides or sojourns in, a foreign country at war with the United States or its allies (or territory it occupies).",
                  "The time from the start of the war to the end of hostilities (for a national who cannot sue), or the period of residence or sojourn there during the war (for a claimant living there), is not counted in the limitation period.",
                  "(b) Right of noncitizen.", "is not a part of the time within which the action must be commenced.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-204-208-tolling"])]),
    D("NY:CPLR 2103", "no_decision",
      "How papers are served between parties after an action is begun (on the attorney, by mail with five added days, fax, overnight, electronic); in-suit mechanics that change no settlement step. Commencement service is CPLR 308-312-a and CCA 403."),
    D("NY:CPLR 2103-A", "new_rule",
      "A court may let a party keep its address confidential for safety, and the address of a domestic-violence program resident is never revealed; changes how a landlord serves and pursues a former tenant who is a domestic-violence victim.",
      proposed=[R("NY:CPLR-2103-a-confidential-address", "NY:CPLR 2103-A", "CPLR 2103-a", "landlord (plaintiff) and its collector; former tenant", "rule",
                  "The landlord sues, or is sued by, a former tenant whose address the court orders kept confidential because disclosure would pose an unreasonable risk to its health or safety, or who lives or lived in a residential program for domestic-violence victims.",
                  "The court may authorize the tenant to keep its residential and business addresses and telephone numbers out of papers, sealed pending the finding, and designates the clerk or another disinterested person as agent for service, who forwards process; the landlord serves through that agent. The present address of a domestic-violence program resident, and the program's address, are not revealed by the court. The tenant keeps the agent informed of address changes. Operator step: where a former tenant ended the lease as a domestic-violence victim (NY:RPL-227-c(1)), do not seek or publish its new address in court papers; use the designated agent.",
                  "(a) Notwithstanding any other provision of law, in any civil proceeding,", "of any change in address for purposes of receipt of service of process or any papers.",
                  severity="major", walk_step="8.10", dependencies=["NY:RPL-227-c(1)"])]),
    D("NY:CPLR 2104", "new_rule",
      "A settlement with a former tenant in a pending case binds only if in a writing signed by the party or its attorney, made in open court, or so-ordered, and its terms are filed by the defendant with the county clerk; decides whether a settlement is enforceable.",
      proposed=[R("NY:CPLR-2104-stipulations", "NY:CPLR 2104", "CPLR 2104", "landlord; former tenant", "rule",
                  "The landlord and a former tenant agree to settle or otherwise resolve a pending action or proceeding over the tenancy (a payment plan, a reduced balance, return of part of the deposit).",
                  "The agreement binds a party only if it is in a writing signed by that party or its attorney, made between counsel in open court, or reduced to an order and entered; an oral out-of-court settlement is not binding. The defendant files the terms of a stipulation of settlement with the county clerk. Payment on a settled deposit claim: NY:CPLR-5003-a-settlement-payment.",
                  "An agreement between parties or their attorneys relating to any matter in an action,", "shall be filed by the defendant with the county clerk.",
                  severity="major", walk_step="8.1b", dependencies=["NY:CPLR-5003-a-settlement-payment"])]),
    D("NY:CPLR 213-A", "excluded_regime",
      "Residential rent overcharge claims arise only for rent-stabilized or rent-controlled units (regulated rent); out of aperture for a market-rate unit (Review 2)."),
    D("NY:CPLR 214-C", "no_decision",
      "Discovery accrual for injury from latent exposure to substances (toxic torts); no claim in the settlement chain is of that kind."),
    D("NY:CPLR 216", "new_rule",
      "Where one person sues for a contract sum and another claims the same sum but cannot be served, the defendant may notify the other claimant and cut its time to sue to one year; a tool for a landlord facing competing claims to a deposit refund.",
      proposed=[R("NY:CPLR-216-adverse-claimant-notice", "NY:CPLR 216", "CPLR 216(a)", "landlord (defendant)", "permission",
                  "A former tenant (or its estate, trustee or co-tenant) sues the landlord for the deposit refund over $50, and another person who cannot be served within the court's jurisdiction claims the same sum (for example an absent co-tenant, or a person claiming as the tenant's agent).",
                  "Within 20 days after service of the complaint or receipt of the adverse claim, whichever is later, the landlord may move for an order permitting notice to the absent claimant; the court grants it if the claim exists, the action is not collusive and the claimant cannot be served. Notice is sent by registered mail with the summons, complaint and order to the claimant's last known address; proof of mailing is filed within 10 days of the order or the order lapses, and notice is deemed given on the tenth day after the order. The claimant must then sue within one year after notice (never longer than its own period). The court stays the action up to one year, may require the landlord to post an undertaking, and vacates the stay if the claimant intervenes or sues.",
                  "(a) Action to recover money.", "may be treated as an adverse claimant.",
                  severity="minor", walk_step="6.6", dependencies=["NY:ADJ-cotenants-payee", "NY:CPLR-1006-interpleader"])]),
    D("NY:CPLR 217-A", "no_decision",
      "Notice of claim and a one-year-ninety-day limit for actions against public entities; no party to a market-rate tenancy settlement is one."),
    D("NY:CPLR 218", "no_decision",
      "Transitional rules for claims that accrued before CPLR article 2 took effect in 1963; no current claim is affected."),
    D("NY:CPLR 2201", "no_decision",
      "General power of a court to stay a pending action; the effect of a stay on limitations is stated at NY:CPLR-204-208-tolling and bankruptcy and military stays elsewhere. It adds no step."),
    D("NY:CPLR 2222", "new_rule",
      "On request the clerk dockets an order directing payment of money (including motion costs, a so-ordered payment) as a judgment, making it enforceable and interest-bearing; a step for enforcing a court-ordered payment from a former tenant.",
      proposed=[R("NY:CPLR-2222-docket-order", "NY:CPLR 2222", "CPLR 2222", "landlord; former tenant", "permission",
                  "A court order in a case over the tenancy directs a party to pay money (for example motion costs, or payment under a so-ordered settlement).",
                  "At a party's request the clerk dockets the order as a judgment; it then bears interest from docketing (NY:CPLR-5003-judgment-interest) and is enforced as a money judgment.",
                  "At the request of any party the clerk shall docket as a judgment an order directing the payment of money,", "including motion costs,",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-5003-judgment-interest"])]),
    D("NY:CPLR 3002", "new_rule",
      "Suing one co-tenant or the guarantor, or holding an unsatisfied judgment against one, does not bar an action against the others; and a tenant may sue either the managing agent or the undisclosed owner. Changes whom the balance or deposit claim may be pursued against.",
      proposed=[R("NY:CPLR-3002-no-election", "NY:CPLR 3002", "CPLR 3002(a)-(b)", "landlord; former tenant", "rule",
                  "Branch (a): several persons are liable for the balance (co-tenants, a guarantor). Branch (b): the lease was made by a managing agent for an owner the tenant did not know, and the tenant has a claim (for example for the deposit).",
                  "Branch (a): starting or pursuing an action against one, or recovering an unsatisfied judgment against one, is not an election that bars an action against the others (releases: NY:GOL-15-104-105-cotenant-release). Branch (b): after the principal is disclosed, suing either the agent or the principal, or an unsatisfied judgment against either, does not bar an action against the other.",
                  "(a) Action against several persons.", "shall not be deemed an election of remedies which bars an action against the other.",
                  severity="major", walk_step="8.10", dependencies=["NY:GOL-15-104-105-cotenant-release"])]),
    D("NY:CPLR 3004", "no_decision",
      "Rescission of a transaction void or voidable for fraud, mistake, duress or incapacity without tendering back benefits first; rescinding a lease is not a step in settling the account of a tenancy that has ended."),
]
write(rows)
