from q2_lib import *

rows = [
    D("NY:CPLR 501", "new_rule",
      "A written venue clause agreed before suit (for example in the lease) is enforced on a motion to change venue; CPLR 514's ban on venue clauses in consumer-goods contracts does not reach a residential lease. Changes where the balance or deposit suit is tried.",
      proposed=[R("NY:CPLR-501-venue-clause", "NY:CPLR 501", "CPLR 501; CPLR 514", "landlord; former tenant", "rule",
                  "The lease (or another written agreement made before suit) fixes the county where disputes are tried, and one side sues elsewhere.",
                  "The clause is enforced on a motion to change the place of trial, subject to CPLR 510(2) (an impartial trial cannot be had there). CPLR 514, which voids venue clauses in contracts for the sale or lease of consumer goods (goods, wares, merchandise or services bought for personal, family or household purposes), does not void it, because a residential lease conveys an interest in real property, not goods or services. A federal debt collector's suit is still limited to where the tenant signed or lives (US:15USC1692i(a)), and the pending S9760 venue rule would control once in force (NY:S9760-venue).",
                  "Subject to the provisions of subdivision two of section five hundred ten", "shall be enforced upon a motion for change of place of trial.",
                  severity="minor", walk_step="8.10", determinacy="RULE", dependencies=["US:15USC1692i(a)", "NY:S9760-venue"],
                  construction=[{"source_file": "register/texts/NY_CPLR/514.txt", "quote": q("register/texts/NY_CPLR/514.txt", "“consumer goods” shall mean goods, wares, paid merchandise or services purchased or paid for by a consumer,")}],
                  reasoning="CPLR 514 reaches contracts for 'consumer goods', defined as goods, wares, merchandise or services; a residential lease is a conveyance of an estate in land, so the specific ban does not displace the general enforcement rule of CPLR 501.")]),
    D("NY:CPLR 5011", "no_decision",
      "Defines a judgment and its contents (and payment into court for incarcerated plaintiffs); no settlement or collection step turns on it."),
    D("NY:CPLR 5013", "new_rule",
      "A dismissal after the plaintiff has closed its evidence is on the merits unless it says otherwise, so the landlord (or tenant) cannot sue again; an earlier dismissal is not. Decides whether a failed suit can be re-brought.",
      proposed=[R("NY:CPLR-5013-dismissal-effect", "NY:CPLR 5013", "CPLR 5013", "landlord; former tenant", "rule",
                  "A court dismisses a party's claim over the tenancy (the balance or the deposit).",
                  "Branch (a): dismissed before the close of that party's evidence: not on the merits unless the judgment says so; the claim may be brought again within the limitations period (and CPLR 205(a) where it applies). Branch (b): dismissed after the close of its evidence: on the merits unless the judgment says otherwise, so the claim is barred.",
                  "A judgment dismissing a cause of action before the close of the proponent’s evidence", "is a dismissal on the merits unless it specifies otherwise.",
                  severity="minor", walk_step="8.10")]),
    D("NY:CPLR 5014", "new_rule",
      "An action on a New York money judgment is allowed only after ten years from docketing (to renew the lien, begun in the ninth year), after a default on non-personal service, or by leave; this governs renewing a judgment against a former tenant.",
      proposed=[R("NY:CPLR-5014-renewal-judgment", "NY:CPLR 5014", "CPLR 5014", "landlord (judgment creditor)", "rule",
                  "The landlord holds a New York money judgment against a former tenant and wants to sue on it.",
                  "Between the original parties it may do so only (1) once ten years have passed since first docketing, or during the year before that, to obtain a renewal judgment whose real-property lien takes effect when the original's ten years end; (2) where the judgment was taken by default after service other than personal delivery; or (3) by leave of court. The 20-year presumption of payment (NY:CPLR-5205-5231-enforcement-limits) bounds how long the judgment is worth renewing.",
                  "Except as permitted by section 15-102 of the general obligations law,", "shall take effect upon the expiration of ten years from the first docketing of the original judgment.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-5205-5231-enforcement-limits"])]),
    D("NY:CPLR 5015", "new_rule",
      "The grounds and deadlines on which a former tenant (or the landlord) can vacate a judgment: excusable default within one year after service with notice of entry, lack of jurisdiction at any time, fraud or misconduct, new evidence, and mass vacatur of improper defaults, with restitution. Decides how durable a default judgment on the balance is.",
      proposed=[R("NY:CPLR-5015-relief-from-judgment", "NY:CPLR 5015", "CPLR 5015", "former tenant; landlord", "rule",
                  "A judgment or order was entered in a case over the tenancy and the losing party moves to vacate it.",
                  "The court may relieve a party on these grounds: (1) excusable default, if moved within one year after the judgment was served with written notice of entry on the movant (or after entry, if the movant entered it); (2) newly discovered evidence that would probably change the result; (3) fraud, misrepresentation or other misconduct of the adverse party (for example a false affidavit of service or of the amount); (4) lack of jurisdiction (for example service at the vacated unit: NY:CPLR-308-natural-person), with no one-year limit; (5) reversal of a judgment it rests on. The clerk vacates a CPLR 3215 default on a stipulation of the parties. An administrative judge may bring a proceeding to vacate groups of default judgments obtained by fraud, illegality, unconscionability or lack of due service. On vacatur the court may order restitution of what was collected. Operator step: serve the judgment with notice of entry on the tenant to start its one-year period for excusable default.",
                  "(a) On motion.", "subject to the same conditions as where a judgment is reversed or modified on appeal.",
                  severity="major", walk_step="8.9", determinacy="MIXED", judgment_terms=["excusable default", "misconduct of an adverse party"],
                  dependencies=["NY:CPLR-308-natural-person", "NY:CPLR-317-defend-after-default"])]),
    D("NY:CPLR 5016", "no_decision",
      "When a judgment is entered and how after a verdict or a party's death; clerical mechanics (substitution and death are stated at NY:CPLR-1203-1015-5208-parties)."),
    D("NY:CPLR 5018", "new_rule",
      "Docketing of a money judgment (and by transcript in other counties) with the debtor's last known address; a docketed judgment is the lien on the former tenant's real property and must mark unsummoned joint debtors.",
      proposed=[R("NY:CPLR-5018-docketing", "NY:CPLR 5018", "CPLR 5018(a), (c)", "landlord (judgment creditor)", "rule",
                  "The landlord obtains a money judgment against a former tenant and wants it to bind the tenant's real property in a county.",
                  "The clerk dockets a money judgment on filing of the judgment-roll; a judgment of a court other than the Supreme, County or Family Court (such as the NYC Civil Court) is docketed by the county clerk on filing a transcript (NY:CCA-1502-transcript), and in any other county on filing a transcript of that docket, with the same effect as a Supreme Court judgment docketed there. On a joint liability, 'not summoned' is written next to each defendant not served. The docket shows each debtor's name and last known address, the creditor's name and address, the sum, dates and court; if no address is known, the party docketing files an affidavit saying so.",
                  "(a) Docketing by clerk; docketing elsewhere by transcript.", "stating that the affiant has no knowledge of an address.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CCA-1502-transcript"])]),
    D("NY:CPLR 5019", "new_rule",
      "A person other than the judgment creditor who becomes entitled to enforce the judgment (an assignee such as a collector or debt buyer) must file its acknowledged instrument with the clerk before enforcing; changes the steps when the landlord assigns a judgment.",
      proposed=[R("NY:CPLR-5019-assignee-of-judgment", "NY:CPLR 5019", "CPLR 5019(c)", "assignee of the landlord's judgment", "obligation",
                  "The landlord assigns or transfers a money judgment against a former tenant to another person (a collection agency, debt buyer or affiliate) who will enforce it.",
                  "The assignee files, with the clerk of the court that entered the judgment (for a Civil Court judgment docketed with the county clerk, with that county clerk), a copy of the instrument of its authority acknowledged as for recording a deed, or a certified copy of the court order; the clerk notes the change on the docket. This does not apply to a transfer of a balance on which no judgment exists (whose limits are NY:JUD-489-champerty and NY:CCA-1809(1)).",
                  "(c) Change in judgment creditor.", "where no judgment exists.",
                  severity="minor", walk_step="8.12", dependencies=["NY:JUD-489-champerty"])]),
    D("NY:CPLR 5020-A", "new_rule",
      "A landlord that owes a former tenant a judgment, and whose certified-mail payment to the tenant's last known address came back, may deposit a certified check with the clerk to stop execution charges; the route for paying an unlocatable tenant's judgment.",
      proposed=[R("NY:CPLR-5020-a-deposit-with-clerk", "NY:CPLR 5020-A", "CPLR 5020-a", "landlord (judgment debtor)", "permission",
                  "A former tenant holds a money judgment against the landlord (for example for the deposit), an execution has issued, and the landlord's payment sent by registered or certified mail, return receipt requested, to the tenant's last known address came back unclaimed or undeliverable.",
                  "On showing that to the clerk of the court that issued the execution, the landlord may deposit with the clerk a certified check for the full amount that satisfies the judgment; execution charges then stop accruing and the clerk notifies each sheriff that the execution is rescinded (effective on the sheriff's receipt). Satisfaction is entered on the docket only under CPLR 5021 (NY:CPLR-5021-entry-of-satisfaction).",
                  "When a judgment debtor has shown to the satisfaction of the clerk of the court", "except pursuant to the provisions of section 5021.",
                  severity="major", walk_step="7.6", dependencies=["NY:CPLR-5021-entry-of-satisfaction"])]),
    D("NY:CPLR 5021", "partial",
      "The satisfaction rule states the creditor's duty to file a satisfaction-piece; 5021 adds how a paying judgment debtor gets satisfaction entered when the creditor will not furnish one (court order or deposit), and the sheriff's return of a small-claims execution within 90 days.",
      atoms=["NY:CPLR-5020-satisfaction"],
      proposed=[R("NY:CPLR-5021-entry-of-satisfaction", "NY:CPLR 5021", "CPLR 5021(a)-(b)", "judgment debtor (landlord or former tenant); judgment creditor", "rule",
                  "A money judgment between the landlord and a former tenant is paid in whole or part.",
                  "The clerk enters satisfaction on the docket on the filing of a satisfaction-piece (NY:CPLR-5020-satisfaction); or, where the debtor paid but cannot get a satisfaction-piece from the creditor (for example an unlocatable former tenant), on a court order made on motion; or on a court-permitted deposit with the clerk of the sum that satisfies it, if no execution with unpaid sheriff's fees is outstanding; or on filing a release of a compounding joint debtor (satisfied as to that debtor only). A sheriff returns a satisfied execution and the clerk enters it; an execution on a small-claims or commercial-claims judgment is returned and entered within 90 days after the sheriff receives it, whether satisfied or not.",
                  "(a) Entry upon satisfaction-piece, court order, deposit into court, discharge of compounding joint debtor.", "and the clerk shall make an appropriate entry on his docket of the judgment.",
                  severity="minor", walk_step="8.12", amends="NY:CPLR-5020-satisfaction", dependencies=["NY:CPLR-5020-satisfaction", "NY:CCA-1811(d)-satisfaction-proof"])]),
    D("NY:CPLR 5101", "no_decision",
      "Says a money judgment or money order is enforced under CPLR article 52; the article 52 rules themselves carry the steps and limits (NY:CPLR-5205-5231-enforcement-limits and the article 52 rules proposed in this batch)."),
    D("NY:CPLR 5104", "no_decision",
      "Contempt enforcement of judgments not enforceable under article 52 or 5102; a money judgment on a lease balance or deposit is enforced under article 52 (the fiduciary exception is CPLR 5105)."),
    D("NY:CPLR 5105", "new_rule",
      "A judgment requiring a trustee or fiduciary to pay money for a willful default may be enforced by contempt as well as by execution; the landlord holds the deposit in trust (GOL 7-103), so a judgment for a deposit it willfully withheld or commingled carries contempt exposure.",
      proposed=[R("NY:CPLR-5105-fiduciary-contempt", "NY:CPLR 5105", "CPLR 5105(2)", "landlord (judgment debtor)", "rule",
                  "A former tenant obtains a judgment requiring the landlord to pay back the security deposit, which the landlord held in trust as the tenant's money (NY:GOL-7-103(1)-trust). Branch (a): the judgment rests on the landlord's willful default or dereliction of that trust duty (for example commingling or a willful failure to return: NY:CASE-Paterno-commingling-forfeiture, NY:GOL-7-108(1-a)(g)). Branch (b): it rests only on the amount of lawful deductions or on a non-willful miss.",
                  "Branch (a): the judgment may be enforced by execution under article 52, by contempt (a certified copy served and, on refusal or willful neglect to pay, punishment for contempt: CPLR 5104), or both, because it requires a person holding money in a fiduciary relationship to pay for a willful default of its duty. Branch (b): enforcement is by execution only.",
                  "An interlocutory or final judgment or order, or any part thereof, may be enforced either by the method prescribed in article fifty-two", "to pay a sum of money for a willful default or dereliction of his duty.",
                  severity="major", walk_step="7.5", determinacy="MIXED", judgment_terms=["willful default or dereliction of duty"],
                  dependencies=["NY:GOL-7-103(1)-trust", "NY:GOL-7-108(1-a)(g)", "NY:CASE-Paterno-commingling-forfeiture"])]),
    D("NY:CPLR 514", "no_decision",
      "Voids venue clauses only in contracts for the sale or lease of consumer goods (goods, wares, merchandise or services); a residential lease of real property is not one, so the lease venue clause is governed by CPLR 501 (proposed NY:CPLR-501-venue-clause)."),
    D("NY:CPLR 5201", "partial",
      "The enforcement-limits rule states the exemptions; 5201 states what the landlord can reach (any assignable debt or property, present or future, in or out of state) and that a joint-liability judgment reaches individual property only of co-tenants summoned.",
      atoms=["NY:CPLR-5205-5231-enforcement-limits"],
      proposed=[R("NY:CPLR-5201-reachable-property", "NY:CPLR 5201", "CPLR 5201(a)-(b)", "landlord (judgment creditor)", "rule",
                  "The landlord enforces a money judgment against a former tenant.",
                  "It may enforce against any debt owed to the tenant, past due or to become due, and any property that could be assigned or transferred, present or future, vested or not, in or out of the state, unless exempt (NY:CPLR-5205-5231-enforcement-limits). A judgment on a joint liability (co-tenants) is enforced against the individual property of those summoned and their joint property with the others; the individual property of a co-tenant not summoned is reached only through NY:CPLR-1502-later-action-co-obligor.",
                  "(a) Debt against which a money judgment may be enforced.", "and joint property of such persons with any other persons against whom the judgment is entered.",
                  severity="minor", walk_step="8.12", amends="NY:CPLR-5205-5231-enforcement-limits",
                  dependencies=["NY:CPLR-5205-5231-enforcement-limits", "NY:CPLR-1502-later-action-co-obligor"])]),
    D("NY:CPLR 5202", "no_decision",
      "Priority between an execution creditor and third parties who acquire the debtor's property; it decides contests with transferees, not any step, amount or deadline in the landlord's settlement or collection."),
]
write(rows)
