from q2_lib import *

MECH = "in-suit litigation mechanics that change no amount, deadline, precondition or payee in settling the account or deciding to pursue it."
G103 = "register/texts/NY_GOL/7-103.txt"
rows = [
    D("NY:CCA 2104", "no_decision", "References to the predecessor City and Municipal Courts mean the Civil Court; interpretive housekeeping with no step."),
    D("NY:CPLR 101", "no_decision", "Short title and general application of the CPLR; the specific CPLR rules carry the steps."),
    D("NY:CPLR 1023", "no_decision", "Public bodies sued by official title; not parties to the tenancy."),
    D("NY:CPLR 1204", "new_rule",
      "A guardian ad litem appointed for an incapacitated or infant former tenant may be paid reasonable compensation by any other party, including the landlord that sued; a cost of pursuing such a tenant.",
      proposed=[R("NY:CPLR-1204-gal-compensation", "NY:CPLR 1204", "CPLR 1204", "landlord (plaintiff)", "rule",
                  "A guardian ad litem is appointed for a former tenant the landlord is suing (NY:CPLR-1202-guardian-ad-litem-motion).",
                  "The court may allow the guardian reasonable compensation, on the guardian's or its attorney's affidavit of services, payable in whole or part by any other party (the landlord), from any recovery for the tenant, or from the tenant's other property. The pursue-or-write-off estimate includes this possible cost.",
                  "A court may allow a guardian ad litem a reasonable compensation", "showing the services rendered.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-1202-guardian-ad-litem-motion"])]),
    D("NY:CPLR 1206", "new_rule",
      "Money an infant, adjudicated incompetent or conservatee former tenant recovers (for example a deposit settlement or judgment) is paid to its guardian, committee or conservator, or as the court orders, not to the person; decides to whom the landlord pays.",
      proposed=[R("NY:CPLR-1206-proceeds-payee", "NY:CPLR 1206", "CPLR 1206", "landlord (paying a settlement or judgment)", "rule",
                  "The landlord pays a settlement or judgment on a claim of a former tenant who is an infant, a person judicially declared incompetent, or a conservatee (for example on the deposit).",
                  "After court-allowed expenses, the money goes to the guardian of the property, committee or conservator, to hold for the person, unless the court orders otherwise: to an adult spouse of a married infant; up to $10,000 to a person the infant, incompetent or conservatee lives with or who has an interest in its welfare; into a specified insured bank account or investment withdrawable only by court order (payable to an infant at 18); or as held under CPLR 1210(d). Payment to the person directly does not discharge the landlord. A refund owed outside any claim to a tenant with a committee or conservator is paid to that representative.",
                  "Except as provided in EPTL 7-4.9, any property to which an infant,", "as provided by subdivision (d) of section 1210.",
                  severity="major", walk_step="6.6", dependencies=["NY:CPLR-1207-incapacitated-settlement"])]),
    D("NY:CPLR 1207", "new_rule",
      "A settlement of a claim by an infant, adjudicated incompetent or conservatee (for example a deposit claim of a tenant under guardianship) binds only when the court approves it on the representative's motion or petition; decides whether a settlement with such a tenant is final.",
      proposed=[R("NY:CPLR-1207-incapacitated-settlement", "NY:CPLR 1207", "CPLR 1207", "landlord; representative of the former tenant", "precondition",
                  "The landlord settles a claim or action brought by or on behalf of a former tenant who is an infant, a person judicially declared incompetent, or a conservatee.",
                  "The court orders the settlement on motion of the guardian of the property or guardian ad litem (or, for an infant without one, a parent or custodian or an adult spouse), the committee, or the conservator; if no action is pending, the representative petitions in a special proceeding in any court where an action for that amount could be brought. Notice is given as the court directs. The order has the effect of a judgment, is entered without costs, and approves any attorney's fee. Until approved, the settlement does not bind the infant or incapacitated person. Payment follows NY:CPLR-1206-proceeds-payee.",
                  "Upon motion of a guardian of the property or guardian ad litem of an infant", "shall approve the fee for the infant’s, incompetent’s or conservatee’s attorney, if any.",
                  severity="major", walk_step="8.1b", dependencies=["NY:CPLR-1206-proceeds-payee"])]),
    D("NY:CPLR 1210", "no_decision", "Appointment of a guardian of an infant's property by petition; the landlord pays and settles through a guardian already appointed (proposed NY:CPLR-1206-proceeds-payee) and takes no step here."),
    D("NY:CPLR 2105", "no_decision", "Attorneys may certify copies; clerical, no settlement step."),
    D("NY:CPLR 2211", "no_decision", "Defines a motion; " + MECH),
    D("NY:CPLR 2212", "no_decision", "Where Supreme Court motions are heard; " + MECH),
    D("NY:CPLR 2213", "no_decision", "Where County Court motions are heard; outside New York City."),
    D("NY:CPLR 2217", "no_decision", "Prior motions, ex parte affidavits and transfer of motions; " + MECH),
    D("NY:CPLR 3014", "no_decision", "Pleadings in numbered paragraphs; " + MECH),
    D("NY:CPLR 306-C", "no_decision", "Notice to social services of personal injury actions by Medicaid recipients; not a claim in the chain."),
    D("NY:CPLR 328", "no_decision", "Service in New York for out-of-state tribunals; it does not bind recognition of foreign judgments and adds no step in the chain."),
    D("NY:CPLR 4504", "no_decision", "Physician-patient privilege; an evidentiary privilege with no settlement step."),
    D("NY:CPLR 4515", "no_decision", "Form of expert opinion testimony; trial evidence, no settlement step."),
    D("NY:CPLR 4523", "no_decision", "Title company searches in place of official searches; not used in the chain."),
    D("NY:CPLR 4534", "no_decision", "Surveyors' measurement standards; not used in the chain."),
    D("NY:CPLR 4538", "no_decision", "An acknowledged writing is prima facie proof of execution; residential leases are not acknowledged and the lease is proved as a business record or by the parties, so no step turns on it."),
    D("NY:CPLR 5017", "no_decision", "Preparation and contents of the judgment-roll; clerk and attorney mechanics."),
    D("NY:CPLR 6402", "no_decision", "Oath of a temporary receiver; the receiver's duty."),
    D("NY:CPLR 6403", "no_decision", "Undertaking of a temporary receiver; the receiver's duty."),
    D("NY:CPLR 8006", "no_decision", "Fiduciaries' bond premiums as expenses; not the landlord's cost."),
    D("NY:CPLR 8009", "no_decision", "Fees of officers for oaths and acknowledgments ($2); affirmations under CPLR 2106 avoid them, and they are not a decision in the chain."),
    D("NY:CPLR 8010", "new_rule",
      "The NYC Commissioner of Finance takes 2% of money paid out of court; a deposit refund the landlord pays into court (interpleader, or a tender left unclaimed) reaches the claimant less 2%, which the court may charge against the fund.",
      proposed=[R("NY:CPLR-8010-court-fund-fee", "NY:CPLR 8010", "CPLR 8010(1), (4)", "landlord; claimant to a fund in court", "rule",
                  "Money over the tenancy is paid into court and later paid out (a deposit refund paid in on interpleader, NY:CPLR-1006-interpleader, or a CPLR 3219 tender not withdrawn in ten days and deemed paid into court).",
                  "The county treasurer, in New York City the Commissioner of Finance, takes 2% of the sum paid out of court (and 2% of the par value of securities deposited, paid by the depositor). The fee comes out of the fund unless the court charges it to a party as part of the costs it allows.",
                  "1. two per cent upon a sum of money paid out of court by him;", "to be paid at the time of the deposit by the parties making it; and",
                  severity="minor", walk_step="6.6", dependencies=["NY:CPLR-1006-interpleader", "NY:CPLR-3219-tender"])]),
    D("NY:Judiciary Law 474-A", "no_decision", "Contingent-fee caps in medical malpractice cases; not a claim in the chain."),
    D("NY:Judiciary Law 474-B", "no_decision", "Sharing attorney retainer statements with social services; not a step in the chain."),
    D("NY:Judiciary Law 476-A", "no_decision", "Attorney General actions for unauthorized practice of law; an enforcement remedy for the State. The prohibitions that bind Handoff are stated (NY:CPLR-321-JUD-495-appearance) and proposed (NY:JUD-484-nonlawyer-preparation)."),
    D("NY:Judiciary Law 476-C", "no_decision", "Attorney General investigations of unauthorized practice; an enforcement power for the State."),
    D("NY:Judiciary Law 483", "no_decision", "Signs advertising legal services must name the attorney; no settlement step."),
    D("NY:Judiciary Law 486", "no_decision", "Practice by disbarred or suspended attorneys; it binds such persons, not the landlord or Handoff."),
    D("NY:Judiciary Law 497", "new_rule",
      "Attorney escrow funds that are nominal or short-term go into an IOLA account whose interest goes to the state fund; a tenant's security deposit held for the tenancy by the landlord's attorney is neither, and GOL 7-103 gives any interest to the tenant, so it cannot sit in IOLA.",
      proposed=[R("NY:JUD-497-attorney-escrow-deposit", "NY:Judiciary Law 497", "Judiciary Law 497(1)-(4); GOL 7-103", "landlord's attorney holding the deposit in escrow", "obligation",
                  "The landlord's attorney (or a law firm) holds a tenant's security deposit in escrow for the tenancy (a lease or co-op or condo sublet arrangement).",
                  "IOLA accounts are for qualified funds, those too small or held too briefly to earn net interest for the client, whose interest goes to the IOLA fund. A security deposit held for the term is money of the tenant in trust (NY:GOL-7-103(1)-trust), and any interest it earns belongs to the tenant less the 1% fee (NY:GOL-7-103(2)-interest-owed); the specific deposit statute controls over the attorney's IOLA discretion. So: in a building of six or more units the attorney holds it in a separate interest-bearing account at a New York bank with interest paid to the tenant (NY:GOL-7-103(2-a)); in a smaller building, in a separate non-interest escrow account or a separate interest-bearing account with interest to the tenant, never in IOLA. The bank-notice duty applies (NY:GOL-7-103(2)-bank-notice).",
                  "1. An “interest on lawyer account” or “IOLA” is an unsegregated interest-bearing deposit account", "such funds shall be deposited in an IOLA account in a banking institution of his or her choice offering such accounts.",
                  severity="minor", walk_step="1.2", determinacy="RULE",
                  dependencies=["NY:GOL-7-103(1)-trust", "NY:GOL-7-103(2)-interest-owed", "NY:GOL-7-103(2-a)", "NY:GOL-7-103(2)-bank-notice"],
                  construction=[{"source_file": G103, "quote": q(G103, "Any provision of such a contract or agreement whereby a person who so deposits or advances money waives any provision of this section is absolutely void.")}],
                  reasoning="GOL 7-103 makes the deposit the tenant's trust money and gives the tenant the interest on any interest-bearing account; its anti-waiver clause bars any arrangement diverting that interest. Judiciary Law 497 is a general rule for attorney escrow and yields to the specific deposit statute; a deposit held for the whole tenancy is also not 'held for too short a time' within 497(2).")]),
]
write(rows)
