from q2_lib import *

NOE = "enforcement-officer or court mechanics that add no step, amount or deadline for the landlord or tenant."
rows = [
    D("NY:CPLR 510", "no_decision", "Grounds on which a court may change venue (improper county, impartiality, convenience); the timing that binds a defendant is CPLR 511 (proposed NY:CPLR-511-venue-demand)."),
    D("NY:CPLR 5103", "no_decision", "Enforcement of judgments directing sale of specific real property (foreclosure, partition); not a money judgment on a lease."),
    D("NY:CPLR 5106", "no_decision", "Receiver to carry out a judgment about specific property; not a money judgment on a lease (enforcement receivers are CPLR 5228, proposed)."),
    D("NY:CPLR 5107", "no_decision", "Court may direct the sheriff's conveyance; " + NOE),
    D("NY:CPLR 511", "new_rule",
      "In Supreme Court a former tenant who objects to the landlord's county must serve a written demand with or before its answer and move within 15 days; otherwise venue stands. Mirrors the Civil Court rule.",
      proposed=[R("NY:CPLR-511-venue-demand", "NY:CPLR 511", "CPLR 511(a)-(b)", "landlord (plaintiff); former tenant (defendant)", "rule",
                  "The landlord sues a former tenant in the Supreme Court in a county the tenant says is not proper (or the tenant sues the landlord).",
                  "The defendant serves a written demand, with or before its answer, that the action be tried in a county it names as proper, and may move within 15 days after the demand unless the plaintiff consents within five days; the plaintiff may serve within five days an affidavit showing its county is proper or the defendant's is not. A motion on other grounds (impartiality, convenience) is made within a reasonable time after commencement. Without a timely demand the plaintiff's county stands. Civil Court counterpart: NY:CCA-306-venue-objection.",
                  "(a) Time for motion or demand.", "or that the county designated by him is proper.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-306-venue-objection"])]),
    D("NY:CPLR 512", "no_decision", "Place of trial for non-jury issues within the judicial district; in-suit mechanics."),
    D("NY:CPLR 5207", "no_decision", "The State as judgment debtor or garnishee; a former tenant's state wages are reached by the income execution already stated (NY:CPLR-5205-5231-enforcement-limits), adding no step."),
    D("NY:CPLR 5237", "no_decision", "An execution-sale purchaser's recovery of the price if title fails; a remote contest after a sheriff's sale that adds no settlement step."),
    D("NY:CPLR 5238", "no_decision", "Court directions to the sheriff on levied property; " + NOE),
    D("NY:CPLR 6001", "no_decision", "Lists the provisional remedies and requires disclosure of other remedies sought; the attachment rules proposed at CPLR 6201-6223 carry the steps."),
    D("NY:CPLR 6210", "no_decision", "Attachment on notice and an interim restraint on garnishees; mechanics within the proposed attachment rules (CPLR 6201, 6211, 6212)."),
    D("NY:CPLR 6217", "no_decision", "Undertaking to a common-carrier garnishee; not a party in the chain."),
    D("NY:CPLR 6220", "no_decision", "Court-ordered disclosure about attached property; " + NOE),
    D("NY:CPLR 6225", "no_decision", "Directions to the clerk and sheriff to release attached property; " + NOE),
    D("NY:CPLR 6404", "no_decision", "Temporary receivers' accounts; the receiver's duty, not the landlord's."),
    D("NY:CPLR 8001", "new_rule",
      "A non-party subpoenaed to testify or produce records gets $15 a day plus mileage outside a city (and $3 more at an examination before trial); a cost the landlord tenders when it subpoenas a bank or employer to find a former tenant's assets.",
      proposed=[R("NY:CPLR-8001-witness-fees", "NY:CPLR 8001", "CPLR 8001(a)-(b)", "landlord (party serving a subpoena)", "obligation",
                  "The landlord subpoenas a person to attend (a trial, an examination, or an article 52 deposition or production: NY:CPLR-5224-enforcement-subpoenas).",
                  "The person receives $15 a day as attendance fee and 23 cents a mile travel each way from where served, with no mileage for travel wholly within a city; a non-party subpoenaed to an examination before trial gets $3 more a day. The judgment debtor and recipients of information subpoenas get no fee (CPLR 5224(b)). These fees are recoverable disbursements (NY:CCA-1908-disbursements, NY:CPLR-8301-disbursements).",
                  "(a) Persons subpoenaed.", "he shall receive an additional three dollars for each day’s attendance.",
                  severity="minor", walk_step="8.12", dependencies=["NY:CPLR-5224-enforcement-subpoenas"])]),
    D("NY:CPLR 8003", "no_decision", "Referees' fees; no referee is used in settling or collecting the account."),
    D("NY:CPLR 8004", "no_decision", "Receivers' commissions (up to 5%); stated for enforcement receivers at proposed NY:CPLR-5228-receiver."),
    D("NY:CPLR 8007", "no_decision", "Newspaper publication rates; no publication route exists for a balance or deposit action (see CPLR 315)."),
    D("NY:CPLR 8008", "no_decision", "Officers transmit papers only on request and payment of fees; " + NOE),
    D("NY:CPLR 8015", "no_decision", "County clerk's fees when acting for a disqualified sheriff; " + NOE),
    D("NY:CPLR 8016", "no_decision", "Fees of clerks of courts of record other than the NYC Civil Court and county clerks; not the courts where this chain's suits are brought."),
    D("NY:CPLR 8017", "no_decision", "Fee exemptions for the State and counties; not parties to the tenancy."),
    D("NY:CPLR 8018", "new_rule",
      "Commencing a Supreme Court action costs a $190 index-number fee (plus $20 in surcharges), which covers later filings including judgment and satisfaction docketing; a cost of choosing Supreme Court for the balance suit.",
      proposed=[R("NY:CPLR-8018-index-fee", "NY:CPLR 8018", "CPLR 8018(a), (d)", "landlord (plaintiff) or former tenant (plaintiff)", "rule",
                  "A party commences an action over the tenancy in the Supreme Court (NY:CPLR-304-commencement).",
                  "The county clerk charges $190 for the index number, plus an additional $5 and $15 for state funds, payable in advance; with the index number assigned, no further county clerk fee is charged for filing, entering, docketing or recording papers in the action, entering judgment, taxing costs, docketing a satisfaction or an execution return, or discharging a judgment by deposit. Filing a Civil Court transcript with the county clerk is not an action and does not require an index number. Fees are recovered only as disbursements in a judgment (NY:CPLR-8301-disbursements). Civil Court fees: NY:CCA-1911-clerk-fees.",
                  "(a) Amount of fee.", "for discharging a judgment of record by deposit with the clerk.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-304-commencement", "NY:CPLR-8301-disbursements"])]),
    D("NY:CPLR 8019", "no_decision", "County clerks' general recording and copying fees; none is a step in a lease-balance or deposit suit beyond the index fee (CPLR 8018)."),
    D("NY:CPLR 8020", "new_rule",
      "Supreme Court fees after filing: $95 request for judicial intervention (needed for any motion, including a default judgment motion), $45 per motion, $30 to calendar, $65 jury demand, and $35 paid by the defendant to file a settlement or discontinuance; costs in the pursue decision and on settling a suit.",
      proposed=[R("NY:CPLR-8020-court-fees", "NY:CPLR 8020", "CPLR 8020(a), (c)-(d)", "landlord; former tenant", "rule",
                  "An action over the tenancy is pending in the Supreme Court.",
                  "Fees payable in advance to the county clerk: $95 for a request for judicial intervention before a judge is assigned, then $30 to place the cause on a trial or inquest calendar (without an RJI regime, $125); $45 for each motion or cross-motion (none for a poor-person motion); $65 for a jury demand in New York City counties; and, when the action is settled or discontinued, $35 paid by the defendant for filing the stipulation of settlement or notice of discontinuance (NY:CPLR-2104-stipulations, NY:CPLR-3217-discontinuance). These are recoverable only as disbursements through a judgment.",
                  "(a) Placing cause on calendar.", "Provided, however, that only one such fee shall be charged for each notice, stipulation or certificate filed pursuant to this subdivision.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-2104-stipulations", "NY:CPLR-3217-discontinuance"])]),
    D("NY:CPLR 8022", "no_decision", "Fees on civil appeals; appellate practice."),
    D("NY:CPLR 8203", "no_decision", "Costs on appeals to the Appellate Division and Term; appellate practice."),
    D("NY:CPLR 8204", "no_decision", "Costs on appeals to the Court of Appeals; appellate practice."),
    D("NY:CPLR 8404", "no_decision", "Court review of the clerk's taxation of costs on motion; in-suit mechanics (the taxation rule is proposed at NY:CPLR-8401-clerk-taxation)."),
    D("NY:Judiciary Law 469", "no_decision", "Continuances when counsel is a legislator in session; in-suit mechanics."),
    D("NY:Judiciary Law 475-A", "new_rule",
      "An attorney who serves a written notice of lien before suit (for example with a tenant's deposit demand) has a lien from that notice on any settlement or recovery, unaffected by a later direct settlement; decides to whom a pre-suit deposit settlement is paid.",
      proposed=[R("NY:JUD-475-a-notice-of-lien", "NY:Judiciary Law 475-A", "Judiciary Law 475-a", "landlord; former tenant's attorney", "rule",
                  "Before any action or ADR, the former tenant's attorney serves the landlord, personally or by registered mail, a written notice of lien stating the attorney-client relationship, the nature of the claim (for example the deposit) and the lien claimed, signed by the client (witnessed by a disinterested person with address) and by the attorney.",
                  "From the notice, the attorney has a lien on the claim that attaches to any settlement, award or recovery and to the money in whatever hands it comes, and no settlement between landlord and tenant after the notice defeats it; it is enforced like a Judiciary Law 475 lien (NY:JUD-475-attorney-lien). Operator step: after such a notice, pay any refund or settlement to the tenant and attorney jointly or as the attorney directs. A notice lacking the required form or service creates no pre-suit lien.",
                  "If prior to the commencement of an action, arbitration, mediation", "shall otherwise have the same effect and be enforced in the same manner as a lien obtained under section four hundred seventy-five of this article.",
                  severity="major", walk_step="7.6", dependencies=["NY:JUD-475-attorney-lien"])]),
    D("NY:Judiciary Law 476", "new_rule",
      "An attorney who knowingly lets a non-partner prosecute an action in the attorney's name, and the person who does so, each forfeit $50 to the other side; bars Handoff or a manager from running suits in a lawyer's name.",
      proposed=[R("NY:JUD-476-lending-name", "NY:Judiciary Law 476", "Judiciary Law 476", "Handoff; managing agent; collection attorney", "prohibition",
                  "Handoff, a manager or another non-lawyer (not the attorney's general law partner or a clerk in its office) prosecutes a balance action against a former tenant in an attorney's name, with the attorney's knowing permission (the attorney lends its name; the non-lawyer runs the case).",
                  "The attorney and the person using its name each forfeit $50 to the former tenant, recoverable in an action; the conduct is also a misdemeanor for both (NY:JUD-492-use-of-attorney-name). The attorney must actually conduct the suit.",
                  "If an attorney knowingly permits a person not being his general law partner,", "the sum of fifty dollars, to be recovered in an action.",
                  severity="minor", walk_step="8.10", dependencies=["NY:JUD-492-use-of-attorney-name", "NY:CPLR-321-JUD-495-appearance"])]),
    D("NY:Judiciary Law 476-B", "no_decision", "Injunctions in unauthorized-practice actions brought by the Attorney General or a bar association; an enforcement remedy for others, not a settlement step."),
    D("NY:Judiciary Law 477", "no_decision", "Attorney consent to settlements of personal injury actions; not a claim in the chain."),
    D("NY:Judiciary Law 479", "new_rule",
      "No person may solicit legal business or retainers for an attorney; bars Handoff or a manager from soliciting owners' collection matters or tenants' claims for a law firm.",
      proposed=[R("NY:JUD-479-no-solicitation", "NY:Judiciary Law 479", "Judiciary Law 479, 485", "Handoff; managing agent", "prohibition",
                  "Handoff or a manager, or its employees or agents, solicits or procures for an attorney legal business, a retainer, or an agreement authorizing the attorney to render legal services (for example signing up owners to retain a collection firm on the firm's behalf, or steering former tenants to a lawyer), or makes a business of doing so.",
                  "It is unlawful and a misdemeanor (Judiciary Law 485). The owner may itself choose and retain counsel; Handoff may give the owner the facts of its balance, but may not act as the attorney's solicitor. Payment for referrals is separately barred (NY:JUD-491-no-fee-sharing).",
                  "It shall be unlawful for any person or his agent, employee or any person acting on his behalf,", "or to make it a business so to solicit or procure such business, retainers or agreements.",
                  severity="minor", walk_step="8.6a", dependencies=["NY:JUD-491-no-fee-sharing"])]),
    D("NY:Judiciary Law 481", "no_decision", "Bars hospital, police, prison, court and bail-bond personnel from aiding attorney solicitation; none is an actor in the chain."),
    D("NY:Judiciary Law 485-A", "partial",
      "The appearance rule makes unauthorized practice a misdemeanor; 485-a makes it a class E felony where the person falsely holds itself out as able to provide attorneys' services and causes loss over $1,000.",
      atoms=["NY:CPLR-321-JUD-495-appearance"],
      proposed=[R("NY:JUD-485-a-felony", "NY:Judiciary Law 485-A", "Judiciary Law 485-a", "Handoff; managing agent", "prohibition",
                  "Handoff, a manager or its staff violates Judiciary Law 478, 484, 486 or 495 (appearing, preparing pleadings or practicing law for an owner or tenant) and falsely holds itself out as licensed or able to provide services only attorneys may provide.",
                  "If the conduct causes another person monetary loss or damage over $1,000, or other material damage from impairment of a legal right (for example a lost claim or a void default judgment), it is a class E felony rather than a misdemeanor.",
                  "Any person who violates the provisions of sections four hundred seventy-eight,", "resulting from impairment of a legal right to which he or she is entitled.",
                  severity="major", walk_step="8.10", amends="NY:CPLR-321-JUD-495-appearance", dependencies=["NY:CPLR-321-JUD-495-appearance", "NY:JUD-484-nonlawyer-preparation"])]),
    D("NY:Judiciary Law 487", "new_rule",
      "An attorney who deceives a court or party (for example with a false affidavit of service or amount in a balance suit) is liable to the injured former tenant for treble damages; a risk the owner's choice of collection counsel carries.",
      proposed=[R("NY:JUD-487-attorney-deceit", "NY:Judiciary Law 487", "Judiciary Law 487", "collection attorney; landlord", "rule",
                  "An attorney pursuing a former tenant's balance for the landlord (or defending the landlord) engages in deceit or collusion, or consents to it, with intent to deceive the court or a party (for example knowingly filing a false affidavit of service, of the amount due, or of non-military status), or willfully delays the client's suit for its own gain.",
                  "The attorney is guilty of a misdemeanor and forfeits treble damages to the injured party (the tenant, or the landlord where the attorney deceived it), recoverable in a civil action; a judgment obtained by such deceit is open to vacatur for fraud (NY:CPLR-5015-relief-from-judgment).",
                  "An attorney or counselor who:", "he forfeits to the party injured treble damages, to be recovered in a civil action.",
                  severity="minor", walk_step="8.9", determinacy="MIXED", judgment_terms=["intent to deceive"], dependencies=["NY:CPLR-5015-relief-from-judgment"])]),
    D("NY:Judiciary Law 490", "partial",
      "The champerty rule treats an assignment of a balance taken to sue on as void; 490 excepts a claim received in payment for services actually rendered or for a pre-existing debt, which changes whether an owner can assign a balance to Handoff or a vendor in payment of what it owes them.",
      atoms=["NY:JUD-489-champerty"],
      proposed=[R("NY:JUD-490-champerty-exception", "NY:Judiciary Law 490", "Judiciary Law 490", "owner; Handoff; vendor; collector", "rule",
                  "An owner transfers a former tenant's balance (a book debt or thing in action) to Handoff, a manager, a vendor or another person. Branch (a): the transfer is in payment for property sold or services actually rendered to the owner, or for a debt the owner already owed the transferee. Branch (b): the transfer is made so the transferee can sue on the balance, with no such payment purpose.",
                  "Branch (a): Judiciary Law 488 and 489 do not prohibit the transfer; the transferee may enforce the balance in its own name (it is then an assignee barred from small claims, NY:CCA-1809(1), and, if it collects balances for others or buys them as a business, subject to the collection licensing and conduct rules, NYC:DCA-debt-buyer). Branch (b): NY:JUD-489-champerty governs.",
                  "Sections four hundred eighty-eight and four hundred eighty-nine of this chapter do not prohibit", "for the purpose of remittance.",
                  severity="major", walk_step="8.1b", amends="NY:JUD-489-champerty", dependencies=["NY:JUD-489-champerty", "NY:CCA-1809(1)", "NYC:DCA-debt-buyer"])]),
    D("NY:Judiciary Law 492", "new_rule",
      "An attorney who knowingly lets a non-partner prosecute an action in the attorney's name, and the person who uses the name, commit a misdemeanor; the criminal counterpart of Judiciary Law 476.",
      proposed=[R("NY:JUD-492-use-of-attorney-name", "NY:Judiciary Law 492", "Judiciary Law 492", "Handoff; managing agent; collection attorney", "prohibition",
                  "A non-lawyer (Handoff, a manager, a collector that is not the attorney's partner or office clerk) sues out process or prosecutes or defends an action in an attorney's name with the attorney's knowing permission.",
                  "The attorney and every person who so uses the name commit a misdemeanor (civil forfeiture: NY:JUD-476-lending-name).",
                  "If an attorney knowingly permits any person, not being his general law partner or a clerk in his office,", "such attorney, and every person who shall so use his name, is guilty of a misdemeanor.",
                  severity="minor", walk_step="8.10", dependencies=["NY:JUD-476-lending-name"])]),
]
write(rows)
