from q2_lib import *

MECH = "in-suit Supreme Court litigation mechanics (calendar, discovery, motion, trial or papers practice) that change no amount, deadline, precondition or payee in settling the account or deciding to pursue it."
rows = [
    D("NY:22 NYCRR 202.1", "no_decision", "Scope, waiver and definitions of the Supreme Court rules; no rule of this chain depends on it beyond the rules it introduces."),
    D("NY:22 NYCRR 202.11", "no_decision", "Counsel's consultation before preliminary conferences; " + MECH),
    D("NY:22 NYCRR 202.12a", "no_decision", "Settlement conferences in residential mortgage foreclosure actions on home loans; not a landlord-tenant claim."),
    D("NY:22 NYCRR 202.13", "no_decision", "Removal of Supreme Court actions to lower courts without consent (CPLR 325(d)); a court's docket power that adds no step for the parties (costs after removal: CPLR 8104)."),
    D("NY:22 NYCRR 202.19", "no_decision", "Differentiated case management tracks; " + MECH),
    D("NY:22 NYCRR 202.20", "no_decision", "Limit of 25 interrogatories; " + MECH),
    D("NY:22 NYCRR 202.20-a", "no_decision", "Privilege logs; " + MECH),
    D("NY:22 NYCRR 202.20-c", "no_decision", "Responses to document requests; " + MECH),
    D("NY:22 NYCRR 202.20-i", "no_decision", "Direct testimony by affidavit at a non-jury trial on request; " + MECH),
    D("NY:22 NYCRR 202.21", "no_decision", "Note of issue and certificate of readiness; " + MECH + " (The want-of-prosecution consequence is CPLR 3216, proposed.)"),
    D("NY:22 NYCRR 202.24", "no_decision", "Trial preferences (CPLR 3403), mainly personal-injury; " + MECH),
    D("NY:22 NYCRR 202.25", "no_decision", "Objections to trial preferences; " + MECH),
    D("NY:22 NYCRR 202.27-a", "no_decision",
      "Default-judgment proof rules for consumer credit transactions, defined here as revolving or open-end credit extended by a financial institution; a residential lease balance is not one (NY:ADJ-lease-balance-not-consumer-credit)."),
    D("NY:22 NYCRR 202.28", "new_rule",
      "Parties, including self-represented ones, must promptly notify the court in writing when a case is settled or discontinued, or when a party dies or files for bankruptcy; a step the landlord must take when a sued former tenant settles, dies or files.",
      proposed=[R("NY:22NYCRR-202.28-notify-court", "NY:22 NYCRR 202.28", "22 NYCRR 202.28", "landlord (party) or its counsel; former tenant", "obligation",
                  "An action over the tenancy is pending in the Supreme Court and it is settled, discontinued or otherwise disposed of, becomes wholly or partly moot, or a party dies or files a bankruptcy petition.",
                  "Counsel, and a self-represented party, must promptly notify the assigned judge in writing, and on settlement or discontinuance immediately submit a copy of the stipulation or a letter to the part clerk with notice to chambers, in addition to filing the stipulation with the county clerk. On the tenant's bankruptcy filing the landlord also stops pursuing the claim (US:11USC362(a)(6)).",
                  "(a) If an action is settled, discontinued, or otherwise disposed of,", "Such notification shall be made to the assigned judge in writing.",
                  severity="minor", walk_step="8.8", dependencies=["US:11USC362(a)(6)", "NY:CPLR-2104-stipulations"])]),
    D("NY:22 NYCRR 202.32", "no_decision", "Adjournments for counsel's engagement; " + MECH),
    D("NY:22 NYCRR 202.35", "no_decision", "Papers submitted for trial; " + MECH),
    D("NY:22 NYCRR 202.40", "no_decision", "Order of trial where a jury is demanded on some issues; " + MECH),
    D("NY:22 NYCRR 202.43", "no_decision", "References to referees and judicial hearing officers; " + MECH),
    D("NY:22 NYCRR 202.44", "no_decision", "Motions to confirm referees' reports; " + MECH),
    D("NY:22 NYCRR 202.5", "new_rule",
      "Papers filed in Supreme Court must omit the tenant's taxpayer or social security number, birth date (except year), minors' names and account numbers (except last four); governs what the landlord's filed evidence may contain. The index-number and format parts decide nothing.",
      proposed=[R("NY:22NYCRR-202.5(e)-redaction", "NY:22 NYCRR 202.5", "22 NYCRR 202.5(e)", "landlord, its attorney, Handoff (preparing filed papers)", "obligation",
                  "The landlord files papers in a Supreme Court action against a former tenant (or answers the tenant's action), including the lease, ledger, statement, payment records or screening documents.",
                  "The filer omits or redacts confidential personal information: a taxpayer identification or social security number except the last four digits; a birth date except the year; the full name of a known minor except initials; a financial account number (card, bank, investment, insurance) except the last four digits; and sealed matrimonial material. The court may order removal, resubmission or sealing, or permit inclusion for good cause. The consumer-credit account-number exception does not reach a lease balance (NY:ADJ-lease-balance-not-consumer-credit). NYC Civil Court counterpart: NY:22NYCRR-208.4(b)-redaction.",
                  "(e) Omission or redaction of confidential personal information.", "for good cause permit the inclusion of CPI in papers;",
                  severity="major", walk_step="6.10", dependencies=["NY:22NYCRR-208.4(b)-redaction"])]),
    D("NY:22 NYCRR 202.52", "no_decision", "Bank accounts and accountings of court-appointed receivers and assignees; the receiver's duties, not the landlord's (enforcement receivers: CPLR 5228, proposed)."),
    D("NY:22 NYCRR 202.55", "no_decision", "Perfecting civil appeals to County Court from courts outside New York City; appellate practice."),
    D("NY:22 NYCRR 202.57", "no_decision",
      "Judicial review of State Division of Human Rights orders; the discrimination rules that bind the settlement are stated (NY:EXEC-296(5)(a)(2)-terms), and review procedure changes no settlement step."),
    D("NY:22 NYCRR 202.5bb", "new_rule",
      "In designated counties and case types a represented party must commence and litigate a Supreme Court action by NYSCEF e-filing (with a hard-copy exception on the last limitations day), while an unrepresented party is exempt; changes how a balance or deposit action is commenced and when it is interposed.",
      proposed=[R("NY:22NYCRR-202.5bb-mandatory-efiling", "NY:22 NYCRR 202.5bb", "22 NYCRR 202.5-bb(a)-(b), (e)(1)", "landlord's attorney; former tenant", "rule",
                  "A balance action against a former tenant, or a tenant's deposit action, is brought in the Supreme Court in a county and class of cases where the Chief Administrator has made e-filing mandatory.",
                  "A represented party commences the action by e-filing the initiating documents with the county clerk through NYSCEF; the clerk refuses hard copies. If the limitations period expires that day or the next business day and the filer cannot e-file for technical reasons, it may file in hard copy with an affirmation saying so and must e-file within three business days; the action counts as e-filed. Initiating papers are served under CPLR article 3 (NY:CPLR-308-natural-person), electronically only if the tenant agrees. An unrepresented litigant (an individual owner or a tenant appearing pro se) is exempt and cannot be compelled to e-file. Interposition: NY:CPLR-203-accrual-interposition.",
                  "(a) Application.", "he or she may at any time opt out of such participation by presenting the clerk of the court with a form so declaring.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-203-accrual-interposition", "NY:CPLR-308-natural-person"])]),
    D("NY:22 NYCRR 202.6", "no_decision", "The request for judicial intervention needed before a judge acts in a Supreme Court case; a filing step inside litigation whose fee is set by CPLR 8020, adding no settlement decision."),
    D("NY:22 NYCRR 202.7", "no_decision", "Motion calendaring, notice-of-motion form and good-faith affirmation for discovery motions; " + MECH),
]
write(rows)
