from q2_lib import *

rows = [
    D("NY:CCA 202", "new_rule",
      "Caps the NYC Civil Court's money jurisdiction at $50,000; a larger balance or deposit claim goes to Supreme Court. Decides the forum for the suit.",
      proposed=[R("NY:CCA-202-money-limit", "NY:CCA 202", "CCA 202", "landlord; former tenant", "rule",
                  "The landlord sues a former tenant for a balance, or the tenant sues for the deposit or damages.",
                  "Branch (a): the amount sought is $50,000 or less: the NYC Civil Court has jurisdiction (small claims up to $10,000: NY:CCA-1801-tenant-claim; commercial claims: NY:CCA-1801-A(a)-eligibility). Branch (b): more than $50,000: the claim goes to the Supreme Court, unless it exceeds the limit only because several claims each within the limit are joined (NY:CCA-211-joinder) or it is a counterclaim (NY:CCA-208-counterclaims).",
                  "The court shall have jurisdiction of actions and proceedings for the recovery of money,", "does not exceed $50,000.",
                  severity="major", walk_step="8.10")]),
    D("NY:CCA 204", "new_rule",
      "In an NYC summary proceeding the court renders judgment for rent due without regard to amount; this fixes what a nonpayment proceeding that preceded the move-out may already have awarded, which the final account credits and does not re-claim.",
      proposed=[R("NY:CCA-204-summary-rent-judgment", "NY:CCA 204", "CCA 204", "landlord (petitioner)", "rule",
                  "A summary proceeding to recover possession of an NYC unit, or to remove the tenant, preceded or caused the move-out.",
                  "The Civil Court may render judgment for rent due in the proceeding without regard to amount. Rent awarded there is carried on the final account as a judgment, credited with any payment, and not claimed again; amounts not awarded are pursued by separate action (NY:RPAPL-749(3)-after-proceeding).",
                  "The court shall have jurisdiction over summary proceedings to recover possession", "and to render judgment for rent due without regard to amount,",
                  severity="minor", walk_step="3.8", dependencies=["NY:RPAPL-749(3)-after-proceeding"])]),
    D("NY:CCA 205", "new_rule",
      "Gives the Civil Court interpleader jurisdiction up to $50,000; the route by which a landlord facing competing claims to a refund (co-tenants, an estate, a trustee) pays it into court.",
      proposed=[R("NY:CCA-205-interpleader", "NY:CCA 205", "CCA 205", "landlord (stakeholder)", "permission",
                  "Two or more persons make conflicting claims to the deposit refund (for example co-tenants who disagree, a relative and an estate fiduciary), and the amount is $50,000 or less.",
                  "The landlord may bring interpleader in the NYC Civil Court under the CPLR (NY:CPLR-1006-interpleader).",
                  "The court shall have jurisdiction of an action of interpleader", "does not exceed $50,000.",
                  severity="minor", walk_step="6.6", dependencies=["NY:CPLR-1006-interpleader", "NY:ADJ-cotenants-payee"])]),
    D("NY:CCA 206", "new_rule",
      "Where the Chief Administrator has ordered it for the county, a Civil Court money action of $10,000 or less per claim (not small claims) is heard by an arbitration panel; this changes how the landlord's small balance suit is tried.",
      proposed=[R("NY:CCA-206-compulsory-arbitration", "NY:CCA 206", "CCA 206(c)", "landlord (plaintiff); former tenant", "rule",
                  "The landlord's balance action (or the tenant's deposit action) is a civil action for money only in the regular part of the NYC Civil Court, in a county where the Chief Administrator has ordered the arbitration program, seeking $10,000 or less per cause of action exclusive of costs and interest.",
                  "The action is heard and decided by a panel of arbitrators under the court's rules. Actions begun in the small claims part and not transferred are not included. Awards under CPLR article 75 within the court's jurisdiction are confirmed in the Civil Court.",
                  "(b) Proceedings on award under CPLR article 75.", "exclusive of costs and interest.",
                  severity="minor", walk_step="8.10")]),
    D("NY:CCA 208", "new_rule",
      "In NYC Civil Court a counterclaim for money is heard without regard to amount; the tenant's deposit counterclaim, or the landlord's balance counterclaim to a tenant's regular-part suit, is not capped at $50,000.",
      proposed=[R("NY:CCA-208-counterclaims", "NY:CCA 208", "CCA 208(a)-(b)", "landlord; former tenant", "rule",
                  "A party sued in the NYC Civil Court regular part over the tenancy counterclaims for money.",
                  "The court has jurisdiction of a counterclaim within its jurisdiction if sued separately, and of any counterclaim for money only without regard to amount. (Small claims limits counterclaims to its own limit: NY:CCA-1805-small-claims-remedies.)",
                  "The court shall have jurisdiction of counterclaims as follows:", "(b) Of any counterclaim for money only, without regard to amount.",
                  severity="minor", walk_step="7.6")]),
    D("NY:CCA 209", "new_rule",
      "Allows an order of attachment out of the NYC Civil Court wherever Supreme Court could issue one, and limits injunctions and receivers; a pre-judgment option against a tenant leaving the state or hiding assets.",
      proposed=[R("NY:CCA-209-provisional-remedies", "NY:CCA 209", "CCA 209(a)-(c)", "landlord (plaintiff)", "permission",
                  "The landlord sues a former tenant in the NYC Civil Court and seeks a remedy before judgment.",
                  "An order of attachment may issue if it could issue out of the Supreme Court in a like case (grounds: NY:CPLR-6201-attachment-grounds), executed only within New York City (NY:CCA-801-provisional-city-only). No injunction, restraining order or restraining notice issues except for chattel recovery, prevention of waste, a CCA 1508 enforcement proceeding, or housing-standards enforcement; no receiver except in an enforcement proceeding, a mortgage foreclosure or an MDL 309(5) action.",
                  "(a) Attachment, arrest, seizure of chattel.", "or in the removal or demolition of a building pursuant thereto.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CPLR-6201-attachment-grounds"])]),
    D("NY:CCA 211", "new_rule",
      "Several claims each within the $50,000 limit may be joined and judgment may exceed $50,000; changes whether a large combined balance (rent, damage, guaranty) can stay in Civil Court.",
      proposed=[R("NY:CCA-211-joinder", "NY:CCA 211", "CCA 211", "landlord (plaintiff)", "rule",
                  "The landlord's complaint joins several causes of action against a former tenant (for example rent after vacating and physical damage) whose total exceeds $50,000.",
                  "If each cause of action would be within the $50,000 limit if sued separately, the Civil Court has jurisdiction and may render judgment above $50,000 when the excess results solely from the joinder; judgment on a counterclaim is unlimited.",
                  "Where several causes of action are asserted in the complaint", "granting judgment in an unlimited amount on a counterclaim.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-202-money-limit"])]),
    D("NY:CCA 302", "no_decision",
      "Venue of real property actions (title, liens, possession other than summary proceedings); a suit for a lease balance or a deposit is a transitory money action, not a real property action."),
    D("NY:CCA 303", "no_decision",
      "Venue of a summary proceeding to recover possession, which is part of how possession is regained before the settlement chain starts; it changes nothing in the account."),
    D("NY:CCA 304", "no_decision",
      "Venue for actions by or against the City of New York or the Transit Authority; neither is a party to a market-rate tenancy settlement."),
    D("NY:CCA 306", "new_rule",
      "Suing in the wrong county is not fatal; the tenant must move to transfer at or before joinder of issue or waives venue. Changes the consequence of a venue error in the landlord's suit.",
      proposed=[R("NY:CCA-306-venue-objection", "NY:CCA 306", "CCA 306", "landlord (plaintiff); former tenant (defendant)", "rule",
                  "The landlord's balance action (or the tenant's deposit action) is filed in an NYC Civil Court county that is not a proper venue.",
                  "The wrong county is not a jurisdictional defect. The court may transfer on its own motion and must transfer on the defendant's written motion on notice, filed before or at joinder of issue, naming the proper county and stating the facts under oath. Without a timely motion the defendant waives venue.",
                  "The bringing of an action or proceeding in the wrong county shall not be deemed a jurisdictional", "except in the case of a real property action.",
                  severity="minor", walk_step="8.10", dependencies=["NY:22NYCRR-208.8-wrong-county"])]),
    D("NY:CCA 400", "new_rule",
      "An NYC Civil Court action is commenced by filing the summons and complaint with the fee (the limitations interposition date) and jurisdiction is acquired by service; the index number must be on the papers served.",
      proposed=[R("NY:CCA-400-commencement", "NY:CCA 400", "CCA 400", "landlord (plaintiff) or former tenant (plaintiff)", "rule",
                  "A balance action against a former tenant, or a tenant's deposit action, is brought in the NYC Civil Court regular part.",
                  "It is commenced by filing (delivering to the clerk in the county of suit) the summons and complaint with the CCA 1911 fee; that filing date is the commencement for CPLR 203 (NY:CPLR-203-accrual-interposition). The clerk date-stamps and returns a copy. Jurisdiction over the defendant is acquired only by serving it with the summons and complaint. The actual index number must appear on the summons as served; an omission is cured by stipulation or by leave of court, which is not unreasonably withheld.",
                  "1. An action is commenced in this court by filing a summons and complaint.", "or by leave of court, which shall not be unreasonably withheld.",
                  severity="critical", walk_step="8.10", dependencies=["NY:CPLR-203-accrual-interposition"])]),
    D("NY:CCA 401", "new_rule",
      "Who issues the Civil Court summons and what it must contain (answer with the clerk, the plaintiff's residence address, the attorney's office address); the consumer-credit bilingual summons does not reach a lease balance.",
      proposed=[R("NY:CCA-401-summons-form", "NY:CCA 401", "CCA 401(a), (b), (d)", "landlord (plaintiff) or its attorney", "obligation",
                  "The landlord sues a former tenant in the NYC Civil Court.",
                  "The summons is issued by the landlord's attorney or, if the landlord appears without an attorney (an individual owner), by the clerk. It directs the tenant to file an answer with the clerk, is in the form the rules prescribe, and states the plaintiff's residence address and, if an attorney issues it, the attorney's office address. The Spanish-and-English summons required in consumer credit transaction actions does not apply to a lease balance (NY:ADJ-lease-balance-not-consumer-credit).",
                  "(a) The summons may be issued by the plaintiff's attorney", "must be printed legibly in both Spanish and English.",
                  severity="minor", walk_step="8.10", dependencies=["NY:ADJ-lease-balance-not-consumer-credit"])]),
    D("NY:CCA 402", "new_rule",
      "Fixes the tenant's time to answer a Civil Court summons (20 days after personal delivery in the city; otherwise 30 days after proof of service is filed), which sets when a default judgment becomes available.",
      proposed=[R("NY:CCA-402-answer-time", "NY:CCA 402", "CCA 402; CCA 410", "landlord (plaintiff); former tenant", "rule",
                  "The landlord serves a Civil Court summons on a former tenant (or the tenant serves one on the landlord).",
                  "Branch (a): personally delivered to the defendant within New York City: it must appear and answer within 20 days after service, and service is complete on delivery. Branch (b): served any other way (substituted, nail-and-mail, mail under CPLR 312-a, outside the city under CCA 404): it must appear and answer within 30 days after proof of service is filed with the clerk, and service is complete on that filing (NY:CCA-410-service-complete). A default judgment is sought only after that time runs (and after the 3215(g)(3) 20-day mailing: NY:CPLR-3215(g)(3)).",
                  "(a) If the summons is personally delivered to the defendant within the city of New York,", "within thirty days after proof of service is filed with the clerk.",
                  severity="major", walk_step="8.9", dependencies=["NY:CPLR-3215(g)(3)"])]),
    D("NY:CCA 403", "new_rule",
      "A Civil Court summons is served as in Supreme Court (including mail under CPLR 312-a) but only within New York City unless a statute such as CCA 404 authorizes more; decides whether a tenant who has left the city can be served.",
      proposed=[R("NY:CCA-403-service-within-city", "NY:CCA 403", "CCA 403", "landlord (plaintiff)", "rule",
                  "The landlord serves a summons on a former tenant in a Civil Court action.",
                  "Service follows Supreme Court practice (personal delivery, substituted service, affix-and-mail: NY:CPLR-308-natural-person; mail with acknowledgment: NY:CPLR-312-a-mail-service), but is made only within New York City unless another law authorizes service beyond the city. A tenant who has left the city is served outside it under CCA 404 on a claim arising from its possession of the NYC unit (NY:CCA-404-long-arm).",
                  "Service of summons shall be made in the manner prescribed in supreme court practice,", "as expressly applies to courts of limited jurisdiction or to all courts of the state.",
                  severity="major", walk_step="8.10", dependencies=["NY:CCA-404-long-arm", "NY:CPLR-308-natural-person", "NY:CPLR-312-a-mail-service"])]),
    D("NY:CCA 404", "new_rule",
      "Gives the Civil Court personal jurisdiction over a non-resident of the city on a claim arising from its possession or use of real property in the city, served anywhere; a former tenant who moved out of the city or state can be sued in NYC Civil Court for the balance, and a non-resident owner by the tenant.",
      proposed=[R("NY:CCA-404-long-arm", "NY:CCA 404", "CCA 404", "landlord; former tenant", "rule",
                  "A party to a claim over the tenancy does not reside in New York City when suit is brought. Branch (a): the landlord sues a former tenant who moved out of the city or state. Branch (b): the tenant sues an owner who lives or is organized outside the city.",
                  "The Civil Court has personal jurisdiction over a non-resident of the city (or its executor or administrator) on a cause of action arising from its transacting business in the city, contracting to supply goods or services there, committing a tortious act there (not defamation), or owning, using or possessing real property in the city, in person or by an agent. Branch (a): the former tenant's balance arises from its use and possession of the NYC unit, so it may be served outside the city and the state in any manner that would give the Supreme Court jurisdiction. Branch (b): the owner owns the NYC property, so the same applies. An appearance does not extend jurisdiction to unrelated claims. A corporation or association that cannot be served by personal delivery in the city is treated as a non-resident.",
                  "(a) Acts which are the basis of jurisdiction.", "shall be deemed a non-resident of the city of New York for purposes of this section.",
                  severity="critical", walk_step="8.10")]),
    D("NY:CCA 405", "no_decision",
      "Out-of-city service without personal jurisdiction for real property, chattel, attachment and interpleader-deposit cases; a balance or deposit action against a moved-away party is reached with personal jurisdiction under CCA 404 instead."),
    D("NY:CCA 406", "no_decision",
      "Publication only in the CCA 405 in-rem cases, which do not include a balance or deposit action; publication against a natural person in a personal action is CPLR 315-316."),
    D("NY:CCA 409", "new_rule",
      "Proof of service must be filed with the Civil Court clerk by the marshal's or sheriff's certificate or the server's affidavit; the filing starts the tenant's 30-day answer time where service was not personal.",
      proposed=[R("NY:CCA-409-proof-of-service", "NY:CCA 409", "CCA 409", "landlord (plaintiff)", "obligation",
                  "The landlord has served the summons and complaint on a former tenant in a Civil Court action.",
                  "Proof of service is filed with the clerk in the county of suit, by the certificate of the sheriff or marshal or the affidavit of the person who served. Where service was not personal delivery in the city, the tenant's time to answer runs 30 days from this filing (NY:CCA-402-answer-time).",
                  "(a) Proof of service of the summons and complaint,", "or by the affidavit of the person by whom the service was made.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-402-answer-time"])]),
    D("NY:CCA 410", "new_rule",
      "Service of a Civil Court summons is complete on personal delivery, or otherwise on filing proof of service; this fixes the start of the answer period and default timing.",
      proposed=[R("NY:CCA-410-service-complete", "NY:CCA 410", "CCA 410", "landlord (plaintiff)", "rule",
                  "The landlord serves a former tenant with a Civil Court summons.",
                  "Service is complete immediately on personal delivery to the tenant within the city, or, for any other method, on the filing of proof of service (NY:CCA-409-proof-of-service).",
                  "The service of summons is complete:", "where § 402 (b) is applicable.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-402-answer-time"])]),
    D("NY:CCA 411", "new_rule",
      "The summons and complaint must be served within 120 days after filing or the action is dismissed without prejudice unless the court extends; a deadline whose miss can end a suit brought near the limitations date.",
      proposed=[R("NY:CCA-411-120-days", "NY:CCA 411", "CCA 411", "landlord (plaintiff) or former tenant (plaintiff)", "obligation",
                  "A party has filed a summons and complaint (or third-party complaint) in NYC Civil Court over the tenancy.",
                  "It must serve the defendant within 120 days after filing. If not, the court on motion dismisses the action without prejudice as to that defendant, or extends the time on good cause or in the interest of justice. A dismissal after the limitations period has run leaves only the CPLR 205(a) six-month recommencement where it applies (NY:CPLR-204-208-tolling).",
                  "Service of the summons and complaint,", "or upon good cause shown or in the interest of justice, extend the time for service.",
                  severity="major", walk_step="8.10", dependencies=["NY:CPLR-204-208-tolling"])]),
    D("NY:CCA 412", "partial",
      "The interest rule sets interest from each due date; 412 adds that where interest runs from the start of the action (for example a single intermediate date the court takes as commencement), it starts only when service is complete with the actual index number on the summons.",
      atoms=["NY:CPLR-5001(a)-(b)"],
      proposed=[R("NY:CCA-412-interest-from-service", "NY:CCA 412", "CCA 412", "landlord (plaintiff) or former tenant (plaintiff)", "rule",
                  "In an NYC Civil Court case over the tenancy, interest is awarded from the date the action or proceeding began (rather than from each amount's due date under NY:CPLR-5001(a)-(b)).",
                  "That interest does not begin to accrue until service is complete with the actual index number properly shown on the summons given to the party who must pay the interest. Interest computed from each amount's own due date is unaffected.",
                  "In any action, petition, order to show cause or other proceeding wherein interest accrues", "provided to the party to be charged with the payment of interest.",
                  severity="minor", walk_step="8.10", amends="NY:CPLR-5001(a)-(b)", dependencies=["NY:CPLR-5001(a)-(b)"])]),
    D("NY:CCA 801", "new_rule",
      "A Civil Court provisional remedy (such as attachment) runs only within New York City against persons or property there; limits pre-judgment attachment against a tenant who moved away.",
      proposed=[R("NY:CCA-801-provisional-city-only", "NY:CCA 801", "CCA 801", "landlord (plaintiff)", "limit",
                  "The landlord obtains a provisional remedy (attachment) out of the NYC Civil Court against a former tenant.",
                  "Practice follows the CPLR, but the remedy is executed only within New York City against persons or property there, with returns to the Civil Court clerk; property outside the city is reached only through the Supreme Court.",
                  "Whenever the remedies set forth in § 209 of this act may issue out of this court", "(b) When a return is required, the return shall be made to the clerk of this court in the county out of which the remedy issued.",
                  severity="minor", walk_step="8.10", dependencies=["NY:CCA-209-provisional-remedies"])]),
    D("NY:CCA 802", "new_rule",
      "Applies CPLR tender and offer-to-compromise rules (3219-3221) in Civil Court, with the added duty to file a copy with the clerk; changes how a landlord or tenant makes a cost-shifting settlement offer.",
      proposed=[R("NY:CCA-802-tender-offer", "NY:CCA 802", "CCA 802", "landlord; former tenant", "obligation",
                  "A party to an NYC Civil Court case over the tenancy makes a written tender, a conditional offer to liquidate damages, or an offer to compromise (NY:CPLR-3219-tender, NY:CPLR-3221-offer-to-compromise).",
                  "The CPLR rules apply, and a copy of the tender, offer or notice must be filed with the clerk when it is served on the other party.",
                  "The provisions of Rules 3219, 3220 and 3221 of the CPLR,", "a copy of such tender, offer or notice shall be filed with the clerk.",
                  severity="minor", walk_step="8.1b", dependencies=["NY:CPLR-3219-tender", "NY:CPLR-3221-offer-to-compromise"])]),
    D("NY:CCA 902", "new_rule",
      "In Civil Court a money-only claim may be pleaded by an endorsement on the summons (nature, substance and default amount); a formal complaint is served with the summons; changes what the landlord must serve to commence.",
      proposed=[R("NY:CCA-902-pleading-form", "NY:CCA 902", "CCA 902", "landlord (plaintiff)", "rule",
                  "The landlord sues a former tenant in the NYC Civil Court for money only.",
                  "Pleadings are formal as in Supreme Court, except that the claim may be stated by an endorsement on the summons giving the nature and substance of the claim and the amount for which judgment will be taken on default (by the clerk if the landlord has no attorney); a tenant appearing without an attorney may state its answer to the clerk. A formal complaint, if used, is served with the summons. The court may at any time direct a formal pleading. The pending S9760 would require the complaint, with the lease attached, served with the summons (NY:S9760-pleading-service).",
                  "(a) All pleadings shall be formal pleadings,", "direct the service and filing of a formal pleading.",
                  severity="minor", walk_step="8.10", dependencies=["NY:S9760-pleading-service", "NY:CCA-1402-default-on-endorsed-summons"])]),
    D("NY:CCA 905", "no_decision",
      "Lets the court hear legal or equitable defenses; it adds no step, amount or deadline for either side."),
    D("NY:CCA 907", "new_rule",
      "In Civil Court a plaintiff need not reply to a counterclaim, which is deemed denied; a landlord suing for the balance is not defaulted on the tenant's deposit counterclaim by not replying.",
      proposed=[R("NY:CCA-907-counterclaim-reply", "NY:CCA 907", "CCA 907(a)", "landlord (plaintiff); former tenant", "rule",
                  "The former tenant answers the landlord's Civil Court balance action with a counterclaim (for example for the deposit or double damages), or the reverse.",
                  "The plaintiff need not reply unless the court orders; a voluntary reply is due within 10 days after service of the answer; without a reply the counterclaim's allegations are deemed denied, so no default arises on it.",
                  "(a) Counterclaim. The plaintiff may reply to a counterclaim", "the allegations of the counterclaim shall be deemed denied by the plaintiff.",
                  severity="minor", walk_step="7.6")]),
    D("NY:CCA 908", "no_decision",
      "Verification of Civil Court pleadings follows the CPLR; verification form changes no step in the chain (default proof is CPLR 3215(f))."),
    D("NY:CCA 909", "no_decision",
      "Amending pleadings in a pending Civil Court case; in-suit litigation mechanics that change no amount, deadline or precondition in the settlement or the decision to sue (relation back is at CPLR 203(f))."),
    D("NY:CCA 910", "no_decision",
      "Makes the CPLR simplified procedure (a voluntary submission of an agreed controversy without pleadings) available in Civil Court; a litigation-format option that changes no amount, deadline or precondition."),
]
write(rows)
