from q2_lib import *

rows = [
    D("NY:CPLR 3211", "new_rule",
      "Lists the grounds on which the former tenant (or the landlord, when sued) can have a claim dismissed early (limitations, release, payment, lack of capacity, no personal jurisdiction, failure to state a claim) and when each is waived; decides which defects end the balance suit.",
      proposed=[R("NY:CPLR-3211-dismissal-grounds", "NY:CPLR 3211", "CPLR 3211(a), (e)", "landlord; former tenant", "rule",
                  "A claim over the tenancy is pleaded against a party (the landlord's balance suit, or the tenant's deposit suit) and the defending party moves to dismiss before or with its answer.",
                  "It may move on these grounds, among others: documentary evidence (a signed release or stipulation); no subject-matter jurisdiction; the claimant's lack of legal capacity to sue (for example an unauthorized foreign LLC: NY:LLC-808(a)-foreign-authority); another action pending on the same claim; arbitration and award, collateral estoppel, bankruptcy discharge, infancy or disability, payment, release, res judicata, statute of limitations or statute of frauds; the pleading fails to state a claim (for example a collection agency that does not plead its licence: NY:CPLR-3015(e)-licence-pleading); no personal jurisdiction. Only one pre-answer motion is allowed. Documentary evidence, capacity, prior action, the (a)(5) defenses and counterclaim objections are waived unless raised by that motion or in the answer; failure to state a claim, subject-matter jurisdiction and missing parties may be raised later. Lack of personal jurisdiction is waived if not raised in the first motion or in the answer; an improper-service objection pleaded in the answer is waived unless the defendant moves on it within 60 days after serving the answer (this 60-day rule does not apply in a consumer-credit collection suit, which a lease balance is not: NY:ADJ-lease-balance-not-consumer-credit).",
                  "(a) Motion to dismiss cause of action.", "includes any amended responsive pleading.",
                  severity="major", walk_step="8.10", dependencies=["NY:LLC-808(a)-foreign-authority", "NY:CPLR-3015(e)-licence-pleading", "NY:ADJ-lease-balance-not-consumer-credit"])]),
    D("NY:CPLR 3213", "new_rule",
      "An action on an instrument for the payment of money only, or on a judgment, may start with a summary-judgment motion instead of a complaint; decides whether a former tenant's signed payment note or a judgment can be enforced this fast track (a lease itself cannot).",
      proposed=[R("NY:CPLR-3213-summary-judgment-in-lieu", "NY:CPLR 3213", "CPLR 3213", "landlord (plaintiff)", "permission",
                  "The landlord sues a former tenant in the Supreme Court. Branch (a): on a writing in which the tenant (or a guarantor) unconditionally promised to pay a sum certain (a signed payment agreement or note for the balance, an unconditional guaranty of payment), or on a judgment (for example a sister-state judgment). Branch (b): on the lease itself.",
                  "Branch (a): the landlord may serve with the summons a notice of motion for summary judgment and supporting papers instead of a complaint, returnable no earlier than the CPLR 320(a) appearance time; no default judgment under CPLR 3215(a) before the hearing date; if denied, the motion papers become the complaint and answer. Branch (b): a lease is not an instrument for the payment of money only, because recovery on it requires proof of facts outside the writing (possession delivered, the tenant's breach, the amounts accrued), so the landlord proceeds by summons and complaint.",
                  "When an action is based upon an instrument for the payment of money only or upon any judgment,", "the moving and answering papers shall be deemed the complaint and answer, respectively, unless the court orders otherwise.",
                  severity="minor", walk_step="8.10", determinacy="MIXED", judgment_terms=["instrument for the payment of money only"])]),
    D("NY:CPLR 3216", "new_rule",
      "A landlord that sues and then neglects the case for a year after joinder can be served a 90-day demand to file a note of issue, after which the action may be dismissed; a deadline that can end the balance suit.",
      proposed=[R("NY:CPLR-3216-want-of-prosecution", "NY:CPLR 3216", "CPLR 3216", "landlord (plaintiff) or former tenant (plaintiff)", "rule",
                  "A party's action over the tenancy has been pending with issue joined for at least one year (or six months after a preliminary conference order, whichever is later), and it has not filed a note of issue.",
                  "The court or the other party may serve by registered or certified mail a written demand to resume prosecution and serve and file a note of issue within 90 days, warning that default is a basis for dismissal. Filing the note of issue within the 90 days is compliance. If not filed, the court may dismiss the claim (not on the merits unless the order says so) unless the party shows a justifiable excuse and a meritorious cause of action.",
                  "(a) Where a party unreasonably neglects to proceed generally in an action", "unless the said party shows justifiable excuse for the delay and a good and meritorious cause of action.",
                  severity="minor", walk_step="8.10")]),
    D("NY:CPLR 3217", "new_rule",
      "How a landlord (or tenant) discontinues its claim, and that a second discontinuance by notice is an adjudication on the merits; decides whether withdrawing a suit (for example after a settlement or to re-file) forfeits the claim.",
      proposed=[R("NY:CPLR-3217-discontinuance", "NY:CPLR 3217", "CPLR 3217(a)-(d)", "landlord; former tenant (claimant)", "rule",
                  "A party that sued over the tenancy wants to withdraw its claim (after settlement, to re-file elsewhere, or to write the balance off).",
                  "It may discontinue without an order by serving a notice of discontinuance before a responsive pleading is served (and filing it with proof of service), or by filing a stipulation signed by all attorneys of record before submission (not where a party is an infant, incompetent or conservatee); otherwise only by court order on terms. A discontinuance is without prejudice unless stated otherwise, except that a discontinuance by notice is an adjudication on the merits if the party had already once discontinued an action on the same claim in any court. The defendant files the notice, stipulation or certificate with the county clerk.",
                  "(a) Without an order.", "shall be filed with the county clerk by the defendant.",
                  severity="minor", walk_step="8.1b")]),
    D("NY:CPLR 3218", "new_rule",
      "A former tenant may confess judgment by affidavit for the balance, filed within three years only in the county where the tenant resided, with the consumer-rate statement where it applies; a payment-plan security option with strict limits.",
      proposed=[R("NY:CPLR-3218-confession", "NY:CPLR 3218", "CPLR 3218", "landlord; former tenant", "permission",
                  "The landlord and a former tenant agree that the tenant will confess judgment for the balance (for example as security for a payment plan).",
                  "The tenant signs an affidavit stating the sum, authorizing entry of judgment, stating the county where it resides, stating that the 2% consumer-debt interest rate applies where it does (NY:CPLR-5004(a)-consumer-2pct), and concisely stating the facts from which the debt arose and showing the sum is justly due or to become due. The landlord may file it within three years after execution, only with the clerk of the county where the tenant resided when it signed or resides at filing; the clerk enters judgment (in the NYC Civil Court for sums within its jurisdiction: NY:CCA-1403-confession-civil-court) with $15 costs plus disbursements. No judgment by confession is entered after the tenant's death. Where the sum is payable in installments, execution issues only for what has fallen due, and the judgment stands as security for later installments. Joint debtors bind only those who sign; the others remain suable on the demand.",
                  "(a) Affidavit of defendant.", "it is not a bar to an action against the other joint debtors upon the same demand.",
                  severity="major", walk_step="8.1b", dependencies=["NY:CPLR-5004(a)-consumer-2pct", "NY:CCA-1403-confession-civil-court"])]),
    D("NY:CPLR 3219", "new_rule",
      "A landlord sued on the lease (for example for the deposit) may deposit a sum with the clerk and tender it; if the tenant does not beat it, the tenant loses interest and costs from the tender and pays the landlord's costs. A cost-shifting settlement tool.",
      proposed=[R("NY:CPLR-3219-tender", "NY:CPLR 3219", "CPLR 3219", "landlord (defendant) or former tenant (defendant)", "permission",
                  "A party is sued on a contract claim over the tenancy (the landlord for the deposit or damages under the lease; the tenant for the balance) and a separate judgment may be taken against it.",
                  "Up to ten days before trial, without an order, it may deposit with the clerk an amount it deems sufficient and serve a written tender, filing a copy with the clerk (in Civil Court: NY:CCA-802-tender-offer). The claimant may withdraw the deposit within ten days by filing an acknowledged statement that it satisfies the claim; the clerk then dismisses the claim without costs. Otherwise the deposit is returned on request. If the claimant does not accept and fails to obtain a more favorable judgment, it recovers no interest or costs from the tender and pays the defendant's costs of defending from then. The tender is not disclosed to the jury.",
                  "At any time not later than ten days before trial, any party against whom a cause of action based upon contract,", "A tender shall not be made known to the jury.",
                  severity="major", walk_step="8.1b")]),
    D("NY:CPLR 3220", "new_rule",
      "A party sued on the lease may offer to fix damages at a stated sum if it loses on liability; a claimant that refuses and does no better pays the expense of trying damages from the offer.",
      proposed=[R("NY:CPLR-3220-conditional-offer", "NY:CPLR 3220", "CPLR 3220", "landlord (defendant) or former tenant (defendant)", "permission",
                  "A party is sued on a contract claim over the tenancy and disputes liability.",
                  "Up to ten days before trial it may serve a written offer that, if it loses on liability, judgment be taken for a specified sum with accrued costs. If the claimant accepts in writing within ten days and wins, damages are that sum. If the claimant does not accept and fails to obtain a more favorable judgment, it pays the expenses the offeror necessarily incurred in trying damages from the time of the offer.",
                  "At any time not later than ten days before trial, any party against whom a cause of action based upon contract, express or implied,", "An offer under this rule shall not be made known to the jury.",
                  severity="minor", walk_step="8.1b")]),
    D("NY:CPLR 3221", "new_rule",
      "An offer to allow judgment for a stated sum: if accepted within ten days judgment is entered; if refused and the claimant does no better, it loses costs from the offer and pays the offeror's costs. A cost-shifting settlement tool in a deposit or balance suit.",
      proposed=[R("NY:CPLR-3221-offer-to-compromise", "NY:CPLR 3221", "CPLR 3221", "landlord (defendant) or former tenant (defendant)", "permission",
                  "A claim over the tenancy is pending against a party against whom a separate judgment may be taken.",
                  "Up to ten days before trial it may serve a written offer to allow judgment for a specified sum (or property or effect) with accrued costs (in Civil Court, also filed with the clerk: NY:CCA-802-tender-offer). If the claimant accepts in writing within ten days, either party files the summons, complaint and offer with proof of acceptance and the clerk enters judgment. If not accepted and the claimant fails to obtain a more favorable judgment, it recovers no costs from the offer and pays the offeror's costs from then. The offer is not disclosed to the jury.",
                  "Except in a matrimonial action, at any time not later than ten days before trial,", "An offer of judgment shall not be made known to the jury.",
                  severity="major", walk_step="8.1b")]),
    D("NY:CPLR 327", "no_decision",
      "A court's discretionary dismissal for inconvenient forum; a claim over an NYC tenancy is heard in New York, and the doctrine adds no step, amount or deadline for either side."),
    D("NY:CPLR 4501", "no_decision",
      "A witness cannot refuse to answer because the answer shows it owes a debt; the judgment debtor's duty to answer on examination is stated through CPLR 5223-5224, and this adds no step."),
    D("NY:CPLR 4519-A", "no_decision",
      "Bars possession of an opioid antagonist as evidence of illegal use in illegal-use eviction proceedings; an eviction ground, not a step in settling the account."),
    D("NY:CPLR 4527", "no_decision",
      "Federal missing-person and presumed-death findings are prima facie evidence; the tenant-death and military rules stated elsewhere govern the settlement, and this evidentiary rule adds no step."),
    D("NY:CPLR 4531", "no_decision",
      "An absent server's affidavit is prima facie proof of service or posting at trial; an evidentiary convenience that adds no step or requirement to the settlement."),
    D("NY:CPLR 4533-A", "new_rule",
      "In any civil action an itemized, receipted repair bill of $2,000 or less, certified by the vendor and served with notice ten days before trial, is prima facie proof of the reasonable value and necessity of the repair; sets how the landlord proves a damage charge outside small claims.",
      proposed=[R("NY:CPLR-4533-a-repair-bill-proof", "NY:CPLR 4533-A", "CPLR 4533-a", "landlord (plaintiff or defendant)", "rule",
                  "The landlord proves a damage charge (repair, cleaning, replacement) in a civil action against a former tenant, or defends a deposit deduction, outside the small claims part (there: NY:CCA-1804-small-claims-proof).",
                  "An itemized bill or invoice, receipted or marked paid, for services or repairs of $2,000 or less is admissible and prima facie evidence of the reasonable value and necessity of the itemized work if it bears the vendor's (or its authorized agent's or employee's) certification, contains a verified statement that no part of the payment will be refunded to the debtor and that the amounts are the vendor's usual and customary rates, and a true copy is served on every party with a notice of intent to offer it at least ten days before trial. Only one bill from the same vendor to the same debtor is admissible this way in the action. Larger bills and unpaid estimates need a witness. Operator step: obtain from each repair vendor a paid, itemized invoice with the certification and no-refund statement.",
                  "An itemized bill or invoice, receipted or marked paid, for services or repairs of an amount not in excess of two thousand dollars", "shall be admissible in evidence under this rule in the same action.",
                  severity="major", walk_step="7.4", dependencies=["NY:GOL-7-108(1-a)(f)"])]),
    D("NY:CPLR 4547", "new_rule",
      "Settlement offers and statements made in compromise negotiations over a disputed balance or deduction are not admissible to prove liability or amount; changes how Handoff or the manager can negotiate with a former tenant.",
      proposed=[R("NY:CPLR-4547-compromise-inadmissible", "NY:CPLR 4547", "CPLR 4547", "landlord, managing agent, Handoff; former tenant", "rule",
                  "The landlord (or its manager or Handoff) and a former tenant negotiate a disputed balance or deposit deduction, for example an offer to waive a charge or accept less.",
                  "Offering, promising, furnishing or accepting consideration to compromise a claim disputed as to validity or amount, and any conduct or statement made during the compromise negotiations, are inadmissible to prove liability, invalidity or amount. Evidence otherwise discoverable is not excluded because it was shown during negotiations, and the evidence may be offered for another purpose (bias, undue delay, obstruction). The itemized statement itself is not a compromise communication and is admissible.",
                  "Evidence of (a) furnishing, or offering or promising to furnish, or", "or proof of an effort to obstruct a criminal investigation or prosecution.",
                  severity="minor", walk_step="8.1b")]),
    D("NY:CPLR 4548", "no_decision",
      "Privileged communications keep their privilege when sent electronically; no settlement step turns on it."),
    D("NY:CPLR 5002", "partial",
      "The interest rules state pre-decision interest and the rate; 5002 adds interest on the whole award (including interest to decision) from the verdict or decision to entry of judgment, computed by the clerk.",
      atoms=["NY:CPLR-5001(a)-(b)", "NY:CPLR-5004(a)-consumer-2pct"],
      proposed=[R("NY:CPLR-5002-decision-to-judgment", "NY:CPLR 5002", "CPLR 5002", "prevailing party (landlord or former tenant)", "rule",
                  "A verdict, report or decision awards a sum in an action over the tenancy and judgment is entered later.",
                  "Interest runs on the total sum awarded, including interest up to the decision, from the decision to entry of final judgment, at the NY:CPLR-5004(a)-consumer-2pct rate; the clerk computes it and includes it in the judgment. From entry, NY:CPLR-5003-judgment-interest applies.",
                  "Interest shall be recovered upon the total sum awarded,", "computed by the clerk of the court and included in the judgment.",
                  severity="major", walk_step="8.10", amends="NY:CPLR-5001(a)-(b)", dependencies=["NY:CPLR-5004(a)-consumer-2pct", "NY:CPLR-5003-judgment-interest"])]),
    D("NY:CPLR 5003-B", "no_decision",
      "Limits confidentiality terms that an employer may put in settlements of discrimination claims; it binds employers, not a landlord settling a tenancy account."),
]
write(rows)
