from q2_lib import *

MECH = "in-suit litigation mechanics that change no amount, deadline, precondition or payee in settling the account or deciding to pursue it."
EVID = "an evidentiary privilege or competency rule applied at trial; no settlement, collection or record-keeping step turns on it."
rows = [
    D("NY:CPLR 3021", "no_decision", "Wording of an affidavit of verification; who may verify is at proposed NY:CPLR-3020-verification. " + MECH),
    D("NY:CPLR 3023", "no_decision", "How verified allegations are construed; " + MECH),
    D("NY:CPLR 3024", "no_decision", "Motions to correct vague or scandalous pleadings; " + MECH),
    D("NY:CPLR 3032", "no_decision", "Contents of a simplified-procedure statement; a voluntary litigation format."),
    D("NY:CPLR 3034", "no_decision", "Motion to settle a simplified-procedure statement under a contract to submit; a voluntary litigation format."),
    D("NY:CPLR 3035", "no_decision", "Authorizes the simplified procedure's rules; a voluntary litigation format."),
    D("NY:CPLR 304", "new_rule",
      "In Supreme Court an action is commenced by filing the summons and complaint (or summons with notice) with the county clerk and paying the index fee; the filing date is the interposition date for limitations.",
      proposed=[R("NY:CPLR-304-commencement", "NY:CPLR 304", "CPLR 304(a)-(c)", "landlord (plaintiff) or former tenant (plaintiff)", "rule",
                  "A balance action against a former tenant, or a tenant's deposit action, is brought in the Supreme Court.",
                  "It is commenced by filing (delivering to the county clerk, or a person the clerk designates) the summons and complaint or summons with notice, and the filing is not accepted unless the CPLR 8018 index-number fee is paid; filing by fax or electronic means is allowed where the Chief Administrator authorizes it (mandatory e-filing: NY:22NYCRR-202.5bb-mandatory-efiling). The filing date is the commencement for CPLR 203 (NY:CPLR-203-accrual-interposition). Where circumstances prevent immediate filing, a court order requiring filing within five days commences the action. Service must follow within 120 days (NY:CPLR-306-b-120-days). NYC Civil Court counterpart: NY:CCA-400-commencement.",
                  "(a) An action is commenced by filing a summons and complaint or summons with notice", "Such filing shall not be accepted unless any fee required as specified in section eight thousand eighteen of this chapter has been paid.",
                  severity="critical", walk_step="8.10", dependencies=["NY:CPLR-203-accrual-interposition", "NY:CPLR-306-b-120-days"])]),
    D("NY:CPLR 3041", "no_decision", "A party may demand a bill of particulars or a copy of the items of an account in a pending suit; " + MECH),
    D("NY:CPLR 3042", "no_decision", "Procedure and preclusion for bills of particulars; " + MECH),
    D("NY:CPLR 3044", "no_decision", "Verification of bills of particulars; " + MECH),
    D("NY:CPLR 305", "new_rule",
      "A Supreme Court summons must state the basis of venue (and the plaintiff's address if venue rests on its residence), the index number and filing date; a summons served without the complaint must state the nature of the claim, relief and the default amount. Changes what the landlord serves to commence.",
      proposed=[R("NY:CPLR-305-summons-contents", "NY:CPLR 305", "CPLR 305(a)-(c)", "landlord (plaintiff) or its attorney", "obligation",
                  "The landlord commences a Supreme Court action against a former tenant for the balance.",
                  "The summons states the basis of the venue chosen and, if venue rests on the plaintiff's residence, the plaintiff's address, and bears the index number and filing date. If the complaint is not served with it, the summons carries a notice stating the nature of the action, the relief sought and the sum for which judgment will be taken on default. The 'consumer credit transaction' legend and county statements apply only to consumer credit actions, which a lease balance is not (NY:ADJ-lease-balance-not-consumer-credit). The court may allow a summons or proof of service to be amended where no substantial right is prejudiced.",
                  "(a) Summons; supplemental summons.", "if a substantial right of a party against whom the summons issued is not prejudiced.",
                  severity="minor", walk_step="8.10", dependencies=["NY:ADJ-lease-balance-not-consumer-credit"])]),
    D("NY:CPLR 306-A", "no_decision", "Assignment of the index number and payment of its fee on filing in Supreme or County Court; the fee's amount is CPLR 8018 and commencement is at proposed NY:CPLR-304-commencement."),
    D("NY:CPLR 307", "no_decision", "Service on the State and state officers; not a party to the tenancy."),
    D("NY:CPLR 310-A", "new_rule",
      "How a limited partnership owner (or tenant) is served: its managing or general agent or general partner in New York, an authorized agent, or a designated person; fixes how a tenant sues an LP owner.",
      proposed=[R("NY:CPLR-310-a-limited-partnership", "NY:CPLR 310-A", "CPLR 310-a", "former tenant (plaintiff); landlord limited partnership", "rule",
                  "A party to a claim over the tenancy is a domestic or foreign limited partnership (or limited liability partnership).",
                  "Service is by personal delivery to a managing or general agent or general partner in New York, an agent or employee authorized by appointment, or a person it designated to receive process; also as the Partnership Law allows (section 121-109, or 121-1505 for an LLP); or as the court directs if impracticable.",
                  "(a) Personal service upon any domestic or foreign limited partnership", "may also be served pursuant to section 121-1505 of the partnership law.",
                  severity="minor", walk_step="7.6")]),
    D("NY:CPLR 311-A", "new_rule",
      "How a limited liability company is served (a member or manager in New York, an authorized or designated agent, or the Secretary of State under the LLC Law); the usual route for a tenant suing an LLC owner, and for the landlord suing a company tenant organized as an LLC.",
      proposed=[R("NY:CPLR-311-a-llc", "NY:CPLR 311-A", "CPLR 311-a", "former tenant (plaintiff); landlord LLC; company tenant", "rule",
                  "A party to a claim over the tenancy is a domestic or foreign limited liability company (the usual owner form, or a company tenant).",
                  "Service is by personal delivery in New York to a member (if member-managed) or manager (if manager-managed), to an agent authorized by appointment, or to a person the LLC designated to receive process; or under LLC Law article 3 (service on the Secretary of State as its agent); or as the court directs if impracticable. Operator step: an owner LLC keeps its Secretary of State address current so a tenant's deposit suit reaches it and no default is taken.",
                  "(a) Service of process on any domestic or foreign limited liability company", "it may be made in such manner as the court, upon motion without notice, directs.",
                  severity="minor", walk_step="7.6")]),
    D("NY:CPLR 312", "no_decision", "Service on courts, boards and commissions; not parties to the tenancy."),
    D("NY:CPLR 314", "no_decision",
      "Service outside the state without personal jurisdiction in matrimonial, in-rem and attachment-based cases; a personal balance or deposit claim is reached with personal jurisdiction under CPLR 302 (proposed NY:CPLR-302-long-arm)."),
    D("NY:CPLR 3214", "no_decision", "Motions before the disclosure judge and the disclosure stay on dispositive motions; " + MECH),
    D("NY:CPLR 322", "no_decision", "Proof of an attorney's authority in actions affecting real property; a balance or deposit action is not one."),
    D("NY:CPLR 3222", "no_decision", "Actions on an agreed submission of facts; a voluntary litigation format."),
    D("NY:CPLR 325", "no_decision", "Removal of actions between courts (mistake in court, limited jurisdiction, consent); a court power whose cost effect is CPLR 8104, adding no settlement step."),
    D("NY:CPLR 326", "no_decision", "Procedure on removal; " + MECH),
    D("NY:CPLR 4502", "no_decision", "Spousal privilege; " + EVID),
    D("NY:CPLR 4503", "no_decision", "Attorney-client privilege; " + EVID),
    D("NY:CPLR 4505", "no_decision", "Clergy privilege; " + EVID),
    D("NY:CPLR 4506", "no_decision",
      "Excludes recordings obtained by criminal eavesdropping; a participant's own recording of a call with a former tenant is not eavesdropping under Penal Law 250.05, so no settlement step turns on it."),
    D("NY:CPLR 4507", "no_decision", "Psychologist privilege; " + EVID),
    D("NY:CPLR 4508", "no_decision", "Social worker privilege; " + EVID),
    D("NY:CPLR 4509", "no_decision", "Library records privilege; " + EVID),
    D("NY:CPLR 4510", "no_decision", "Rape crisis counselor and domestic violence advocate privilege; " + EVID + " (The domestic-violence termination and address rules are stated elsewhere.)"),
    D("NY:CPLR 4511", "no_decision", "Judicial notice of law; " + EVID),
    D("NY:CPLR 4512", "no_decision", "Interested parties and spouses are competent witnesses; " + EVID),
    D("NY:CPLR 4513", "no_decision", "Convicted persons are competent witnesses; " + EVID),
    D("NY:CPLR 4514", "no_decision", "Impeachment by prior inconsistent statement; " + EVID),
]
write(rows)
