import sys; sys.path.insert(0, 'register/work'); from q4_lib import *
s='NY:GBL 380-T'
add([{'section_id': s, 'decision': 'new_rule', 'reason': 'Decides whether a landlord, its agent or collector may still obtain a former tenant\'s report after the tenant freezes it: yes, to collect the lease obligation.', 'proposed': [rule(s, instrument='NY General Business Law art. 25 (Fair Credit Reporting Act)',
  id='NY:GBL-380-t-freeze-collection', provision='GBL 380-t(m)(1)', actor='landlord, its managing agent or Handoff as agent, a collector, or an assignee of the balance', modality='permission',
  condition='The former tenant has placed a security freeze on its consumer credit report, and the landlord (or its subsidiary, affiliate or agent, or an assignee or prospective buyer of the balance) wants the report.',
  effect='The freeze does not apply to the use of the report by a person with which the tenant had a contract (the lease), or its agent or assignee, for reviewing the account or collecting the obligation owed under that contract; for that purpose the report may still be obtained. For any other purpose the freeze applies and the agency may not release it. The purpose limits of NY:GBL-380-b-permissible-purpose still apply.',
  dependencies=['NY:GBL-380-b-permissible-purpose'],
  quote=q(s, 'with which the consumer has or had prior to assignment an account or contract, including a demand deposit account, or to whom the consumer issued a negotiable instrument, for the purposes of reviewing the account or collecting the financial obligation owing for the account, contract, or negotiable instrument.'),
  severity='minor', walk_step='8.7')]}])
add([
 {'section_id': 'NY:GBL 604', 'decision': 'stated', 'atom_ids': ['NY:ADJ-lease-balance-not-consumer-credit', 'NY:GBL-601-a-family'], 'reason': 'The article 29-H definitions (consumer claim requires credit offered or extended) are what the adjudication applies to keep a lease balance outside 601, 601-b and 602; 601-a reaches it by its own terms.'},
 nd('NY:GBL 380-A', 'Article 25 definitions (consumer report, consumer reporting agency, user); the proposed art. 25 rules use them in their ordinary scope, and none widens or narrows the landlord\'s or collector\'s position.'),
 nd('NY:GBL 349-A', 'Disclosure of algorithmic pricing when a price is offered to a consumer; move-out charges are not price offers, and lease pricing at leasing is outside the chain.'),
 nd('NY:GBL 349-F', 'Veterans\' benefits advisers (pension poaching); not a tenancy matter.'),
 nd('NY:GBL 350-A', 'Definition of false advertising of commodities and employment; not a settlement or collection communication.'),
 nd('NY:GBL 350-C', 'Attorney General notice before a false-advertising action; agency procedure.'),
 nd('NY:GBL 350-F', 'Exempts broadcasters and publishers from the false-advertising article.'),
 nd('NY:GBL 391-K', 'Safety standards for automatic garage door openers; not a settlement charge or credit.'),
 nd('NY:GBL 391-U', 'Gender-based pricing of consumer goods and services; lease charges are governed by the deposit and fee rules and tested under NY:EXEC-296(5)(a)(2)-terms.'),
 nd('NY:GBL 392-H', 'Marking of dumpsters on public streets; not a tenancy matter.'),
 nd('NY:GBL 394-E', 'Reports of abortion referrals; not a tenancy matter.'),
 nd('NY:GBL 396-AA', 'Simulated checks in solicitations; a refund check is a real negotiable instrument.'),
 nd('NY:GBL 396-AAA', 'Tobacco advertising near schools; not a tenancy matter.'),
 nd('NY:GBL 396-I', 'Gift certificates; not a tenancy matter.'),
 nd('NY:GBL 396-MM', 'Free trial offers; not a tenancy matter.'),
 nd('NY:GBL 396-X*2', 'Removal of newspapers from another\'s property; not a tenancy settlement matter.'),
 nd('NY:GBL 396-Y', 'Incentives in sales of consumer goods; not a tenancy matter.'),
 nd('NY:GBL 397', 'Use of non-profit organizations\' names in advertising; not a tenancy matter.'),
 nd('NY:GBL 397-A', 'Unsolicited flyers on private property in large cities; not a settlement step.'),
 nd('NY:GBL 399-CCC', 'Sale of battery smoke detectors with ten-year sealed batteries; detector charges at move-out are stated by NYC:HMC-27-2045-detector-charge.'),
 nd('NY:GBL 399-I', 'Sale and use of unsafe cribs in child care and lodging; not a tenancy matter.'),
 nd('NY:GBL 399-J', 'Movable soccer goal safety; not a tenancy matter.'),
 nd('NY:GBL 399-V', 'Towing from parking facilities; not a residential settlement matter.'),
 nd('NY:GBL 399-W', 'Gap amounts in non-motor-vehicle retail lease agreements for goods; not a lease of real property.'),
 nd('NY:GBL 399-YY', 'Directory listing protections by cable telephone providers for domestic violence victims; binds those providers.'),
 nd('NY:GBL 399-ZZZZZ', 'Affordable broadband for low-income consumers; binds broadband providers.'),
 nd('NY:GBL 399-ZZZZZ*2', 'Preferred names and pronouns by telephone providers; binds those providers.'),
 nd('NY:GBL 603', 'Severability clause.'),
 nd('NY:GBL 391-L', 'Personal emergency response service agreements; not a tenancy matter.'),
 nd('NY:GBL 394-C', 'Dating and social referral service contracts; not a tenancy matter.'),
 nd('NY:GBL 396-M', 'Mail-order and telephone-order merchandise; not a tenancy matter.'),
 nd('NY:GBL 396-Z', 'Rental vehicle protections; not a residential lease.'),
 nd('NY:GBL 399-NN', 'Right to repair digital electronic equipment; not a tenancy matter.'),
 nd('NY:GBL 399-PP', 'State enforcement of telemarketing sales rules; settlement and collection calls are not telemarketing sales calls. Collection calling is governed by US:47USC227-TCPA and the collection rules.'),
 nd('NY:GBL 399-Z', 'Do-not-call registry for telemarketing sales calls; a settlement or collection call is not a sales call.'),
])
