import sys; sys.path.insert(0, 'register/work'); from q4_lib import *
s='NY:18 NYCRR 352.3'
add([{'section_id': s, 'decision': 'new_rule', 'reason': 'Subdivision (i)(7) makes a landlord that took a homeless-family housing allowance return a pro rata share when the family leaves early, a payable in the final account; the rest of 352.3 sets grant amounts and shelter oversight that bind the district.', 'proposed': [rule(s, instrument='18 NYCRR Part 352 (public assistance)',
  id='NY:18NYCRR-352.3(i)(7)-pro-rata-return', provision='18 NYCRR 352.3(i)(1), (7)', actor='landlord participating in a district homeless-family housing allowance program', modality='obligation',
  condition='The landlord received an allowance from the social services district to secure an apartment for a homeless family under 18 NYCRR 352.3(i), agreeing to keep a specified apartment available to the family for a set period (up to 32 months), and the family leaves before that period ends, for any reason.',
  effect='The landlord must return to the district a pro rata portion of the allowance reflecting the balance of the period not used. This is owed to the district, not the tenant, and is not a deduction from the tenant\'s deposit; the district may place another eligible family in the apartment for the balance of the period. The tenant\'s own deposit and account are settled separately under the ordinary rules.',
  dependencies=['NY:GOL-7-108(1-a)(e)'],
  quote=q(s, 'the landlord will return a pro rata portion of the allowance reflecting the balance of the period.'),
  severity='critical', walk_step='5.8')]}])
s='NY:SSL 145-B'
add([{'section_id': s, 'decision': 'new_rule', 'reason': 'Makes a knowingly false claim to a social services district (for example an inflated damage or rent claim on an HRA security voucher, or keeping shelter payments for months the household was gone) liable for treble damages or $5,000.', 'proposed': [rule(s, instrument='NY Social Services Law',
  id='NY:SSL-145-b-false-claims', provision='SSL 145-b(1)-(2)', actor='landlord, managing agent, Handoff', modality='liability',
  determinacy='MIXED', judgment_terms=['knowingly', 'false statement or representation', 'deliberate concealment of any material fact'],
  condition='The landlord or its agent seeks or obtains payment from a social services district for housing furnished to a public-assistance household: a claim on a security voucher or agreement (NYC:HRA-voucher-claim-window), a claim under a housing allowance, or direct shelter payments; and the claim or a statement supporting it is knowingly false or conceals a material fact (for example damage the tenant did not cause, rent for months after the household left, or failure to disclose payments already received).',
  effect='The district or the State may recover civil damages of three times the amount falsely overstated (or three times its damages for a non-monetary falsehood), or $5,000, whichever is greater. A claim for payment made to a political subdivision or its contractor is a statement for this purpose, and any payment funded in part by public money counts. Claims on vouchers therefore carry only the itemized, supported amounts the ordinary deposit rules would allow (NY:GOL-7-108(1-a)(b)-refundable, NYC:HRA-voucher-proof).',
  dependencies=['NYC:HRA-voucher-claim-window', 'NYC:HRA-voucher-proof', 'NY:SSL-143-c-agency-deposit-refund'],
  quote=q(s, 'It shall be unlawful for any person, firm or corporation knowingly by means of a false statement or representation, or by deliberate concealment of any material fact, or other fraudulent scheme or device, on behalf of himself or others, to attempt to obtain or to obtain payment from public funds for services or supplies furnished or purportedly furnished pursuant to this chapter.'),
  construction=[{'source_file': 'register/texts/NY_SSL/145-b.txt', 'quote': q(s, 'three times the amount by which any figure is falsely overstated')}],
  reasoning='Housing furnished to a recipient under a security agreement (SSL 143-c) or shelter allowance (SSL 131-a) is furnished pursuant to the Social Services Law, and a claim for payment made to a social services district is a statement under 145-b(1)(b).',
  severity='critical', walk_step='5.8')]}])
nds = {
 'NY:SSL 131-BB': 'Designates NYC to run the FHEPS voucher program at HUD fair market rent; the landlord\'s duties for such vouchers are stated in the city rules (NYC:RCNY68-10-14(a), NYC:RCNY68-10-14(h)).',
 'NY:SSL 131-J': 'Utilities may not require deposits from public assistance recipients; binds utility corporations, not landlords.',
 'NY:SSL 131-U': 'Districts provide emergency domestic-violence shelter; binds the district.',
 'NY:SSL 141': 'Burial of deceased recipients and recovery from relatives; binds the district and relatives.',
 'NY:SSL 143-A': 'Retail instalment sellers and lenders give districts information on recipients; a landlord is neither.',
 'NY:SSL 152-B': 'Surplus from assets assigned to a district is credited to the recipient\'s estate; binds the district.',
 'NY:SSL 131-L': 'Agent Orange benefits disregarded in eligibility; eligibility only.',
 'NY:SSL 131-N': 'Resources exempt in calculating benefits; eligibility only.',
 'NY:SSL 131-O': 'Personal allowance accounts in residential care; not a market-rate tenancy.',
 'NY:SSL 131-Q': 'Expired electronic payment pilot for grants; eligibility administration.',
 'NY:SSL 131-R': 'Recovery of assistance from lottery winnings; binds the recipient and the district.',
 'NY:SSL 131-T': 'Periodic reporting by recipients with earnings; eligibility administration.',
 'NY:SSL 131-V': 'Temporary emergency shelter in nonprofit-operated units; shelter placement, not a market-rate tenancy.',
 'NY:SSL 131-X': 'Reverse mortgage proceeds not counted as income; eligibility only.',
 'NY:SSL 134': 'Supervision and visits of recipients by officials; binds the district.',
 'NY:SSL 136': 'Confidentiality of public welfare records held by officials; binds officials. A landlord\'s handling of tenant data is governed by the data rules stated at step 6.10.',
 'NY:SSL 142': 'Exclusiveness of SSI and family assistance; eligibility only.',
 'NY:SSL 142-A': 'Economic Opportunity Act payments disregarded; eligibility only.',
 'NY:SSL 142-B': 'Manpower training payments disregarded; eligibility only.',
 'NY:SSL 143': 'Employers give districts information on recipients on request; a landlord acting as landlord is not asked under it.',
 'NY:SSL 144-A': 'Banks give districts account information on recipients; binds financial institutions.',
 'NY:SSL 145': 'Crime of obtaining assistance by fraud; binds applicants and those who aid them. Landlord false claims are proposed at SSL 145-B.',
 'NY:SSL 145-A': 'Liens for Medicaid provider penalties; not a tenancy matter.',
 'NY:SSL 145-C': 'Sanctions on recipients who commit fraud; eligibility only.',
 'NY:SSL 146': 'Sale of assistance supplies; not a tenancy matter.',
 'NY:SSL 148': 'Bringing a needy person into a district to make them a public charge; not a settlement step.',
 'NY:SSL 151': 'Unlawful cashing of assistance checks and EBT transactions by liquor stores and similar licensees; not a landlord.',
 'NY:SSL 152-A': 'Burial reserves from assigned assets; binds the district.',
 'NY:SSL 131': 'Duty of districts to provide assistance and conditions on eligibility; binds the district and recipients.',
 'NY:SSL 131-A': 'Grant standards; subdivision on direct shelter payments to the owner when a recipient does not apply the shelter allowance to rent decides only who pays the rent during the tenancy, and such payments are credited as rent received. False claims are proposed at SSL 145-B.',
 'NY:SSL 139-A': 'Residency presumptions and anti-abuse rules for applicants; eligibility only.',
 'NY:18 NYCRR 352.10': 'Payment of life insurance premiums for recipients; not a tenancy matter.',
 'NY:18 NYCRR 352.11': 'Advance allowances recouped from grants; binds the district and recipient.',
 'NY:18 NYCRR 352.13': 'Military service income in budgeting; eligibility only.',
 'NY:18 NYCRR 352.15': 'Support payments in budgeting; eligibility only.',
 'NY:18 NYCRR 352.16': 'Exemption of income and resources; eligibility only.',
 'NY:18 NYCRR 352.22': 'Noncountable income and resources; eligibility only.',
 'NY:18 NYCRR 352.23': 'Use of resources; eligibility only.',
 'NY:18 NYCRR 352.25': 'Net income from assigned assets; eligibility only.',
 'NY:18 NYCRR 352.26': 'Life insurance as a resource; eligibility only.',
 'NY:18 NYCRR 352.27': 'Real property as a resource; eligibility only.',
 'NY:18 NYCRR 352.31': 'Estimate of need, application of income and recovery of overpayments from recipients; binds the district and recipient (the recipient-side recovery of a security payment is referenced in 352.6, proposed there).',
 'NY:18 NYCRR 352.32': 'Calculating the budget; eligibility only.',
 'NY:18 NYCRR 352.34': 'Referral where a household\'s living situation endangers its members; binds the district.',
 'NY:18 NYCRR 352.35': 'Eligibility for temporary housing assistance for homeless persons; shelter placement, not a market-rate tenancy.',
 'NY:18 NYCRR 352.36': 'Temporary housing placement of certain sex offenders; shelter placement, not a market-rate tenancy.',
 'NY:18 NYCRR 352.37': 'Repealed.',
 'NY:18 NYCRR 352.38': 'Security measures in homeless shelters; binds shelter operators, not a market-rate tenancy.',
 'NY:18 NYCRR 352.39': 'Operational plans for uncertified homeless shelters; binds shelter operators, not a market-rate tenancy.',
 'NY:18 NYCRR 352.4': 'Shelter costs for recipient-owned homes; the recipient is the owner, not a tenant.',
 'NY:18 NYCRR 352.5': 'Energy assistance and vendor payments to home energy vendors; a landlord is paid for heat only as rent, and utility credits are stated by NY:RPL-235-a.',
 'NY:18 NYCRR 352.7': 'Allowances for other items of need (furniture, clothing, services); grants to recipients.',
}
add([nd(k, v) for k, v in nds.items()])
