import sys; sys.path.insert(0, 'register/work'); from q4_lib import *
s='NY:EPTL 11-4.7'
add([{'section_id': s, 'decision': 'new_rule', 'reason': 'Decides whether a claim arising during estate administration (the estate as owner, or an estate that kept the unit after the tenant died) is pursued against the estate or the fiduciary personally.', 'proposed': [rule(s, instrument='NY Estates, Powers and Trusts Law',
  id='NY:EPTL-11-4.7-fiduciary-liability', provision='EPTL 11-4.7(a)-(c)', actor='landlord, managing agent, former tenant', modality='liability',
  determinacy='MIXED', judgment_terms=['failed to exercise reasonable care, diligence and prudence'],
  condition='Branch (a): an estate owns the building and its executor or administrator runs it (so the deposit refund and statement duties arise during administration). Branch (b): a deceased tenant\'s executor or administrator kept or used the unit, or entered a settlement or payment plan with the landlord, during administration.',
  effect='Claims on contracts the fiduciary made in its fiduciary capacity, on obligations from the estate\'s ownership or control of property (for example the deposit refund owed by an estate-owned building, or use and occupancy owed by the estate), or on torts in administration are asserted against the estate by suing the fiduciary in its fiduciary capacity. The fiduciary is personally liable on such a contract only if it did not disclose its representative capacity and identify the estate, and personally liable for ownership obligations or torts only if it failed to exercise reasonable care, diligence and prudence.',
  dependencies=['NY:ADJ-tenant-death-payee', 'NY:COMMONLAW-owner-death-agency'],
  quote=q(s, 'Claims based on contracts entered into by a personal representative in his fiduciary capacity, on obligations arising from ownership or control of the estate or on torts committed in the course of estate administration may be asserted against the estate by proceeding against the personal representative in his fiduciary capacity'),
  severity='major', walk_step='2.5')]}])
add([
 {'section_id': 'NY:EPTL 1-2.13', 'decision': 'stated', 'atom_ids': ['NY:ADJ-tenant-death-payee'], 'reason': 'A personal representative is one holding letters, and excludes guardians and conservators; the rule pays the executor or administrator on letters.'},
 {'section_id': 'NY:EPTL 11-1.3', 'decision': 'stated', 'atom_ids': ['NY:ADJ-tenant-death-payee'], 'reason': 'A named executor has no power before letters beyond funeral expenses and preservation; the rule pays the executor only on letters and holds the refund in trust until a fiduciary presents authority.'},
 nd('NY:EPTL 1-1.5', 'Temporal application of the EPTL; transitional.'),
 nd('NY:EPTL 1-2.12', 'Definition of person in the EPTL; no stated rule depends on it.'),
 nd('NY:EPTL 1-2.14', 'Definition of per stirpes distribution among heirs; internal to the estate.'),
 nd('NY:EPTL 1-2.16', 'Definition of distribution by representation among heirs; internal to the estate.'),
 nd('NY:EPTL 1-2.19', 'Definition of a will (electronic wills from 2027-12-12); the landlord relies on letters, not on the will.'),
 nd('NY:EPTL 1-2.9-A', 'Definition of infant or minor for the EPTL; capacity of a minor tenant is governed by the CPLR rules already stated (NY:CPLR-1203-1015-5208-parties).'),
 nd('NY:EPTL 11-1.2', 'Estate and income tax elections by fiduciaries; internal to the estate.'),
 nd('NY:EPTL 11-1.4', 'Cures recorded deeds, mortgages or leases executed by fewer than all executors once ten years have passed after recording; not a step in settling a residential tenancy.'),
 nd('NY:EPTL 11-1.5', 'When a fiduciary pays legacies and distributive shares; internal to the estate. The creditor\'s claim period is stated in NY:ADJ-tenant-death-payee.'),
 nd('NY:EPTL 11-1.6', 'Fiduciaries keep estate property separate; binds the fiduciary. A deposit held by an estate-owned building is already trust money under NY:GOL-7-103(1)-trust.'),
 nd('NY:EPTL 11-1.7', 'Voids exoneration clauses for executors and trustees; internal to the estate.'),
 nd('NY:EPTL 11-2.1', 'Allocation of receipts between income and principal in trusts and estates; accounting among beneficiaries, not between landlord and tenant.'),
 nd('NY:EPTL 11-2.3', 'Prudent investor rule for trustees; not a tenancy matter.'),
 nd('NY:EPTL 11-2.4', 'Optional unitrust for trusts; not a tenancy matter.'),
 nd('NY:EPTL 13-1.2', 'A testator\'s claim against the executor is an estate asset; internal to the estate.'),
 nd('NY:EPTL 13-1.4', 'Supreme Court action to compromise claims to estate assets under SCPA 2106; internal to the estate.'),
 nd('NY:EPTL 13-3.1', 'Payees of non-transferable U.S. savings bonds take them outside the estate; not a tenancy matter.'),
 nd('NY:EPTL 13-3.2', 'Designated beneficiaries of pensions, insurance and annuities take outside the will and intestacy rules; those assets are not estate property from which the landlord\'s claim is paid, which the estate-claim rules already reflect by reaching only estate assets and distributees\' receipts.'),
 nd('NY:EPTL 4-1.1', 'Intestate shares among spouse and relatives; the landlord pays the fiduciary, not the heirs (NY:ADJ-tenant-death-payee).'),
 nd('NY:EPTL 4-1.2', 'Inheritance by non-marital children; internal to the estate.'),
 nd('NY:EPTL 4-1.6', 'A joint tenant convicted of murdering the other loses joint bank account funds; not a tenancy matter.'),
])
