import sys; sys.path.insert(0, 'register/work'); from q4_lib import *
U = 'NY Uniform Commercial Code art. 3 (commercial paper)'
s='NY:UCC 3-116'
add([{'section_id': s, 'decision': 'partial', 'atom_ids': ['NY:ADJ-cotenants-payee'], 'reason': 'The payee rule decides who owns the refund; 3-116 decides how a refund check to several co-tenants must be drawn to match it.', 'proposed': [rule(s, instrument=U,
  id='NY:UCC-3-116-cotenant-refund-check', provision='UCC 3-116(a)-(b)', actor='landlord or managing agent paying a refund by check', modality='procedure',
  condition='The refund is owed to two or more co-tenants and is paid by one check naming more than one payee.',
  effect='A check payable to the payees in the alternative ("A or B") may be negotiated, discharged or enforced by any one payee who holds it; a check payable to them jointly ("A and B") may be negotiated, discharged or enforced only by all of them together. So: where the refund is joint and paying the whole to any one discharges the landlord (NY:ADJ-cotenants-payee branch (a)), either form discharges it once paid; where records show each co-tenant\'s share (branch (b)), a check payable "A or B" lets one co-tenant take the whole and does not discharge the landlord as to the others, so pay separate checks in the proportions owed or one check payable jointly ("A and B").',
  dependencies=['NY:ADJ-cotenants-payee'],
  quote=q(s, 'if not in the alternative is payable to all of them and may be negotiated, discharged or enforced only by all of them.'),
  severity='major', walk_step='6.6', amends='NY:ADJ-cotenants-payee')]}])
s='NY:UCC 3-403'
add([{'section_id': s, 'decision': 'new_rule', 'reason': 'Decides whether a manager or Handoff that signs refund checks for the owner becomes personally liable on them, which turns on the form of signature.', 'proposed': [rule(s, instrument=U,
  id='NY:UCC-3-403-agent-signature', provision='UCC 3-403(1)-(3)', actor='managing agent, Handoff or their staff signing refund checks for the owner', modality='liability',
  condition='A managing agent, Handoff or an employee signs a refund check (or other instrument) drawn for the owner.',
  effect='Configuration (a): the check names the owner and the signature shows representative capacity (for example "Owner LLC, by Jane Doe, Agent", or the organization\'s name with the signer\'s name and office): the signer is not personally liable on it. (b) The check neither names the owner nor shows representative capacity: the signer is personally liable on it to any holder. (c) It names the owner but does not show capacity, or shows capacity but does not name the owner: the signer is personally liable, except as against the immediate party (the tenant) where it is shown that both understood the signer acted for the owner. Checks drawn on the owner\'s or the manager\'s escrow account in the owner\'s name with a representative signature fall in (a).',
  dependencies=['NY:ADJ-provide-address-branches'],
  quote=q(s, 'is personally obligated if the instrument neither names the person represented nor shows that the representative signed in a representative capacity'),
  severity='major', walk_step='6.4')]}])
s='NY:UCC 3-802'
add([{'section_id': s, 'decision': 'new_rule', 'reason': 'Decides when a refund or balance paid by check counts as paid: a check suspends the obligation until presentment and, if dishonored, the obligation revives.', 'proposed': [rule(s, instrument=U,
  id='NY:UCC-3-802-check-suspends-obligation', provision='UCC 3-802(1)', actor='landlord, managing agent, former tenant', modality='effect',
  condition='Branch (a): the landlord pays the refund by its own (or its manager\'s) check. Branch (b): the landlord pays the refund by a bank\'s cashier\'s or teller\'s check with no recourse against it. Branch (c): the former tenant pays the balance by personal check.',
  effect='(a) The refund obligation is suspended from delivery until the check is presented; if the check is dishonored (for example insufficient funds or a stop-payment order not justified by the tenant\'s conduct), the tenant may sue on the check or on the deposit claim, so a refund check that is dishonored has not returned the deposit, and if it is not made good within the 14 days the refund was not returned on time (NY:GOL-7-108(1-a)(e)-forfeiture). (b) The refund obligation is discharged to the check\'s amount when the tenant takes it. (c) The balance is suspended until presentment; if the tenant\'s check is dishonored, the landlord may sue on the check or on the balance (returned-check fee limits: NY:RPL-238-a(2-a)); payment of the check discharges the balance to its amount. A check marked "payment in full" is governed by NY:UCC-1-308-full-payment-check.',
  dependencies=['NY:GOL-7-108(1-a)(e)', 'NY:GOL-7-108(1-a)(e)-forfeiture', 'NY:ADJ-provide-written-dispatch', 'NY:RPL-238-a(2-a)', 'NY:UCC-1-308-full-payment-check'],
  quote=q(s, 'in any other case the obligation is suspended pro tanto until the instrument is due or if it is payable on demand until its presentment. If the instrument is dishonored action may be maintained on either the instrument or the obligation'),
  reasoning='A drawer\'s own check only suspends the refund obligation; on dishonor the obligation is enforceable as if unpaid, so the deposit was not returned by the dishonored check. A bank-drawn check without recourse discharges it.',
  severity='critical', walk_step='6.4')]}])
s='NY:UCC 3-804'
add([{'section_id': s, 'decision': 'new_rule', 'reason': 'Decides what the landlord faces when a tenant says the refund check was lost or stolen: the tenant can still recover, with court-ordered security protecting the landlord.', 'proposed': [rule(s, instrument=U,
  id='NY:UCC-3-804-lost-refund-check', provision='UCC 3-804; 3-802(1)(b)', actor='landlord or managing agent', modality='liability',
  condition='The former tenant says the refund check was lost, destroyed or stolen before it was paid.',
  effect='The refund is not paid by a check that was never paid (NY:UCC-3-802-check-suspends-obligation), and the tenant, as owner of the lost check, may sue and recover from the landlord on proof of ownership, the facts preventing its production and its terms; the court must then require security of at least twice the unpaid amount indemnifying the landlord against later claims on the check. Reissuing a replacement check or electronic payment satisfies the refund; the landlord\'s exposure to a later holder of the original check is what the security protects.',
  dependencies=['NY:UCC-3-802-check-suspends-obligation'],
  quote=q(s, 'The court shall require security, in an amount fixed by the court not less than twice the amount allegedly unpaid on the instrument, indemnifying the defendant'),
  severity='major', walk_step='6.4')]}])
nds = {
 'NY:UCC 1-103': 'Construction of the UCC and supplementary principles of law; general canon.',
 'NY:UCC 1-104': 'Construction against implied repeal; general canon.',
 'NY:UCC 1-202': 'When a person has notice or knowledge under the UCC; no settlement rule on checks turns on it beyond NY:UCC-1-308-full-payment-check, which turns on the reservation made at acceptance.',
 'NY:UCC 1-205': 'Reasonable time and seasonable action under the UCC; no chain deadline is a UCC deadline.',
 'NY:UCC 1-206': 'Meaning of presumptions under the UCC; evidence canon.',
 'NY:UCC 1-207': 'Statute of frauds for personal property sales over $5,000; a lease of real property is not such a contract.',
 'NY:UCC 1-303': 'Course of performance and dealing for UCC transactions; the lease is not a UCC transaction.',
 'NY:UCC 1-307': 'Third-party documents as prima facie evidence in UCC transactions; evidence rule.',
 'NY:UCC 1-309': 'Acceleration at will under UCC instruments and agreements; a lease acceleration clause is not governed by the UCC.',
 'NY:UCC 1-102': 'Article 1 applies only to transactions governed by another UCC article; confirms that only checks and other instruments in the chain are UCC matters.',
 'NY:UCC 1-201': 'General UCC definitions; the proposed article 3 rules use them in their ordinary scope and none changes a chain rule\'s reach.',
 'NY:UCC 1-204': 'Definition of value; relevant only to holder-in-due-course status.',
 'NY:UCC 1-310': 'Subordination agreements; not a tenancy matter.',
 'NY:UCC 3-103': 'Scope of article 3 (excludes money, documents of title, investment securities); a check is within it, which the proposed rules assume.',
 'NY:UCC 3-104': 'Formal requisites of a negotiable instrument; an ordinary refund or rent check meets them, and no settlement step turns on the form.',
 'NY:UCC 3-105': 'When a promise or order is unconditional; formal requisite of negotiability.',
 'NY:UCC 3-106': 'Sum certain; formal requisite of negotiability.',
 'NY:UCC 3-107': 'Money and foreign-currency instruments; not a settlement step.',
 'NY:UCC 3-108': 'Instruments payable on demand; a check is a demand instrument, as the proposed rules assume.',
 'NY:UCC 3-109': 'Definite time; formal requisite of negotiability.',
 'NY:UCC 3-110': 'Payable to order; formal requisite.',
 'NY:UCC 3-111': 'Payable to bearer; formal requisite.',
 'NY:UCC 3-112': 'Terms and omissions not affecting negotiability; formal requisite.',
 'NY:UCC 3-113': 'Seals on instruments; formal.',
 'NY:UCC 3-114': 'Dating, antedating and postdating instruments; a refund is provided when sent with the payment (NY:ADJ-provide-written-dispatch), and a postdated check is not a payment on the date sent.',
 'NY:UCC 3-115': 'Incomplete instruments; not a settlement step.',
 'NY:UCC 3-117': 'Instruments payable to a named person with words of description (for example as executor); payable to that representative, whose authority is decided by the payee rules (NY:ADJ-tenant-death-payee).',
 'NY:UCC 3-118': 'Rules of construction for ambiguous instrument terms; mechanics.',
 'NY:UCC 3-119': 'Other writings affecting an instrument; mechanics.',
 'NY:UCC 3-120': 'Instruments payable through a bank; mechanics.',
 'NY:UCC 3-121': 'Instruments payable at a bank; mechanics.',
 'NY:UCC 3-122': 'Accrual of actions on instruments (against a drawer on demand after dishonor); the landlord\'s claim for a balance is timed by the lease-claim period, which is longer and unaffected.',
 'NY:UCC 3-201': 'Transfer and right to indorsement; negotiation mechanics.',
 'NY:UCC 3-202': 'What negotiation is; mechanics.',
 'NY:UCC 3-203': 'Indorsement in a wrong or misspelled name; mechanics.',
 'NY:UCC 3-204': 'Special and blank indorsements; mechanics.',
 'NY:UCC 3-205': 'Kinds of restrictive indorsement; a "paid in full" legend is governed by NY:UCC-1-308-full-payment-check, not by restrictive indorsement rules.',
 'NY:UCC 3-206': 'Effect of restrictive indorsements on banks and transferees; bank mechanics.',
 'NY:UCC 3-207': 'Negotiation effective though rescindable; mechanics.',
 'NY:UCC 3-208': 'Reacquisition of instruments; mechanics.',
 'NY:UCC 3-301': 'Rights of a holder; mechanics.',
 'NY:UCC 3-302': 'Holder in due course; not a settlement step between landlord and tenant.',
 'NY:UCC 3-303': 'Taking for value; holder-in-due-course mechanics.',
 'NY:UCC 3-304': 'Notice to purchaser; holder-in-due-course mechanics.',
 'NY:UCC 3-305': 'Defenses against a holder in due course; not between landlord and tenant.',
 'NY:UCC 3-306': 'Defenses against one not a holder in due course; between landlord and tenant the lease defenses govern.',
 'NY:UCC 3-401': 'No one is liable on an instrument unless it bears the person\'s signature; agent signatures are proposed at UCC 3-403.',
 'NY:UCC 3-402': 'Signature in ambiguous capacity is an indorsement; mechanics.',
 'NY:UCC 3-404': 'Unauthorized signatures; bank and fraud mechanics.',
 'NY:UCC 3-405': 'Impostors and fictitious payees; bank and fraud mechanics.',
 'NY:UCC 3-406': 'Negligence contributing to alteration or forgery; bank and fraud mechanics.',
 'NY:UCC 3-407': 'Alteration of instruments; bank and fraud mechanics.',
 'NY:UCC 3-411': 'Certification of checks; a certified refund check is bank-drawn and handled by proposed NY:UCC-3-802-check-suspends-obligation branch (b).',
 'NY:UCC 3-413': 'The drawer promises to pay on dishonor; the landlord\'s liability on a dishonored refund check is proposed at UCC 3-802 and the signer\'s at UCC 3-403.',
 'NY:UCC 3-414': 'Contract of an indorser; mechanics.',
 'NY:UCC 3-415': 'Accommodation parties on instruments; a lease guarantor\'s liability is on the guaranty (NY:GOL-5-701(a)(2)-guaranty).',
 'NY:UCC 3-416': 'Guarantors of instruments; a lease guaranty is not an instrument guaranty (NY:GOL-5-701(a)(2)-guaranty).',
 'NY:UCC 3-417': 'Presentment and transfer warranties; bank mechanics.',
 'NY:UCC 3-418': 'Finality of payment or acceptance; bank mechanics.',
 'NY:UCC 3-419': 'Conversion of instruments (for example paying over a missing co-payee indorsement); binds the paying bank; the landlord\'s draw on co-tenant checks is proposed at UCC 3-116.',
 'NY:UCC 3-501': 'When presentment and notice of dishonor are needed; bank mechanics.',
 'NY:UCC 3-502': 'Effect of unexcused delay in presentment; the drawer is discharged only where the drawee bank fails during the delay, which changes no settlement step.',
 'NY:UCC 3-503': 'Reasonable time for presentment (30 days for a drawer\'s liability on a check); an uncashed refund stays owed and is handled as unclaimed funds (NY:OSC-MS11-refunds-due).',
 'NY:UCC 3-504': 'How presentment is made; bank mechanics.',
 'NY:UCC 3-505': 'Rights of the party to whom presentment is made; bank mechanics.',
 'NY:UCC 3-506': 'Time allowed for acceptance or payment; bank mechanics.',
 'NY:UCC 3-507': 'Definition of dishonor; used by proposed NY:UCC-3-802-check-suspends-obligation in its ordinary meaning.',
 'NY:UCC 3-508': 'Notice of dishonor; bank and indorser mechanics.',
 'NY:UCC 3-509': 'Protest; formal mechanics.',
 'NY:UCC 3-510': 'Evidence of dishonor; evidence mechanics.',
 'NY:UCC 3-511': 'Waived or excused presentment and notice; mechanics.',
 'NY:UCC 3-601': 'Ways parties to an instrument are discharged; the discharge of the refund or balance obligation is proposed at UCC 3-802.',
 'NY:UCC 3-602': 'Discharge and holders in due course; mechanics.',
 'NY:UCC 3-603': 'Payment to the holder discharges a party on the instrument; the underlying refund is discharged when the check is paid (proposed UCC 3-802).',
 'NY:UCC 3-604': 'Tender of payment on an instrument stops later interest and costs on the instrument; a refund owed under the lease is not an instrument obligation.',
 'NY:UCC 3-605': 'Cancellation and renunciation of rights on an instrument; mechanics.',
 'NY:UCC 3-606': 'Impairment of recourse or collateral; suretyship on instruments.',
 'NY:UCC 3-803': 'Vouching in a party answerable over; litigation mechanics.',
 'NY:UCC 3-805': 'Non-negotiable instruments; mechanics.',
 'NY:UCC 3-409': 'A check is not an assignment of the drawer\'s bank funds; mechanics.',
 'NY:UCC 3-410': 'Acceptance of drafts; mechanics.',
 'NY:UCC 3-412': 'Acceptance varying a draft; mechanics.',
 'NY:UCC 3-801': 'Drafts in a set; mechanics.',
}
add([nd(k, v) for k, v in nds.items()])
