import sys; sys.path.insert(0, 'register/work'); from q4_lib import *
SC = 'NY Surrogate\'s Court Procedure Act'
s='NY:SCPA 720'
add([{'section_id': s, 'decision': 'partial', 'atom_ids': ['NY:ADJ-tenant-death-payee'], 'reason': 'Decides whether a refund paid to a fiduciary whose letters are later revoked still discharges the landlord.', 'proposed': [rule(s, instrument=SC,
  id='NY:SCPA-720-revoked-letters', provision='SCPA 720', actor='landlord or managing agent', modality='effect',
  condition='The landlord paid the refund to, or settled the balance with, a tenant\'s (or owner\'s) executor or administrator whose letters were later suspended, modified or revoked, or who was removed.',
  effect='The payment or settlement stays valid if it was within the fiduciary\'s powers and the landlord acted in good faith before the removal, suspension, modification or revocation, or before process in the removal proceeding was served (or after service where the fiduciary\'s powers over that act were not suspended). After the decree the former fiduciary\'s powers cease: pay or settle only with the successor or the person the decree names.',
  dependencies=['NY:ADJ-tenant-death-payee', 'NY:SCPA-703-letters-evidence'],
  quote=q(s, 'does not affect the validity of any act within the powers of the fiduciary done by him before his removal or the suspension, modification or revocation of his letters or the service of process, where the other party acted in good faith'),
  severity='major', walk_step='2.5', amends='NY:ADJ-tenant-death-payee')]}])
s='NY:SCPA 704'
add([{'section_id': s, 'decision': 'new_rule', 'reason': 'Decides who has authority when two surrogate\'s courts issue letters on the same estate, and whether good-faith dealings with the later holder stand.', 'proposed': [rule(s, instrument=SC,
  id='NY:SCPA-704-first-letters', provision='SCPA 704', actor='landlord or managing agent', modality='priority',
  condition='Two different surrogate\'s courts have issued letters on the same deceased tenant\'s or owner\'s estate.',
  effect='The person to whom letters were first issued, on a good-faith application, has exclusive authority and is the payee. Acts of the later holder done in good faith before notice of the first letters (for example receiving the refund) remain valid; once the landlord has notice of the first letters, it deals only with their holder.',
  dependencies=['NY:SCPA-703-letters-evidence'],
  quote=q(s, 'But the acts of a person to whom letters were afterwards issued, done in good faith before notice of the letters first issued are valid'),
  severity='minor', walk_step='2.5')]}])
nds = {
 'NY:SCPA 1120': 'Consuls may appear for non-resident noncitizens in public administrator proceedings; court procedure.',
 'NY:SCPA 1125': 'Service on the public administrator in certain proceedings; court procedure.',
 'NY:SCPA 1805': 'Claims of the fiduciary itself against the estate; the landlord is not the fiduciary.',
 'NY:SCPA 2103': 'A fiduciary\'s proceeding to discover property withheld; a forum for the estate\'s existing refund claim, changing nothing the landlord owes (the payee is stated in NY:ADJ-tenant-death-payee).',
 'NY:SCPA 2104': 'Trial and decree in a discovery proceeding; court procedure.',
 'NY:SCPA 2105': 'Proceeding to compel a fiduciary to deliver property claimed by another; the landlord\'s claim route is presentation (proposed SCPA 1803, 1806, 1810).',
 'NY:SCPA 2109': 'Money paid into the surrogate\'s court follows CPLR 2601-2608; court procedure.',
 'NY:SCPA 1001': 'Order of priority among persons for letters of administration; the landlord\'s route as creditor and the fallback to the public administrator or petitioner are proposed at SCPA 1002.',
 'NY:SCPA 1003': 'Service of process in a proceeding for letters; court procedure.',
 'NY:SCPA 1004': 'Decree on return of process for letters; court procedure.',
 'NY:SCPA 1005': 'Notice of an application for letters to distributees; court procedure.',
 'NY:SCPA 1006': 'A designated administrator who does not qualify is deemed to renounce; court procedure the landlord may invoke as creditor but that changes no settlement step.',
 'NY:SCPA 1007': 'Appointment of an administrator de bonis non when the office falls vacant; who is then paid is proposed at EPTL 11-3.4 and SCPA 706.',
 'NY:SCPA 102': 'CPLR procedure applies in surrogate\'s court unless the SCPA provides otherwise; general procedure.',
 'NY:SCPA 103': 'SCPA definitions; the terms the tenant-death rules use (fiduciary, letters, creditor, property) carry their ordinary meaning in those rules and do not change their reach.',
 'NY:SCPA 104': 'Application of the act and confirmation of prior acts; transitional.',
 'NY:SCPA 1103': 'Appointment of deputy public administrators; internal office rules.',
 'NY:SCPA 1104': 'Oath and bond of NYC public administrators; internal office rules.',
 'NY:SCPA 1106': 'Commissions of public administrators; internal office rules.',
 'NY:SCPA 1107': 'Public administrators pay commissions into the city treasury; internal office rules.',
 'NY:SCPA 1110': 'The City answers for its public administrators\' conduct; changes nothing the landlord does.',
 'NY:SCPA 1111': 'Delivery of papers and money on a public administrator\'s vacancy; internal office rules.',
 'NY:SCPA 1114': 'The public administrator\'s inquiry and subpoena power; the landlord complies with any subpoena as a witness, which changes no settlement step.',
 'NY:SCPA 1116': 'The public administrator may apply for letters; the payee rules for it are stated or proposed (NY:ADJ-tenant-death-payee, SCPA 1112, 1115, 1118).',
 'NY:SCPA 1119': 'Public administrator notifies consuls for noncitizen estates; binds the public administrator only.',
 'NY:SCPA 1121': 'Distributees may supersede the public administrator; the landlord then deals with the new fiduciary under its letters (proposed NY:SCPA-703-letters-evidence).',
 'NY:SCPA 1122': 'A superseded public administrator accounts to its successor; internal to the estate.',
 'NY:SCPA 1124': 'Public administrator\'s appeals without bond; court procedure.',
 'NY:SCPA 1126': 'The public administrator may destroy valueless papers and property after five years; binds the public administrator only.',
 'NY:SCPA 1127': 'Public administrator record destruction after ten years; internal office rules.',
 'NY:SCPA 1128': 'Administrative board for public administrators; internal office rules.',
 'NY:SCPA 1303': 'Who may qualify as a voluntary administrator; the landlord relies on the court\'s short certificate (NY:ADJ-tenant-death-payee), not on the order of eligibility.',
 'NY:SCPA 1308': 'Liability of a voluntary administrator to creditors and distributees; binds the administrator.',
 'NY:SCPA 1311': 'Public administrators may receive small social security, unemployment and workers\' compensation payments; not a landlord payment.',
 'NY:SCPA 1312': 'Liberal construction of the small-estates article.',
 'NY:SCPA 1601': 'Purpose of ancillary administration; the landlord\'s payment choice for a non-domiciliary tenant is proposed at EPTL 13-3.4 and SCPA 1309.',
 'NY:SCPA 1602': 'Ancillary probate of a foreign-probated will; court procedure.',
 'NY:SCPA 1603': 'Effect of a pending foreign will contest on ancillary distribution; internal to the estate.',
 'NY:SCPA 1604': 'Who receives ancillary letters on a foreign will; the landlord relies on the letters issued (proposed NY:SCPA-703-letters-evidence).',
 'NY:SCPA 1605': 'Original probate of a non-domiciliary\'s will in New York; court procedure.',
 'NY:SCPA 1606': 'Proof of a non-domiciliary\'s will; court procedure.',
 'NY:SCPA 1607': 'Who receives ancillary letters of administration; the landlord relies on the letters issued.',
 'NY:SCPA 1608': 'Designation and qualification of ancillary fiduciaries; court procedure.',
 'NY:SCPA 1609': 'Who may petition for ancillary letters (including creditors); court procedure paralleling proposed SCPA 1002.',
 'NY:SCPA 1610': 'An ancillary fiduciary has a fiduciary\'s powers and may be directed to pay New York creditors; the landlord presents its claim to it like any fiduciary (proposed SCPA 1803).',
 'NY:SCPA 1611': 'Ancillary administration for an absentee presumed dead; court procedure.',
 'NY:SCPA 1612': 'Foreign adjudications bind the ancillary fiduciary; court procedure.',
 'NY:SCPA 1613': 'New York law governs non-domiciliary wills and administration here; no settlement step changes.',
 'NY:SCPA 1614': 'Authentication of foreign wills and letters under the CPLR; evidence procedure.',
 'NY:SCPA 1615': 'Evidentiary effect of wills recorded under former law; historical.',
 'NY:SCPA 1807': 'An allowed claim is established, subject to objections for fraud, negligence or collusion on the accounting; the allowance route is proposed at SCPA 1806.',
 'NY:SCPA 1809': 'Either side may ask the court to decide a claim\'s validity; an optional forum that changes no deadline or amount (deadlines proposed at SCPA 1806, 1808, 1810).',
 'NY:SCPA 1813': 'Court authorization to compromise or sell estate claims; the fiduciary\'s own power to settle with the landlord is proposed at EPTL 11-1.1.',
 'NY:SCPA 1814': 'Article 18 does not apply to trusts; the landlord\'s claims are against estates.',
 'NY:SCPA 2101': 'General rules for miscellaneous surrogate\'s court proceedings; court procedure.',
 'NY:SCPA 2102': 'Proceedings to compel a fiduciary to give information or pay an allowed claim; the landlord\'s right to compel payment of an allowed claim is in proposed NY:SCPA-1806-allowance-rejection.',
 'NY:SCPA 2106': 'Court-approved compromises affecting persons under disability; internal to the estate.',
 'NY:SCPA 2107': 'Court direction on sale of estate property; internal to the estate.',
 'NY:SCPA 2110': 'Fixing attorneys\' compensation in an estate; internal to the estate.',
 'NY:SCPA 2112': 'Compensation of persons acting under powers of attorney; internal to the estate.',
 'NY:SCPA 2113': 'Proof of heirship to real property; affects title, not the settlement.',
 'NY:SCPA 701': 'Formal requisites of letters; the landlord relies on letters as issued (proposed NY:SCPA-703-letters-evidence).',
 'NY:SCPA 705': 'Periods measured from letters run from the first letters on successive letters; the 7-month claim period in NY:ADJ-tenant-death-payee already runs from letters, and successive letters do not restart it.',
 'NY:SCPA 707': 'Eligibility to receive letters; the landlord relies on letters issued.',
 'NY:SCPA 708': 'Fiduciary files a domiciliary address and designates the clerk for process; the delivery address for claims is in proposed NY:SCPA-1803-claim-form.',
 'NY:SCPA 709': 'Objections to granting letters; court procedure.',
 'NY:SCPA 710': 'When a bond is required of an executor; internal to the estate.',
 'NY:SCPA 711': 'Grounds for suspending or revoking letters, on petition of a creditor among others; the effect on payments is proposed at SCPA 720.',
 'NY:SCPA 712': 'Petition and process to revoke letters; court procedure.',
 'NY:SCPA 713': 'Hearing and decree on revocation; court procedure.',
 'NY:SCPA 716': 'Intermediate orders in revocation proceedings; court procedure.',
 'NY:SCPA 717': 'Suspension of a fiduciary\'s powers during war service; the landlord then deals with the successor or remaining fiduciary (proposed SCPA 706).',
 'NY:SCPA 718': 'Nominated fiduciaries in war service; court procedure.',
 'NY:SCPA 719': 'Cases where letters are revoked without process; effect on payments proposed at SCPA 720.',
 'NY:SCPA 721': 'Distributees remain liable to the rightful owner after letters are revoked; internal to the estate.',
 'NY:SCPA 724': 'Article 7 does not apply to lifetime trustees.',
 'NY:SCPA 725': 'Court rules on estate valuation after letters; internal to the estate.',
}
add([nd(k, v) for k, v in nds.items()])
