import sys
sys.path.insert(0, "register/work")
from q5_lib import add, nd, rule

p = rule("US:11 USC 726", "US:11USC726-ch7-distribution-order", "11 U.S.C. 726(a)(1)-(4), (b)", "landlord; tenant", "applies",
         "A chapter 7 estate is distributed while the landlord holds a claim against a former tenant (or a former tenant holds a claim against the owner).",
         "Distribution order: (1) priority claims in 507 order (including a tenant's deposit priority, US:11USC507(a)(7)-deposit-priority) filed on time or tardily before the trustee's final report deadline; (2) general unsecured claims filed on time, and tardy claims of a creditor that had neither notice nor actual knowledge of the case in time to file, if filed in time to permit payment; (3) other tardily filed unsecured claims, paid only after class (2) is paid in full; (4) claims for fines, penalties, forfeitures and multiple, exemplary or punitive damages to the extent they are not compensation for actual pecuniary loss (the punitive part of a statutory deposit penalty, for example the amount above the deposit in a twice-the-deposit award); (5) post-petition interest at the legal rate; (6) the debtor. Claims in the same class share pro rata. A landlord that files after the 3002(c) deadline with notice of the case is paid only in class (3).",
         "major", "8.8", "(a) Except as provided in section 510 of this title, property of the estate shall be distributed", "(6) sixth, to the debtor.",
         dependencies=["US:FRBP-3002(c)-claim-deadline"])
add("US:11 USC 726", "partial",
    "Fixes where a late landlord claim and a tenant's penalty damages rank in chapter 7; the existing deadline rule says only that a late claim is disallowed except as tardy filing is permitted.",
    atom_ids=["US:FRBP-3002(c)-claim-deadline"], proposed=[{**p, "amends": "US:FRBP-3002(c)-claim-deadline"}])

add("US:11 USC 727", "new_rule",
    "Decides whether a chapter 7 debtor (tenant or individual owner) gets a discharge at all, what it covers, and the landlord's right to object or revoke; the existing discharge rule assumes a discharge covering the balance.",
    proposed=[rule("US:11 USC 727", "US:11USC727-ch7-discharge", "11 U.S.C. 727(a)(1), (a)(2)-(12), (b), (c)(1), (d), (e)", "landlord; collector; manager", "discharges",
                   "A former tenant (or an individual owner owing a tenant's refund) is a chapter 7 debtor.",
                   "(1) Tenant not an individual (an LLC or corporation): no discharge is granted; the balance survives against the company, but its assets are liquidated for all creditors and collection is stayed while the case is open. (2) Individual: the court grants a discharge unless a ground in 727(a) is proved (transfer or concealment of property with intent to hinder, delay or defraud a creditor within one year before filing or after; failure to keep records; false oath; unexplained loss of assets; refusal to obey orders; a chapter 7 or 11 discharge in a case commenced within 8 years before this filing; a chapter 12 or 13 discharge in a case commenced within 6 years unless that plan paid 100%, or 70% in good faith and best effort; a waiver; no financial-management course). (3) Scope: the discharge covers every debt that arose before the order for relief (including lease rejection damages and any claim treated as pre-petition), whether or not the landlord filed a claim or it was allowed, except debts excepted under 523 (US:11USC523-landlord-exceptions). (4) The landlord (or a collector as its agent) may object to the discharge by complaint filed within 60 days after the first date set for the 341 meeting (US:FRBP4004-discharge-objection). (5) After discharge, the landlord may ask to revoke it for fraud it learned of only after the discharge, within one year after it is granted, or for concealed estate property or refusal to obey orders before the later of one year or case closing. A discharged balance is written off as to the tenant (US:11USC524(a)(2)).",
                   "critical", "8.8", "(a) The court shall grant the debtor a discharge, unless— (1) the debtor is not an individual;",
                   "(B) the date the case is closed.",
                   determinacy="MIXED", judgment_terms=["intent to hinder, delay, or defraud", "knowingly and fraudulently", "failed to explain satisfactorily"],
                   dependencies=["US:11USC524(a)(2)"])])

p = rule("US:FRBP 3001", "US:FRBP3001-claim-contents", "FRBP 3001(a), (c)(1)-(3), (e), (f)", "landlord; collector; debt buyer", "shall",
         "The landlord (or its agent, or a buyer of the balance) files a proof of claim in a former tenant's bankruptcy.",
         "The claim is filed on Official Form 410, signed by the creditor or its authorized agent (the manager or Handoff may sign as agent). It attaches a copy of the lease (or a statement why it is lost). In an individual's case it also attaches an itemized statement of principal and any interest, fees, expenses or other charges incurred before the petition (the move-out statement's itemization serves). If that information is omitted, the court may bar the landlord from using it as evidence in any contested matter unless the omission was substantially justified or harmless, and award the debtor's reasonable expenses and attorney's fees. A balance sold before a claim is filed may be claimed only by the buyer; a buyer after filing files evidence of the transfer, and the seller has 21 days after the clerk's notice to object. A claim filed in accordance with the rules is prima facie evidence of its validity and amount.",
         "major", "8.8", "(a) Definition and Form. A proof of claim is a written statement of a creditor", "prima facie evidence of the claim's validity and amount.",
         dependencies=["US:FRBP-3002(c)-claim-deadline"])
add("US:FRBP 3001", "partial",
    "States what the landlord's proof of claim must contain (Form 410, the lease, an itemization in an individual's case) and the sanction for omitting it; the existing rule states only the deadline.",
    atom_ids=["US:FRBP-3002(c)-claim-deadline"], proposed=[{**p, "amends": "US:FRBP-3002(c)-claim-deadline"}])

nd("US:FRBP 3005", "Lets a co-tenant or guarantor file a proof of claim in the landlord's name within 30 days after the landlord's own deadline passes; the landlord's deadline and duties are unchanged and any distribution simply reduces the balance.")

add("US:FRBP 3015", "new_rule",
    "Sets when a landlord must object to a former tenant's chapter 13 plan (at least 7 days before the confirmation hearing) and that a confirmed plan's stay-termination and secured-amount provisions bind it.",
    proposed=[rule("US:FRBP 3015", "US:FRBP3015-plan-objection", "FRBP 3015(b), (d), (f), (g), (h)", "landlord", "shall",
                   "A former tenant has filed chapter 13 and served a plan (filed with the petition or within 14 days after it, or 14 days after conversion) that treats the landlord's claim, the unexpired lease or the deposit.",
                   "To contest the plan's treatment (for example rejection of the lease, the value placed on the deposit setoff, or payment to unsecured creditors below the disposable-income test), the landlord files and serves an objection on the debtor, the trustee and any entity the court designates, and sends a copy to the United States trustee, at least 7 days before the confirmation hearing unless the court orders otherwise; the objection is a contested matter. If no timely objection is filed, the court may find good faith without evidence and confirm. On confirmation the plan's determination of a secured claim's amount binds the landlord even if its proof of claim says otherwise, and a plan request to terminate the stay is granted. A later modification is noticed at least 21 days ahead and objected to the same way. The confirmed plan then binds the landlord (US:11USC1327-plan-binds).",
                   "major", "8.8", "(f) Objection to Confirmation; Determining Good Faith When No Objection is Filed.", "is granted.",
                   dependencies=[])])

add("US:11 USC 522", "new_rule",
    "Decides whether a bankrupt tenant's deposit refund is exempt, which moves the payee from the chapter 7 trustee to the tenant, keeps the landlord's setoff right, voids a lease waiver of exemptions and lets the tenant avoid the landlord's judgment lien.",
    proposed=[rule("US:11 USC 522", "US:11USC522-refund-exemption", "11 U.S.C. 522(b), (c), (d)(5), (e), (f)(1)(A), (l); NY DCL 282, 285; CPLR 5205(g)", "landlord; manager; tenant", "applies",
                   "A former tenant who is an individual domiciled in New York is a debtor in chapter 7 or 13 while its deposit refund is unpaid, or while the landlord holds a judgment lien on the tenant's property.",
                   "(1) Election: the tenant exempts either New York's list (DCL 282, which includes CPLR 5205(g): money deposited as security for the rental of the debtor's residence, without dollar limit) or, instead, the federal list in 522(d) (DCL 285), whose wildcard (d)(5) covers any property up to $1,675 plus up to $15,800 of unused homestead amount (cases filed from 2025-04-01, US:11USC104-dollar-amounts). (2) The tenant lists the refund on its exemption schedule; unless a party in interest objects within the FRBP 4003(b) period (US:FRBP4003-exemption-objection), it is exempt and leaves the estate. From then the refund is paid to the tenant, not the chapter 7 trustee (US:11USC542-refund-payee branch (a) ends for the exempt amount); before then, or for any part not exempted, the chapter 7 trustee is the payee. (3) The exemption reaches only the tenant's interest, which is the refund left after the charges the landlord may lawfully keep under the lease and GOL 7-108; 553 preserves the landlord's setoff against the deposit notwithstanding 522(c), but applying it still needs stay relief while the stay lasts (US:11USC362(a)(7)-deposit-is-setoff). (4) Exempt property is not liable during or after the case for the landlord's other pre-petition claims, so the landlord may not later enforce a balance against the exempt refund or other exempt property unless the debt is a nondischargeable domestic-support or tax debt or secured by an unavoided lien. (5) A lease clause waiving exemptions is unenforceable in the case as to an unsecured claim. (6) A judicial lien the landlord obtained on the tenant's property (a docketed judgment against a tenant who owns real property) may be avoided by the tenant to the extent it impairs an exemption; an unavoided lien survives the discharge against that property.",
                   "critical", "6.7", "(b) (1) Notwithstanding section 541 of this title, an individual debtor may exempt", "Unless a party in interest objects, the property claimed as exempt on such list is exempt.",
                   dependencies=["US:11USC542-refund-payee", "US:11USC362(a)(7)-deposit-is-setoff", "US:11USC104-dollar-amounts"],
                   construction=[{"source_file": "register/texts/NY_DCL/285.txt", "quote": "an individual debtor may opt to exempt from property of the estate such property as is permitted to be exempted pursuant to section five hundred twenty-two of title eleven of the United States Code in lieu of such property as is permitted to be exempted pursuant to the applicable provisions of this article."},
                                 {"source_file": "register/texts/NY_DCL/282.txt", "quote": "personal and real property exempt from application to the satisfaction of money judgments under sections fifty-two hundred five and fifty-two hundred six of the civil practice law and rules"},
                                 {"source_file": "register/texts/NY_CPLR/5205.txt", "quote": "Money deposited as security for the rental of real property to be used as the residence of the judgment debtor or the judgment debtor’s family"},
                                 {"source_file": "sources/US_11USC_553.txt", "quote": "this title does not affect any right of a creditor to offset a mutual debt owing by such creditor to the debtor that arose before the commencement of the case under this title against a claim of such creditor against the debtor that arose before the commencement of the case"}],
                   reasoning="New York lets a debtor choose the state list (DCL 282, incorporating CPLR 5205, whose subdivision (g) exempts a residential rent security deposit) or the federal list (DCL 285). Section 553(a) preserves setoff against anything in 'this title', which includes 522(c), and 522(h)-(i) let a debtor undo a setoff only where the trustee could recover it under 553(b); so exemption does not defeat the landlord's setoff. A deposit is security, so the debtor's interest that 541 brings in and 522 exempts is the refund net of the landlord's lawful charges.")])

add("US:FRBP 4003", "new_rule",
    "Fixes when a claimed exemption of the deposit refund becomes final (30 days after the 341 meeting concludes), which decides when the refund is paid to the tenant rather than the trustee.",
    proposed=[rule("US:FRBP 4003", "US:FRBP4003-exemption-objection", "FRBP 4003(b)(1)-(2), (c), (d)", "landlord; manager", "may",
                   "A former tenant in chapter 7 or 13 claims its deposit refund (or other property the landlord could reach) as exempt on Form 106C.",
                   "A party in interest (the landlord included) may object within 30 days after the later of the conclusion of the 341 meeting, an amendment to the exemption list, or a supplemental schedule; the court may extend this only on a motion filed before the time runs out. The objector bears the burden of proof. If no objection is filed in time, the exemption stands (522(l)) and the refund is paid to the tenant (US:11USC522-refund-exemption); a trustee may still object to a fraudulently claimed exemption within one year after the case closes. A tenant's request to avoid the landlord's judicial lien under 522(f) is made by motion or by a served chapter 12 or 13 plan, and the landlord may oppose it by challenging the exemption.",
                   "major", "6.7", "(b) Objecting to a Claimed Exemption. (1) By a Party in Interest.", "by challenging the validity of the exemption asserted to be impaired by the lien.",
                   dependencies=[])])

add("US:FRBP 4004", "new_rule",
    "Sets the deadline for a landlord to object to a former tenant's discharge (60 days after the first date set for the 341 meeting in chapter 7) and when the discharge enters.",
    proposed=[rule("US:FRBP 4004", "US:FRBP4004-discharge-objection", "FRBP 4004(a)-(c), (g)", "landlord; collector", "shall",
                   "The landlord wants to object to a former tenant's discharge as a whole (a 727(a) ground, or a prior discharge under 727(a)(8)-(9) or 1328(f)).",
                   "Chapter 7: file the complaint (or, for a prior discharge, a motion) within 60 days after the first date set for the 341(a) meeting. Chapter 13: a motion under 1328(f) within 60 days after that first date. Chapter 11: a complaint on or before the first date set for the confirmation hearing. Creditors get at least 28 days' notice of the date. The time may be extended only on a motion filed before it runs out, for cause; after it runs out and before discharge, only for facts that would support revocation under 727(d) that the landlord did not know in time, on a motion filed promptly after learning them. When the objection and dismissal deadlines pass, a chapter 7 individual's discharge enters promptly (unless an objection, dismissal motion, waiver, missing course certificate, unpaid fee or listed motion is pending), and the clerk mails the final discharge order to all creditors. The deadline cannot be extended or reduced except as this rule permits (US:FRBP9006-time).",
                   "critical", "8.8", "(a) Time to Object to a Discharge; Notice. (1) Chapter 7.", "(C) the movant files the motion promptly after learning about them.",
                   dependencies=[])])

add("US:FRBP 4007", "new_rule",
    "Sets the landlord's 60-day deadline to have a fraud, false-financial-statement or willful-and-malicious-injury balance held nondischargeable; missing it discharges the balance.",
    proposed=[rule("US:FRBP 4007", "US:FRBP4007-523c-deadline", "FRBP 4007(a)-(d); 11 U.S.C. 523(c)", "landlord; collector", "shall",
                   "The landlord claims a former tenant's balance is nondischargeable because it was obtained by false pretenses, a false representation, actual fraud or a materially false written statement of financial condition (523(a)(2)), arose from fraud as a fiduciary, embezzlement or larceny (523(a)(4)), or is for willful and malicious injury to the landlord's property (523(a)(6)).",
                   "The landlord must file a complaint to determine dischargeability within 60 days after the first date set for the 341(a) meeting (chapters 7, 11, 12 and 13); creditors get at least 30 days' notice. The court may extend the time only on a motion filed before it expires, for cause. If no complaint is filed in time, the debt is discharged. In chapter 13, a 523(a)(6) property-damage debt is dischargeable in a completed-plan discharge, so a complaint on that ground is due only when the debtor moves for a hardship discharge, by the date the court sets (US:11USC1328-ch13-discharge). A complaint on any other 523(a) ground (for example an unscheduled debt under 523(a)(3)) may be filed at any time, including in a reopened case without a reopening fee. The deadline cannot be extended or reduced except as this rule permits (US:FRBP9006-time).",
                   "critical", "8.8", "(a) Who May File a Complaint.", "extend the time to file.",
                   dependencies=[])])

add("US:FRBP 9006", "new_rule",
    "Computes every bankruptcy deadline a landlord must meet (proof of claim, objections, dischargeability) and bars extending most of them after they run.",
    proposed=[rule("US:FRBP 9006", "US:FRBP9006-time", "FRBP 9006(a), (b)(1)-(3), (c)(2), (e), (f)", "landlord; collector; Handoff", "applies",
                   "A deadline in a former tenant's or owner's bankruptcy case applies to the landlord (proof of claim, objection to discharge or exemption, dischargeability complaint, reaffirmation filing, plan objection, stay-relief response).",
                   "Count days by excluding the triggering day, counting every day, and including the last day; if the last day is a Saturday, Sunday or legal holiday (the federal holidays, days declared by the President or Congress, and, for periods measured after an event, New York State holidays), the period runs to the end of the next day that is not. If the clerk's office is inaccessible on the last day, the period extends to the next accessible business day. The last day ends at midnight in the court's time zone for electronic filing, or when the clerk's office closes for other filing. Service by mail is complete on mailing; when the landlord must act within a time after being served by mail, 3 days are added. The court may extend a deadline for cause on a request made before it expires, or after it expires for excusable neglect; but the deadlines to file a proof of claim (3002(c)), object to exemptions (4003(b)), object to discharge (4004(a)), file a 523(c) complaint (4007(c)) and file a reaffirmation agreement (4008(a)) may be extended only as those rules permit, and none of them may be reduced.",
                   "critical", "8.8", "(a) Computing Time.", "3 days are added after the period would otherwise expire under (a).",
                   dependencies=["US:FRBP-3002(c)-claim-deadline"])])
