import sys
sys.path.insert(0, "register/work")
from q5_lib import add, nd, rule, SEC
F = SEC["US:11 USC 523"]["text_file"]

p = rule("US:11 USC 523", "US:11USC523-landlord-exceptions", "11 U.S.C. 523(a)(2)(A)-(B), (a)(3), (a)(6), (c)(1), (d)", "landlord; collector; manager", "applies",
         "A former tenant who is an individual receives (or will receive) a discharge under 727, 1141, 1192 or 1328(b) while owing the landlord a balance; for a completed chapter 13 plan discharge (1328(a)) see US:11USC1328-ch13-discharge.",
         "The discharge does not cover the part of the balance that is: (1) money, property, services or credit obtained by false pretenses, a false representation or actual fraud, other than a statement about the tenant's financial condition (for example, occupancy obtained under a false identity); (2) obtained by a written statement about the tenant's or an insider's financial condition (a rental application stating income, employment or assets) that was materially false, on which the landlord reasonably relied, and that the tenant made with intent to deceive; a false oral statement about finances, even about a single asset or income, does not qualify (Lamar, Archer & Cofrin, LLP v. Appling, 584 U.S. 709 (2018)); (3) for willful and malicious injury by the tenant to the landlord's property, meaning damage the tenant intended to cause, not a deliberate act that happens to cause damage, and not negligent or reckless damage or a plain breach of the lease (Kawaauhau v. Geiger, 523 U.S. 57 (1998)); (4) not listed or scheduled with the landlord's name in time for the landlord to file a timely claim (and, for kinds (1)-(3), a timely dischargeability complaint), unless the landlord had notice or actual knowledge of the case in time; in a no-asset chapter 7 case with no claims deadline set, an unlisted balance of any kind other than (1)-(3) is discharged, because a timely claim remains possible (In re Massa, 187 F.3d 292 (2d Cir. 1999)). Kinds (1)-(3) are discharged unless the landlord obtains a court determination on a complaint filed by the FRBP 4007(c) deadline (US:FRBP4007-523c-deadline); a kind (4) balance and an unscheduled kind (1)-(3) balance without notice survive without a filing, and may be pursued after the case, with a complaint at any time if the tenant disputes it. If the landlord sues under (1) or (2) on a consumer debt (a residential lease balance owed by an individual) and loses, the court awards the tenant its costs and a reasonable attorney's fee if the landlord's position was not substantially justified, unless special circumstances make that unjust. A surviving balance is collected after the stay ends without violating the discharge (US:11USC105-discharge-contempt applies only to discharged debt).",
         "critical", "8.8", "(c) (1) Except as provided in subsection (a)(3)(B) of this section, the debtor shall be discharged from a debt of a kind specified in paragraph (2), (4), or (6)",
         "as the case may be, of subsection (a) of this section.",
         determinacy="MIXED",
         judgment_terms=["false pretenses, a false representation, or actual fraud", "materially false", "reasonably relied", "intent to deceive", "willful and malicious injury", "notice or actual knowledge", "substantially justified"],
         dependencies=["US:11USC524(a)(2)"],
         construction=[{"source_file": F, "quote": q} for q in [
             "(A) false pretenses, a false representation, or actual fraud, other than a statement respecting the debtor’s or an insider’s financial condition;",
             "(i) that is materially false; (ii) respecting the debtor’s or an insider’s financial condition; (iii) on which the creditor to whom the debtor is liable for such money, property, services, or credit reasonably relied; and (iv) that the debtor caused to be made or published with intent to deceive; or",
             "(6) for willful and malicious injury by the debtor to another entity or to the property of another entity;",
             "(A) if such debt is not of a kind specified in paragraph (2), (4), or (6) of this subsection, timely filing of a proof of claim, unless such creditor had notice or actual knowledge of the case in time for such timely filing; or",
             "if the court finds that the position of the creditor was not substantially justified, except that the court shall not award such costs and fees if special circumstances would make the award unjust."]],
         reasoning="")
p["reasoning"] = ("Section 523(c)(1) makes (a)(2), (4) and (6) debts dischargeable unless the creditor obtains a determination, which FRBP 4007(c) times. Appling holds a statement about a single asset is 'respecting the debtor's financial condition' and so must be written; Geiger requires a deliberate or intentional injury for (a)(6). "
                  "Massa (2d Cir.) holds an omitted debt is discharged in a no-asset case because a timely proof of claim can still be filed. Section 523(d) applies to consumer debts, and a residential lease balance owed by an individual is incurred primarily for a personal, family or household purpose (101(8)).")
add("US:11 USC 523", "new_rule",
    "Decides which parts of a former tenant's balance survive a discharge (fraud, false rental application, willful and malicious damage, unscheduled debt), what the landlord must file to keep them, and its fee exposure if it loses.",
    proposed=[p])
