import sys
sys.path.insert(0, "register/work")
from q5_lib import add, nd, rule

add("US:11 USC 547", "new_rule",
    "Decides when a landlord or collector must give back payments a former tenant made in the 90 days before filing bankruptcy, and the defences (ordinary course, $600 consumer floor, new value, secured by the deposit).",
    proposed=[rule("US:11 USC 547", "US:11USC547-preference", "11 U.S.C. 547(b), (c)(1), (c)(2), (c)(4), (c)(8), (c)(9), (f), (g), (h)", "landlord; manager; collector", "must return",
                   "A former tenant (individual or company) paid the landlord, its manager or a collector on a balance already owed (rent in arrears, a move-out balance, a settlement or payment plan) within 90 days before the tenant's bankruptcy petition (one year if the landlord was an insider of the tenant).",
                   "The trustee (after reasonable due diligence that takes account of the landlord's known or reasonably knowable defences) may avoid the payment and recover it (US:11USC550-transferee-liability) if it was on account of an antecedent debt, made while the tenant was insolvent (presumed in the 90 days), and let the landlord receive more than it would in a chapter 7 distribution. It is not avoidable: (1) if the case is an individual's with primarily consumer debts and the payments to the landlord total less than $600; (2) in a case whose debts are not primarily consumer debts, if they total less than the 547(c)(9) amount ($8,575 for cases filed from 2025-04-01; US:11USC104-dollar-amounts); (3) to the extent it paid a debt incurred in the ordinary course of the tenant's and landlord's affairs and was made in that ordinary course or on ordinary business terms (monthly rent paid as due is; a lump-sum catch-up after demand or a new payment plan is judged on the facts); (4) to the extent it was intended as and was a substantially contemporaneous exchange for new value (rent paid for the current period of occupancy); (5) to the extent the landlord later gave the tenant unsecured new value (further occupancy not paid for); (6) to the extent the landlord's claim was fully covered by the deposit it could set off, since it then received no more than in chapter 7; (7) if made under an alternative repayment schedule created by an approved nonprofit credit counseling agency. The trustee proves the elements; the landlord proves a defence. The landlord's own pre-petition application of the deposit is a setoff tested under 553(b), not a preference. A returned preference gives the landlord a pre-petition claim for that amount (502(h)), which it files as a proof of claim; until it returns an avoidable transfer, its other claims are disallowed (502(d)).",
                   "critical", "8.8", "(b) Except as provided in subsections (c) and (i) of this section, the trustee may", "created by an approved nonprofit budget and credit counseling agency.",
                   determinacy="MIXED", judgment_terms=["ordinary course of business or financial affairs", "ordinary business terms", "substantially contemporaneous exchange", "new value", "primarily consumer debts"],
                   dependencies=["US:11USC104-dollar-amounts", "US:11USC362(a)(7)-deposit-is-setoff"])])

add("US:11 USC 548", "new_rule",
    "Decides when rent or a balance paid for the tenant by someone not liable for it (a parent, relative, employer) must be returned to that payer's bankruptcy trustee; payments by the tenant on its own debt are for value.",
    proposed=[rule("US:11 USC 548", "US:11USC548-constructive-fraud-third-party", "11 U.S.C. 548(a)(1), (c), (d)(2)(A)", "landlord", "must return",
                   "A payment to the landlord on the tenancy was made within 2 years before a bankruptcy petition filed by the person who made it.",
                   "(1) Payer is the tenant, or a co-tenant or guarantor paying its own liability: the payment satisfied the payer's own present or antecedent debt, which is value, so it is not avoidable as constructively fraudulent; it can be attacked only as a preference (US:11USC547-preference) or for actual intent to hinder, delay or defraud creditors. (2) Payer was not liable on the lease (a parent or relative paying an adult tenant's rent, not a guarantor): the payer's trustee may avoid the payment if the payer received less than reasonably equivalent value and was insolvent when paying, was left with unreasonably small capital, or intended to incur debts beyond its ability to pay; the landlord, as initial transferee, returns it (US:11USC550-transferee-liability). The landlord's good faith does not protect it, because it gave value to the tenant, not to the payer. (3) Any payment made with the payer's actual intent to hinder, delay or defraud its creditors is avoidable; a landlord that took for value and in good faith keeps it to the extent it gave value to the payer. State law extends the look-back to four years (US:11USC544(b)-state-lookback).",
                   "major", "8.8", "(a) (1) The trustee may avoid any transfer", "under an employment contract and not in the ordinary course of business.",
                   determinacy="MIXED", judgment_terms=["reasonably equivalent value", "insolvent", "actual intent to hinder, delay, or defraud", "good faith"])])

add("US:11 USC 549", "new_rule",
    "Decides when a payment the landlord receives from a tenant after its bankruptcy filing must be returned to the trustee.",
    proposed=[rule("US:11 USC 549", "US:11USC549-postpetition-payment", "11 U.S.C. 549(a), (b), (d)", "landlord; manager; collector", "must return",
                   "After a former tenant's bankruptcy petition, the landlord, manager or collector receives a payment from the tenant (or applies money of the tenant) on a balance.",
                   "The trustee may avoid and recover (US:11USC550-transferee-liability) a transfer of property of the estate made after the filing that the Code or the court did not authorize, whether or not the landlord knew of the case. Chapter 7: money the tenant held at filing (cash, bank balances, a tax refund for pre-filing income) is estate property, so a post-filing payment from it is avoidable; a payment from wages earned after the filing is not estate property and may be kept if the tenant pays voluntarily (collecting it is still stayed, US:11USC362(a)(6)). Chapter 13: the tenant's post-filing earnings are estate property (1306), so a payment outside the plan without court authority is avoidable. Involuntary case: a payment between the filing and the order for relief is protected only to the extent of value given after the filing (not payment of a pre-filing debt). The trustee must sue within two years after the payment and before the case is closed or dismissed.",
                   "major", "8.8", "(a) Except as provided in subsection (b) or (c) of this section, the trustee may avoid a transfer of property of the estate", "(2) the time the case is closed or dismissed.",
                   dependencies=["US:11USC362(a)(6)"])])

add("US:11 USC 550", "new_rule",
    "Decides who repays an avoided preference or post-filing payment: the landlord for whose benefit a collector took it, and when a collector itself is liable; sets the trustee's time limit.",
    proposed=[rule("US:11 USC 550", "US:11USC550-transferee-liability", "11 U.S.C. 550(a), (b), (d), (f)", "landlord; manager; collector", "is liable",
                   "A payment on a former tenant's balance is avoided as a preference, fraudulent or post-filing transfer (547, 548, 544, 549) or setoff improvement (553(b)), and the payment passed through a manager, Handoff or a collector.",
                   "The trustee recovers the payment (or its value if the court orders) from the initial transferee or the entity for whose benefit it was made, and may also recover from a later transferee unless that transferee took for value, in good faith and without knowing the transfer was avoidable. The landlord, for whose benefit a manager or collector received the payment, is liable. An agent (the manager, Handoff or a collector) that received the money only to pass it to the landlord and had no dominion over it is not an initial transferee (Second Circuit dominion-and-control test); a collector or debt buyer that took the payment for its own account (a purchased balance or a contingency fee it kept) is an initial transferee of what it kept. The trustee gets one satisfaction. The recovery action must be brought within one year after the avoidance and before the case is closed or dismissed.",
                   "major", "8.8", "(a) Except as otherwise provided in this section, to the extent that a transfer is avoided", "(2) the time the case is closed or dismissed.",
                   determinacy="MIXED", judgment_terms=["dominion over the funds", "good faith"],
                   dependencies=[])])

add("US:11 USC 552", "new_rule",
    "In an owner's bankruptcy, a lender's pre-filing assignment of rents reaches rents and balances collected after the filing, which makes them cash collateral.",
    proposed=[rule("US:11 USC 552", "US:11USC552(b)(2)-postpetition-rents", "11 U.S.C. 552(a), (b)(2)", "owner; manager; trustee", "applies",
                   "The owner is a debtor and, before its filing, granted a lender a security interest (mortgage or assignment of rents) covering the building's rents; the manager collects rent or a former tenant's balance after the filing.",
                   "The lender's security interest extends to rents and payments for use or occupancy the estate receives after the filing, to the extent the security agreement provides, unless the court orders otherwise on the equities; other property acquired after the filing is free of pre-filing security agreements. Those collections are cash collateral handled under US:11USC363-owner-cash-collateral. A deposit the tenant can trace is the tenant's trust money, not rent, and is not reached.",
                   "major", "0.5", "(2) Except as provided in sections 363, 506(c), 522, 544, 545, 547, and 548 of this title, and notwithstanding section 546(b)",
                   "such security interest extends to such rents",
                   dependencies=["US:11USC541-704-owner-chapter7"])])

add("US:11 USC 558", "new_rule",
    "In a tenant's (or owner's) bankruptcy the estate keeps every defence the debtor had, including limitations and the deposit-statement forfeiture, and a debtor's post-filing waiver or acknowledgment does not bind it.",
    proposed=[rule("US:11 USC 558", "US:11USC558-estate-defenses", "11 U.S.C. 558", "landlord; tenant", "applies",
                   "A former tenant (or the owner) is a debtor and the other side asserts a claim in the case: the landlord's proof of claim for the balance, or the tenant's claim for the deposit.",
                   "The estate may raise every defence the debtor had against the claimant: statutes of limitation, statute of frauds, usury and other personal defences, including New York's bars on the landlord keeping or recovering against the deposit (forfeiture for a missed 14-day statement, NY:GOL-7-108(1-a)(g)). A waiver of such a defence by the debtor after the filing, including a post-filing written acknowledgment or promise that would restart the limitation period (NY:GOL-17-101-acknowledgment), does not bind the estate; it can bind the debtor personally only as to a debt not discharged.",
                   "major", "8.8", "The estate shall have the benefit of any defense available to the debtor", "does not bind the estate.",
                   dependencies=["NY:GOL-17-101-acknowledgment"])])
