import sys
sys.path.insert(0, "register/work")
from q5_lib import add, nd, rule

nd("US:11 USC 1325", "Sets the court's confirmation tests for a chapter 13 plan; the landlord's acts are the proof of claim and an objection, whose deadline, effect and the binding result are proposed at FRBP 3015 and 1327 (US:FRBP3015-plan-objection, US:11USC1327-plan-binds).")
nd("US:11 USC 1326", "Plan payments run from the debtor to the trustee, who pays creditors; direct payments to a lessor reach only leases of personal property, not a residential lease, so nothing changes for the landlord beyond the plan's binding effect (US:11USC1327-plan-binds).")

add("US:11 USC 303", "new_rule",
    "Decides whether a landlord may put a former tenant into involuntary bankruptcy to collect a balance, the liability if the petition is dismissed, and that an owner in an involuntary case keeps operating until relief is ordered.",
    proposed=[rule("US:11 USC 303", "US:11USC303-involuntary", "11 U.S.C. 303(a), (b), (f), (h), (i)", "landlord; collector; owner", "may",
                   "Branch (a): the landlord considers filing an involuntary petition against a former tenant (an individual or company) to collect a balance. Branch (b): creditors filed an involuntary petition against the owner.",
                   "(a) An involuntary case may be filed only under chapter 7 or 11 and not against a farmer or a non-business corporation. If the tenant has fewer than 12 qualifying creditors (excluding employees, insiders and holders of avoidable transfers), the landlord alone may file if its claim is not contingent as to liability and not subject to a bona fide dispute as to liability or amount, and totals at least the 303(b) amount ($21,050 for cases filed from 2025-04-01, US:11USC104-dollar-amounts) above any lien securing it; otherwise three such creditors must join. If the tenant contests, relief is ordered only if the tenant is generally not paying its undisputed debts as they come due (or a custodian took charge within 120 days). If the court dismisses the petition (other than on consent of all petitioners and the debtor), it may award the tenant costs or a reasonable attorney's fee against the petitioners, and against a petitioner that filed in bad faith, damages proximately caused and punitive damages. A balance the tenant disputes in good faith cannot support a petition. (b) Until an order for relief, unless the court orders otherwise, the owner may keep operating and using its property as if no case were filed, so the manager keeps collecting and refunding in the ordinary course; the automatic stay applies to collection from the owner from the filing of the petition.",
                   "major", "8.8", "(a) An involuntary case may be commenced only under chapter 7 or 11 of this title", "(B) punitive damages.",
                   determinacy="MIXED", judgment_terms=["bona fide dispute as to liability or amount", "generally not paying such debtor's debts", "bad faith"],
                   dependencies=["US:11USC104-dollar-amounts"])])

add("US:11 USC 342", "new_rule",
    "Decides when a landlord, manager or collector has effective notice of a tenant's bankruptcy, which gates any monetary penalty for a stay violation or for paying a refund to the wrong party, and lets the landlord fix the address notices must use.",
    proposed=[rule("US:11 USC 342", "US:11USC342-effective-notice", "11 U.S.C. 342(c)(2), (e), (f), (g)", "landlord; manager; collector; Handoff", "may",
                   "A former tenant files bankruptcy (any chapter) while the landlord, its manager or a collector holds a balance or the deposit.",
                   "(1) If, in the 90 days before a voluntary filing, the landlord (or its manager as its agent) sent the tenant at least two communications stating the tenant's current account number and the address at which it asks to receive correspondence, any notice the debtor must send it goes to that address with that account number. (2) In an individual's chapter 7 or 13 case the landlord may at any time file with the court and serve on the debtor a notice of the address to use in that case; notices sent more than 7 days after receipt must go there. (3) An entity may file with any or all bankruptcy courts a standing notice of address for all its chapter 7 and 13 cases there; court notices sent more than 30 days after filing go to it unless a case-specific address was served. (4) A notice not sent as this section requires is not effective until it is brought to the creditor's attention; if the creditor designated a person or unit to receive bankruptcy notices with reasonable delivery procedures, it is brought to its attention only when that person or unit receives it. (5) No monetary penalty (including 362(k) damages) may be imposed on the creditor for violating the stay, or for failing to turn over estate property under 542 (the deposit refund, US:11USC542-refund-payee), for conduct before it received notice effective under this section. Actual knowledge of the case from another source still makes later conduct a stay violation. Handoff configuration: where Handoff or the manager receives mail for the owner, the owner may designate it as the responsible unit and the filing notice address points there.",
                   "critical", "6.7", "(2) (A) If, within the 90 days before the commencement of a voluntary case", "occurs after such creditor receives notice effective under this section of the order for relief.",
                   determinacy="MIXED", judgment_terms=["brought to the attention of such creditor", "reasonable procedures"],
                   dependencies=["US:11USC362(a)(6)", "US:11USC542-refund-payee"])])

add("US:11 USC 348", "new_rule",
    "Conversion of a tenant's chapter 13 to chapter 7 changes who is paid the refund, turns charges incurred during the chapter 13 into pre-filing (stayed, dischargeable) claims, and restarts the lease-rejection clock.",
    proposed=[rule("US:11 USC 348", "US:11USC348-conversion", "11 U.S.C. 348(a)-(d), (f)", "landlord; manager; collector", "applies",
                   "A former tenant's bankruptcy case is converted from one chapter to another (for example chapter 13 to chapter 7) while the refund, a balance or the lease is outstanding.",
                   "(1) The petition date does not change; the conversion order is the order for relief for the new chapter's lease rule, so in a case converted to chapter 7 an unexpired lease not assumed within 60 days after conversion is deemed rejected (US:11USC365(d)(1)-ch7-rejection), and notices follow 342. (2) A claim that arose after the original order for relief but before conversion from chapter 11, 12 or 13 (rent or charges incurred during the chapter 13) is treated as if it arose immediately before the petition: it is stayed, paid only as a claim in the converted case, and discharged with the rest, unless it is an administrative expense under 503(b). (3) Chapter 13 converted in good faith: the chapter 7 estate is the property of the estate at the petition date that remains in the debtor's possession or control at conversion; a deposit refund still unpaid at conversion is paid to the chapter 7 trustee once the landlord has notice of the conversion (US:11USC542-refund-payee branch (a)); a refund already paid to the chapter 13 debtor is not paid again. Converted in bad faith: the estate is all property at conversion. (4) A pre-filing default not cured under the plan keeps its state-law effect. (5) Conversion ends the service of the prior trustee.",
                   "critical", "6.7", "(a) Conversion of a case from a case under one chapter of this title", "the default shall have the effect given under applicable nonbankruptcy law.",
                   dependencies=["US:11USC542-refund-payee", "US:11USC365(d)(1)-ch7-rejection"])])

add("US:11 USC 349", "new_rule",
    "Dismissal of the tenant's case ends the bankruptcy constraints: no discharge, the refund reverts to the tenant, and setoff or turnover orders are vacated; a later case may still discharge the balance.",
    proposed=[rule("US:11 USC 349", "US:11USC349-dismissal", "11 U.S.C. 349(a), (b)", "landlord; manager; collector", "applies",
                   "A former tenant's bankruptcy case is dismissed before a discharge while a balance, a held deposit or the refund is outstanding.",
                   "Unless the court orders otherwise for cause: the dismissed case grants no discharge, and with the automatic stay ended on dismissal the landlord may collect the balance and apply the held deposit to it under state law (the 14-day statement was already due, US:11USC542-refund-payee); estate property, including the tenant's right to the refund, revests in the tenant, so any refund still due is paid to the tenant, not a trustee; any order under 542 (turnover) or 553 (setoff) is vacated, and transfers avoided in the case (preferences, US:11USC547-preference) are reinstated. The dismissal does not bar the tenant from discharging the same balance in a later case, except that an individual whose case was dismissed for willful failure to obey court orders or appear, or who voluntarily dismissed after a stay-relief request, may not be a debtor for 180 days (109(g)); the court may order a dismissal with prejudice for cause.",
                   "major", "8.8", "(a) Unless the court, for cause, orders otherwise, the dismissal of a case under this title does not bar the discharge",
                   "in the entity in which such property was vested immediately before the commencement of the case under this title.",
                   dependencies=["US:11USC542-refund-payee"])])

add("US:11 USC 363", "new_rule",
    "In an owner's bankruptcy, balances collected from former tenants are rents that may be a lender's cash collateral the owner and manager may not use without consent or court order; ordinary refunds need no court order.",
    proposed=[rule("US:11 USC 363", "US:11USC363-owner-cash-collateral", "11 U.S.C. 363(a), (c)(1)-(4), (f)", "owner; manager; trustee", "shall not",
                   "The owner is a debtor (chapter 7 trustee operating under 721, or a chapter 11 or 13 debtor operating the building) and the manager collects a former tenant's balance or pays a refund.",
                   "(1) The estate (trustee or debtor in possession) may collect rents and balances and pay refunds in the ordinary course of the building's business without notice or a hearing. (2) Rents and other payments for use or occupancy that are subject to a lender's security interest (a mortgage with an assignment of rents, perfected as 552(b) allows) are cash collateral: they may be used only with every interested entity's consent or a court order, and the estate must segregate and account for them. The manager deposits a collected former-tenant balance to the account the cash-collateral order or consent designates and does not spend it otherwise. (3) A deposit the tenant can trace is not estate property and is refunded as trust money (US:11USC541-704-owner-chapter7). (4) A sale of the building by the estate outside the ordinary course needs notice and a hearing; it passes free and clear of an entity's interest only on one of the grounds in 363(f) and only as the sale order states, so whether the buyer holds and owes a former tenant's deposit follows the sale order and the leases assumed and assigned to it.",
                   "major", "0.5", "(c) (1) If the business of the debtor is authorized to be operated under section 721", "shall segregate and account for any cash collateral in the trustee's possession, custody, or control.",
                   dependencies=["US:11USC541-704-owner-chapter7", "US:11USC1107-1306-owner-reorganization"])])
