import sys
sys.path.insert(0, "register/work")
from q7_lib import *

N = "no_decision"
rows = [
    D("NY:GBL 399-X", N, "Card payment for towing and storage outside NYC (inapplicable in NYC by its subdivision 4); outside the chain."),
    D("NY:GBL 399-XX", N, "Duties of commercial towers to disabled vehicles; outside the chain."),
    D("NY:GBL 399-Y", N, "Child safety devices offered on sale, lease or rental of instant hot water dispensers; a device-sale rule with no charge, credit or step in the tenancy account."),
    D("NY:GBL 399-Y*2", N, "ATM surcharge disclosure; outside the chain."),
    D("NY:GBL 399-Y-1", N, "No fee for denied ATM transactions; outside the chain."),
    D("NY:GBL 399-YYY", N, "Domestic-violence victims may leave satellite TV contracts; binds satellite providers, not landlords (tenancy DV rules are stated at RPL 227-c)."),
    D("NY:GBL 399-YYYY", N, "Wireless industry report on renewable energy at cell sites (repealed 2026-12-21); outside the chain."),
    D("NY:GBL 399-Z-1", N, "Carriers' blocking of invalid or unallocated calling numbers; binds carriers, and the caller-side calling rules are stated (TCPA, Reg F)."),
    D("NY:GBL 399-Z-1*2", N, "STIR/SHAKEN caller authentication for voice providers; binds carriers only."),
    D("NY:GCN 1", N, "Short title of the General Construction Law; changes no rule's reach."),
    D("NY:GCN 11-A", N, "Definition of acquisition by eminent domain; outside the chain."),
    D("NY:GCN 11-B", N, "Definition of appropriation by eminent domain; outside the chain."),
    D("NY:GCN 13", N, "Adjournment of meetings of public bodies; outside the chain."),
    D("NY:GCN 13-B", N, "Definition of board of supervisors; outside the chain."),
    D("NY:GCN 16", N, "'Choose' includes elect and appoint; no stated rule uses it."),
    D("NY:GCN 16-A", N, "Definition of civil action as any action other than a criminal prosecution; the deposit and balance suits are civil actions on any reading, so no rule's reach changes."),
    D("NY:GCN 16-B", N, "Definition of condemnation; outside the chain."),
    D("NY:GCN 17", N, "'Criminal code' means the code of criminal procedure; outside the chain."),
    D("NY:GCN 18", N, "Definition of the Consolidated Laws; changes no rule's reach."),
    D("NY:GCN 18-A", N, "Definition of criminal action; the misdemeanors stated in the chain do not turn on it."),
    D("NY:GCN 20-A", N, "Definition of distinct parcel of real property; outside the chain."),
    D("NY:GCN 25-C", N, "Investment in shares of bonds and mortgages; outside the chain."),
    D("NY:GCN 26", N, "Definition of judge; no stated rule's reach turns on it."),
    D("NY:GCN 26-B", N, "Just compensation for lost mortgage financing on a taking; outside the chain."),
    D("NY:GCN 27", N, "References to the last, preceding, next or following section of a statute; a cross-reference convention, not time computation (stated at GCN 19-25-a)."),
    D("NY:GCN 28", N, "Mental disability terms take their Mental Hygiene Law meanings; the incapacity rules the chain uses turn on judicial declarations, not these terms."),
    D("NY:GCN 28-A", N, "Definition of mandate (a writ or court direction); no stated rule's reach turns on it."),
    D("NY:GCN 28-B", N, "A magistrate is any judge; outside the chain."),
    D("NY:GCN 28-C", N, "Replacement of outdated terms with Down's syndrome in public documents; outside the chain."),
    D("NY:GCN 29", N, "'Men' includes boys; no stated rule uses it."),
    D("NY:GCN 33-A", N, "'Notify' for jurors means summon; outside the chain."),
    D("NY:GCN 36", N, "Oath and affidavit include every mode of attestation the law authorizes; every affidavit the chain requires is a court paper, where the affirmation alternative is decided by CPLR 2106 (proposed NY:CPLR-2106-affirmation), so this adds no reach."),
    D("NY:GCN 37-A", N, "Personal injury includes libel, slander and malicious prosecution; no deposit or balance claim is a personal-injury claim."),
    D("NY:GCN 37-B", N, "Population means the latest federal census count; the chain's population-based rules (the 1,000,000 city carve-outs) apply to NYC on any count."),
    D("NY:GCN 38", N, "Property includes real and personal property; no stated rule's reach turns on it."),
    D("NY:GCN 40", N, "Real property includes lands and tenements; no stated rule's reach turns on it."),
    D("NY:GCN 41", N, "Quorum of public boards; outside the chain."),
    D("NY:GCN 47", N, "'State' includes territories and D.C.; the stated capacity rules speak of 'formed outside New York', which this does not change."),
    D("NY:GCN 47-A", N, "Definition of superintendent of schools; outside the chain."),
    D("NY:GCN 53-A", N, "Trial juror means petit juror; outside the chain."),
    D("NY:GCN 54", N, "Village means an incorporated village; outside NYC and the chain."),
    D("NY:GCN 55", N, "'Women' includes girls; no stated rule uses it."),
    D("NY:GCN 61", N, "Assessment rolls for constitutional tax limits; outside the chain."),
    D("NY:GCN 65", N, "Classification of corporations; the capacity rules turn on domestic or foreign formation, not class."),
    D("NY:GCN 66", N, "Corporate definitions (domestic and foreign corporation, office, business of a corporation); the stated capacity rules use 'formed outside New York' consistently with 66(14), and 66(19) leaves 'doing business' to the governing statute, so no rule's reach changes."),
    D("NY:GCN 67", N, "Short citations of three corporation laws; changes no rule's reach."),
    D("NY:GCN 81", N, "Amended section headings carry into tables of contents; changes no rule's reach."),
    D("NY:GCN 96", N, "Hyphen in a schedule of repeals includes intermediate numbers; changes no rule's reach."),
    D("NY:GOL 1-101", N, "Short title of the General Obligations Law; changes no rule's reach."),
]
save(rows)
