import sys; sys.path.insert(0, "register/work")
from q8_lib import D, P, q, save
N = "no_decision"
F = "register/texts/NYC_ADC/20-105.txt"
r105 = P("NYC:ADC-20-105-unlicensed-daily-fine", "Admin. Code 20-105(a), (b), (d), (g)", "debt collection agency required to hold a DCWP licence (for Handoff by configuration, NYC:DCA-handoff-principal-purpose; a debt buyer, NYC:DCA-debt-buyer)", "must not / penalty",
  "A person that must hold a DCWP licence under Admin. Code title 20 chapter 2 (for this chain, a debt collection agency under 20-489 and 20-490) collects former NYC tenants' balances without the licence.",
  "Besides the chapter 2 penalties (20-490, 20-494) and the 20-106 sanctions, DCWP may, after notice and hearing: (1) fine it $100 per violation for each day of unlicensed activity, each day a separate violation, not offset by the chapter 2 penalties; (2) order it to stop the activity at the premises at once; (3) seal premises used primarily for the activity; and (4) remove or seal the devices and goods used in it. Orders under (2)-(4) are stayed for a person that filed a full and complete licence or renewal application with the fee before DCWP served its notice, while the application is pending. Sealed premises and devices are released only on payment of all fines and costs and proof of a licence. Operator step: hold the licence (or a pending complete application) before any collection that makes Handoff or a buyer a debt collection agency.",
  F, q(F, "to impose fines upon any person in violation of subdivision a of this section of one hundred dollars per violation per day"),
  "major", "8.6", jurisdiction="NYC", instrument="NYC Admin. Code tit. 20 ch. 1 (DCWP licensing, general provisions)", amends="NYC:ADC-20-490",
  dependencies=["NYC:ADC-20-490", "NYC:ADC-20-489(a)", "NYC:DCA-handoff-principal-purpose", "NYC:DCA-debt-buyer"],
  construction=[(F, q(F, "It shall be unlawful for any person required to be licensed pursuant to the provisions of chapter two"))],
  reasoning="20-105(a) makes unlicensed activity unlawful for anyone chapter 2 requires to be licensed, which includes a debt collection agency under subchapter 30 (20-489, 20-490); (b)(1) adds a per-day fine expressly cumulative with chapter 2 penalties, which NYC:ADC-20-490 does not list.")
save([
 D("NYC:ADC 20-105", "partial", "NYC:ADC-20-490 states that unlicensed collection is unlawful with the 20-494 penalties, but not the separate $100-per-day fine, stop order and sealing DCWP may impose under 20-105 on an unlicensed collector.", atoms=["NYC:ADC-20-490"], proposed=[r105]),
 D("NYC:ADC 20-108", N, "DCWP licence terms are two years unless chapter 2 says otherwise; whether a collector holds a current licence is a fact the licensing rules already test."),
 D("NYC:ADC 20-706.1", N, "DCWP outreach to young adults; agency program, no duty on a chain party."),
 D("NYC:ADC 20-706.2", N, "DCWP business education events; agency program."),
 D("NYC:ADC 20-706.3", N, "DCWP outreach to seniors; agency program."),
 D("NYC:ADC 20-706.4", N, "DCWP outreach to immigrants; agency program."),
 D("NYC:ADC 20-706.5", N, "DCWP outreach to women; agency program."),
 D("NYC:ADC 20-706.6", N, "DCWP outreach to tourists; agency program."),
 D("NYC:ADC 20-706.7", N, "DCWP outreach on Hajj and Umrah scams; agency program."),
 D("NYC:ADC 20-807", N, "Definitions for the tenant screening report subchapter; its operative sections (20-808, 20-809) govern applications before the lease and were decided no_decision in the queue."),
 D("NYC:ADC 26-1101", N, "Definitions for the housing information guide chapter; its operative sections (26-1102 to 26-1104) were decided no_decision in the queue."),
 D("NYC:ADC 26-402", N, "Short title of the city rent and rehabilitation law (rent control); decides nothing, and the regime itself is outside the market-rate aperture."),
 D("NYC:ADC 27-2001", N, "Short title of the Housing Maintenance Code."),
 D("NYC:ADC 27-2018", N, "Repealed section; no text in force."),
 D("NYC:ADC 27-2050", N, "Repealed section; no text in force."),
 D("NYC:ADC 27-2088", N, "Board of Standards and Appeals powers over cellar and basement occupancies by reference to MDL 310; variance procedure, no settlement step (the cellar rent rule is NYC:HMC-27-2087-cellar-basement)."),
 D("NYC:ADC 27-2090", N, "HPD's power to make HMC regulations; administrative."),
 D("NYC:ADC 27-2096.2", N, "HPD publishes median asking rents; agency report, no chain duty."),
 D("NYC:ADC 27-2126", N, "Repealed section; no text in force."),
 D("NYC:ADC 27-2129.1", N, "HPD annual elevator-violation report; agency report."),
 D("NYC:ADC 8-103", N, "Repealed section; no text in force."),
 D("NYC:ADC 8-104", N, "Repealed section; no text in force."),
 D("NYC:ADC 8-105", N, "Repealed section; no text in force."),
 D("NYC:ADC 8-106", N, "Repealed section; no text in force."),
 D("NYC:ADC 8-108", N, "Reserved section; no text."),
 D("NYC:ADC 8-108.2", N, "Repealed section; no text in force."),
 D("NYC:ADC 8-110", N, "Reserved section; no text."),
 D("NYC:ADC 8-127", N, "Civil penalties under the Human Rights Law go to the city's general fund; the tenant's own remedies are in the stated anti-discrimination rules."),
 D("NYC:ADC 8-132", N, "Commission's online sexual-harassment resources; agency duty."),
 D("NYC:ADC 8-401", N, "Legislative declaration for the Corporation Counsel's systemic-discrimination actions; declares policy."),
 D("NYC:RCNY 28 1-13", N, "HPD rehabilitation-program community participation statement; decides nothing."),
 D("NYC:RCNY 28 12-05", N, "Chapter 12 definitions (CO alarm, private dwelling); the detector charge caps in NYC:HMC-27-2045-detector-charge come from Admin. Code 27-2045 itself, so the rule's narrower 'Private Dwelling' definition does not change the charge a departing tenant may bear."),
 D("NYC:RCNY 28 43-05", N, "Definition of mortgagee for HPD's chapter 43 rules by reference to Admin. Code 27-2109.1; no stated or proposed rule turns on it."),
 D("NYC:RCNY 47 2-02", N, "Severability clause of the Human Rights Commission rules; decides nothing."),
 D("NYC:RCNY 47 2-07", N, "Exceptions to the ban on pre-employment marijuana testing; employment matter."),
])
