import sys; sys.path.insert(0, "register/work")
from q8_lib import D, P, q, save
N = "no_decision"
SS = "sources/REVIEW4B_NY_CASE_SmallStep_v_BroadwayBushwick_2016_2dDept.txt"
SSQ = "Failure to comply with these requirements precludes a limited liability company from maintaining any action or special proceeding in New York"
F201 = "register/texts/NY_PTR/121-201.txt"
F1506 = "register/texts/NY_PTR/121-1506.txt"
F1504 = "register/texts/NY_PTR/121-1504.txt"
r201 = P("NY:PTR-121-201-lp-publication", "Partnership Law 121-201(c)", "owner (New York limited partnership) or a collector suing in its name", "precondition",
  "The owner is a New York limited partnership and it, or a collector in its name, sues or would sue a former tenant for a balance. Branch (a): the partnership was formed on or after the effective date of 121-201(c)(i) and did not file proof of publication (certificate of publication with the newspapers' affidavits) with the Department of State within 120 days after its formation. Branch (b): it was formed before that date, did not comply with the earlier publication requirement (a partnership formed before 1999-01-01, or formed from 1999-01-01 on that filed at least one publisher's affidavit, is deemed to have complied), and did not file proof of publication within twelve months after that date. Branch (c): it complied, or is deemed to have complied, with the requirement that applied to it.",
  "(a) and (b): its authority to carry on, conduct or transact business in New York is suspended from the end of the 120-day (or twelve-month) period, and while suspended it cannot maintain the suit. Filing proof of publication in substantial compliance at any time annuls the suspension, so the suit may proceed once it is filed. The suspension does not impair the lease, the deposit statement, any right or remedy of the tenant, the tenant's right to sue the partnership, or the partnership's defense of the tenant's suit, and does not make any partner or agent liable for the partnership's obligations. (c): no bar. Operator step: confirm the Department of State record shows the publication filing before suing.",
  F201, q(F201, "If within one hundred twenty days after its formation, proof of such publication", "effective as of the expiration of such one hundred twenty day period."),
  "critical", "8.10", jurisdiction="NY", instrument="NY Partnership Law art. 8-A (Revised Limited Partnership Act)", dependencies=["NY:LLC-206-publication-suspension"],
  construction=[(SS, SSQ), (F201, q(F201, "such suspension of such limited partnership’s authority to carry on, conduct or transact business shall be annulled."))],
  reasoning="121-201(c) uses the same suspension and annulment words as LLC Law 206, which the Appellate Division reads as barring the entity from maintaining an action while suspended (NY:LLC-206-publication-suspension, Small Step Day Care); the section's savings clause preserves contracts, the other party's rights and suits and the partnership's defense, and filing proof annuls the suspension. The queue's proposals cover foreign limited partnerships (121-902) and LLPs (121-1500, 121-1502); this is the domestic limited partnership branch.")
r1506 = P("NY:PTR-121-1506-llp-process-address-suspension", "Partnership Law 121-1506(b)-(d)", "owner (New York registered limited liability partnership) or a collector suing in its name", "precondition",
  "The owner is a New York registered limited liability partnership; the party whose address it designated for the Secretary of State to mail process filed a certificate of resignation for receipt of process, and the partnership has not filed a certificate of amendment or statement designating a new address, when it or a collector in its name sues a former tenant.",
  "Its authority to do business in New York is suspended, so it cannot maintain the suit until the Department of State files its certificate of amendment or statement of a new address; that filing annuls the suspension and restores authority as if no suspension had occurred. While suspended, the tenant may serve process on the partnership through the Secretary of State. The lease and the deposit statement are unaffected.",
  F1506, q(F1506, "Upon the failure of the designating limited liability partnership to file a certificate of amendment", "its authority to do business in this state shall be suspended."),
  "major", "8.10", jurisdiction="NY", instrument="NY Partnership Law art. 8-B (limited liability partnerships)", dependencies=["NY:LLC-206-publication-suspension"],
  construction=[(SS, SSQ), (F1506, q(F1506, "shall annul the suspension and its authority to do business in this state shall be restored and continued as if no suspension had occurred."))],
  reasoning="Suspension of authority to do business bars maintaining an action, as with the publication suspensions (NY:LLC-206-publication-suspension); 121-1506(d) annuls it retroactively on filing a new address. The queue's NY:PTR-121-104-a-process-address-suspension states the same rule for limited partnerships; this is the LLP branch.")
r1504 = P("NY:PTR-121-1504-foreign-related-llp", "Partnership Law 121-1504", "owner (foreign related limited liability partnership) or a collector suing in its name", "precondition",
  "The owner is a foreign related limited liability partnership (a foreign LLP that obtained a certificate of authority under LLC Law 802) that leases NYC units, and it or a collector in its name sues a former tenant.",
  "Branch (a): within five years after it filed its application for the LLC Law 802 certificate of authority, having satisfied all of 802's requirements, it is deemed to have filed the 121-1502 notice, so the 121-1502 bar for a foreign LLP that has not filed its notice does not apply. Branch (b): from the fifth anniversary of that application it must file the 121-1502 notice; if it has not, it cannot maintain the suit until it files the notice and pays the fees (the queue's NY:PTR-121-1502-foreign-llp).",
  F1504, q(F1504, "Any foreign related limited liability partnership that has filed a certificate of authority", "shall file a notice pursuant to section 121-1502 of this chapter."),
  "major", "8.10", jurisdiction="NY", instrument="NY Partnership Law art. 8-B (limited liability partnerships)", dependencies=["NY:LLC-808(a)-foreign-authority"])
save([
 D("NY:Partnership Law 121-1202", N, "Adoption of the Revised Act by pre-1991 limited partnerships; which statute governs, no settlement consequence."),
 D("NY:Partnership Law 121-1300", N, "Department of State filing fees; no settlement consequence."),
 D("NY:Partnership Law 121-1501", N, "Name requirements for a registered LLP; the suit consequence of using another name is in NY:GBL-130-assumed-name."),
 D("NY:Partnership Law 121-1503", N, "Recognition of New York LLPs outside the state and choice of New York law for partner liability; no effect on a NYC tenancy account."),
 D("NY:Partnership Law 121-1504", "new_rule", "A foreign related LLP with an LLC Law 802 certificate of authority is deemed to have filed the 121-1502 notice for five years, which narrows the queue's proposed foreign-LLP suit bar for that owner; no rule states it.", proposed=[r1504]),
 D("NY:Partnership Law 121-1506", "new_rule", "A New York LLP whose process address resigns is suspended until it files a new address, which bars its suit for a former tenant's balance; the queue proposed this only for limited partnerships (121-104-A).", proposed=[r1506]),
 D("NY:Partnership Law 121-1507", N, "Definitions for the LLP article (partnership interest, publication affidavits); the proposed LLP publication rules (121-1500, 121-1502) do not change reach under them."),
 D("NY:Partnership Law 121-201", "new_rule", "A domestic limited partnership that has not filed proof of publication has its authority suspended and cannot sue a former tenant until it files; the queue proposed the foreign-LP and LLP versions but no rule covers the domestic LP.", proposed=[r201]),
 D("NY:Partnership Law 121-202", N, "Amendments to the certificate of limited partnership on changes of partners, name or process address; no suspension or settlement consequence attaches."),
 D("NY:Partnership Law 121-202-A", N, "Certificate of change of office, process address or agent; filing mechanics."),
 D("NY:Partnership Law 121-203", N, "Certificate of cancellation after dissolution; winding-up capacity is governed by 121-803, and cancellation itself changes nothing in the account."),
])
