import sys; sys.path.insert(0, "register/work")
from q8_lib import D, save
N = "no_decision"
TAX = "information-return duty for an unrelated transaction type; no landlord, collector or tenant reporting in this chain turns on it (deposit interest and write-offs are in US:26USC6049-deposit-interest and US:26USC6050P-no-1099C)"
save([
 D("US:12 CFR 1005.15", N, "Regulation E for government-benefit EFT accounts held by agencies; binds benefit agencies, not a landlord taking rent or paying a refund."),
 D("US:12 CFR 1005.16", N, "ATM fee disclosures; binds ATM operators."),
 D("US:12 CFR Appendix_B_to_Part_1005", N, "Reserved appendix; no text."),
 D("US:12 CFR Appendix_C_to_Part_1005", N, "How the CFPB issues official Regulation E interpretations; procedure, no chain duty."),
 D("US:12 CFR 1022.2", N, "Regulation V examples are illustrative; changes the reach of none of the stated furnisher rules."),
 D("US:12 CFR 1022.50-1022.53", N, "Reserved sections; no text."),
 D("US:12 CFR 1022.55-1022.59", N, "Reserved sections; no text."),
 D("US:12 CFR 1022.80-1022.81", N, "Reserved sections; no text."),
 D("US:12 CFR Appendix_A_to_Part_1022", N, "Reserved appendix; no text."),
 D("US:12 CFR Appendix_D_to_Part_1022", N, "Model notices for prescreened firm offers of credit or insurance; not used in a tenancy settlement."),
 D("US:12 CFR Appendix_J_to_Part_1022", N, "Reserved appendix; no text."),
 D("US:12 CFR Appendixes_F-G_to_Part_1022", N, "Reserved appendixes; no text."),
 D("US:12 USC 5513", N, "FSOC review of CFPB regulations; agency procedure."),
 D("US:12 USC 5515", N, "CFPB supervision of very large banks; not a landlord or collector."),
 D("US:12 USC 5516", N, "Supervision of smaller banks; not a landlord or collector."),
 D("US:12 USC 5519", N, "CFPB exclusion for motor vehicle dealers; not a tenancy matter."),
 D("US:12 USC 5535", N, "Private education loan ombudsman; not a tenancy matter."),
 D("US:12 USC 5537", N, "Grants for senior investor protection; not a tenancy matter."),
 D("US:15 USC 1601", N, "TILA findings and purpose; the operative TILA creditor test for payment plans is stated in US:15USC1602(f)-(g)."),
 D("US:15 USC 1608", N, "Views of other agencies on TILA; agency procedure."),
 D("US:15 USC 1609", N, "Repealed section; no text in force."),
 D("US:15 USC 1613", N, "CFPB annual TILA report; agency duty."),
 D("US:15 USC 1614", N, "Repealed section; no text in force."),
 D("US:15 USC 1616", N, "Board review of consumer credit plans; agency procedure."),
 D("US:15 USC 1692m", N, "CFPB FDCPA reports to Congress; agency duty."),
 D("US:15 USC 1693", N, "EFTA findings and purpose; the payee duties are in the queue's Regulation E proposals."),
 D("US:15 USC 1693l–1", N, "Gift card and general-use prepaid card fee and expiry limits; a refund card is not marketed to the general public, which (a)(2)(D)(iv) excludes, matching the queue's proposal that a refund prepaid card is not a gift card, so no refund step changes."),
 D("US:15 USC 1693p", N, "EFTA reports to Congress; agency duty."),
 D("US:15 USC 1693r", N, "CFPB may exempt state-regulated classes of EFTs; no New York exemption governs a rent or refund transfer, and the section itself places no duty on a chain party."),
 D("US:15 USC 7005", N, "E-SIGN studies; agency duty (the consent rule is stated in US:15USC7001(c)-esign-consent)."),
 D("US:24 CFR 100.1", N, "Authority for HUD's Fair Housing Act regulations; decides nothing."),
 D("US:24 CFR 100.200", N, "Purpose of the disability-discrimination subpart; the operative accommodation rules (US:42USC3604(f)(3)(A)-(B)) are stated."),
 D("US:24 CFR 5.150", N, "Affirmatively furthering fair housing definitions; binds HUD program participants' planning, not a market-rate settlement."),
 D("US:24 CFR 5.152-5.180", N, "Reserved sections; no text."),
 D("US:24 CFR 982.2", N, "Part 982 governs the tenant-based Housing Choice Voucher program; the stated voucher rules (US:24CFR982.313(c) and related) already apply to an HCV tenant by their own terms, so this does not change their reach."),
 D("US:24 CFR 982.3", N, "HUD field office delegation for the voucher program; administrative."),
 D("US:26 CFR 1.6041-9", N, "Coordination with widely held fixed investment trust reporting; " + TAX + "."),
 D("US:26 CFR 1.6049-10", N, "OID reporting on tax-exempt obligations; " + TAX + "."),
 D("US:26 USC 6043", N, "Returns on corporate liquidations and exempt-organization terminations; " + TAX + "."),
 D("US:26 USC 6043A", N, "Returns on taxable mergers and acquisitions; " + TAX + "."),
 D("US:26 USC 6045A", N, "Transfer statements for covered securities; " + TAX + "."),
 D("US:26 USC 6045B", N, "Returns on actions affecting basis of securities; " + TAX + "."),
 D("US:26 USC 6046", N, "Returns on foreign corporations; " + TAX + "."),
 D("US:26 USC 6047", N, "Returns on trusts and annuity plans; " + TAX + "."),
 D("US:26 USC 6050", N, "Repealed section; no text in force."),
 D("US:26 USC 6050A", N, "Returns by fishing boat operators; " + TAX + "."),
 D("US:26 USC 6050D", N, "Returns on energy grants and financing; " + TAX + "."),
 D("US:26 USC 6050F", N, "Returns on social security benefits; " + TAX + "."),
 D("US:26 USC 6050G", N, "Returns on railroad retirement benefits; " + TAX + "."),
 D("US:26 USC 6050K", N, "Returns on exchanges of partnership interests; " + TAX + "."),
 D("US:26 USC 6050L", N, "Returns on donated property; " + TAX + "."),
 D("US:26 USC 6050M", N, "Returns on federal executive agency contracts; " + TAX + "."),
 D("US:26 USC 6050Q", N, "Returns on long-term care benefits; " + TAX + "."),
 D("US:26 USC 6050R", N, "Returns on purchases of fish; " + TAX + "."),
 D("US:26 USC 6050S", N, "Returns on higher education tuition and student loan interest; " + TAX + "."),
 D("US:26 USC 6050T", N, "Returns on health coverage tax credit payments; " + TAX + "."),
 D("US:26 USC 6050U", N, "Returns on long-term care insurance charges; " + TAX + "."),
 D("US:26 USC 6050Y", N, "Returns on life insurance contract transactions; " + TAX + "."),
 D("US:26 USC 6050Z", N, "Long-term care premium statements; " + TAX + "."),
 D("US:34 USC 12493", N, "HUD gender-based violence prevention office; agency duties, the tenant's VAWA protections are stated in US:34USC12491-VAWA."),
 D("US:34 USC 12496", N, "VAWA housing training and technical assistance grants; agency program."),
 D("US:42 USC 3601", N, "Fair Housing Act policy declaration; declares policy."),
 D("US:42 USC 3609", N, "HUD education and conciliation programs; agency duty."),
 D("US:42 USC 3614a", N, "HUD rulemaking authority under the Fair Housing Act; decides nothing."),
 D("US:42 USC 3616", N, "HUD cooperation with state and local fair housing agencies; agency duty."),
 D("US:42 USC 3618", N, "Authorization of appropriations; decides nothing."),
 D("US:42 USC 3619", N, "Severability; decides nothing."),
 D("US:47 CFR 64.1202", N, "Autodialer calls to numbers on the public safety answering point do-not-call registry; a collector's calls to a former tenant's own number are governed by US:47USC227-TCPA, and PSAP lines are not tenant contact numbers."),
 D("US:47 CFR 64.1203", N, "Registration of the robocall traceback consortium; industry procedure."),
 D("US:47 CFR 64.1204", N, "Private submissions of robocall violations to the FCC; industry procedure."),
 D("US:50 USC 3901", N, "Short title of the SCRA."),
 D("US:50 USC 3916", N, "Military departments inform servicemembers of SCRA rights; no landlord duty."),
 D("US:50 USC 3938", N, "Child custody protections for deployed servicemembers; not a tenancy matter."),
 D("US:50 USC 3938a", N, "Annual notice of custody protections; not a tenancy matter."),
 D("US:50 USC 4025a", N, "Portability of professional licences for servicemembers and spouses; not a tenancy matter."),
 D("US:FRBP 1001", N, "Scope and title of the Bankruptcy Rules; the claim deadline rule is stated in US:FRBP-3002(c)-claim-deadline."),
 D("US:FRBP 9030", N, "The Bankruptcy Rules do not extend or limit jurisdiction or venue; decides nothing for the landlord's claim or the tenant's refund."),
])
