import pathlib,re,json
p=pathlib.Path('research/legal-engine/j1/lanes/local_agency')
s=(p/'sources/fppc-selected-targets.txt').read_text()+'\n'+(p/'sources/fppcMixedCampaignRemedy.txt').read_text()
targets={}
for line in s.splitlines():
 m=re.search(r'\((https://www.fppc.ca.gov/[^\s]+/01_index/[^\s]+\.pdf)\)',line)
 if not m: continue
 url=m.group(1); match=re.match(r'([0-9]+(?:\.[0-9]+)?)[._]',url.rsplit('/',1)[1])
 if not match: print('unparsed',url); continue
 n=match.group(1)
 title=line[:m.start()].strip().lstrip('§ ').strip()
 if not title: title='Complaints Filed with the Commission'
 targets[n]={'number':n,'heading':title,'ref':url,'source_unit_kind':'section'}
for n,title,url in [('18200','Terms and References','https://www.fppc.ca.gov/siteassets/documents/legal_div/regulations/01_index/chapter_02/18200._Terms_and_References.pdf'),('18321','Review of Requests Denied by the Executive Director','https://www.fppc.ca.gov/siteassets/documents/legal_div/regulations/01_index/chapter_03/18321._Review_of_Requests_Denied_by_the_Executive_Director.pdf')]:
 targets[n]={'number':n,'heading':title,'ref':url,'source_unit_kind':'section'}
groups=[
('FPPC conflict and contribution definitions','18200 18215 18216 18219 18229.1 18230 18232 18233 18234 18235 18237','Definitions determine whose contribution, income, investment, leasehold, trust or family interest affects a permit or public-work contracting decision; complete mixed definitions retained.'),
('FPPC permit and covered-contract contribution restrictions','18438 18438.1 18438.2 18438.4 18438.5 18438.6 18438.7 18438.8','GOV84308 implementing regime: covered proceedings and actors, aggregation, solicitation, disqualification, cure and disclosure. Section18438.2 reaches permits and covered contracts and preserves statutory contract exclusions.'),
('FPPC financial-interest decision and recusal standards','18700 18700.1 18700.2 18700.3 18701 18701.1 18702 18702.1 18702.2 18702.3 18702.4 18702.5 18703 18704 18705 18706 18707','GOV87100 decision chain and GOV84308 participant dependency: foreseeability, materiality for property/business/income/gifts/personal finances, public-generally exception, participation, legally required participation, segmentation and recusal. Property standard expressly reaches permits, leases, services and repair exceptions.'),
('FPPC conflict disclosure and agency-code dependencies','18729 18730 18740','Leasehold valuation, complete mixed model COI code including disqualification, and privileged disclosure expressly referenced by18707 support permit/work decisions. Separate statement reporting, interim filing, disclosure-category appeals and code-adoption administration are excluded.'),
('FPPC former-official and prospective-employment conflicts','18741.1 18746.1 18746.2 18746.3 18746.4 18747','Representation before permitting/contracting agencies and influence linked to prospective employment affect lawful procurement/provider commitments; conditional former-official regime, not general employment administration.'),
('FPPC gift-interest definitions, valuation and exceptions','18940 18940.1 18940.2 18941 18942 18942.1 18942.2 18942.3 18943 18944 18944.1 18944.2 18944.3 18945 18945.1 18945.2 18946 18946.1 18946.2 18946.3 18946.4 18946.5 18950 18950.1 18950.2 18950.3','Gift source, aggregation, receipt, valuation, return and exclusions define disqualifying financial interests under18700/18702.4 and model code18730. Retain the connected mixed gift regime including exceptions; do not infer every gift or travel payment is disqualifying.'),
('FPPC conflicts advice, complaints and remedies','18316.5 18318 18319 18320 18321 18322 18324 18326 18329 18329.5 18360 18360.1 18360.2 18360.3 18361 18361.1 18361.2 18361.3 18361.4 18361.5 18361.6 18361.7 18361.8 18361.9 18361.10 18361.11 18362 18363','Advice, liability, complaint, settlement, hearing and remedy procedure for selected permit/public-contract conflicts. Mixed18360.1 expressly includes84308 at(b)(12)/(e)(12);18360.2 includes ethics/recusal;18360.3 supplies penalties. Retention does not select the unrelated campaign/lobbying substantive corpus.')]
units=[]
for label,nums,reason in groups:
 ns=nums.split(); missing=set(ns)-targets.keys(); assert not missing,missing
 units.append({'unit':label,'heading':label,'adapter':'generic','toc_url':'https://www.fppc.ca.gov/the-law/fppc-regulations/regulations-index/','toc_authority':'official','reason':reason,'section_list':[targets[n] for n in ns],'version_status':'Publisher current-index targets; later adopted amendments separately selected below. No claim that index alone proves every leaf current.'})
versions=[]
for n in ['18360.1','18360.2','18360.3']:
 url=f'https://www.fppc.ca.gov/siteassets/documents/legal_div/regulations/02_new/august-2026/New_{n}_082426.pdf'
 key=f'FPPC-{n}-2026-amendment'
 units.append({'unit':f'Version source {key}','heading':f'FPPC adopted amendment to2CCR{n}, publisher text dated August24,2026','adapter':'generic','reason':'Retain adopted amendment to selected conflict-enforcement regime without substituting an unestablished effective date for baseline. Markup must be interpreted in J2 extraction.','section_list':[{'number':key,'heading':f'Adopted amendment2CCR{n}','ref':url,'source_unit_kind':'document'}],'internal_units_in_scope':[n],'legal_status':'Publisher lists amended; effective-date column blank','effective_date':None})
 versions.append({'action_id':key,'affected_sections':[n],'source_url':url,'status_source':'https://www.fppc.ca.gov/the-law/fppc-regulations/newly-adopted-amended-or-repealed-regulations/','legal_status':'adopted amendment; effective date not established','adoption_date':'2026-08-20','adoption_source':'https://www.fppc.ca.gov/news-releases/2026/fppc-hearing-summary-august-20-2026/','document_date':'2026-08-24','effective_date':None,'remaining_j1':'Establish filing/effective date; publisher states ordinary amendments effective30days after filing but provides no filing date here. Date printed on amendment is not treated as adoption or operative date.'})
residual={'unit':'Division 6 - Fair Political Practices Commission (residual outside selected conflicts regime)','reason':'Exclude ordinary campaign committee formation/reporting/advertising/funding administration, lobbying registration/reporting, unrelated honoraria, agency staff administration and standalone filing-system logistics. Express exceptions are the selected contribution/conflict definitions,18438regime,18700decision/code/recusal dependencies,former-official restrictions,gift-interest rules,and applicable advice/enforcement including mixed18360.1–.3. No blanket campaign-title exclusion applies to84308 enforcement. Repealed18438.3/18753 are not current operative units.'}
out={'integration':'Additive selection only forCA:CCR2; union functions; append listed units/version records; replace exact blanket Division6 exclusion with residual below. Do not overwrite current canonical instruments or restore CSM/DWC/EDD exclusions.','instrument_id':'CA:CCR2','add_functions':['preconditions','provider_contracts','courts_procedure'],'add_units_in_scope':units,'add_version_records':versions,'remove_units_out_of_scope':['Division 6 - Fair Political Practices Commission'],'add_units_out_of_scope':[residual],'repeal_notes':[{'section':'18438.3','effective_date':'2025-05-15','status':'repealed; statutory agent definition governs','source':'https://training.fppc.ca.gov/the-law/fppc-regulations/newly-adopted-amended-or-repealed-regulations/'},{'section':'18753','effective_date':'2025-06-07','status':'repealed;GOV87500 supersedes filing locations; stale index link not treated current','source':'https://www.fppc.ca.gov/news-releases/2025/2025-second-quarterly-update-conflict-of-interest-revolving-door-and-statement-of-economic-interests/'}],'source_notes':['18700printed cross-reference18503.5 is not a verified regulation identity in recovered FPPC index; retain literal citation for reference discovery, do not invent target or silently correct.18940.2 independently supplies current gift-limit identity.','Primary links establish explicit selected legal sections. Complete verbatim section extraction/history reconciliation is J2; three adopted2026amendment effective dates remain actualJ1 temporal questions.','No live JeV reference flags obtained; captured sources available for passage-level screening.'],'evidence_files':['sources/fppc-primary-index-and-core.txt','sources/fppc-selected-targets.txt','sources/fppc-core-review.txt','sources/fppc-new-amendments-review.txt','sources/fppcEnforceDates.txt','sources/fppcMixedCampaignRemedy.txt','sources/fppc-repeal-status.txt','sources/fppc-final-date-search.txt','sources/fppc-august-adoption.txt']}
(p/'fppc-conflicts-delta.json').write_text(json.dumps(out,indent=2)+'\n')
print('units',len(units),'selectedsections',sum(len(u['section_list']) for u in units)-3)
