"""The NY, NYC and US crosswalk: which chain-map legal functions each registered instrument and unit serves.

INSTRUMENT: the functions of an instrument's in-scope units unless a UNIT rule matches.
UNITS: per instrument, [(pattern, functions)]; the pattern is searched in 'unit | heading'; the first match wins.
Out-of-scope units get functions only when a UNITS rule matches them (regime units parked by aperture, such as rent
regulation); every other out unit maps to no function, with its out reason carried into the crosswalk.
"""
INSTRUMENT = {
    "NY:ABP": ["unclaimed_property"], "NY:BCL": ["entity_capacity"], "NY:CPLR": ["courts_procedure"],
    "NY:DCL": ["bankruptcy"], "NY:EPTL": ["estates_incapacity"], "NY:EXEC": ["anti_discrimination"],
    "NY:GBL": ["consumer_protection"], "NY:GCN": ["general_construction"], "NY:GOL": ["landlord_tenant"],
    "NY:JUD": ["courts_procedure"], "NY:LLC": ["entity_capacity"], "NY:MDL": ["preconditions"],
    "NY:MHY": ["estates_incapacity"], "NY:MIL": ["military"], "NY:NPCL": ["entity_capacity"],
    "NY:PTR": ["entity_capacity"], "NY:RPAPL": ["courts_procedure", "landlord_tenant"],
    "NY:RPL": ["landlord_tenant"], "NY:SSL": ["housing_assistance"], "NY:STT": ["electronic_records"],
    "NY:UCC": ["payments"], "NY:CCA": ["courts_procedure"], "NY:SCPA": ["estates_incapacity"],
    "NY:9NYCRR": ["rent_regulation"], "NY:19NYCRR": ["broker_licensing"], "NY:22NYCRR": ["courts_procedure"],
    "NY:23NYCRR": ["debt_collection"], "NY:16NYCRR": ["fees"], "NY:18NYCRR": ["housing_assistance"],
    "NYC:ADC": ["preconditions"], "NYC:RCNY": ["preconditions"],
    "US:11USC": ["bankruptcy"], "US:FRBP": ["bankruptcy"], "US:15USC-ch41": ["debt_collection"],
    "US:15USC-ch96": ["electronic_records"], "US:42USC-ch45": ["anti_discrimination"], "US:50USC-ch50": ["military"],
    "US:47USC227": ["communications"], "US:26USC-6041-6050": ["tax_reporting"], "US:26USC166": ["tax_reporting"],
    "US:12USC5481": ["consumer_protection"], "US:12USC5220note": ["landlord_tenant"],
    "US:34USC-VAWA": ["early_termination", "housing_assistance"], "US:12CFR1006": ["debt_collection"],
    "US:12CFR1005": ["payments"], "US:12CFR1022": ["credit_reporting"], "US:16CFR682": ["data_security"], "US:24CFR100": ["anti_discrimination"],
    "US:24CFR982": ["housing_assistance"], "US:24CFR5": ["housing_assistance"], "US:47CFR64L": ["communications"],
    "US:26CFR1-info": ["tax_reporting"],
    "US:24CFR966": ["housing_assistance"], "US:24CFR960": ["housing_assistance"], "US:24CFR880": ["housing_assistance"],
    "US:24CFR881": ["housing_assistance"], "US:24CFR882": ["housing_assistance"], "US:24CFR883": ["housing_assistance"],
    "US:24CFR884": ["housing_assistance"], "US:24CFR886": ["housing_assistance"], "US:24CFR891": ["housing_assistance"],
    "US:24CFR983": ["housing_assistance"], "US:24CFR92": ["housing_assistance"], "US:7CFR3560": ["housing_assistance"],
}

UNITS = {
    "NY:ABP": [(r"^art\. 13 |^art\. 14 |^art\. 1 ", ["unclaimed_property"])],
    "NY:CPLR": [(r"^art\. 2 ", ["limitations"]), (r"^art\. 12 ", ["courts_procedure", "estates_incapacity"]),
                (r"^art\. 50 ", ["courts_procedure", "usury_payment_plans"])],
    "NY:DCL": [(r"^art\. 6 ", ["bankruptcy", "courts_procedure"]), (r"^art\. 6-A ", ["bankruptcy", "deposit"]),
               (r"^art\. 9 ", ["estates_incapacity"]), (r"^art\. 10-A ", ["bankruptcy", "courts_procedure"])],
    "NY:GBL": [(r"^art\. 9-B ", ["entity_capacity"]), (r"^art\. 22-A ", ["consumer_protection"]),
               (r"^art\. 25 ", ["credit_reporting"]), (r"^art\. 26 ", ["consumer_protection", "communications", "fees"]),
               (r"^art\. 29-H", ["debt_collection"]), (r"^art\. 39-F ", ["data_security"])],
    "NY:GOL": [(r"^art\. 1 ", ["general_construction"]), (r"^art\. 3 title 1 ", ["estates_incapacity"]),
               (r"^art\. 5 title 1 ", ["general_construction"]), (r"^art\. 5 title 3 ", ["landlord_tenant", "fees"]),
               (r"^art\. 5 title 5 ", ["usury_payment_plans"]), (r"^art\. 5 title 6 ", ["deposit"]),
               (r"^art\. 5 title 13 ", ["general_construction"]), (r"^art\. 5 title 15 ", ["estates_incapacity"]),
               (r"^art\. 7 title 1 ", ["deposit"]), (r"^art\. 13 ", ["debt_collection"]),
               (r"^art\. 15 title 1 ", ["landlord_tenant", "courts_procedure"]),
               (r"^art\. 15 title [35] ", ["usury_payment_plans"]), (r"^art\. 17 ", ["limitations"])],
    "NY:RPAPL": [(r"^art\. 7-[ACD] ", ["preconditions"]), (r"^art\. 7 ", ["landlord_tenant", "courts_procedure"]),
                 (r"^art\. 8 ", ["landlord_tenant"]), (r"^art\. 13 ", ["landlord_tenant"])],
    "NY:RPL": [(r"^art\. 1 ", ["general_construction"]), (r"^art\. 6-A ", ["rent_regulation"]),
               (r"^art\. 7 ", ["landlord_tenant", "deposit", "fees", "early_termination", "abandoned_property"]),
               (r"^art\. 12-A ", ["broker_licensing"])],
    "NY:UCC": [(r"^art\. 1 ", ["general_construction"]), (r"^art\. 3 ", ["payments"])],
    "NY:9NYCRR": [(r"Part 466", ["anti_discrimination"]), (r"Part 540", ["electronic_records"]),
                  (r"Part 2[0-9]{3}", ["rent_regulation"])],
    "NYC:ADC": [(r"^tit\. 8 ", ["anti_discrimination"]), (r"Subchapter 30: Debt Collection", ["debt_collection"]),
                (r"^tit\. 20 > Chapter 1:", ["debt_collection", "consumer_protection"]),
                (r"Rental Real Estate", ["fees", "broker_licensing"]), (r"Consumer Protection Law", ["consumer_protection"]),
                (r"Tenant Screening", ["fees"]), (r"Rent Control|Rent Stabilization", ["rent_regulation"]),
                (r"Unlawful Eviction|Housing Information Guide|Buyout", ["landlord_tenant"]),
                (r"Medical Treatment", ["anti_discrimination"]),
                (r"Consumer Credit History", ["anti_discrimination", "credit_reporting"]),
                (r"Tenant Data Privacy", ["data_security"]), (r"Fees Associated with Vacating", ["fees"]),
                (r"Rental Assistance Voucher", ["housing_assistance"]),
                (r"Housing Maintenance Code", ["preconditions"])],
    "NYC:RCNY": [(r"Subchapter S: Debt Collection|Part 6: Debt C", ["debt_collection"]),
                 (r"^tit\. 6 > Chapter 1:", ["debt_collection", "consumer_protection"]),
                 (r"Tenant Screening", ["fees"]), (r"Consumer Protection Law|Penalties", ["consumer_protection"]),
                 (r"Notification by Mortgagee", ["landlord_tenant"]), (r"^tit\. 28 ", ["preconditions"]),
                 (r"^tit\. 31 |^tit\. 68 ", ["housing_assistance"]), (r"^tit\. 47 ", ["anti_discrimination"])],
    "US:15USC-ch41": [(r"CONSUMER CREDIT COST DISCLOSURE", ["usury_payment_plans"]),
                      (r"GARNISHMENT", ["courts_procedure"]), (r"CREDIT REPORTING", ["credit_reporting"]),
                      (r"DEBT COLLECTION", ["debt_collection"]), (r"ELECTRONIC FUND", ["payments"])],
    "US:24CFR5": [(r"SUBPART L", ["early_termination", "housing_assistance", "anti_discrimination"])],
}

# Out units that still carry a function: the regime is parked by aperture, not outside the chain.
OUT_UNITS = {
    "NY:9NYCRR": [(r"Part 2[0-9]{3}|Part 21\d\d|Part 25\d\d", ["rent_regulation"])],
    "NYC:ADC": [(r"Rent Control|Rent Stabilization|Rent Guidelines", ["rent_regulation"])],
    "US:24CFR966": [(r".", ["housing_assistance"])], "US:24CFR960": [(r".", ["housing_assistance"])],
    "US:24CFR880": [(r".", ["housing_assistance"])], "US:24CFR881": [(r".", ["housing_assistance"])],
    "US:24CFR882": [(r".", ["housing_assistance"])], "US:24CFR883": [(r".", ["housing_assistance"])],
    "US:24CFR884": [(r".", ["housing_assistance"])], "US:24CFR886": [(r".", ["housing_assistance"])],
    "US:24CFR891": [(r".", ["housing_assistance"])], "US:24CFR983": [(r".", ["housing_assistance"])],
    "US:24CFR92": [(r".", ["housing_assistance"])], "US:7CFR3560": [(r".", ["housing_assistance"])],
}
