"""Apply the root's reviewed J1 boundary decisions; not a completeness test."""
raise SystemExit("Historical reassessment applied. Online-only continuation now owns canonical state; do not regenerate withdrawn email plan.")
from pathlib import Path
import json, shutil
B=Path(__file__).resolve().parents[2]
def read(p): return json.loads((B/p).read_text())
def write(p,v):
 path=B/p; backup=B/'j1/history/before-status-reassessment'/p.replace('/','__')
 backup.parent.mkdir(parents=True,exist_ok=True)
 if path.exists() and not backup.exists(): shutil.copy2(path,backup)
 path.write_text(json.dumps(v,indent=2,ensure_ascii=False)+'\n')
opens=[
 ('GoGreen','CA:CCR4','OAL 2026-0826-02C: agency adoption of six sections is established, but outcome and final permanent scope can change the selected version and its relationship to the disaster and multifamily emergency amendments.','OAL'),
 ('OEHHA','CA:CCR27','OAL 2026-0810-01: determine actual outcome and final scope for the 1-bromopropane and dermal diethanolamine NSRL amendment; an action-table entry does not establish final approval or text.','OAL'),
 ('Part 7','CA:CCR24','Establish completed readoption/certification filing and current emergency continuation; May 6 and August 25 approvals alone do not establish the operative version.','CBSC'),
 ('Drinking-water correction','CA:CCR22','OAL 2026-0827-01N: establish outcome and exact changed/renumbered/repealed section inventory; selecting the broad parent is insufficient.','OAL'),
 ('FPPC','CA:CCR2','OAL 2026-0824-04: establish filing and operative status of adopted sections 18360.1–18360.3.','OAL'),
 ('Water fees','CA:CCR23','Resolution 2026-0038: establish submission/filing status and whether authorized pre-filing corrections produced a different filed edition of sections 2200 and 2200.7.','OAL'),
 ('SBSD organics amendment','CA-HB:SBSD:ORD22-01','Obtain adopted January 11, 2024 Article V amendment route and scope; the available 2022 body is an older version.','SBSD'),
 ('SBSD named resolutions','CA-HB:SBSD:FINAL-ACTION-EVIDENCE','Establish operative-body routes and general scope for Resolutions 2024-03-01, 2024-02-01 and 2026-06-01. Adoption minutes omit the named bodies; individual parcel/participant records are not requested.','SBSD'),
 ('HOME 2025 Exhibit A','CA-HB:HOME-TBRA-PROVIDER-AGREEMENTS','Identify the guideline edition actually incorporated by the 2025 Families Forward and Mercy House agreements. Their posted scans omit Exhibit A; continued funding does not prove the 2024 edition carries forward.','HB Clerk')]
resolved=[
 {'item':'SCE duplicate form numbers','decision':'Resolved within J1','reason':'Fourteen files inspected: five pairs are different editions, two pairs are alternate publication routes for the same edition. Actual sheet/effective-date identities now selected.','evidence':'j1/reassessment/sce/version-decisions.json'},
 {'item':'Airport Fire signed proclamation','decision':'Resolved within J1','reason':'Recovered signed September 10, 2024 proclamation, pages 2–5 of the official attachment. Whole proclamation selected; requests to Governor and possible landfill waiver do not establish issued grants, suspensions or a waiver.','evidence':'j1/reassessment/airport-proclamation.pdf'},
 {'item':'Battery 18660.40','decision':'J1 established','reason':'OAL expressly records September 24 approval of the identified single-section package without a partial qualifier. A second endorsed copy is not necessary just to reconfirm selection; detailed temporal interpretation remains downstream.'},
 {'item':'LCRI','decision':'J1 established','reason':'Affirmative under-review status and exact adopted package are identified at the cutoff. A future filing is not a missing current source.'},
 {'item':'Other Title 24 packages, DSA subsets, SFM withdrawals, HCD date discrepancy','decision':'J1 established','reason':'Actual motions and package documents establish included and withdrawn items. Future consolidated publication and resolving a non-selection-changing meeting-date discrepancy are downstream.'},
 {'item':'Part 3 NEC viewer','decision':'J1 established','reason':'Exact incorporated-edition viewer route is recovered. Full authenticated text capture belongs to harvest.'},
 {'item':'SBSD state waiver and current fee schedule','decision':'J1 established','reason':'Official register identifies district/category and July 10, 2025–December 1, 2028 term; current 2025 service schedule is identified. No evidence of a separate conditions letter or automatic annual successor requires inventing one.'},
 {'item':'HB Ordinance 4348','decision':'J1 established','reason':'Actual 143-page ordinance/amendment and certified June 2 adoption minutes establish identity, scope and adoption; another certified copy adds no selection decision.'},
 {'item':'Airport Ordinance 24-006 timing conflict','decision':'Downstream interpretation','reason':'Signed adopted instrument is identified in full. Immediate-effect and certification-boilerplate conflict occurs inside the same source, not between unidentified candidate instruments.'},
 {'item':'Shelter model, RainSmart, carrier page handling','decision':'J1 established','reason':'Actual model/adoption and source selectors are identified; county program retained conditionally with HB eligibility limitation. Full body capture/page-extraction mechanics are J2.'},
 {'item':'Hypothetical annual HOME successor and individual MHTBRA agreements','decision':'Not an additional J1 prerequisite','reason':'No identified annual replacement obligation or independently incorporated template. Individual operating agreements are case evidence. This does not excuse the actual missing 2025 HOME Exhibit A above.'}]
audit={'as_of':'2026-10-01','status':'J1 incomplete; completion withdrawn','criterion':'Could resolving the fact change instrument identity, scope, status or acquisition route? If yes, resolve in J1.','open':[{'item':n,'instrument':i,'reason':r,'request':q} for n,i,r,q in opens],'other_items':resolved,'evidence':['j1/lanes/local_agency/regulatory/restored-access/final-public-route-assessment.json','j1/lanes/local_agency/regulatory/restored-access/j1-reevaluation-delta.json','j1/lanes/federal_programs/restored-access/title24-boundary-reassessment.json','j1/lanes/acquisition/restored-local/moved-items-reassessment.json'],'external_requests':'Prepared, not sent; explicit user authorization needed.'}
write('j1/reassessment/moved-items.json',audit)
p=read('j1/register_updates.json'); by={x['id']:x for x in p['instruments']}
for n,i,r,q in opens: by[i]['j1_unresolved_selection']={'item':n,'reason':r,'next_action':q+' narrowly scoped records request','status':'open','audit':'j1/reassessment/moved-items.json'}
by['CA:CCR4']['version_records'][1]['remaining']=opens[0][2]+' Remains in J1.'
for o in [by['CA:CCR27']['units_in_scope'][4]['status_evidence'],by['CA:CCR27']['version_records'][0]]:o['j1_decision']=opens[1][2]+' Remains in J1; prior downstream assignment withdrawn.'
by['CA:CCR24']['version_records'][0]['remaining_dependency']=opens[2][2]+' Remains in J1.'
by['CA:CCR24']['part7_stage_boundary']={'status':'open_in_J1','reason':opens[2][2]}
url='https://ocagendaext.oc.gov/Web_Publisher_sam/Agenda09_10_2024_FILES/images/s22i-09102024_9862012.pdf'
x=by['CA-OC:LOCAL-EMERGENCIES']
u={'unit':'AIRPORT-SIGNED-PROCLAMATION-2024','heading':'Signed September 10, 2024 Airport Fire local emergency proclamation','adapter':'generic','toc_url':url,'source_unit_kind':'document','reason':'Actual emergency instrument affecting residential property; select recitals and operative paragraphs 1–6.','section_list':[{'number':'AIRPORT-SIGNED-PROCLAMATION-2024','heading':'Signed local emergency proclamation','ref':url+'#page=2'}],'source_selection':{'source_route':url,'pdf_pages_inclusive':[2,5],'status':'Signed September 10, 2024 by acting Director of Emergency Services and Board Chairman','selected_units':'Whole proclamation, recitals and paragraphs 1–6; page 1 is supporting counsel memo','local_capture':'j1/reassessment/airport-proclamation.pdf','review':'All five pages visually inspected. Paragraph 4 permits seeking a landfill waiver; paragraph 5 requests governmental actions. Neither proves a waiver or requested action was issued.'}}
x['units_in_scope']=[a for a in x['units_in_scope'] if a['unit']!=u['unit']]+[u]
x['airport_selection_review']={'status':'resolved','signed_proclamation':url,'decision':'Actual signed proclamation recovered and selected separately from adoption minute order; ordinance timing interpretation remains downstream.'}
for a in x['units_in_scope']:
 if a['unit']=='AIRPORT-LOCAL-PROCLAMATION-2024':a['source_selection']['j1_conclusion']='Adoption minute order retained as action evidence; separate signed proclamation now recovered and selected as AIRPORT-SIGNED-PROCLAMATION-2024.'
x=by['CA-HB:ORD4348']; x['adoption_status']='Adopted June 2, 2026; actual ordinance and certified minutes establish passage.';x['reason']='Refuse-franchise amendment and incorporated Exhibit A; actual attachment and certified June 2, 2026 adoption minutes establish selection.'
by['CA:CCR24']['acquisition']['status']='Twelve publisher routes and the exact Part 3 NFPA viewer are identified. Whole-publication text capture and internal enumeration are J2. Part 7 current emergency filing/continuation remains an open J1 selection question.'
by['CA-HB:SBSD:FINAL-ACTION-EVIDENCE']['acquisition']['status']='Adoption minutes identify the named instruments, but operative-body routes and general scope for Resolutions 2024-03-01, 2024-02-01 and 2026-06-01 remain unresolved in J1. See j1_unresolved_selection.'
by['CA:CCR24']['intervening_cycle_identity_review']['boundary']='Approved future package scopes and routes are identified. Part 7 emergency filing/continuation is separately unresolved within J1; no general downstream assignment applies to that fact.'
by['CA-HB:HOME-PLAN-RES2025-32']['program_currentness_review']={'selected_successor': 'CA-HB:HOME-PLAN-RES2026-10', 'provider_sources': 'CA-HB:HOME-TBRA-PROVIDER-AGREEMENTS', 'decision': 'Use the adopted 2026 plan and recovered guideline/provider sources. Prior failed discovery observations are historical. Actual 2025 incorporated Exhibit A edition remains an open J1 question; individual participant contracts and hypothetical annual successors are not additional register prerequisites.', 'open_selection': 'j1/reassessment/moved-items.json', 'historical_review': 'j1/reassessment/superseded-home-currentness.json'}
for u in by['CA-HB:ORD4348']['units_in_scope']: u['reason']='Refuse-franchise amendment and incorporated Exhibit A; actual attachment and certified June 2, 2026 adoption minutes establish selection.'
write('j1/register_updates.json',p)
c=read('j1/completion.json');c.setdefault('withdrawn_basis',c.get('basis',[]));c['basis']=['Item reassessment identifies unresolved selection-changing facts. J1 remains incomplete.'];c['open_selection_questions']=[r for _,_,r,_ in opens];c['downstream_limits']=[r['item']+': '+r['reason'] for r in resolved if r['decision'] in ['Downstream interpretation','J1 established']];c['current_review']='j1/reassessment/moved-items.json';write('j1/completion.json',c)
w=read('j1/WORK.json');w['remaining']=c['open_selection_questions'];w['coordination']='Four bounded reassessment workers completed; root integrated decisions. No active workers required for awaiting request authorization.';w['prior_tasks']=w.pop('tasks',w.get('prior_tasks',[]));w['tasks']=[{'task':'Reassess every moved item','status':'complete','evidence':'j1/reassessment/moved-items.json'},{'task':'Resolve remaining selection facts through narrow named-record requests','status':'open','evidence':'j1/reassessment/records-requests.md'}];w['remaining_decision_review']=audit;w['downstream_source_followthrough']=c['downstream_limits'];write('j1/WORK.json',w)
local=read('j1/lanes/acquisition/restored-local/named-record-requests.json')['requests'];cb=read('j1/lanes/federal_programs/restored-access/part7-status-followthrough.json')['records_request_prepared_not_sent']
first=(B/'j1/lanes/local_agency/regulatory/restored-access/oal-two-action-records-request.txt').read_text();other=(B/'j1/lanes/local_agency/regulatory/restored-access/remaining-action-records-request.txt').read_text()
body='Please provide the existing outcome, filing-status and final-scope records as of October 1, 2026 for the following actions. Existing notices, endorsed filing forms and final-text links suffice; no legal opinion or entire rulemaking file is requested.\n\n'+first.split('1. ',1)[1].split('\n\nFor each',1)[0]
body='Please provide existing records as of October 1, 2026 for:\n\n1. '+body.split('\n\n',1)[1]+'\n\nFor those two actions, please provide the outcome notice and final endorsed text, including any partial withdrawal or modification; if no outcome had occurred, the existing status record.\n\n'+other.split('1. ',1)[1].split('\n\nOur question',1)[0]
# Renumber the three additional action requests without changing their contents.
pos=body.index('2026-0827-01N'); start=body.rfind('\n\n',0,pos)+2
body=body[:start]+'3. '+body[start:];body=body.replace('\n\n2. OAL file 2026-0824','\n\n4. OAL file 2026-0824').replace('\n\n3. State Water','\n\n5. State Water')
body+='\n\nExisting records and links are sufficient; no legal opinion, new analysis or entire rulemaking files are requested.'
req=[{'to':'staff@oal.ca.gov','subject':'Existing outcome and filing records — five named 2026 actions','body':body},{'to':cb['to'][0],'subject':cb['subject'],'body':cb['body']}]+local
write('j1/reassessment/records-requests.json',{'status':'Unsent drafts; require explicit authorization','requests':req})
(B/'j1/reassessment/records-requests.md').write_text('# Four unsent records requests\n\nStatus: prepared for review; none sent. Research cutoff: October 1, 2026.\n\n'+'\n\n'.join('## '+r['to']+'\n\nSubject: '+r['subject']+'\n\n'+r['body'] for r in req)+'\n')
